# Part 1: title, header, abstract, §1.0 (new), §1.1–§1.10.
import pathlib
SRC = (pathlib.Path(__file__).parent / "v11_source.md").read_text(encoding="utf-8")

def block(start, end):
    """The text from `start` (included) to `end` (excluded); both unique in v11."""
    assert SRC.count(start) == 1, start
    assert SRC.count(end) == 1, end
    i = SRC.index(start); j = SRC.index(end, i)
    return SRC[i:j]

DATE = "4 October 2026"

OLD_ABSTRACT = block("## Abstract\n", "---\n\n## 1. Introduction and main results")

NEW_ABSTRACT = """## Abstract

Let `X ⊂ P^{n+1}` be the complex Fermat variety of degree `m ≥ 3` and even dimension `n = 2k`, and let `L(X) ⊆ H_n(X; Z)` be the subgroup generated by the classes of its standard `k`-dimensional linear subspaces. Degtyarev and Shimada conjectured that `H_n(X; Z)/L(X)` is torsion free [DS, Conjecture 1.2]. **We prove this conjecture for every degree `m ≥ 3` in every even dimension**, modulo two topological results used by [DS]: Pham's theorem on the homology of the affine Fermat variety, and their intersection numbers. Its algebraic form — the quotient `Z[G]/(ψ_J)` of the group ring of [DS] is free abelian of rank `m^{2k+1} − Q_k(m)` — is proved with no topology, and it has been verified for every degree by a complete proof in the proof assistant Lean 4 with the Mathlib library, with no gap and no axiom beyond the three standard ones. The proof reduces the conjecture, prime by prime, to dimension counts in truncated polynomial rings, proved by peeling off one variable at a time. Consequences: the integral Hodge conjecture for `X` whenever `m` is prime, or `m = 4`, or `m` is prime to `(n+1)!`, with the integral Hodge classes of middle degree generated by the standard linear subspaces — in particular for the Fermat quartic of every even dimension; and the primitivity of the linear subspaces of the partial Fermat varieties of [DS], which [DS] proved conditionally on the conjecture. This work has not been refereed by a human expert.

"""

SUMMARY = """### 1.0 Summary of results

`m ≥ 3` is the degree, `n = 2k` the dimension, `N = 2k + 2`, and `Q_k(m) = |Γ_𝒥|` is the number of §1.2. «Lean» means that the statement is proved in Lean 4 with Mathlib, with no gap and no axiom beyond `propext`, `Classical.choice` and `Quot.sound` (§14.8, [LC]).

| Result | What it says | Range | What it rests on | Lean |
|---|---|---|---|---|
| **Main Theorem′** (§1.2) | `R/(ψ_J : J ∈ 𝒥)` is free abelian of rank `m^{2k+1} − Q_k(m)`; the same dimension over every field | every `m ≥ 3`, `k ≥ 1` | nothing outside this paper: the upper bound is [DS, Claim 4.3], a count of points re-proved in Appendix B, Step 6 | yes, every `m ≥ 1`, `k ≥ 0` |
| **Main Theorem** = Conjecture 1.2 of [DS] (§1.2) | `H_{2k}(X; Z)/L(X)` is torsion free, and `rank L(X) = Q_k(m) + 1` | every `m ≥ 3`, `k ≥ 0` | Main Theorem′ and [DS, Theorems 1.1(a), 1.4], which Appendix B derives from Pham's theorem [Ph] and [DS, Theorem 2.2] | the algebraic form only |
| **Corollary H** (§1.3, §12) | `L(X)` is primitive in `Hdg(X)` with free quotient of rank `|𝔅| − Q_k(m)`; `Hdg(X) = L(X)`, and the integral Hodge conjecture holds, iff `m` is prime, `m = 4`, or `gcd(m, (n+1)!) = 1` | every `m ≥ 3`, `k ≥ 1` | the Main Theorem; the classical facts (H1)–(H3); Aoki's theorem (H5) [Aok] (for prime `m` and `m = 4`, the proofs (H4), (H4′) given here) | no |
| **Corollary W** (§1.4, §13) | the linear subspaces of [DS] on the partial Fermat varieties span primitive sublattices | every `m ≥ 3`, `0 ≤ s ≤ d` | the Main Theorem; part (i) also the transport argument of [DS, §4.6] | no |
| **Theorem B** (§1.5, §5) | the count at the even box `q − 1`, with equality and a free quotient over `Z` | every odd `q ≥ 3`, every field, every `k` | — | yes |
| **Theorem C** (§7) | the bipartite counts, `≥`; equality over `F̄_p` (Corollaries 7.8, 9.12) | every `q ≥ 2`, fields with `C(q − 1, t) ≠ 0` | — | yes |
| **Theorem O** (§1.5, §8) | the count at the odd box `r`, with equality and a free quotient over `Z` | every odd `r ≥ 3`, every field, every `k` | — | yes |
| **Theorem A** (§1.6, §10) | a different count; it does not imply the conjecture; as a count it is due to Kostant (characteristic `0`) and to [BRR] (odd characteristic) | `char F ≠ 2`, odd `q` | — (Appendix A) | no |
| **Corollary 10.8** | at the odd box, sum and intersection of the matching ideals coincide | `char F ≠ 2`, odd `r` | Theorems O and A | no |
| **Fact 11.2** | the analogue of the Main Theorem for subfamilies of matchings is false | a computation | — | no |

Everything in this table that is not marked «Lean» was read cold by readers other than its writer (§14.6). No human expert has refereed this work. What we found in the literature, and where we searched, is in §1.10.

"""

EDITS = [
    ("title",
     "prime to `(n+2)!`\n\n**Rafael",
     "prime to `(n+1)!`\n\n**Rafael"),
    ("header",
     "Madrid, Spain · tretoef@gmail.com · 2 October 2026 · version 11",
     f"Madrid, Spain · tretoef@gmail.com · {DATE} · version 12"),
    ("abstract", OLD_ABSTRACT, NEW_ABSTRACT),
    ("summary",
     "## 1. Introduction and main results\n\n### 1.1 The conjecture\n",
     "## 1. Introduction and main results\n\n" + SUMMARY + "### 1.1 The conjecture\n"),
    ("1.1 versions",
     "Before the present work (versions 4 to 11 of this paper)",
     "Before the present work (versions 4 to 12 of this paper)"),
    ("1.2 leading forms (reader note 10)",
     "For `m = 2^v` the ideal of leading forms of the `ψ̄_J` in characteristic `2` contains the ideal of Theorem O for the box `2^v − 1` (Proposition 9.2).",
     "For `m = 2^v` the ideal of leading forms of the `ψ̄_J` in characteristic `2` contains the product of `s_1 ⋯ s_{2k+1}` with the ideal of Theorem O for the box `2^v − 1`, an isomorphic copy of it in another ring (Proposition 9.2)."),
    ("1.2 Lean",
     "For odd `m`, Main Theorem′ has been proved again in the proof assistant Lean 4 (§14.8).",
     "Main Theorem′ has been proved again, for every degree, in the proof assistant Lean 4 (§14.8), and so has Theorem O."),
    ("1.3 (n+1)!",
     "For odd `m`, «every prime factor of `m` is at least `2k + 3`» is the same as `gcd(m, (n+2)!) = 1`, and also the same as the condition `gcd(m, (n+1)!) = 1` of [AMV, §1].",
     "For odd `m`, «every prime factor of `m` is at least `2k + 3`» is the same as the condition `gcd(m, (n+1)!) = 1` of [AMV, §1], which we use in the title. (Version 11 wrote `gcd(m, (n+2)!) = 1`. It is the same condition: a prime that divides `n + 2 = 2(k + 1)` and `m` is at most `k + 1`, so it divides `(n+1)!` as well.)"),
    ("1.3 Mizukami",
     "at `k = 1` it is the statement that the lines of the Fermat quartic surface generate its Néron–Severi group, of rank `20`, which is known [SSvL], [De14];",
     "at `k = 1` it is the statement that the lines of the Fermat quartic surface generate its Néron–Severi group, of rank `20`, which is a result of Mizukami [Miz] (1975; [SSvL, §3 and §6] record it, attribute it to Mizukami and Inose and give another proof; we have not read [Miz]), and which also follows from [De14];"),
    ("1.3 related work",
     "Jumagulov [Jum] recently gave a computer-assisted proof of the *rational* Hodge conjecture for the Fermat fourfolds of odd degree at most `199`; that statement is rational, and complementary to ours.",
     "Recent work on the *rational* Hodge conjecture for Fermat varieties is complementary to ours: Jumagulov [Jum] gave a computer-assisted proof for the Fermat fourfolds of odd degree at most `199`; Miranda, Movasati, Rufino and Villaflor [MMRV] prove it for the Fermat varieties of every dimension and every degree `d < 65` other than `44, 51, 52`, by reducing the lengths of Aoki's exceptional tuples; and Favero and Kelly [FK] prove it for the Fermat fourfold of degree `33`, through an explicit formula for Chern characters. These statements are rational; ours concern the lattice `L(X)` over `Z`."),
    ("1.5 Theorem O open problem",
     "Theorem O was stated as an open problem in version 10 of this paper (there: problem 7 of §13).",
     "Theorem O was stated as an open problem in version 10 of this paper (there: problem 7 of §13), and proved in version 11."),
    ("1.7 Lemma 8.7",
     "In the exterior algebra on `v_0, …, v_{r−1}` this says that a divided power of the `2`-form of `D_{r−1}` lies in the ideal of the `2`-forms of the multiples of `D_r`, and it follows from one fact: the generating function of all these `2`-forms is the product of two `1`-forms.",
     "It follows from one fact: the generating function `Σ_σ ζ^σ ω_{2σ+1}(a, b)` of the antisymmetric polynomials that interpolate between `D_{r−1}` and the multiples of `D_r` is `Ev(a)·Od(b) − Ev(b)·Od(a)`, a matrix of rank two. A rank-two update of a bordered Pfaffian (Lemma 8.8) then expresses the Pfaffian of `D_{r−1}` through bordered Pfaffians whose entries are multiples of `D_r`, and a Laplace expansion finishes the proof."),
]

HISTORY_OLD = "The even degrees were found on 2 October 2026 by replacing the generators at `m = 2^v` by their leading forms, which had been measured to generate an ideal of the right dimension in seven cells, and then proving the count for that ideal."
HISTORY_NEW = HISTORY_OLD + " Version 11 was not made public; everything in it is in the present version. Version 12 (the present one) changes no statement of version 11. Main Theorem′ and Theorem O are now proved in Lean 4 for every degree (§14.8). Two proofs are printed in the form that was formalized, which is shorter: Lemma 8.7 by a rank-two update of bordered Pfaffians, in place of the exterior algebra with divided powers of version 11 (§8.5), which also gives the membership for other border sets (Lemma 8.7′); and the upper bound of Corollary 8.13 by a pairing of the box ring, so that §8 no longer uses §10. The signs of §8.3 are given explicitly, and its properties are attributed to the classical sources. The version also adds the summary of §1.0 and the literature of §1.10; incorporates the notes of the cold reading of the printed text of version 11 (§14.6); corrects the place of Mizukami's theorem (§1.3); and writes the condition of the title in the form `(n+1)!` of [AMV], which is the same condition as the `(n+2)!` of version 11."
EDITS.append(("1.8 history v12", HISTORY_OLD, HISTORY_NEW))

LETTERS_OLD = "Symbols introduced inside a section are local to it (§6–§7 have their own local symbols), and Appendix A has its own symbols."
LETTERS_NEW = LETTERS_OLD + " Some letters have two or three meanings in different places, each declared where it is used: `θ` is the map of Lemma 8.12, of Lemma 9.10 and of Corollary 10.6 (the sign of the expansion (F4) is written `ϑ`); `N` is `2k + 2`, and in §8.3 a finite ordered set of indices; `R` is the ring of §2, and in the proof of Proposition 8.10 a product of Vandermonde determinants; `σ` is a shape in §8.2 and §8.6, an index of the polynomials `ω_{2σ+1}` in §8.5, and a bijection in §6, §7 and §9.3; `ζ` is a colour in §6 and §9 and a formal variable in §8.5; `η` is `e^{πi/m}` in Appendix B; `ρ` is a row in §8.2 and §8.6 and the generator `ρ_J` of [DS] in Remark 2.5′; `S` is a set of indices, the Pham cycle in Appendix B and a polynomial ring in §11; and `r` is the odd box in §8 and §9, the cofactor in §6 (written `r'` in §9), and a row in §5.5."
EDITS.append(("1.9 letters (reader note 6)", LETTERS_OLD, LETTERS_NEW))

ROW_OLD = "| `Pf(N; c)`, `Pf_E(N)`, `E_ℓ`, `B_0` | bordered Pfaffians; the border exponents; the marked block of a pattern | §8.3, §8.4 |\n"
ROW_NEW = ROW_OLD + "| `ω_s`, `Ev`, `Od`, `𝔘_p(N)` | the antisymmetric polynomials of §8.5; the two columns of its key identity; the ideal of the membership lemma | §8.5 |\n"
EDITS.append(("1.9 table row", ROW_OLD, ROW_NEW))

LIT = """
### 1.10 Literature and priority
Before this version we searched the literature for each result that we call new: the arXiv listings and its index of titles and abstracts; Google Scholar and the open web; the papers that cite [DS], through Semantic Scholar and OpenAlex; the publication lists of the authors of [DS]; MathOverflow; and GitHub, including Mathlib and DeepMind's `formal-conjectures` repository, for formalizations. The queries, their dates and their results are recorded in [Rep], `record/literature/`. The sources that decide an attribution were read in the original; the others are cited for the statement they make, and the list of references says which is which. What we found:
- *The even degrees.* To the best of our knowledge, no proof of Conjecture 1.2 for an even degree `m ≥ 4` and `k ≥ 1` had appeared before this paper, beyond the cells confirmed by computer in [DS, §5] (and the case `k = 1`, which is [De14]). The conjecture is listed as open in [De15, Conjecture 4.4].
- *The odd box.* Over `Q`, Theorem O and Corollary 10.8 can be derived from Kostant's theorem and the first fundamental theorem of invariant theory for the orthogonal group (Remark 10.7(2)); we did not find this derivation written. In positive characteristic we did not find Theorem O, or the statement that the tensors `D_{r,J}` generate the invariants of the centralizer of a regular unipotent element (Corollary 10.8 and Remark 10.7), in the literature, in particular not in [BRR], [Ric] or [Liu]. To the best of our knowledge, both are new in positive characteristic.
- *Corollary H.* The implication from the primitivity of `L(X)` to `Hdg(X) = L(X)` in the degrees of (i) is the argument of [AMV, §1], with the degrees of Aoki's theorem [Aok]; for `k = 1` the statement is known ([Miz], [SSvL], [De14]); for `m = 4` and `k = 2, 3`, and in the prime cells of [DS, §5], it already followed from computations (§1.3). For `k ≥ 2` the uniform statement — every prime `m`, the quartics of dimension at least `8`, every non-prime `m` of (i), and part (ii) — is, to the best of our knowledge, new.
- *Corollary W.* The implication «Conjecture 1.2 in dimension `2s` ⟹ (i)» is [DS, Corollary 1.7]; what is new is that the hypothesis is now a theorem.
- *Theorem A* is due, as a count, to Kostant and to [BRR] (Remark 10.4); our contribution there is the dictionary and an elementary proof.
- *Pfaffians.* The properties (i)–(iii), (F1)–(F4) and (F7) of §8.3 are classical; we cite [Knu] and [Oka]. We did not find the rank-two update of Lemma 8.8 in the sources we read, and we claim nothing for it: it is of the kind of the classical expansions of the Pfaffian of a sum of two alternating matrices, which we have not traced to a source that we have read. Its use to prove the membership lemma (Lemmas 8.7, 8.7′) is ours.
- *Orbit harmonics.* The lower bounds by degenerating the ideal of a finite set of points to the ideal of its top-degree forms (Lemma 5.8′, Proposition A.5) are the classical method of orbit harmonics (see [GP]).
- *Formalization.* Mathlib has no Pfaffian; we defined Pfaffians and bordered Pfaffians in our project. A separate partial formalization of skew-symmetric matrices and Pfaffians exists outside Mathlib (`Qsdd/Skewsymmetric` on GitHub). We found no formalization of results of the kind of [DS]; to the best of our knowledge, §14.8 is the first machine-checked proof of a case of Conjecture 1.2.
- *Related work on the rational Hodge conjecture:* [Jum], [MMRV], [FK] (§1.3).

"""
EDITS.append(("1.10 literature", "\n## 2. The translation: Conjecture 1.2 as a dimension count\n", LIT + "## 2. The translation: Conjecture 1.2 as a dimension count\n"))

EDITS.append(("1.8 v11 past tense", "Version 11 (the present one) proves the conjecture for the even degrees,", "Version 11 proved the conjecture for the even degrees,"))
