# Part 7: the notes of the cold reader «Grepy Lupa» on the changes of version 12
# (VIVOS/ATAQUES_Y_REPORTES/V12_CHANGES_1/REPORT_COLD_V12.md, md5 fe270b2a…; graded in
# VIVOS/MISIONES_TRAS_BARRIDO/regla315_calificacion_lupa.md). Grepy Mandalay, 4 Oct 2026.
EDITS = [
    ("P-1 abstract, partial Fermat",
     "and the primitivity of the linear subspaces of the partial Fermat varieties of [DS], which [DS] proved conditionally on the conjecture.",
     "and the primitivity of the sublattices spanned by the linear subspaces that [DS] exhibit on the partial Fermat varieties, which [DS] proved conditionally on the conjecture."),
    ("P-8 table, Corollary H",
     "`Hdg(X) = L(X)`, and the integral Hodge conjecture holds, iff `m` is prime, `m = 4`, or `gcd(m, (n+1)!) = 1` |",
     "`Hdg(X) = L(X)` iff `m` is prime, `m = 4`, or `gcd(m, (n+1)!) = 1`, and then the integral Hodge conjecture holds for `X` |"),
    ("P-9 table, Theorem B",
     "| every odd `q ≥ 3`, every field, every `k` | — | yes |",
     "| every odd `q ≥ 3`, every field, every `k` | — | yes, except the graded refinement |"),
    ("P-9 table, Theorem O",
     "| every odd `r ≥ 3`, every field, every `k` | — | yes |",
     "| every odd `r ≥ 3`, every field, every `k` | — | yes, except the graded refinement |"),
    ("P-11 notation table",
     "`ω_s`, `Ev`, `Od`, `𝔘_p(N)`",
     "`ω_s`, `Ev`, `Od`, `𝔘_ℓ(N)`"),
    ("P-3, P-10 §1.8",
     "Version 11 was not made public; everything in it is in the present version. Version 12 (the present one) changes no statement of version 11. Main Theorem′ and Theorem O are now proved in Lean 4 for every degree (§14.8). Two proofs are printed in the form that was formalized, which is shorter: Lemma 8.7 by a rank-two update of bordered Pfaffians, in place of the exterior algebra with divided powers of version 11 (§8.5), which also gives the membership for other border sets (Lemma 8.7′); and the upper bound of Corollary 8.13 by a pairing of the box ring, so that §8 no longer uses §10.",
     "Version 11 was not made public; every statement of it is in the present version, and the two proofs of it that the present version replaces are described where they stood (§8.5, Remark (4); Lemma 9.10). Version 12 (the present one) changes no statement of a theorem, proposition or corollary of version 11, nor Lemma 8.7; the auxiliary results of §8.5 are new (Lemma 8.7′, and a Lemma 8.8 and a Corollary 8.9 whose numbers version 11 used for other statements), and the properties of §8.3 are now stated over every commutative ring (version 11: without `2`-torsion). Main Theorem′ and Theorem O are now proved in Lean 4 for every degree (§14.8). Three proofs are printed in the form that was formalized, which is shorter: Lemma 8.7 by a rank-two update of bordered Pfaffians, in place of the exterior algebra with divided powers of version 11 (§8.5), which also gives the membership for other border sets (Lemma 8.7′); the upper bound of Corollary 8.13 by a pairing of the box ring, so that §8 no longer uses §10; and Lemma 9.10, without the injectivity of the map `θ`."),
    ("§1.8, the cold reading of v12",
     "which is the same condition as the `(n+2)!` of version 11.",
     "which is the same condition as the `(n+2)!` of version 11. Before it was made public, every passage that is new in the writing of version 12 was read cold, with the verdict «holds» (§14.6); its notes are incorporated, and one of its observations extends Remark (2) of §8.5."),
    ("P-11 §1.9 overloaded letters",
     "`ρ` is a row in §8.2 and §8.6 and the generator `ρ_J` of [DS] in Remark 2.5′;",
     "`ρ` is a row in §8.2 and §8.6 and the generator `ρ_J` of [DS] in Remark 2.5′; `E` is the ideal of §1.6 and §10, an exponent set `E_ℓ` in §8.5 and §8.6, and a border column in Lemma 8.8; `κ` is a partition in the proof of Lemma 8.4 and the number `(n − s)/2` in §8.5; `H` is the matrix of Corollary 8.9, and `H'` a group in Lemma 9.10;"),
    ("P-12 §1.10 Mathlib",
     "Mathlib has no Pfaffian; we defined Pfaffians and bordered Pfaffians in our project.",
     "We found no Pfaffian in Mathlib (the version used, tag `v4.28.0`); we defined Pfaffians and bordered Pfaffians in our project."),
    ("P-4 §8.3 attributions",
     "Three properties follow from the definition [Knu, (0.1), (0.4), (2.0)], [Oka, §2.1]:",
     "Three properties follow from the definition ([Knu, (0.1)], [Oka, (2.1)]); (i) and (iii) are classical [Knu, (0.4), (2.0)], [Oka, (2.3), (2.4)], and (ii), for two distinct indices with equal rows, is proved below in every commutative ring:"),
    ("Remark (2) of §8.5, the zero rule (cold reader + auditor)",
     "(2) *Some patterns are zero.* By Corollary 8.9, `Pf_{E_ℓ}(B_0) = 0` when `ℓ ≥ 1` and `t ≥ h`, and when `ℓ = 0` and `t > h`; such patterns of Definition 8.6 contribute nothing, and do no harm.",
     "(2) *Some patterns are zero.* By Corollary 8.9, `Pf_{E_ℓ}(B_0) = 0` when `ℓ ≥ 1` and `ℓ + t ≥ h + 1`, and when `ℓ = 0` and `t > h`. For `ℓ = 1` the first condition is `t ≥ h`. For `ℓ ≥ 2`, expand the bordered Pfaffian of Corollary 8.9(a) by multilinearity in its last two border columns: the coefficient of `ζ^α` in `Ev` is `y^{2α}` and that of `ζ^β` in `Od` is `y^{2β+1}`; a term in which one of them is a border `y^e`, `e ≤ ℓ − 2`, has two equal border columns and vanishes (F2), and every other term has degree at least `⌈(ℓ−1)/2⌉ + ⌈(ℓ−2)/2⌉ = ℓ − 1` in `ζ`, which exceeds `h − 1 − t`. (The case `ℓ = 2`, `t = h − 1` was found by the cold reader of §14.6.) These conditions are sufficient; we do not claim that they list all zero patterns. Such patterns of Definition 8.6 contribute nothing, and do no harm."),
    ("P-5 Remark (3)",
     "(3) *The border `y^{r−1}` in (b) cannot be dropped:* at `r = 5`, `n = 3`, `Pf(N; y^2)` does not lie in `𝔘_0(N)` (§14.9).",
     "(3) *The border `y^{r−1}` in (b) cannot in general be replaced by another power:* at `r = 5`, `n = 3`, `Pf(N; y^2)` does not lie in `𝔘_0(N)` (§14.9). (In the cells tried by the cold reader, the replacement never broke the membership at `r = 3`.)"),
    ("P-6 Remark (4)",
     "with divided powers of `2`-forms: there (8.6) says that the generating function of the `2`-forms of the `ω_s` is the product of two `1`-forms, and Lemma 8.8(ii) is the formula",
     "with divided powers of `2`-forms, by showing that the divided powers `γ_n` of the generating `2`-form vanish for `n ≥ 2` and by a recursion. In that language our (8.6) says that the generating function of the `2`-forms of the `ω_s` is the product of two `1`-forms, and our Lemma 8.8(ii) corresponds to the formula"),
    ("P-7 proof of Theorem O, base change",
     "by Lemma 8.7 with `ℓ = 0`, `Pf_{{r−1}}(B_0)` lies in the ideal generated by",
     "by Lemma 8.7 with `ℓ = 0` (a membership over `Z`, hence also in `C_{2k+1}` over every field), `Pf_{{r−1}}(B_0)` lies in the ideal generated by"),
    ("P-2 Theorem 8.15",
     "In particular `I(2k + 1, 1)` is the ideal generated by the `D_P`, `P ∈ 𝒥`, in `C_{2k+1}`,",
     "In particular `I(2k + 1, 1)` is the ideal generated by the `D_J`, `J ∈ 𝒥`, in `C_{2k+1}`,"),
    ("P-14 §14.6, the cold reading of v12",
     "In the present version, the proof of §8.5 (Lemmas 8.7′, 8.8 and Corollary 8.9) and the upper bound of Corollary 8.13 are new in the writing: they are the proofs that were formalized, and the Lean kernel checks them (§14.8), but no reader other than their writer has read the printed text. Report, grading and code: [Rep], `record/cold-readings/`.",
     "**The changes of version 12.** Version 12 is new in the writing in these places: the proof of §8.5 (Lemmas 8.7′, 8.8 and Corollary 8.9); the upper bound of Corollary 8.13; the proof of Lemma 9.10 in the case `0 ∉ 𝒞_1`; the proof of property (ii) and the explicit signs of §8.3; the base change in case (Z) of Proposition 8.10; the proofs of Lemmas 6.7(iii) and 9.8; and §1.0, §1.8–§1.10, §14.8, §14.9 and §16. Before the version was made public, these passages were read cold on 4 October 2026 by a further instance of the same system, which had the paper, version 11 for comparison and the originals of [DS], [Knu], [Oka], [MMRV] and [FK], and nothing else. It re-derived by hand every sign of §8.3 and §8.5, the proof of Lemma 8.7′ (with the Vandermonde divisibility over `Z[ζ][y]`), the upper bound of Corollary 8.13 step by step, the short route of Lemma 9.10 and the equivalence of the two forms of the degree condition, and made eleven logged runs with its own code, among them the proof of Lemma 8.7′ run as an explicit certificate over `Z` in `33` cells, and Corollary 8.13 over five fields with the intersection computed independently. Its verdict was «holds», with no error and no gap; its `17` notes of presentation are incorporated in this version, and its one mathematical observation (a further zero pattern) is part of §8.5, Remark (2), which the auditing instance generalized and checked with its own code. It did not read §3, §4, the proofs of §5–§7, §10, §11 or the appendices, and could not read the Lean project; it states that it launched no other agent, and every file it produced is in its own folder. The auditing instance graded the report, checked every line it cites and repeated five of its runs with its scripts, with identical output. Reports, gradings and code: [Rep], `record/cold-readings/`."),
    ("P-13 §14.8 duplicate",
     "and Corollary 8.13 — and Theorem 8.15; and all of §9,",
     "and Corollary 8.13 — and all of §9,"),
    ("P-15 §14.9 what was not done",
     "Lemma 8.7 was tested by machine over prime fields only; over `Z` it is proved in Lean (§14.8).",
     "As a membership, Lemma 8.7 was tested by machine over prime fields only; its proof was run as an explicit certificate over `Z` in small cells (the bullet «Lemma 8.7» above, and the cold reading of §14.6), and over `Z` it is proved in Lean (§14.8)."),
    ("P-16 §15 problem 3",
     "for every `k`, the discriminant is given by the sequel note [WED], modulo [BRR, Proposition 2.12] (Remark 12.2).",
     "for `k ≥ 2`, the discriminant is given by the sequel note [WED], modulo [BRR, Proposition 2.12] (Remark 12.2)."),
    ("P-14 §16 READ COLD",
     "The proof of §8.5 and the upper bound of Corollary 8.13 are new in the writing of this version: they are checked by the Lean kernel and have not been read cold.",
     "The passages that are new in the writing of this version (§14.6) — among them the proof of §8.5, the upper bound of Corollary 8.13 and the proof of Lemma 9.10 — are checked by the Lean kernel and were read cold before the version was made public: «holds»."),
    ("P-17 acknowledgements, [WED]",
     "together with every engine and log behind §14 and the Lean project of §14.8.",
     "together with every engine and log behind §14 and the Lean project of §14.8. The sequel note [WED], cited in Remark 12.2 and §15, is deposited at Zenodo and in the repository of the *Watermark* theorem, and a copy is in [Rep]."),
    ("§14.9 gate bullet, count and Remark (2)",
     "(`4 827` checks, no failure)",
     "(`4 831` checks, no failure)"),
    ("§14.9 gate bullet, Remark (2) cells",
     "Remark (2) in five cells where the Pfaffian is identically `0`, with three controls where it is not;",
     "Remark (2) in eight cells where the Pfaffian is identically `0`, among them `(r, ℓ, t) = (5, 2, 1), (7, 2, 2), (7, 3, 1)`, with four controls where it is not;"),
]
