"""The bipartite down-set family.  Points: (xi, eta) in mu_q^alpha x mu_q^beta, residue shape
(lambda_+, lambda_-) = multiplicity partitions of multiset(xi) - multiset(eta^-1) and of the reverse.
Ideal V_Lambda: generated by tight-pattern products prod (x_i - z_j)^{q-1} * prod Delta_x(blocks of lambda_+)
* prod Delta_z(blocks of lambda_-).  Test: dim V_Lambda >= |Z_Lambda| (expect =) for EVERY down-set.
Usage: python3 bip_family.py alpha beta q p [--p12-only]
"""
import sys, itertools, time, resource
from collections import Counter
from math import comb
import numpy as np
from partB_engine import monomials, RREF, pmul

def partitions_of(n, maxpart=None):
    if maxpart is None: maxpart = n
    if n == 0: yield (); return
    for k in range(min(n, maxpart), 0, -1):
        for rest in partitions_of(n - k, k): yield (k,) + rest

def S(lam, t): return sum(lam[:t])
def dominated(lam, mu):   # lam <= mu in weak dominance
    T = max(len(lam), len(mu), 1)
    return all(S(lam, t) <= S(mu, t) for t in range(1, T + 1))

def Par(alpha, beta, q):
    out = []
    for sp in range(alpha + 1):                      # |lambda_+| = sp, |lambda_-| = sp - (alpha - beta)
        sm = sp - (alpha - beta)
        if sm < 0 or sm > beta: continue
        for lp in partitions_of(sp):
            for lm in partitions_of(sm):
                if len(lp) + len(lm) <= q: out.append((lp, lm))
    return out

def leq(a, b): return dominated(a[0], b[0]) and dominated(a[1], b[1])

def downsets(P):
    """all down-sets of the poset (P, leq), as frozensets of indices."""
    n = len(P)
    below = [frozenset(j for j in range(n) if leq(P[j], P[i])) for i in range(n)]
    seen = {frozenset()}; frontier = [frozenset()]
    while frontier:
        new = []
        for D in frontier:
            for i in range(n):
                if i not in D and below[i] - {i} <= D:
                    D2 = D | {i}
                    if D2 not in seen: seen.add(D2); new.append(D2)
        frontier = new
    return sorted(seen, key=lambda D: (len(D), sorted(D)))

def shape(xi, eta, q):
    X = Counter(xi); Y = Counter((-v) % q for v in eta)
    Rp = sorted((X[v] - Y[v] for v in set(X) | set(Y) if X[v] > Y[v]), reverse=True)
    Rm = sorted((Y[v] - X[v] for v in set(X) | set(Y) if Y[v] > X[v]), reverse=True)
    return (tuple(Rp), tuple(Rm))

def columns(lam):
    """column lengths of a partition"""
    return [sum(1 for part in lam if part > c) for c in range(lam[0])] if lam else []

def set_partitions_with_sizes(items, sizes):
    """partitions of the list items into blocks with the given sizes (ordered list of blocks)."""
    if not sizes:
        if not items: yield []
        return
    s = sizes[0]
    first = items[0]
    for rest in itertools.combinations(items[1:], s - 1):
        block = (first,) + rest
        remaining = [x for x in items if x not in block]
        for tail in set_partitions_with_sizes(remaining, sizes[1:]):
            yield [block] + tail

def vandermonde(block, nv):
    """prod_{c<c'} (v_{b_c'} - v_{b_c}) as a dict (block: list of variable indices, increasing)."""
    g = {tuple([0] * nv): 1}
    for a, b in itertools.combinations(sorted(block), 2):
        f = {}
        e = [0] * nv; e[b] = 1; f[tuple(e)] = 1
        e = [0] * nv; e[a] = 1; f[tuple(e)] = -1
        g = pmul(g, f)
    return g

def pair_factor(i, j, nv, q):
    f = {}
    for s in range(q):
        e = [0] * nv; e[i] = s; e[j] = q - 1 - s
        f[tuple(e)] = comb(q - 1, s) * ((-1) ** (q - 1 - s))
    return f

def tight_pattern_products(lam, alpha, beta, q):
    """all tight-pattern products of lam = (lp, lm) on x_0..x_{alpha-1}, z_0..z_{beta-1}."""
    lp, lm = lam; nv = alpha + beta
    sp, sm = sum(lp), sum(lm)
    npairs = alpha - sp
    assert npairs == beta - sm
    out = []
    xs = list(range(alpha)); zs = list(range(alpha, alpha + beta))
    for ux in itertools.combinations(xs, sp):
        mx = [x for x in xs if x not in ux]
        for uz in itertools.combinations(zs, sm):
            mz = [z for z in zs if z not in uz]
            for perm in itertools.permutations(mz):
                base = {tuple([0] * nv): 1}
                for i, j in zip(mx, perm): base = pmul(base, pair_factor(i, j, nv, q), box=q)
                colp, colm = columns(lp), columns(lm)
                # blocks: unordered among equal sizes -> we enumerate ordered lists and dedupe by frozenset of blocks
                seenx = set()
                for bx in set_partitions_with_sizes(list(ux), colp):
                    keyx = frozenset(bx)
                    if keyx in seenx: continue
                    seenx.add(keyx)
                    gx = base
                    for blk in bx: gx = pmul(gx, vandermonde(blk, nv), box=q)
                    seenz = set()
                    for bz in set_partitions_with_sizes(list(uz), colm):
                        keyz = frozenset(bz)
                        if keyz in seenz: continue
                        seenz.add(keyz)
                        g = gx
                        for blk in bz: g = pmul(g, vandermonde(blk, nv), box=q)
                        if g: out.append(g)
    return out

def ideal_dim_multidegree(gens, nv, q, p):
    """dimension of the homogeneous ideal generated by gens (any degrees) in F_p[v]/(v^q)."""
    bydeg = {}
    for g in gens:
        d = sum(next(iter(g)))
        for e in g: assert sum(e) == d
        bydeg.setdefault(d, []).append(g)
    if not bydeg: return 0, {}
    dmin, dmax = min(bydeg), nv * (q - 1)
    dims = {}
    mons = monomials(nv, q, dmin); idx = {e: i for i, e in enumerate(mons)}
    B = RREF(len(mons), p)
    C = np.zeros((len(bydeg[dmin]), len(mons)))
    for gi, g in enumerate(bydeg[dmin]):
        for e, c in g.items(): C[gi, idx[e]] = c % p
    B.insert_batch(C); dims[dmin] = B.dim()
    d = dmin
    while d < dmax:
        mons2 = monomials(nv, q, d + 1); idx2 = {e: i for i, e in enumerate(mons2)}
        B2 = RREF(len(mons2), p)
        if B.dim():
            for i in range(nv):
                src, dst = [], []
                for j, e in enumerate(mons):
                    if e[i] < q - 1:
                        e2 = list(e); e2[i] += 1; src.append(j); dst.append(idx2[tuple(e2)])
                Cc = np.zeros((B.dim(), len(mons2))); Cc[:, dst] = B.B[:, src]
                B2.insert_batch(Cc)
        if d + 1 in bydeg:
            C = np.zeros((len(bydeg[d + 1]), len(mons2)))
            for gi, g in enumerate(bydeg[d + 1]):
                for e, c in g.items(): C[gi, idx2[e]] = c % p
            B2.insert_batch(C)
        d += 1; mons, idx, B = mons2, idx2, B2; dims[d] = B.dim()
        if B.dim() == 0 and all(dd <= d for dd in bydeg): break
    return sum(dims.values()), dims

# ---------------- P1 / P2 combinatorial checks ----------------
def options(mu, q):
    """the q options (in chain order) when a new x-value is added to a tail of shape mu=(mp,mm)."""
    mp, mm = mu; lp, lm = len(mp), len(mm)
    opts = []
    for j in range(lp := len(mp)) if False else range(len(mm)):           # removals from lambda_-, rows 1..l_-
        new = list(mm); new[j] -= 1; new = tuple(sorted([x for x in new if x > 0], reverse=True))
        opts.append((mp, new))
    for _ in range(q - len(mp) - len(mm)):
        opts.append((tuple(sorted(mp + (1,), reverse=True)), mm))
    for j in range(len(mp) - 1, -1, -1):                                   # additions to lambda_+, rows l_+..1
        new = list(mp); new[j] += 1; new = tuple(sorted(new, reverse=True))
        opts.append((new, mm))
    assert len(opts) == q
    return opts

def check_P1_P2(alpha, beta, q, brute=True):
    """P1: the fibre of a tail depends only on its shape and equals the option count (brute force over points).
       P2: options are a chain, and opt_p is monotone in the product order (all comparable pairs)."""
    P = Par(alpha - 1, beta, q)
    # chain
    for mu in P:
        o = options(mu, q)
        for a, b in zip(o, o[1:]): assert leq(a, b), ("chain fails", mu, a, b)
        for o_ in o: assert (o_ in set(Par(alpha, beta, q))), ("option outside Par", mu, o_)
    # monotone
    n_cmp = 0
    for mu in P:
        for nu in P:
            if leq(mu, nu):
                om, on = options(mu, q), options(nu, q)
                for a, b in zip(om, on): assert leq(a, b), ("P2 fails", mu, nu, a, b)
                n_cmp += 1
    # P1 brute force: fibre of every tail equals {opt_p(shape(tail))}
    n_tails = 0
    if brute and q ** (alpha + beta) <= 400000:
        for xi in itertools.product(range(q), repeat=alpha - 1):
            for eta in itertools.product(range(q), repeat=beta):
                mu = shape(xi, eta, q)
                fib = Counter(shape(xi + (v,), eta, q) for v in range(q))
                assert fib == Counter(options(mu, q)), ("P1 fails", xi, eta, fib, options(mu, q))
                n_tails += 1
    return len(P), n_cmp, n_tails

if __name__ == "__main__":
    alpha, beta, q, p = map(int, sys.argv[1:5])
    t0 = time.time()
    nP, ncmp, ntails = check_P1_P2(alpha, beta, q)
    print(f"({alpha},{beta},q={q}) P1/P2: |Par(alpha-1,beta)| = {nP}, comparable pairs checked {ncmp}, tails checked {ntails}: OK")
    if '--p12-only' in sys.argv: sys.exit(0)
    P = Par(alpha, beta, q)
    D = downsets(P)
    pts = [(xi, eta) for xi in itertools.product(range(q), repeat=alpha) for eta in itertools.product(range(q), repeat=beta)]
    shapes = Counter(shape(xi, eta, q) for xi, eta in pts)
    assert set(shapes) <= set(P), set(shapes) - set(P)
    print(f"  |Par({alpha},{beta})| = {len(P)}: {P}\n  shape counts: {dict(shapes)}\n  down-sets: {len(D)}")
    nv = alpha + beta; fails = 0
    for Dset in D:
        Lam = [P[i] for i in sorted(Dset)]
        Z = sum(shapes[l] for l in Lam)
        gens = []
        for lam in Lam: gens += tight_pattern_products(lam, alpha, beta, q)
        dim, dims = ideal_dim_multidegree(gens, nv, q, p) if gens else (0, {})
        flag = "=" if dim == Z else (">" if dim > Z else "<  FAIL")
        if dim < Z: fails += 1
        print(f"    Lambda={Lam}: |Z|={Z} dim V={dim} {flag}  gens={len(gens)}")
    mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 2**20
    print(f"  RESULT ({alpha},{beta},q={q},p={p}): {len(D)} down-sets, failures of >=: {fails}; time {time.time()-t0:.1f}s maxrss {mem:.0f} MB")
