"""Direct check of (P3): for every down-set Lambda of Par_q(alpha,beta) and every i in 0..q-1,
every tight-pattern generator of V_{Lambda_i} (on the tail) lies in W_{q-1-i}(V_Lambda), the
slice of x_0-degree <= q-1-i.  Also checks the coverage formula (BP.1).
Usage: python3 bip_P3.py alpha beta q p
"""
import sys, itertools, time, resource
import numpy as np
from bip_family import Par, downsets, options, tight_pattern_products, shape, leq
from partB_engine import monomials, RREF, rref_rows

alpha, beta, q, p = map(int, sys.argv[1:5])
nv = alpha + beta
t0 = time.time()
P = Par(alpha, beta, q); Pt = Par(alpha - 1, beta, q)
D = downsets(P)

def bases_by_degree(gens):
    """RREF basis of the ideal generated by gens, per degree: {d: (mons, idx, B)}"""
    bydeg = {}
    for g in gens:
        d = sum(next(iter(g))); bydeg.setdefault(d, []).append(g)
    out = {}
    if not bydeg: return out
    dmin, dmax = min(bydeg), nv * (q - 1)
    mons = monomials(nv, q, dmin); idx = {e: i for i, e in enumerate(mons)}
    B = RREF(len(mons), p)
    C = np.zeros((len(bydeg[dmin]), len(mons)))
    for gi, g in enumerate(bydeg[dmin]):
        for e, c in g.items(): C[gi, idx[e]] = c % p
    B.insert_batch(C); out[dmin] = (mons, idx, B)
    d = dmin
    while d < dmax:
        mons2 = monomials(nv, q, d + 1); idx2 = {e: i for i, e in enumerate(mons2)}
        B2 = RREF(len(mons2), p)
        if B.dim():
            for i in range(nv):
                src, dst = [], []
                for j, e in enumerate(mons):
                    if e[i] < q - 1:
                        e2 = list(e); e2[i] += 1; src.append(j); dst.append(idx2[tuple(e2)])
                Cc = np.zeros((B.dim(), len(mons2))); Cc[:, dst] = B.B[:, src]
                B2.insert_batch(Cc)
        if d + 1 in bydeg:
            C = np.zeros((len(bydeg[d + 1]), len(mons2)))
            for gi, g in enumerate(bydeg[d + 1]):
                for e, c in g.items(): C[gi, idx2[e]] = c % p
            B2.insert_batch(C)
        d += 1; mons, idx, B = mons2, idx2, B2; out[d] = (mons, idx, B)
        if B.dim() == 0 and all(dd <= d for dd in bydeg): break
    return out

def slice_basis(bases, j, deg_tail):
    """W_j(V) in tail-degree deg_tail: rows over tail monomials (variables 1..nv-1) of degree deg_tail."""
    d = deg_tail + j
    if d not in bases: return None, None
    mons, idx, B = bases[d]
    if B.dim() == 0: return None, None
    high = [i for i, e in enumerate(mons) if e[0] > j]
    low = [i for i, e in enumerate(mons) if e[0] <= j]
    order = high + low
    M = B.B[:, order].copy()
    R, piv = rref_rows(M, p)
    nh = len(high)
    rows = [r for r, c in enumerate(piv) if c >= nh]       # pivots in the low part: zero on the high part
    tail_mons = monomials(nv - 1, q, deg_tail); tidx = {e: i for i, e in enumerate(tail_mons)}
    W = np.zeros((len(rows), len(tail_mons)))
    for wi, r in enumerate(rows):
        for k, i in enumerate(low):
            e = mons[i]
            if e[0] == j and R[r, nh + k]:
                W[wi, tidx[e[1:]]] = R[r, nh + k]
    return W, tidx

def F_Lambda(mu, Lam_set):
    return sum(1 for o in options(mu, q) if o in Lam_set)

n_checked = 0; n_fail = 0; n_cov_fail = 0
for Dset in D:
    Lam = [P[i] for i in sorted(Dset)]; Lam_set = set(Lam)
    gens = []
    for lam in Lam: gens += tight_pattern_products(lam, alpha, beta, q)
    bases = bases_by_degree(gens)
    # coverage formula (BP.1)
    for mu in Pt:
        mp, mm = mu; lp, lm = len(mp), len(mm)
        rem = [j for j in range(lm) if options(mu, q)[j] in Lam_set]
        r = len(rem)
        mid = (q - lp - lm) > 0 and ((tuple(sorted(mp + (1,), reverse=True)), mm) in Lam_set)
        adds = [j for j in range(lp) if (tuple(sorted([x + (1 if k == j else 0) for k, x in enumerate(mp)], reverse=True)), mm) in Lam_set]
        j0 = min(adds) + 1 if adds else None
        formula = r + (q - lp - lm) * (1 if mid else 0) + ((lp - j0 + 1) if j0 else 0)
        if formula != F_Lambda(mu, Lam_set): n_cov_fail += 1
    for i in range(q):
        Lam_i = [mu for mu in Pt if F_Lambda(mu, Lam_set) > i]
        # down-set check of the layer
        for mu in Lam_i:
            for nu in Pt:
                if leq(nu, mu) and nu not in Lam_i: print("  layer not a down-set!", Lam, i, mu, nu); n_fail += 1
        j = q - 1 - i - (1 if '--tight' in sys.argv else 0)
        if j < 0: continue
        for mu in Lam_i:
            for G in tight_pattern_products(mu, alpha - 1, beta, q):
                deg = sum(next(iter(G)))
                W, tidx = slice_basis(bases, j, deg)
                n_checked += 1
                if W is None or W.shape[0] == 0:
                    n_fail += 1; print("  FAIL (empty slice):", Lam, "i", i, "mu", mu); continue
                v = np.zeros(len(tidx))
                for e, c in G.items(): v[tidx[e]] = c % p
                Rw, pivw = rref_rows(W.copy(), p)
                res = np.mod(v - v[pivw] @ Rw, p)
                if res.any(): n_fail += 1; print("  FAIL (not in slice):", Lam, "i", i, "mu", mu)
mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 2**20
print(f"P3{' TIGHT(negative control)' if '--tight' in sys.argv else ''} ({alpha},{beta},q={q},p={p}): {len(D)} down-sets, {n_checked} (layer generator, slice) memberships checked, failures {n_fail}; "
      f"coverage-formula failures {n_cov_fail}; time {time.time()-t0:.1f}s maxrss {mem:.0f} MB")
