"""GATE G3: per-colouring dimensions computed DIRECTLY in R_c over F_{p^d}, k = 1.
Usage: python3 gate_G3.py m p
"""
import sys, itertools, time, resource
import numpy as np
from collections import Counter

m, p = int(sys.argv[1]), int(sys.argv[2])
q = 1
while m % (q * p) == 0: q *= p
r = m // q
d = 1
while (p ** d - 1) % r: d += 1
Nf = p ** d
t0 = time.time()

# ---------------- GF(p^d) via an irreducible polynomial and log tables ----------------
def poly_mod(a, f):          # a, f lists of coefficients low->high, f monic; returns a mod f (mod p)
    a = a[:]
    while len(a) >= len(f):
        c = a[-1] % p
        if c:
            for i in range(len(f)):
                a[len(a) - len(f) + i] = (a[len(a) - len(f) + i] - c * f[i]) % p
        a.pop()
    return [x % p for x in a]
def poly_mul(a, b):
    out = [0] * (len(a) + len(b) - 1)
    for i, x in enumerate(a):
        if x:
            for j, y in enumerate(b): out[i + j] = (out[i + j] + x * y) % p
    return out
def is_irreducible(f):
    deg = len(f) - 1
    for e in range(1, deg // 2 + 1):
        for coeffs in itertools.product(range(p), repeat=e):
            g = list(coeffs) + [1]
            if not any(poly_mod(f, g)): return False
    return True
if d == 1:
    f = [0, 1]  # unused
else:
    f = None
    for coeffs in itertools.product(range(p), repeat=d):
        cand = list(coeffs) + [1]
        if cand[0] != 0 and is_irreducible(cand): f = cand; break
def enc(poly):  # low->high digits to int
    poly = poly + [0] * (d - len(poly))
    return sum(int(c) * p ** i for i, c in enumerate(poly[:d]))
def dec(x): return [(x // p ** i) % p for i in range(d)]
def gf_mul_slow(x, y):
    if d == 1: return (x * y) % p
    return enc(poly_mod(poly_mul(dec(x), dec(y)), f))
# primitive element
def order(g):
    k, x = 1, g
    while x != 1:
        x = gf_mul_slow(x, g); k += 1
        if k > Nf: return None
    return k
gen = None
for g in range(2, Nf):
    if order(g) == Nf - 1: gen = g; break
exp = np.zeros(2 * Nf, dtype=np.int64); log = np.zeros(Nf, dtype=np.int64)
x = 1
for k in range(Nf - 1):
    exp[k] = x; log[x] = k; x = gf_mul_slow(x, gen)
exp[Nf - 1:2 * Nf - 2] = exp[:Nf - 1]
digits = np.array([dec(x) for x in range(Nf)], dtype=np.int64)          # Nf x d
weights = np.array([p ** i for i in range(d)], dtype=np.int64)
ADD = (((digits[:, None, :] + digits[None, :, :]) % p) * weights).sum(axis=2)   # Nf x Nf
NEG = (((-digits) % p) * weights).sum(axis=1)
MUL = np.zeros((Nf, Nf), dtype=np.int64)
nzs = np.arange(1, Nf)
MUL[1:, 1:] = exp[(log[nzs][:, None] + log[nzs][None, :]) % (Nf - 1)]
INV = np.zeros(Nf, dtype=np.int64); INV[1:] = exp[(-log[nzs]) % (Nf - 1)]
zeta = int(exp[(Nf - 1) // r])           # element of order r
mu_r = [1]
for _ in range(r - 1): mu_r.append(int(MUL[mu_r[-1], zeta]))
assert len(set(mu_r)) == r
# sanity of field tables
for a_ in range(Nf):
    assert MUL[a_, 1] == a_ and ADD[a_, 0] == a_ and ADD[a_, NEG[a_]] == 0
    if a_: assert MUL[a_, INV[a_]] == 1

# ---------------- truncated polynomials in u_1,u_2,u_3 over GF ----------------
shape = (q, q, q)
def zero(): return np.zeros(shape, dtype=np.int64)
def const(c): a = zero(); a[0, 0, 0] = c; return a
def var(i, c):  # t_i = u_i + c
    a = const(c); e = [0, 0, 0]; e[i] = 1; a[tuple(e)] = 1; return a
def pmul(a, b):
    out = zero()
    for ea in zip(*np.nonzero(a)):
        ca = a[ea]
        for eb in zip(*np.nonzero(b)):
            e = (ea[0] + eb[0], ea[1] + eb[1], ea[2] + eb[2])
            if max(e) >= q: continue
            out[e] = ADD[out[e], MUL[ca, b[eb]]]
    return out
def padd(a, b): return ADD[a, b]
def psub(a, b): return ADD[a, NEG[b]]
one = const(1)
def phi(u):
    acc = one.copy(); pw = one.copy()
    for _ in range(m - 1):
        pw = pmul(pw, u); acc = padd(acc, pw)
    return acc
matchings = [((0, 1), (2, 3)), ((0, 2), (1, 3)), ((0, 3), (1, 2))]

# ---------------- RREF over GF via tables ----------------
def rref_dim_closure(gens):
    """dimension of the ideal generated by gens in R_c (closure under u_1,u_2,u_3)."""
    size = q ** 3
    B = np.zeros((size, size), dtype=np.int64); piv = []; nrow = 0
    def reduce(v):
        v = v.copy()
        for j in range(nrow):
            c = v[piv[j]]
            if c:
                v = ADD[v, NEG[MUL[c, B[j]]]]
        return v
    def insert(v):
        nonlocal nrow
        v = reduce(v)
        nz = np.flatnonzero(v)
        if nz.size == 0: return False
        c = int(nz[0]); v = MUL[INV[v[c]], v]
        for j in range(nrow):
            cj = B[j, c]
            if cj: B[j] = ADD[B[j], NEG[MUL[cj, v]]]
        B[nrow] = v; piv.append(c); nrow += 1
        return True
    queue = []
    for g in gens:
        if insert(g.reshape(-1)): queue.append(B[nrow - 1].copy())
    qi = 0
    while qi < len(queue):
        w = queue[qi].reshape(shape); qi += 1
        for i in range(3):
            v = zero()
            sl_src = [slice(None)] * 3; sl_dst = [slice(None)] * 3
            sl_src[i] = slice(0, q - 1); sl_dst[i] = slice(1, q)
            v[tuple(sl_dst)] = w[tuple(sl_src)]
            if insert(v.reshape(-1)): queue.append(B[nrow - 1].copy())
    return nrow

# ---------------- expected block counts (k = 1) ----------------
def colour1_count(e):
    if e % 2: return 0
    return sum(1 for a in itertools.product(range(1, q), repeat=e) if all(Counter(a)[v] == Counter(a)[(-v) % q] for v in a))
def N_bal(a):
    return sum(1 for xi in itertools.product(range(q), repeat=a) for eta in itertools.product(range(q), repeat=a)
               if Counter(xi) == Counter((-v) % q for v in eta))
def N_ph(a):
    cnt = 0
    for xi in itertools.product(range(q), repeat=a + 1):
        cx = Counter(xi)
        for eta in itertools.product(range(q), repeat=a):
            ce = Counter((-v) % q for v in eta)
            if all(cx[v] >= ce[v] for v in ce): cnt += 1
    return cnt

total = 0; n_incompat_nonzero = 0; n_mismatch = 0; n_compat = 0
types = Counter()
for cidx in itertools.product(range(r), repeat=3):
    c = [mu_r[i] for i in cidx]
    c0idx = (-sum(cidx)) % r
    col = (c0idx,) + cidx
    cnt = Counter(col)
    compatible = cnt[0] % 2 == 0 and all(cnt[z] == cnt[(-z) % r] for z in range(1, r))
    t = [var(i, c[i]) for i in range(3)]          # t_1,t_2,t_3 as u_i + c_i
    T = {1: t[0], 2: t[1], 3: t[2]}
    gens = []
    for (j0, k0), (j1, k1) in matchings:
        psi = pmul(psub(T[k0], one), pmul(psub(T[k1], one), phi(pmul(T[j1], T[k1]))))
        gens.append(psi)
    allzero = all(not g.any() for g in gens)
    dim = 0 if allzero else rref_dim_closure(gens)
    if not compatible:
        if dim or not allzero: n_incompat_nonzero += 1
        continue
    n_compat += 1
    # expected: product of block counts
    E = cnt[0]; exp_dim = colour1_count(E)
    for z in range(1, (r + 1) // 2):
        a = cnt[z]
        if a == 0: continue
        if c0idx in (z, (r - z) % r): exp_dim *= N_ph(a - 1)
        else: exp_dim *= N_bal(a)
    types[(E, c0idx == 0, tuple(sorted((cnt[z], c0idx in (z, (r - z) % r)) for z in range(1, (r + 1) // 2) if cnt[z])))] += 1
    if dim != exp_dim:
        n_mismatch += 1; print("  MISMATCH at colouring", col, "dim", dim, "expected", exp_dim)
    total += dim
mem = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss / 2**20
print(f"G3 m={m} p={p} (q={q}, r={r}, field F_{Nf}): compatible colourings {n_compat}; "
      f"incompatible colourings with a non-zero image: {n_incompat_nonzero}; per-colouring mismatches: {n_mismatch}; "
      f"sum of dims = {total}  (|Gamma| = {3*(m-1)*(m-2)})   time {time.time()-t0:.1f}s maxrss {mem:.0f} MB")
print("  colouring types (|E|, 0 in E, pair blocks (size, 0 in block)) -> count:", dict(types))
