# Piece E3 checks (q_odd3.md): the odd box r = 3.  Box ring F_p[y_1..y_m]/(y_i^3), D(a,b) = a^2 - ab + b^2.
# (A) the count recursion of (i);  (B) dim I(m,J) against |Z_J^(m)| and the slice inclusions of (ii), on the computed slices;
# (C) the two identities of Case II, J = 1, and the explicit witnesses;  (D) (iv)-(vi): the generators of I(2k+1,1) are the D_J, and the number;
# (E) controls that can fail: a slice one step too low; I(m,0) without its Vandermonde generators; the wrong sign in D.
# The engine is the auditor's gate of 2 Oct (corpus4/regla298_sky/auditoria_T3.py), with an incremental span.
import sys, itertools
import numpy as np

def matchings(S, k):
    S = list(S)
    if k == 0: yield (); return
    if len(S) < 2 * k: return
    a = S[0]; rest = S[1:]
    for i, b in enumerate(rest):
        for M in matchings(rest[:i] + rest[i+1:], k - 1): yield ((a, b),) + M
    yield from matchings(rest, k)

class Box:
    def __init__(s, m, p, sign=-1): s.m, s.p, s.N, s.sign = m, p, 3 ** m, sign
    def mono(s, exps):
        A = np.zeros((3,) * s.m, dtype=np.int64); A[tuple(exps)] = 1; return A
    def var(s, i, e=1):
        x = [0] * s.m; x[i] = e; return s.mono(x)
    def mul(s, A, B):
        C = np.zeros_like(A)
        for idx in zip(*np.nonzero(B)):
            c = B[idx]; src = tuple(slice(0, 3 - d) for d in idx); dst = tuple(slice(d, 3) for d in idx)
            C[dst] += c * A[src]
        return C % s.p
    def D(s, a, b): return (s.var(a, 2) + s.sign * s.mul(s.var(a), s.var(b)) + s.var(b, 2)) % s.p
    def DP(s, P):
        A = s.mono([0] * s.m)
        for a, b in P: A = s.mul(A, s.D(a, b))
        return A
    def echelon(s, M):
        p = s.p; r = 0; piv = []
        for c in range(M.shape[1]):
            nz = np.flatnonzero(M[r:, c])
            if len(nz) == 0: continue
            i = nz[0] + r
            if i != r: M[[r, i]] = M[[i, r]]
            M[r] = (M[r] * pow(int(M[r, c]), -1, p)) % p
            o = np.flatnonzero(M[:, c]); o = o[o != r]
            if len(o): M[o] = (M[o] - M[o, c][:, None] * M[r][None, :]) % p
            piv.append(c); r += 1
            if r == M.shape[0]: break
        return M[:r], piv
    def span(s, gens):                     # reduced echelon basis of the ideal generated by gens, one generator at a time
        E = np.zeros((0, s.N), dtype=np.int64); piv = []
        for g in gens:
            rows = []
            for idx in itertools.product(range(3), repeat=s.m):
                src = tuple(slice(0, 3 - d) for d in idx); dst = tuple(slice(d, 3) for d in idx)
                C = np.zeros_like(g); C[dst] = g[src]
                if C.any(): rows.append(C.reshape(-1))
            if not rows: continue
            M = np.array(rows, dtype=np.int64) % s.p
            if len(piv): M = (M - np.rint(M[:, piv].astype(np.float64) @ E.astype(np.float64)).astype(np.int64)) % s.p   # entries < p^2 * 729: exact in float64
            M = M[M.any(axis=1)]
            if len(M) == 0: continue
            E, piv = s.echelon(np.vstack([E, M]))
        return E, piv
    def member(s, E, piv, v):
        v = v.reshape(-1) % s.p
        if len(piv): v = (v - v[piv] @ E) % s.p
        return not v.any()

def gens(R, m, J, vand=True):              # generators of I(m,J), as in the Setting of q_odd3.md
    idx = list(range(m)); out = []
    if J >= m: return [R.mono([0] * R.m)]
    if (m - J) % 2 == 0:
        for P in matchings(idx, (m - J) // 2): out.append(R.DP(P))
    elif J >= 1:
        p = (m - 1 - J) // 2
        for P in matchings(idx, p):
            used = {x for pr in P for x in pr}; free = [x for x in idx if x not in used]
            for a, b in itertools.combinations(free, 2): out.append(R.mul((R.var(b) - R.var(a)) % R.p, R.DP(P)))
        for P in matchings(idx, p + 1): out.append(R.DP(P))
    else:
        for c in idx:
            rest = [x for x in idx if x != c]
            for P in matchings(rest, len(rest) // 2): out.append(R.mul(R.var(c, 2), R.DP(P)))
        if vand:
            for a, b, c in itertools.combinations(idx, 3):
                rest = [x for x in idx if x not in (a, b, c)]
                V = R.mul(R.mul((R.var(b) - R.var(a)) % R.p, (R.var(c) - R.var(a)) % R.p), (R.var(c) - R.var(b)) % R.p)
                for P in matchings(rest, len(rest) // 2): out.append(R.mul(V, R.DP(P)))
    return out

def Zcount(m, J): return sum(1 for M in itertools.product((-1, 0, 1), repeat=m) if abs(sum(M)) <= J)

def slices(R, E):                           # W_0, W_1, W_2 (peeling the first variable), as echelon bases in the box of the others
    m = R.m; out = []; T = E.reshape((-1,) + (3,) * m); R2 = Box(m - 1, R.p); n1 = 3 ** (m - 1)
    M = np.concatenate([T[:, d].reshape(len(T), -1) for d in (2, 1, 0)], axis=1) % R.p
    Ech, piv = R2.echelon(M.copy()) if len(M) else (M, [])
    for j in range(3):
        blk = 2 - j
        rows = [row[blk * n1:(blk + 1) * n1] for row, pc in zip(Ech, piv) if pc // n1 == blk]
        W = np.array(rows, dtype=np.int64).reshape(-1, n1) if rows else np.zeros((0, n1), dtype=np.int64)
        out.append(R2.echelon(W.copy()) if len(W) else (W, []))
    return out

checks = bad = 0
def rec(ok, line):
    global checks, bad
    checks += 1; bad += (not ok)
    if not ok: print("  FAIL " + line, flush=True)

print("(A) the count recursion of (i)")
ZC = {(m, J): Zcount(m, J) for m in range(0, 9) for J in range(0, 11)}
for m in range(1, 9):
    for J in range(0, 10):
        ok = (ZC[m, J] == ZC[m-1, J+1] + ZC[m-1, J] + ZC[m-1, J-1]) if J >= 1 else (ZC[m, 0] == ZC[m-1, 1])
        rec(ok, f"recursion m={m} J={J}")
print(f"  m = 1..8, J = 0..9: {8*10} identities; |Z_1^(3)|, |Z_1^(5)|, |Z_1^(7)| = {ZC[3,1]}, {ZC[5,1]}, {ZC[7,1]}", flush=True)

print("(B) dimensions and slices")
nB = 0; nS = 0
for p, mmax in ((2, 6), (3, 6), (5, 5), (7, 5)):
    for m in range(1, mmax + 1):
        R = Box(m, p); R2 = Box(m - 1, p)
        for J in range(0, m + 1):
            E, piv = R.span(gens(R, m, J)); dim = len(piv); z = ZC[m, J]
            ok = (dim == z); line = f"p={p} m={m} J={J}: dim I = {dim}, |Z| = {z}"
            if J < m:
                W = slices(R, E)
                want = [(0, J - 1), (1, J), (2, J + 1)] if J >= 1 else [(2, 1)]
                for j, Jt in want:
                    inside = all(R2.member(W[j][0], W[j][1], g) for g in gens(R2, m - 1, Jt)); nS += 1
                    line += f" | W_{j} contains I({m-1},{Jt}): {inside}"; ok = ok and inside
                dims = [len(W[j][1]) for j in range(3)]; ok = ok and (sum(dims) == dim); line += f" | slice dims {dims}"
            nB += 1; rec(ok, line)
            if m >= 5 or not ok: print("  " + line, flush=True)
print(f"  {nB} ideals (p = 2, 3 with m <= 6; p = 5, 7 with m <= 5), {nS} slice inclusions", flush=True)

print("(C) the identities and witnesses of the proof (over F_10007, m = 5; index 1 of the file is index 0 here)")
R = Box(5, 10007); y = [R.var(i) for i in range(5)]; P = R.p
sub = lambda A, B: (A - B) % P
for (a, b, c) in [(1, 2, 3), (1, 3, 4), (2, 3, 4)]:
    lhs = R.var(c, 2); rhs = (R.mul(y[0], sub(y[c], y[0])) + R.D(0, c)) % P
    rec(np.array_equal(lhs, rhs), "y_c^2 identity")
    V = R.mul(R.mul(sub(y[b], y[a]), sub(y[c], y[a])), sub(y[c], y[b]))
    rhs = (R.mul(R.D(0, a), sub(y[c], y[b])) - R.mul(R.D(0, b), sub(y[c], y[a])) + R.mul(R.D(0, c), sub(y[b], y[a]))) % P
    rec(np.array_equal(V, rhs), "Vandermonde identity")
    lhs = sub(R.D(0, b), R.D(0, a)); rhs = (-R.mul(y[0], sub(y[b], y[a])) + sub(R.var(b, 2), R.var(a, 2))) % P
    rec(np.array_equal(lhs, rhs), "D(1,b) - D(1,a) identity")
    V1 = R.mul(R.mul(sub(y[a], y[0]), sub(y[b], y[0])), sub(y[b], y[a]))     # Delta(y_1, y_a, y_b)
    coef2 = V1[2].reshape(-1); want = sub(y[b], y[a])[0].reshape(-1)
    rec(np.array_equal(coef2, want), "y_1^2-coefficient of Delta(y_1,y_a,y_b)")
print("  y_c^2 = y_1(y_c - y_1) + D(1,c);  Delta(a,b,c) = D(1,a)(y_c-y_b) - D(1,b)(y_c-y_a) + D(1,c)(y_b-y_a);")
print("  D(1,b) - D(1,a) = -y_1(y_b-y_a) + y_b^2 - y_a^2;  [y_1^2] Delta(y_1,y_a,y_b) = y_b - y_a:  3 index triples each", flush=True)

print("(D) (iv)-(vi): the ideal of the matchings and the number")
def Qe4(k):   # 1 + sum_c C(2k+2, 2c) * C(2(k-c)+2, k-c+1)  (q_even_count.md (i), with Q_j(3) = C(2j+2, j+1))
    from math import comb
    return 1 + sum(comb(2*k + 2, 2*c) * comb(2*(k - c) + 2, k - c + 1) for c in range(k + 1))
for k in (0, 1, 2):
    m = 2*k + 1
    for p in (2, 3, 5):
        R = Box(m, p)
        # D_J over the matchings J of {0..2k+1} (index 0 is the extra point; variables are 1..2k+1 -> 0..2k here)
        DJ = []
        for J in matchings(list(range(2*k + 2)), k + 1):
            DJ.append(R.DP([(a - 1, b - 1) for a, b in J if a != 0]))
        E1, p1 = R.span(DJ); E2, p2 = R.span(gens(R, m, 1))
        same = (p1 == p2) and np.array_equal(E1, E2)
        z1 = ZC[m, 1]; zero_sum = sum(1 for M in itertools.product((-1, 0, 1), repeat=2*k + 2) if sum(M) == 0)
        ok = same and len(p1) == z1 == zero_sum == Qe4(k)
        rec(ok, f"k={k} p={p}")
        print(f"  k={k} p={p}: (D_J) = I({m},1): {same}; dim = {len(p1)}; |Z_1| = {z1}; tuples of sum 0 = {zero_sum}; Qe_k(4) = {Qe4(k)}", flush=True)

print("(E) controls")
f1 = n1 = 0
for p in (2, 3, 5):
    for m in range(2, 6):
        R = Box(m, p); R2 = Box(m - 1, p)
        for J in range(1, m):
            E, piv = R.span(gens(R, m, J)); W = slices(R, E)
            inside = all(R2.member(W[0][0], W[0][1], g) for g in gens(R2, m - 1, J)); n1 += 1; f1 += (not inside)
print(f"  W_0 contains I(m-1, J) (one step too far): false in {f1} of {n1} cases")
f2 = n2 = 0
for p in (2, 3, 5):
    for m in (3, 5):
        R = Box(m, p); E, piv = R.span(gens(R, m, 0, vand=False)); n2 += 1; f2 += (len(piv) < ZC[m, 0])
        print(f"  I({m},0) without the Vandermonde generators, p={p}: dim {len(piv)} against |Z| = {ZC[m,0]}")
print(f"  smaller than |Z| in {f2} of {n2} cases")
f3 = n3 = 0
for p in (2, 3, 5, 7):
    for m in (3, 5):
        R = Box(m, p, sign=+1); E, piv = R.span(gens(R, m, 1)); n3 += 1; f3 += (len(piv) != ZC[m, 1])
        print(f"  with a^2 + ab + b^2 in place of D, p={p}: dim I({m},1) = {len(piv)} against {ZC[m,1]}")
print(f"  differs in {f3} of {n3} cases")
print(f"checks {checks}, failures {bad}")
print("FIN-OK")
