# chkE4.py -- brute force for piece E4 (q_pow2_leading.md, Proposition 9.2 of PAPER_OFICIAL_v11).
# Grepy Chats, 2 Oct 2026.  Everything over F_2 (the generators have coefficients in F_2), except
# two integer controls.  Polynomials over F_2 are Python sets of exponent tuples (addition = XOR).
import itertools, random, sys, time
from math import comb, factorial

T0 = time.time()
NCHK = 0
NFAIL = 0
def chk(name, ok, extra=""):
    global NCHK, NFAIL
    NCHK += 1
    if not ok:
        NFAIL += 1
    print(("ok   " if ok else "FAIL ") + name + ((" | " + extra) if extra else ""), flush=True)

FIRED = []
def control(name, fired, extra=""):
    FIRED.append((name, fired))
    print(("CONTROL fires   " if fired else "CONTROL SILENT  ") + name + ((" | " + extra) if extra else ""), flush=True)

# ---------- polynomial arithmetic over F_2 in d variables, with a reduction rule ----------
def mul(A, B, red):
    R = set()
    for a in A:
        for b in B:
            e = red(tuple(x + y for x, y in zip(a, b)))
            if e is not None:
                R ^= {e}
    return R
def red_box(q):          # F_2[s]/(s_i^q)
    return lambda e: None if max(e, default=0) >= q else e
def red_wrap(q):         # F_2[t]/(t_i^q - 1)
    return lambda e: tuple(x % q for x in e)
def red_free(e):
    return e
def power(A, n, red, d):
    R = {tuple([0] * d)}
    for _ in range(n):
        R = mul(R, A, red)
    return R
def var(i, d):
    e = [0] * d; e[i] = 1
    return {tuple(e)}
def one(d):
    return {tuple([0] * d)}
def prod(L, red, d):
    R = one(d)
    for A in L:
        R = mul(R, A, red)
    return R
def lowest(A):
    if not A: return set(), None
    m = min(sum(e) for e in A)
    return {e for e in A if sum(e) == m}, m
def top(A):
    if not A: return set(), None
    m = max(sum(e) for e in A)
    return {e for e in A if sum(e) == m}, m

# ---------- dimension of the ideal generated by a list of elements ----------
def ideal_dim(gens, d, q, red, wrap=False):
    # rows = (monomial) * (generator), as bit rows over the monomial basis with exponents < q
    import numpy as np
    n = q ** d
    radix = np.array([q ** (d - 1 - i) for i in range(d)], dtype=np.int64)
    nus = np.array(list(itertools.product(range(q), repeat=d)), dtype=np.int64).reshape(-1, d)
    piv = {}
    for g in gens:
        if not g: continue
        G = np.array(sorted(g), dtype=np.int64).reshape(-1, d)
        for nu in nus:
            E = G + nu
            if wrap:
                E %= q
            else:
                E = E[(E < q).all(axis=1)]
                if E.shape[0] == 0: continue
            arr = np.zeros(n, dtype=np.uint8)
            arr[E @ radix] = 1
            r = int.from_bytes(np.packbits(arr).tobytes(), 'big')
            while r:
                h = r.bit_length() - 1
                p = piv.get(h)
                if p is None:
                    piv[h] = r; break
                r ^= p
    return len(piv)

def matchings(V):
    V = list(V)
    if not V:
        yield []; return
    a = V[0]
    for b in V[1:]:
        rest = [x for x in V if x != a and x != b]
        for M in matchings(rest):
            yield [(a, b)] + M

# ---------- the count Q^e_k(m) of q_even_count.md, two ways ----------
def QkEven(k, m):
    h = (m - 2) // 2
    tot = 0
    for c in range(k + 2):
        for b in itertools.product(range(2 * k + 3), repeat=h):
            if 2 * c + 2 * sum(b) == 2 * k + 2:
                den = factorial(2 * c)
                for x in b: den *= factorial(x) ** 2
                tot += factorial(2 * k + 2) // den
    return tot
def closed_count(k, m):      # tuples in (Z/m \ {0})^(2k+2) that split into pairs (u, -u)
    n = 0
    for g in itertools.product(range(1, m), repeat=2 * k + 2):
        ok = True
        for u in range(1, m):
            if u == (m - u) % m:
                if g.count(u) % 2: ok = False; break
            elif g.count(u) != g.count((m - u) % m): ok = False; break
        if ok: n += 1
    return n

# ================= (i) phi(u) = (u+1)^(q-1) in F_2[u] =================
for v in range(1, 7):
    q = 2 ** v
    phi = {(i,) for i in range(q)}
    chk(f"(i) phi_q(u) = (u+1)^(q-1) in F_2[u], q={q}", phi == power({(0,), (1,)}, q - 1, red_free, 1))
q = 6
control("(i) with q = 6 (not a power of 2)", {(i,) for i in range(q)} != power({(0,), (1,)}, q - 1, red_free, 1))

# ================= (v) b(a+b)^(q-1) = a b D(a,b) mod b^q, in F_2[a,b] =================
def Dab(q, A, B, red, d):
    R = set()
    for u in range(q - 1):
        R ^= mul(power(A, u, red, d), power(B, q - 2 - u, red, d), red)
    return R
for v in range(1, 6):
    q = 2 ** v
    redb = lambda e, q=q: None if e[1] >= q else e          # only b^q = 0
    a, b = var(0, 2), var(1, 2)
    lhs = mul(b, power(a ^ b, q - 1, redb, 2), redb)
    rhs = mul(mul(a, b, redb), Dab(q, a, b, redb, 2), redb)
    chk(f"(v) b(a+b)^(q-1) = a b D_q(a,b) mod b^q over F_2, q={q}", lhs == rhs)
    if q >= 2:
        rhs_wrong = mul(mul(a, b, redb), Dab(q + 1, a, b, redb, 2), redb)
        control(f"(v) with D of the box q instead of q-1, q={q}", lhs != rhs_wrong)

# ================= integer controls on the change of variables t = 1 + s =================
def pow1ps_mod(q, p):     # coefficients of (1+s)^q mod p, truncated at s^q
    return [comb(q, i) % p for i in range(q)]
for v in range(1, 6):
    q = 2 ** v
    chk(f"(ii) (1+s)^q = 1 in F_2[s]/(s^q), q={q}", pow1ps_mod(q, 2) == [1] + [0] * (q - 1))
control("(ii) q = 6 over F_2: (1+s)^6 = 1 mod s^6 ?", pow1ps_mod(6, 2) != [1] + [0] * 5)
control("(ii) q = 4 over F_3: (1+s)^4 = 1 mod s^4 ?", pow1ps_mod(4, 3) != [1, 0, 0, 0])

# ================= the cells =================
CELLS = [(0, 2), (0, 4), (0, 8), (1, 2), (1, 4), (1, 8), (1, 16), (2, 2), (2, 4), (3, 2)]
for (k, q) in CELLS:
    d = 2 * k + 1
    rb, rw = red_box(q), red_wrap(q)
    Js = list(matchings(range(2 * k + 2)))
    assert len(Js) == factorial(2 * k + 2) // (2 ** (k + 1) * factorial(k + 1))
    # variable of the vertex a >= 1 is the variable a-1
    t = lambda a: var(a - 1, d)
    psi_t, psi_s, form, LJ, YDJ, DJc, YwDJ = [], [], [], [], [], [], []
    Y = prod([var(i, d) for i in range(d)], rb, d)
    PW = {(i, x): power(var(i, d) ^ one(d), x, rb, d) for i in range(d) for x in range(q)}
    for J in Js:
        # psi_J in F_2[G] (literal, in t)
        f = one(d)
        for (a, b) in J:
            f = mul(f, t(b) ^ one(d), rw)
        for (a, b) in J:
            if a > 0:
                u = mul(t(a), t(b), rw)
                ph = set()
                for i in range(q):
                    ph ^= power(u, i, rw, d)
                f = mul(f, ph, rw)
        psi_t.append(f)
        # Theta(psi_J): substitute t_i = 1 + s_i
        g = set()
        for e in f:
            term = one(d)
            for i, x in enumerate(e):
                term = mul(term, PW[(i, x)], rb)
            g ^= term
        psi_s.append(g)
        # the formula of Step 1
        h = one(d)
        for (a, b) in J:
            h = mul(h, t(b), rb)
        for (a, b) in J:
            if a > 0:
                w = t(a) ^ t(b) ^ mul(t(a), t(b), rb)
                h = mul(h, power(w, q - 1, rb, d), rb)
        form.append(h)
        # L_J (as a polynomial, then reduced)
        L = one(d)
        for (a, b) in J:
            L = mul(L, t(b), red_free)
        for (a, b) in J:
            if a > 0:
                L = mul(L, power(t(a) ^ t(b), q - 1, red_free, d), red_free)
        Lb = {e for e in L if max(e) < q}
        LJ.append(Lb)
        # D_J in the box q (for Y*D_J) and in the box q-1 (the ideal of Theorem O)
        Dq = one(d); Dq1 = one(d)
        for (a, b) in J:
            if a > 0:
                Dq = mul(Dq, Dab(q, t(a), t(b), rb, d), rb)
                Dq1 = mul(Dq1, Dab(q, t(a), t(b), red_box(q - 1), d), red_box(q - 1))
        YDJ.append(mul(Y, Dq, rb))
        DJc.append(Dq1)
        Yw = one(d)
        for (a, b) in J:
            if a > 0:
                Yw = mul(Yw, mul(t(a), t(b), rb), rb)
        YwDJ.append(mul(Yw, Dq, rb))
    tag = f"(k,q)=({k},{q})"
    chk(f"(iii) Theta(psi_J) = formula of Step 1, all {len(Js)} matchings, {tag}", psi_s == form)
    low = [lowest(g) for g in psi_s]
    degL = (k + 1) + k * (q - 1)
    chk(f"(iv) lowest form of Theta(psi_J) is L_J, of degree (k+1)+k(q-1), {tag}",
        all(lo == L and (m == degL) and L for (lo, m), L in zip(low, LJ)))
    chk(f"(v) L_J = Y * D_J in B, {tag}", LJ == YDJ)
    if k >= 1:
        control(f"(v) with Y replaced by the product without s_(k_0), {tag}", LJ != YwDJ)
    dI_t = ideal_dim(psi_t, d, q, rw, wrap=True)
    dI_s = ideal_dim(psi_s, d, q, rb)
    dL = ideal_dim(LJ, d, q, rb)
    dD = ideal_dim(DJc, d, q - 1, red_box(q - 1)) if q >= 3 else (1 if any(DJc) else 0)
    N = QkEven(k, q)
    chk(f"(ii) dim of (psi_J) in F_2[G] = dim of (Theta psi_J) in B, {tag}", dI_t == dI_s, f"{dI_t}")
    chk(f"(vi) dim (D_J) C at box q-1 = dim (L_J) B, {tag}", dD == dL, f"{dD}")
    chk(f"(vi) dim (D_J) C <= dim I, {tag}", dD <= dI_t, f"{dD} <= {dI_t}")
    chk(f"(measured) dim I = QkEven(k,q), {tag}", dI_t == N, f"{dI_t} vs {N}")
    chk(f"(measured) dim (D_J) C = QkEven(k,q), {tag}", dD == N, f"{dD} vs {N}")
    if (k, q) in [(0, 2), (0, 4), (0, 8), (1, 2), (1, 4), (1, 8), (2, 2), (2, 4), (3, 2)]:
        chk(f"QkEven(k,q) = number of closed tuples, {tag}", closed_count(k, q) == N, f"{N}")
    print(f"   t={time.time()-T0:.1f}s", flush=True)

# ================= the general lemma on lowest forms (random test over F_2) =================
random.seed(20261002)
def rand_poly(d, e, nterms, mindeg):
    mons = [x for x in itertools.product(range(e), repeat=d) if sum(x) >= mindeg]
    return set(random.sample(mons, min(nterms, len(mons))))
ntr = 0; nbad = 0; nmix = 0; nmixbad = 0
for trial in range(400):
    d = random.choice([2, 3]); e = random.choice([2, 3, 4]) if d == 2 else random.choice([2, 3])
    rb = red_box(e)
    s = random.choice([1, 2, 3])
    fs = [rand_poly(d, e, random.randint(1, 4), random.choice([0, 1, 1, 2])) for _ in range(s)]
    fs = [f for f in fs if f]
    if not fs: continue
    dI = ideal_dim(fs, d, e, rb)
    lows = [lowest(f)[0] for f in fs]
    ntr += 1
    if ideal_dim(lows, d, e, rb) > dI: nbad += 1
    mixed = [(lowest(f)[0] if i % 2 == 0 else top(f)[0]) for i, f in enumerate(fs)]
    nmix += 1
    if ideal_dim(mixed, d, e, rb) > dI: nmixbad += 1
chk(f"(iv, general lemma) dim (lowest forms) <= dim I in {ntr} random ideals of F_2[s]/(s^e)", nbad == 0, f"failures {nbad}")
control(f"(iv) mixing lowest and top forms, {nmix} random ideals", nmixbad > 0, f"violations {nmixbad}")
# a second random control, built so that it can fail: f and x*f, lowest form of one and top form of the other
nc = 0; ncbad = 0
for trial in range(400):
    d = 2; e = random.choice([3, 4, 5]); rb = red_box(e)
    f = rand_poly(d, e, random.randint(2, 4), 1)
    if len({sum(x) for x in f}) < 2: continue
    x = {tuple(random.choice([(1, 0), (0, 1)]))}
    f2 = mul(x, f, rb)
    if not f2: continue
    dI = ideal_dim([f, f2], d, e, rb)
    nc += 1
    if ideal_dim([lowest(f)[0], top(f2)[0]], d, e, rb) > dI: ncbad += 1
control(f"(iv) lowest form of f and top form of x*f, {nc} random pairs", ncbad > 0, f"violations {ncbad}")
# the explicit example: f1 = s1 + s2^2, f2 = s2*f1 in F_2[s1,s2]/(s^4)
rb = red_box(4)
f1 = {(1, 0), (0, 2)}; f2 = mul({(0, 1)}, f1, rb)
dI = ideal_dim([f1, f2], 2, 4, rb)
dm = ideal_dim([lowest(f1)[0], top(f2)[0]], 2, 4, rb)
control("(iv) explicit: f1 = s1 + s2^2, f2 = s2 f1, lowest(f1) and top(f2)", dm > dI, f"{dm} > {dI}")

print()
print(f"CHECKS {NCHK}  FAILURES {NFAIL}")
print(f"CONTROLS {len(FIRED)}  FIRED {sum(1 for _, x in FIRED if x)}")
print(f"time {time.time()-T0:.1f}s")
print("FIN-OK")
