module

public import RequestProject.ColTensor.Box

/-!
# Box rings over a partition of the variables: Lemma 6.4 (iii) and (iv) (`q_col_tensor.md`)

This file formalizes parts **(iii)** (two blocks) and **(iv)** (finitely many blocks) of
**Lemma 6.4** of `q_col_tensor.md`. Dimensions of ideals are `Module.finrank F` of the ideals
regarded as `F`-subspaces.
-/

@[expose] public section

open scoped TensorProduct

namespace ColTensor

variable {F : Type*} [Field F]

/-- **Proof of Lemma 6.4 (iii)** of `q_col_tensor.md`: an `F`-algebra isomorphism maps an ideal
onto an ideal of the same dimension. -/
theorem finrank_map_algEquiv {A B : Type*} [CommRing A] [CommRing B] [Algebra F A] [Algebra F B]
    (φ : A ≃ₐ[F] B) (J : Ideal A) :
    Module.finrank F (J.map φ) = Module.finrank F J := by
  have h : (J.map φ).restrictScalars F =
      (J.restrictScalars F).map φ.toLinearEquiv.toLinearMap := by
    ext y
    simp only [Submodule.restrictScalars_mem, Ideal.mem_map_of_equiv, Submodule.mem_map]
    rfl
  change Module.finrank F ((J.map φ).restrictScalars F) =
    Module.finrank F (J.restrictScalars F)
  rw [h, LinearEquiv.finrank_map_eq]

/-- **Proof of Lemma 6.4 (iv)** of `q_col_tensor.md` (case `s = 0`): the unit ideal of an
`F`-algebra `R` has the dimension of `R`. -/
theorem finrank_top_ideal {R : Type*} [CommRing R] [Algebra F R] :
    Module.finrank F (⊤ : Ideal R) = Module.finrank F R :=
  ((Submodule.topEquiv).restrictScalars F).finrank_eq

variable {d : ℕ} (S : BoxSetting F d)

namespace BoxSetting

/-- **Lemma 6.4 (iii)** of `q_col_tensor.md` (two blocks): if `W = W_1 ⊔ W_2` (disjoint union)
and `I_1 = (E_1) ⊆ B(W_1)`, `I_2 = (E_2) ⊆ B(W_2)`, then the ideal of `B(W)` generated by
`{ι_{W_1,W}(e_1)·ι_{W_2,W}(e_2) : e_1 ∈ E_1, e_2 ∈ E_2}` has dimension `dim I_1 · dim I_2`. -/
theorem lemma64_iii (W₁ W₂ W : Finset (Fin d)) (hW : W = W₁ ∪ W₂) (hd : Disjoint W₁ W₂)
    (E₁ : Set (S.Box W₁)) (E₂ : Set (S.Box W₂)) :
    Module.finrank F (Ideal.span {x : S.Box W | ∃ e₁ ∈ E₁, ∃ e₂ ∈ E₂,
      x = S.iota W₁ W (hW ▸ Finset.subset_union_left) e₁ *
        S.iota W₂ W (hW ▸ Finset.subset_union_right) e₂}) =
      Module.finrank F (Ideal.span E₁) * Module.finrank F (Ideal.span E₂) := by
  have hset : {x : S.Box W | ∃ e₁ ∈ E₁, ∃ e₂ ∈ E₂,
      x = S.iota W₁ W (hW ▸ Finset.subset_union_left) e₁ *
        S.iota W₂ W (hW ▸ Finset.subset_union_right) e₂} =
      S.splitEquiv W₁ W₂ W hW hd '' tensorGens (F := F) E₁ E₂ := by
    ext x
    constructor
    · rintro ⟨e₁, he₁, e₂, he₂, rfl⟩
      exact ⟨e₁ ⊗ₜ e₂, ⟨e₁, he₁, e₂, he₂, rfl⟩, S.splitEquiv_tmul _ _ _ _ _ _ _⟩
    · rintro ⟨_, ⟨e₁, he₁, e₂, he₂, rfl⟩, rfl⟩
      exact ⟨e₁, he₁, e₂, he₂, S.splitEquiv_tmul _ _ _ _ _ _ _⟩
  rw [hset, ← Ideal.map_span]
  rw [finrank_map_algEquiv (S.splitEquiv W₁ W₂ W hW hd)
    (Ideal.span (tensorGens (F := F) E₁ E₂))]
  exact finrank_span_tensorGens E₁ E₂

/-- **Proof of Lemma 6.4 (iv)** of `q_col_tensor.md`: `ι_{W',W}` extended by `0` to the case
`W' ⊄ W` (used only for `W' ⊆ W`, where it is `ι_{W',W}`). -/
noncomputable def iotaFun (W' W : Finset (Fin d)) (x : S.Box W') : S.Box W :=
  if h : W' ⊆ W then S.iota W' W h x else 0

/-- **Proof of Lemma 6.4 (iv)** of `q_col_tensor.md`: for `W' ⊆ W`, the extension by `0` agrees
with `ι_{W',W}`. -/
theorem iotaFun_eq {W' W : Finset (Fin d)} (h : W' ⊆ W) (x : S.Box W') :
    S.iotaFun W' W x = S.iota W' W h x := dif_pos h

/-- **Proof of Lemma 6.4 (iv)** of `q_col_tensor.md`: `ι_{W',W} ∘ ι_{W'',W'} = ι_{W'',W}`,
stated for the extension by `0`. -/
theorem iota_iotaFun {W'' W' W : Finset (Fin d)} (h₁ : W'' ⊆ W') (h₂ : W' ⊆ W)
    (x : S.Box W'') : S.iota W' W h₂ (S.iotaFun W'' W' x) = S.iotaFun W'' W x := by
  rw [S.iotaFun_eq h₁, S.iotaFun_eq (h₁.trans h₂), iota_iota]

/-- **Proof of Lemma 6.4 (iv)** of `q_col_tensor.md` (case `s = 0`): `B(∅) = F` has dimension
`1`. -/
theorem finrank_box_of_eq_empty {W : Finset (Fin d)} (hW : W = ∅) :
    Module.finrank F (S.Box W) = 1 := by
  subst hW
  have hbot : S.boxIdeal ∅ = ⊥ := by
    rw [boxIdeal, Set.range_eq_empty, Ideal.span_empty]
  haveI : Nontrivial (S.Box ∅) :=
    Ideal.Quotient.nontrivial_iff.2 (by rw [hbot]; exact bot_ne_top)
  have hbij : Function.Bijective (Algebra.ofId F (S.Box ∅)) := by
    refine ⟨(algebraMap F (S.Box ∅)).injective, ?_⟩
    intro x
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
    refine ⟨MvPolynomial.coeff 0 p, ?_⟩
    conv_rhs => rw [MvPolynomial.eq_C_of_isEmpty p]
    rfl
  rw [← (AlgEquiv.ofBijective _ hbij).toLinearEquiv.finrank_eq, Module.finrank_self]

variable {ι : Type*} (Wb : ι → Finset (Fin d)) (E : (j : ι) → Set (S.Box (Wb j)))

/-- **Proof of Lemma 6.4 (iv)** of `q_col_tensor.md`: the generators
`Π_{j ∈ s} ι_{W_j,W}(e_j)` for a finite set `s` of blocks, with `W = ⋃_{j ∈ s} W_j`. -/
def blockGens (s : Finset ι) : Set (S.Box (s.biUnion Wb)) :=
  {x | ∃ e : (j : ι) → S.Box (Wb j), (∀ j ∈ s, e j ∈ E j) ∧
    x = ∏ j ∈ s, S.iotaFun (Wb j) (s.biUnion Wb) (e j)}

/-- **Proof of Lemma 6.4 (iv)** of `q_col_tensor.md` (induction on the number of blocks). -/
theorem finrank_span_blockGens (hdisj : Pairwise fun j k => Disjoint (Wb j) (Wb k))
    (s : Finset ι) :
    Module.finrank F (Ideal.span (S.blockGens Wb E s)) =
      ∏ j ∈ s, Module.finrank F (Ideal.span (E j)) := by
  classical
  induction s using Finset.induction_on with
  | empty =>
    have h1 : S.blockGens Wb E ∅ = {1} := by
      ext x
      simp only [blockGens, Finset.notMem_empty, IsEmpty.forall_iff, implies_true,
        Finset.prod_empty, true_and, Set.mem_setOf_eq, Set.mem_singleton_iff]
      exact ⟨fun ⟨_, h⟩ => h, fun h => ⟨fun _ => 0, h⟩⟩
    rw [h1, Ideal.span_singleton_one, Finset.prod_empty, finrank_top_ideal]
    exact S.finrank_box_of_eq_empty (Finset.biUnion_empty)
  | insert a s ha ih =>
    have hW : (insert a s).biUnion Wb = Wb a ∪ s.biUnion Wb := Finset.biUnion_insert
    have hd : Disjoint (Wb a) (s.biUnion Wb) :=
      (Finset.disjoint_biUnion_right _ _ _).2 fun j hj =>
        hdisj fun h => ha (by rw [h]; exact hj)
    have hsub : ∀ j ∈ s, Wb j ⊆ s.biUnion Wb := fun j hj => Finset.subset_biUnion_of_mem Wb hj
    have hkey : ∀ e : (j : ι) → S.Box (Wb j),
        ∏ j ∈ insert a s, S.iotaFun (Wb j) ((insert a s).biUnion Wb) (e j) =
          S.iota (Wb a) _ (hW ▸ Finset.subset_union_left) (e a) *
            S.iota (s.biUnion Wb) _ (hW ▸ Finset.subset_union_right)
              (∏ j ∈ s, S.iotaFun (Wb j) (s.biUnion Wb) (e j)) := by
      intro e
      rw [Finset.prod_insert ha, map_prod, S.iotaFun_eq (hW ▸ Finset.subset_union_left)]
      congr 1
      exact Finset.prod_congr rfl fun j hj => (S.iota_iotaFun (hsub j hj) _ _).symm
    have hset : S.blockGens Wb E (insert a s) =
        {x | ∃ e₁ ∈ E a, ∃ e₂ ∈ S.blockGens Wb E s,
          x = S.iota (Wb a) _ (hW ▸ Finset.subset_union_left) e₁ *
            S.iota (s.biUnion Wb) _ (hW ▸ Finset.subset_union_right) e₂} := by
      ext x
      constructor
      · rintro ⟨e, he, rfl⟩
        exact ⟨e a, he a (Finset.mem_insert_self a s), _,
          ⟨e, fun j hj => he j (Finset.mem_insert_of_mem hj), rfl⟩, hkey e⟩
      · rintro ⟨e₁, he₁, _, ⟨e, he, rfl⟩, rfl⟩
        refine ⟨Function.update e a e₁, fun j hj => ?_, ?_⟩
        · rcases Finset.mem_insert.1 hj with rfl | hj
          · simpa using he₁
          · rw [Function.update_of_ne (fun h => ha (by rw [← h]; exact hj))]
            exact he j hj
        · rw [hkey, Function.update_self]
          congr 2
          exact Finset.prod_congr rfl fun j hj => by
            rw [Function.update_of_ne (fun h => ha (by rw [← h]; exact hj))]
    rw [hset, S.lemma64_iii _ _ _ hW hd, ih, Finset.prod_insert ha]

/-- **Lemma 6.4 (iv)** of `q_col_tensor.md` (finitely many blocks): let `W = ⊔_j W_j` be a
partition of `W` into pairwise disjoint blocks `W_j` (`j` ranging over a finite type; no block
for the empty index type, where `W = ∅`), and let `I_j = (E_j) ⊆ B(W_j)`. Then the ideal of `B(W)`
generated by `{Π_j ι_{W_j,W}(e_j) : e_j ∈ E_j for every j}` has dimension `Π_j dim I_j`. -/
theorem lemma64_iv [Fintype ι] (hdisj : Pairwise fun j k => Disjoint (Wb j) (Wb k))
    (W : Finset (Fin d)) (hW : W = Finset.univ.biUnion Wb) :
    Module.finrank F (Ideal.span {x : S.Box W | ∃ e : (j : ι) → S.Box (Wb j),
      (∀ j, e j ∈ E j) ∧
        x = ∏ j, S.iota (Wb j) W (hW ▸ Finset.subset_biUnion_of_mem Wb (Finset.mem_univ j))
          (e j)}) =
      ∏ j, Module.finrank F (Ideal.span (E j)) := by
  subst hW
  have hset : {x : S.Box (Finset.univ.biUnion Wb) | ∃ e : (j : ι) → S.Box (Wb j),
      (∀ j, e j ∈ E j) ∧
        x = ∏ j, S.iota (Wb j) _ (Finset.subset_biUnion_of_mem Wb (Finset.mem_univ j))
          (e j)} = S.blockGens Wb E Finset.univ := by
    ext x
    constructor
    · rintro ⟨e, he, rfl⟩
      exact ⟨e, fun j _ => he j, Finset.prod_congr rfl fun j _ => (S.iotaFun_eq _ _).symm⟩
    · rintro ⟨e, he, rfl⟩
      exact ⟨e, fun j => he j (Finset.mem_univ j),
        Finset.prod_congr rfl fun j _ => S.iotaFun_eq _ _⟩
  rw [hset, S.finrank_span_blockGens Wb E hdisj Finset.univ]

/-- **Lemma 6.4 (iv)** of `q_col_tensor.md` with the blocks indexed by `{1, …, s}` (here
`Fin s`), exactly as in the source: for a partition `W = W_1 ⊔ ⋯ ⊔ W_s` into pairwise disjoint
sets (`s ≥ 0`; for `s = 0`, `W = ∅`) and ideals `I_j = (E_j) ⊆ B(W_j)`, the ideal of `B(W)`
generated by `{Π_{j=1}^{s} ι_{W_j,W}(e_j) : e_j ∈ E_j}` has dimension `Π_{j=1}^{s} dim I_j`. -/
theorem lemma64_iv_fin (s : ℕ) (Wb : Fin s → Finset (Fin d))
    (E : (j : Fin s) → Set (S.Box (Wb j)))
    (hdisj : Pairwise fun j k => Disjoint (Wb j) (Wb k))
    (W : Finset (Fin d)) (hW : W = Finset.univ.biUnion Wb) :
    Module.finrank F (Ideal.span {x : S.Box W | ∃ e : (j : Fin s) → S.Box (Wb j),
      (∀ j, e j ∈ E j) ∧
        x = ∏ j, S.iota (Wb j) W (hW ▸ Finset.subset_biUnion_of_mem Wb (Finset.mem_univ j))
          (e j)}) =
      ∏ j, Module.finrank F (Ideal.span (E j)) :=
  S.lemma64_iv Wb E hdisj W hW

end BoxSetting

end ColTensor
