module

public import Mathlib

/-!
# Tensor products of ideals: Lemma 6.4 (i) and (v) (`q_col_tensor.md`)

This file formalizes parts **(i)** (tensor products of ideals) and **(v)** (units) of
**Lemma 6.4** of `q_col_tensor.md`.

Conventions: `F` is a field, all algebras are commutative `F`-algebras, all tensor products are
over `F`, and the dimension `dim I` of an ideal `I` of an `F`-algebra is `Module.finrank F I`,
the `F`-dimension of `I` regarded as an `F`-subspace.
-/

@[expose] public section

open scoped TensorProduct

namespace ColTensor

variable {F : Type*} [Field F]

section PartI

variable {A A' : Type*} [CommRing A] [Algebra F A] [CommRing A'] [Algebra F A']

/-- The `F`-linear map `I ⊗ I' → A ⊗ A'` of **Lemma 6.4 (i)** of `q_col_tensor.md`, induced by
the inclusions `I ⊆ A` and `I' ⊆ A'` of two ideals. -/
noncomputable def idealTensorMap (I : Ideal A) (I' : Ideal A') :
    (I.restrictScalars F) ⊗[F] (I'.restrictScalars F) →ₗ[F] A ⊗[F] A' :=
  TensorProduct.map (I.restrictScalars F).subtype (I'.restrictScalars F).subtype

/-- The generating set `{e ⊗ e' : e ∈ E, e' ∈ E'}` of **Lemma 6.4 (i)** of `q_col_tensor.md`. -/
def tensorGens (E : Set A) (E' : Set A') : Set (A ⊗[F] A') :=
  {x | ∃ e ∈ E, ∃ e' ∈ E', x = e ⊗ₜ[F] e'}

/-- **Proof of Lemma 6.4 (i)** of `q_col_tensor.md`: for `x ∈ (E)` and `x' ∈ (E')`, the pure
tensor `x ⊗ x'` lies in the ideal generated by the `e ⊗ e'`. -/
theorem tmul_mem_span_tensorGens (E : Set A) (E' : Set A') {x : A} {x' : A'}
    (hx : x ∈ Ideal.span E) (hx' : x' ∈ Ideal.span E') :
    x ⊗ₜ[F] x' ∈ Ideal.span (tensorGens (F := F) E E') := by
  induction hx using Submodule.span_induction with
  | mem e he =>
    induction hx' using Submodule.span_induction with
    | mem e' he' => exact Ideal.subset_span ⟨e, he, e', he', rfl⟩
    | zero => simp
    | add a b _ _ ha hb => rw [TensorProduct.tmul_add]; exact Ideal.add_mem _ ha hb
    | smul a b _ hb =>
      have : e ⊗ₜ[F] (a • b) = ((1 : A) ⊗ₜ[F] a) * (e ⊗ₜ[F] b) := by
        simp [Algebra.TensorProduct.tmul_mul_tmul]
      rw [this]; exact Ideal.mul_mem_left _ _ hb
  | zero => simp
  | add a b _ _ ha hb => rw [TensorProduct.add_tmul]; exact Ideal.add_mem _ ha hb
  | smul a b _ hb =>
    have : (a • b) ⊗ₜ[F] x' = (a ⊗ₜ[F] (1 : A')) * (b ⊗ₜ[F] x') := by
      simp [Algebra.TensorProduct.tmul_mul_tmul]
    rw [this]; exact Ideal.mul_mem_left _ _ hb

/-- **Proof of Lemma 6.4 (i)** of `q_col_tensor.md`: the image `M` of `I ⊗ I' → A ⊗ A'` is
stable under multiplication by `A ⊗ A'` (it is an ideal). -/
theorem mul_mem_range_idealTensorMap (I : Ideal A) (I' : Ideal A') (a : A ⊗[F] A')
    {y : A ⊗[F] A'} (hy : y ∈ LinearMap.range (idealTensorMap (F := F) I I')) :
    a * y ∈ LinearMap.range (idealTensorMap (F := F) I I') := by
  obtain ⟨z, rfl⟩ := hy
  induction a using TensorProduct.induction_on with
  | zero => simp
  | add a b ha hb => rw [add_mul]; exact Submodule.add_mem _ ha hb
  | tmul r r' =>
    induction z using TensorProduct.induction_on with
    | zero => simp
    | add a b ha hb => rw [map_add, mul_add]; exact Submodule.add_mem _ ha hb
    | tmul x x' =>
      refine ⟨(⟨r * x, I.mul_mem_left r x.2⟩ : I.restrictScalars F) ⊗ₜ
        (⟨r' * x', I'.mul_mem_left r' x'.2⟩ : I'.restrictScalars F), ?_⟩
      simp [idealTensorMap, Algebra.TensorProduct.tmul_mul_tmul]

/-- **Proof of Lemma 6.4 (i)** of `q_col_tensor.md` (image; the finiteness hypotheses are not
needed): the ideal generated by the `e ⊗ e'` is the image of `(E) ⊗ (E') → A ⊗ A'`. -/
theorem span_tensorGens_eq_range (E : Set A) (E' : Set A') :
    (Ideal.span (tensorGens (F := F) E E')).restrictScalars F =
      LinearMap.range (idealTensorMap (F := F) (Ideal.span E) (Ideal.span E')) := by
  apply le_antisymm
  · intro y hy
    change y ∈ Ideal.span _ at hy
    induction hy using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨e, he, e', he', rfl⟩ := hx
      exact ⟨(⟨e, Ideal.subset_span he⟩ : (Ideal.span E).restrictScalars F) ⊗ₜ
        (⟨e', Ideal.subset_span he'⟩ : (Ideal.span E').restrictScalars F), rfl⟩
    | zero => exact Submodule.zero_mem _
    | add a b _ _ ha hb => exact Submodule.add_mem _ ha hb
    | smul a b _ hb => exact mul_mem_range_idealTensorMap _ _ a hb
  · rintro y ⟨z, rfl⟩
    change _ ∈ Ideal.span _
    induction z using TensorProduct.induction_on with
    | zero => simp
    | add a b ha hb => rw [map_add]; exact Ideal.add_mem _ ha hb
    | tmul x x' => exact tmul_mem_span_tensorGens E E' x.2 x'.2

/-- **Proof of Lemma 6.4 (i)** of `q_col_tensor.md` (injectivity; the finiteness hypotheses are
not needed): over a field every module is flat, so `I ⊗ I' → A ⊗ A'` is injective. -/
theorem idealTensorMap_injective (I : Ideal A) (I' : Ideal A') :
    Function.Injective (idealTensorMap (F := F) I I') :=
  TensorProduct.map_injective_of_flat_flat _ _ (Submodule.injective_subtype _)
    (Submodule.injective_subtype _)

/-- **Proof of Lemma 6.4 (i)** of `q_col_tensor.md` (dimension; the finiteness hypotheses are not
needed): the ideal generated by the `e ⊗ e'` has dimension `dim (E) · dim (E')`. -/
theorem finrank_span_tensorGens (E : Set A) (E' : Set A') :
    Module.finrank F (Ideal.span (tensorGens (F := F) E E')) =
      Module.finrank F (Ideal.span E) * Module.finrank F (Ideal.span E') := by
  have h1 : Module.finrank F (Ideal.span (tensorGens (F := F) E E')) =
      Module.finrank F ((Ideal.span (tensorGens (F := F) E E')).restrictScalars F) := rfl
  rw [h1, span_tensorGens_eq_range, ← LinearEquiv.finrank_eq
    (LinearEquiv.ofInjective _ (idealTensorMap_injective _ _)), Module.finrank_tensorProduct]
  rfl

/-- **Lemma 6.4 (i)** of `q_col_tensor.md` (image): for finite-dimensional algebras `A`, `A'` and
ideals `I = (E) ⊆ A`, `I' = (E') ⊆ A'`, the ideal of `A ⊗ A'` generated by
`{e ⊗ e' : e ∈ E, e' ∈ E'}` is (as an `F`-subspace) the image of `I ⊗ I' → A ⊗ A'`. (The
finite-dimensionality hypotheses of the source are kept but are not used, see
`span_tensorGens_eq_range`.) -/
theorem lemma64_i_range [FiniteDimensional F A] [FiniteDimensional F A']
    (E : Set A) (E' : Set A') :
    (Ideal.span (tensorGens (F := F) E E')).restrictScalars F =
      LinearMap.range (idealTensorMap (F := F) (Ideal.span E) (Ideal.span E')) :=
  span_tensorGens_eq_range E E'

/-- **Lemma 6.4 (i)** of `q_col_tensor.md` (injectivity): for finite-dimensional algebras `A`,
`A'` and ideals `I = (E) ⊆ A`, `I' = (E') ⊆ A'`, the map `I ⊗ I' → A ⊗ A'` is injective. (The
finite-dimensionality hypotheses of the source are kept but are not used, see
`idealTensorMap_injective`.) -/
theorem lemma64_i_injective [FiniteDimensional F A] [FiniteDimensional F A']
    (E : Set A) (E' : Set A') :
    Function.Injective (idealTensorMap (F := F) (Ideal.span E) (Ideal.span E')) :=
  idealTensorMap_injective _ _

/-- **Lemma 6.4 (i)** of `q_col_tensor.md` (dimension): for finite-dimensional algebras `A`, `A'`,
the ideal of `A ⊗ A'` generated by `{e ⊗ e' : e ∈ E, e' ∈ E'}` has dimension `dim I · dim I'`,
where `I = (E)` and `I' = (E')`. (The finite-dimensionality hypotheses of the source are kept but
are not used, see `finrank_span_tensorGens`.) -/
theorem lemma64_i_finrank [FiniteDimensional F A] [FiniteDimensional F A']
    (E : Set A) (E' : Set A') :
    Module.finrank F (Ideal.span (tensorGens (F := F) E E')) =
      Module.finrank F (Ideal.span E) * Module.finrank F (Ideal.span E') :=
  finrank_span_tensorGens E E'

end PartI

/-- **Lemma 6.4 (v)** of `q_col_tensor.md` (units): if every generator `e ∈ E` of an ideal is
multiplied by a unit `u e` of the ring, the ideal generated does not change. -/
theorem lemma64_v {R : Type*} [CommRing R] (E : Set R) (u : R → Rˣ) :
    Ideal.span ((fun e => (u e : R) * e) '' E) = Ideal.span E := by
  apply le_antisymm
  · rw [Ideal.span_le]
    rintro _ ⟨e, he, rfl⟩
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span he)
  · rw [Ideal.span_le]
    intro e he
    have : e = ((u e)⁻¹ : Rˣ) * ((u e : R) * e) := by simp
    rw [this]
    exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨e, he, rfl⟩)

end ColTensor
