module

public import RequestProject.ColUpper.Basis

/-!
# Part (ii) of the Theorem of `q_col_upper.md`: the count

`K` contains a set `μ_m` of `m` distinct `m`-th roots of unity: a `Finset` `μm` with
`X^m − 1 = Π_{ξ ∈ μm} (X − ξ)` (hypothesis `hprod`; `|μm| = m` follows from it, and is not
needed). For `a ∈ μ_m^d`, `evR hprod a : K[G] → K` is `t_i ↦ a_i`, and `Gamma hprod k` is
`Γ = {a ∈ μ_m^d : ev_a(ψ_J) ≠ 0 for some J}`.

* `evalMap_bijective`: `E = (ev_a)_a : K[G] → K^{μ_m^d}` is bijective (Lagrange interpolation
  and (0));
* `finrank_span_pi`: in `K^X`, the ideal generated by `(f_j)` has dimension
  `#{x : f_j(x) ≠ 0 for some j}`;
* `finrank_IK_eq_card_Gamma`: `dim_K I_K = |Γ|`.
-/

@[expose] public section

open MvPolynomial

namespace ColUpper

open ColSplit

set_option synthInstance.maxHeartbeats 200000

variable {K : Type*} [Field K] {m : ℕ}

section roots

variable {μm : Finset K}
  (hprod : (Polynomial.X ^ m - 1 : Polynomial K) = ∏ ξ ∈ μm, (Polynomial.X - Polynomial.C ξ))
include hprod

/-- **Setting** (*Roots of unity*) of `q_col_upper.md`: every `ξ ∈ μ_m` satisfies `ξ^m = 1`. -/
theorem pow_eq_one_of_mem {ξ : K} (hξ : ξ ∈ μm) : ξ ^ m = 1 := by
  have h := congrArg (Polynomial.eval ξ) hprod
  simp only [Polynomial.eval_sub, Polynomial.eval_pow, Polynomial.eval_X, Polynomial.eval_one,
    Polynomial.eval_prod, Polynomial.eval_C] at h
  rw [Finset.prod_eq_zero hξ (sub_self ξ)] at h
  exact sub_eq_zero.1 h

/-- **Setting** (*Roots of unity*) of `q_col_upper.md`: the elements of `μ_m` are exactly the
`m`-th roots of unity in `K`. -/
theorem mem_iff_pow_eq_one (ξ : K) : ξ ∈ μm ↔ ξ ^ m = 1 := by
  refine ⟨pow_eq_one_of_mem hprod, fun h => ?_⟩
  have h2 := congrArg (Polynomial.eval ξ) hprod
  simp only [Polynomial.eval_sub, Polynomial.eval_pow, Polynomial.eval_X, Polynomial.eval_one,
    Polynomial.eval_prod, Polynomial.eval_C, h, sub_self] at h2
  obtain ⟨η, hη, h0⟩ := Finset.prod_eq_zero_iff.1 h2.symm
  rwa [sub_eq_zero.1 h0]

/-- **Setting** (*Roots of unity*) of `q_col_upper.md`: `m ≥ 1` (for `m = 0`, `X^0 − 1 = 0` has
no factorization into linear factors). -/
theorem pos_of_prod : 0 < m := by
  rcases Nat.eq_zero_or_pos m with h | h
  · subst h
    have := congrArg Polynomial.natDegree hprod
    simp only [pow_zero, sub_self, Polynomial.natDegree_zero] at this
    rw [Polynomial.natDegree_prod _ _ (fun ξ _ => Polynomial.X_sub_C_ne_zero ξ)] at this
    simp only [Polynomial.natDegree_X_sub_C, Finset.sum_const, smul_eq_mul, mul_one] at this
    have hc : μm.card = 0 := this.symm
    rw [Finset.card_eq_zero] at hc
    subst hc
    simp at hprod
  · exact h

/-- **Setting** (*Roots of unity*) of `q_col_upper.md`: `|μ_m| = m` (it follows from the
factorization, by comparing degrees). -/
theorem card_of_prod : μm.card = m := by
  have := congrArg Polynomial.natDegree hprod
  rw [Polynomial.natDegree_prod _ _ (fun ξ _ => Polynomial.X_sub_C_ne_zero ξ)] at this
  simp only [Polynomial.natDegree_X_sub_C, Finset.sum_const, smul_eq_mul, mul_one] at this
  rw [← this, Polynomial.natDegree_sub_eq_left_of_natDegree_lt] <;>
    simp [pos_of_prod hprod]

variable {d : ℕ}

/-- **Setting** (*Roots of unity*) of `q_col_upper.md`: for `a ∈ μ_m^d`, the `K`-algebra map
`ev_a : K[G] → K`, `t_i ↦ a_i` (well defined, as `a_i^m = 1`). -/
noncomputable def evR (a : Fin d → μm) : GA K d m →ₐ[K] K :=
  Ideal.Quotient.liftₐ (gaIdeal K d m) (aeval fun i => (a i : K)) (fun f hf => by
    refine (Ideal.span_le (I := RingHom.ker (aeval (R := K) fun i => (a i : K)).toRingHom)).2 ?_ hf
    rintro _ ⟨i, rfl⟩
    simp [pow_eq_one_of_mem hprod (a i).2])

/-- **Setting** (*Roots of unity*) of `q_col_upper.md`: `ev_a` on the class of a polynomial `f`
is `f(a_1, …, a_d)`. -/
@[simp] theorem evR_mk (a : Fin d → μm) (f : MvPolynomial (Fin d) K) :
    evR hprod a (Ideal.Quotient.mk _ f) = aeval (fun i => (a i : K)) f := rfl

/-- **Proof of (ii)** in `q_col_upper.md`: the evaluation map `E : K[G] → K^{μ_m^d}`,
`f ↦ (ev_a(f))_a`, a `K`-algebra map. -/
noncomputable def evalMap : GA K d m →ₐ[K] ((Fin d → μm) → K) :=
  Pi.algHom _ _ fun a => evR hprod a

/-- **Proof of (ii)** in `q_col_upper.md`: `E` is surjective: `Π_i L_{a_i}(t_i)` maps to the
indicator of `a`, where `L_ξ` is the Lagrange basis polynomial of `ξ ∈ μ_m`. -/
theorem evalMap_surjective : Function.Surjective (evalMap (d := d) hprod) := by
  classical
  have hsingle : ∀ a : Fin d → μm, (Pi.single a 1 : (Fin d → μm) → K) ∈
      LinearMap.range (evalMap (d := d) hprod).toLinearMap := by
    intro a
    refine ⟨Ideal.Quotient.mk _ (∏ i, Polynomial.aeval (X i) (Lagrange.basis μm id (a i))), ?_⟩
    funext b
    simp only [AlgHom.toLinearMap_apply, evalMap, Pi.algHom_apply, evR_mk, map_prod]
    have hev : ∀ i, aeval (fun i => (b i : K)) (Polynomial.aeval (X i : MvPolynomial (Fin d) K)
        (Lagrange.basis μm id (a i))) = if b i = a i then 1 else 0 := by
      intro i
      rw [← Polynomial.aeval_algHom_apply, aeval_X, Polynomial.coe_aeval_eq_eval]
      split_ifs with h
      · rw [h]
        exact Lagrange.eval_basis_self (v := id) (Set.injOn_id _) (a i).2
      · exact Lagrange.eval_basis_of_ne (v := id) (fun h' => h (Subtype.ext h'.symm)) (b i).2
    simp only [hev]
    by_cases hab : b = a
    · subst hab; simp
    · rw [Pi.single_eq_of_ne hab]
      obtain ⟨i, hi⟩ := Function.ne_iff.1 hab
      exact Finset.prod_eq_zero (Finset.mem_univ i) (if_neg hi)
  intro v
  have : v ∈ LinearMap.range (evalMap (d := d) hprod).toLinearMap := by
    rw [← Finset.univ_sum_single v]
    refine Submodule.sum_mem _ fun a _ => ?_
    rw [show (Pi.single a (v a) : (Fin d → μm) → K) = v a • (Pi.single a (1 : K) : (Fin d → μm) → K) by
      funext b
      by_cases hb : b = a
      · subst hb; simp
      · simp [hb]]
    exact Submodule.smul_mem _ _ (hsingle a)
  obtain ⟨x, hx⟩ := this
  exact ⟨x, hx⟩

/-- **Proof of (ii)** in `q_col_upper.md`: `E : K[G] → K^{μ_m^d}` is bijective, since it is
surjective and `dim K[G] = m^d = dim K^{μ_m^d}` by (0). -/
theorem evalMap_bijective : Function.Bijective (evalMap (d := d) hprod) := by
  refine ⟨?_, evalMap_surjective hprod⟩
  have hm := pos_of_prod hprod
  haveI : Module.Finite K (GA K d m) := Module.Finite.of_basis (monoBasis K d m hm)
  have h := (LinearMap.injective_iff_surjective_of_finrank_eq_finrank
    (f := (evalMap (d := d) hprod).toLinearMap) (by
      rw [finrank_GA K d m hm, Module.finrank_fintype_fun_eq_card, Fintype.card_fun,
        Fintype.card_coe, card_of_prod hprod, Fintype.card_fin])).2 (evalMap_surjective hprod)
  exact h

/-- **Proof of (ii)** in `q_col_upper.md`: `E` as a `K`-algebra isomorphism
`K[G] ≅ K^{μ_m^d}`. -/
noncomputable def evalEquiv : GA K d m ≃ₐ[K] ((Fin d → μm) → K) :=
  AlgEquiv.ofBijective (evalMap hprod) (evalMap_bijective hprod)

end roots

/-- **Proof of (ii)** in `q_col_upper.md` (*The ideal*): in the product ring `K^X` (`X` finite),
the ideal generated by a family `(f_j)` has `K`-dimension `#{x : f_j(x) ≠ 0 for some j}`. -/
theorem finrank_span_pi {X ι : Type*} [Fintype X] [DecidableEq X] (f : ι → X → K)
    [DecidablePred fun x : X => ∃ j, f j x ≠ 0] :
    Module.finrank K ((Ideal.span (Set.range f)).restrictScalars K) =
      (Finset.univ.filter fun x : X => ∃ j, f j x ≠ 0).card := by
  set Γ := Finset.univ.filter fun x : X => ∃ j, f j x ≠ 0
  let V : Ideal (X → K) :=
    { carrier := {g | ∀ x ∉ Γ, g x = 0}
      add_mem' := by
        intro a b ha hb x hx
        simp [ha x hx, hb x hx]
      zero_mem' := by intro x _; rfl
      smul_mem' := by
        intro c g hg x hx
        simp [hg x hx] }
  have hle : Ideal.span (Set.range f) ≤ V := by
    rw [Ideal.span_le]
    rintro _ ⟨j, rfl⟩ x hx
    simp only [Γ, Finset.mem_filter, Finset.mem_univ, true_and, not_exists, not_not] at hx
    exact hx j
  have heq : (Ideal.span (Set.range f)).restrictScalars K =
      Submodule.span K (Set.range fun x : Γ => (Pi.single (x : X) (1 : K) : X → K)) := by
    apply le_antisymm
    · intro g hg
      have hgV : ∀ x ∉ Γ, g x = 0 := hle hg
      rw [← Finset.univ_sum_single g, ← Finset.sum_subset (Finset.subset_univ Γ)
        (fun x _ hx => by rw [hgV x hx, Pi.single_zero])]
      refine Submodule.sum_mem _ fun x hx => ?_
      rw [show (Pi.single x (g x) : X → K) = g x • (Pi.single x (1 : K) : X → K) by
        funext b
        by_cases hb : b = x
        · subst hb; simp
        · simp [hb]]
      exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨⟨x, hx⟩, rfl⟩)
    · rw [Submodule.span_le]
      rintro _ ⟨⟨x, hx⟩, rfl⟩
      simp only [Γ, Finset.mem_filter, Finset.mem_univ, true_and] at hx
      obtain ⟨j, hj⟩ := hx
      have : (Pi.single x (1 : K) : X → K) = Pi.single x (f j x)⁻¹ * f j := by
        funext y
        by_cases hy : y = x
        · subst hy; simp [inv_mul_cancel₀ hj]
        · simp [Pi.single_eq_of_ne hy]
      show (Pi.single x (1 : K) : X → K) ∈ Ideal.span (Set.range f)
      rw [this]
      exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨j, rfl⟩)
  rw [heq, finrank_span_eq_card, Fintype.card_coe]
  have := (Pi.basisFun K X).linearIndependent.comp (Subtype.val : Γ → X) Subtype.val_injective
  convert this using 1
  funext x
  simp

variable {μm : Finset K}
  (hprod : (Polynomial.X ^ m - 1 : Polynomial K) = ∏ ξ ∈ μm, (Polynomial.X - Polynomial.C ξ))

open Classical in
/-- **Setting** of `q_col_upper.md`: `Γ := {a ∈ μ_m^d : ev_a(ψ_J) ≠ 0 for some matching J}`
(with `d = 2k + 1`). -/
noncomputable def Gamma (k : ℕ) : Finset (Fin (2 * k + 1) → μm) :=
  Finset.univ.filter fun a => ∃ J : BallotBound.Matching k, evR hprod a (psiG K m J) ≠ 0

/-- **Theorem (ii)** of `q_col_upper.md` (the count): if `K` contains a set `μ_m` of `m` distinct
`m`-th roots of unity (`X^m − 1 = Π_{ξ ∈ μ_m} (X − ξ)`), then `dim_K I_K = |Γ|`.
This is slightly more general than the file: the hypotheses `|μ_m| = m` and `m ≠ 0` in `K` are
not needed (the first follows from the factorization, see `card_of_prod`). -/
theorem finrank_IK_eq_card_Gamma (k : ℕ) :
    Module.finrank K ((IK K m k).restrictScalars K) = (Gamma hprod k).card := by
  classical
  let E := evalEquiv (d := 2 * k + 1) hprod
  have h1 : Module.finrank K ((IK K m k).restrictScalars K) =
      Module.finrank K ((Ideal.map E (IK K m k)).restrictScalars K) := by
    rw [← LinearEquiv.finrank_map_eq E.toLinearEquiv]
    have : ((IK K m k).restrictScalars K).map E.toLinearEquiv.toLinearMap =
        (Ideal.map E (IK K m k)).restrictScalars K := by
      ext y
      simp only [Submodule.mem_map, Submodule.restrictScalars_mem, Ideal.mem_map_of_equiv]
      rfl
    rw [this]
  have h2 : Ideal.map E (IK K m k) = Ideal.span (Set.range fun J : BallotBound.Matching k =>
      fun a => evR hprod a (psiG K m J)) := by
    rw [IK, Ideal.map_span, ← Set.range_comp]
    rfl
  rw [h1, h2, finrank_span_pi]
  rfl

end ColUpper

end
