module

public import RequestProject.ColAssembly.EveryField
public import RequestProject.ColAssembly.BasisZ
public import RequestProject.FreeZ.Lemma

/-!
# Main Theorem′ of `q_col_assembly.md`

Let `m ≥ 1` be odd. Then `R/I_ℤ` is a free `ℤ`-module of rank `m^{2k+1} − Q_k(m)`, and for every
field `F`, `dim_F F[G]/I_F = m^{2k+1} − Q_k(m)` (`ColAssembly.mainTheorem'`).

Here `R = RZ (2k+1) m = ℤ[t_1, …, t_{2k+1}]/(t_i^m − 1 : i)`, `I_ℤ = IZ m k` is the ideal of `R`
generated by the images of the polynomials `ColUpper.psiP ℤ m J`, `F[G] = ColSplit.GA F (2k+1) m`
and `I_F = ColUpper.IK F m k`.

This file also collects Proposition 6.9 and the Theorem (every field) (proved in
`RequestProject/ColAssembly/Prop69.lean` and `RequestProject/ColAssembly/EveryField.lean`).
-/

@[expose] public section

namespace ColAssembly

open ColSplit ColUpper TheoremB EveryField

set_option synthInstance.maxHeartbeats 200000

variable {m : ℕ} {k : ℕ}

/-- **Proof of Main Theorem′** in `q_col_assembly.md` (*The ranks*): for every field `F`, the
image of `L` (the `ℤ`-span of the rows of `A`) in `F^n` spans the row space of `A` read in `F`,
of dimension `rank_F(A)`. -/
theorem finrank_span_map_rowLattice (F : Type*) [Field F] {ι κ : Type*} [Fintype ι] [Finite κ]
    (A : Matrix κ ι ℤ) :
    Module.finrank F (Submodule.span F
        (((Submodule.span ℤ (Set.range A.row)).map (castLin F ι) : Submodule ℤ (ι → F)) :
          Set (ι → F))) = rankOver F A := by
  rw [FreeZ.span_map_castLin_span, rankOver, Matrix.rank_eq_finrank_span_row, ← Set.range_comp]
  rfl

/-- **Proof of Main Theorem′** in `q_col_assembly.md` (*The ranks*): for odd `m` and every field
`F`, the image of `L` in `F^n` has dimension `rank_F(A) = Q_k(m)` (by the Theorem (every
field)). -/
theorem finrank_span_map_L (F : Type*) [Field F] (hodd : Odd m) :
    Module.finrank F (Submodule.span F
        (((Submodule.span ℤ (Set.range (intMatU m k).row)).map
          (castLin F (Fin (2 * k + 1) → Fin m)) : Submodule ℤ ((Fin (2 * k + 1) → Fin m) → F)) :
          Set ((Fin (2 * k + 1) → Fin m) → F))) = Qk k m := by
  rw [finrank_span_map_rowLattice, rankOver_intMatU F hodd k]

/-- **Proof of Main Theorem′** in `q_col_assembly.md` (*Freeness*): `ℤ^n/L` is free of rank
`n − Q_k(m) = m^{2k+1} − Q_k(m)`, by the Lemma of `q_free_Z.md`. -/
theorem free_quotient_L (hodd : Odd m) :
    Module.Free ℤ (((Fin (2 * k + 1) → Fin m) → ℤ) ⧸ Submodule.span ℤ (Set.range (intMatU m k).row))
      ∧ Module.finrank ℤ
          (((Fin (2 * k + 1) → Fin m) → ℤ) ⧸ Submodule.span ℤ (Set.range (intMatU m k).row)) =
        m ^ (2 * k + 1) - Qk k m := by
  obtain ⟨hfree, hrank⟩ := FreeZ.quotient_free_of_finrank_image
    (Submodule.span ℤ (Set.range (intMatU m k).row))
    (fun p _ => by rw [finrank_span_map_L _ hodd, finrank_span_map_L _ hodd])
  refine ⟨hfree, ?_⟩
  rw [hrank, finrank_span_map_L _ hodd]
  simp

/-- **Proof of Main Theorem′** in `q_col_assembly.md` (*The basis*): `R/I_ℤ ≅ ℤ^n/L` as
`ℤ`-modules, via the coordinate map `e : R ≅ ℤ^n` of the monomial basis. -/
noncomputable def quotientEquivZ (hm : 0 < m) :
    (RZ (2 * k + 1) m ⧸ IZ m k) ≃ₗ[ℤ]
      (((Fin (2 * k + 1) → Fin m) → ℤ) ⧸ Submodule.span ℤ (Set.range (intMatU m k).row)) :=
  (Submodule.Quotient.restrictScalarsEquiv ℤ (IZ m k)).symm.trans
    (Submodule.Quotient.equiv _ _ (monoBasisZ (2 * k + 1) m hm).equivFun (map_equivFun_IZ hm))

/-- **Main Theorem′** of `q_col_assembly.md`, integral part: for odd `m ≥ 1`, `R/I_ℤ` is a free
`ℤ`-module of rank `m^{2k+1} − Q_k(m)`, where `R = ℤ[t_1, …, t_{2k+1}]/(t_i^m − 1 : i)` and
`I_ℤ` is the ideal of `R` generated by the `ψ_J` (images of `ColUpper.psiP ℤ m J`). -/
theorem mainTheorem'_Z (hodd : Odd m) (k : ℕ) :
    Module.Free ℤ (RZ (2 * k + 1) m ⧸ IZ m k) ∧
      Module.finrank ℤ (RZ (2 * k + 1) m ⧸ IZ m k) = m ^ (2 * k + 1) - Qk k m := by
  obtain ⟨hfree, hrank⟩ := free_quotient_L (k := k) hodd
  let e := quotientEquivZ (k := k) hodd.pos
  exact ⟨Module.Free.of_equiv e.symm, e.finrank_eq.trans hrank⟩

/-- **Main Theorem′** of `q_col_assembly.md`, field part: for odd `m ≥ 1` and every field `F`,
`dim_F F[G]/I_F = m^{2k+1} − Q_k(m)` (by (0) of `q_col_upper.md` and the Theorem (every
field)). -/
theorem mainTheorem'_field (hodd : Odd m) (k : ℕ) (F : Type*) [Field F] :
    Module.finrank F (GA F (2 * k + 1) m ⧸ IK F m k) = m ^ (2 * k + 1) - Qk k m := by
  haveI := finite_GA (F := F) (2 * k + 1) m hodd.pos
  have h := Submodule.finrank_quotient_add_finrank ((IK F m k).restrictScalars F)
  rw [finrank_IK_eq F hodd k, finrank_GA F _ _ hodd.pos] at h
  rw [← (Submodule.Quotient.restrictScalarsEquiv F (IK F m k)).finrank_eq]
  omega

/-- **Main Theorem′** of `q_col_assembly.md`: let `m ≥ 1` be odd. Then `R/I_ℤ` is a free
`ℤ`-module of rank `m^{2k+1} − Q_k(m)`, where `R = ℤ[t_1, …, t_{2k+1}]/(t_1^m − 1, …, t_d^m − 1)`
and `I_ℤ = (ψ_J : J a matching) ⊆ R`. Moreover, for every field `F`,
`dim_F F[G]/I_F = m^{2k+1} − Q_k(m)`. (No hypothesis `m ≥ 3` or `k ≥ 1` is needed.) -/
theorem mainTheorem' (hodd : Odd m) (k : ℕ) :
    (Module.Free ℤ (RZ (2 * k + 1) m ⧸ IZ m k) ∧
      Module.finrank ℤ (RZ (2 * k + 1) m ⧸ IZ m k) = m ^ (2 * k + 1) - Qk k m) ∧
    ∀ (F : Type) [Field F],
      Module.finrank F (GA F (2 * k + 1) m ⧸ IK F m k) = m ^ (2 * k + 1) - Qk k m :=
  ⟨mainTheorem'_Z hodd k, fun F _ => mainTheorem'_field hodd k F⟩

end ColAssembly

end
