module

public import RequestProject.Ballot.Construct
public import RequestProject.Ballot.Comb

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false

/-!
# A lower bound for an ideal generated by products of linear differences

Formalization of the **Theorem** of `q3_ballot_lower_bound.md`:
for every field `F` and every `k ≥ 0`, `dim_F V ≥ binomial(2k + 2, k + 1)`.

The objects `C`, `y_i`, `𝒥`, `D_J` and `V` of the **Setting** are `BallotBound.Alg`,
`BallotBound.y`, `BallotBound.Matching`, `BallotBound.D` and `BallotBound.V`
(file `RequestProject/Ballot/Defs.lean`).
-/

@[expose] public section

open MvPolynomial Finset

namespace BallotBound

/-- Step (ii) of `q3_ballot_lower_bound.md`: every ballot set `U ∈ 𝓤` (positions shifted to
`0, …, 2k`) yields the data `c`, `π` of a matching `J` for which `y_T · D_J` has leading
monomial `y_U`. -/
theorem exists_pairData (k : ℕ) (U : Finset ℕ) (hU : U ∈ ballotSets (2 * k + 1)) :
    Nonempty (PairData k (univ.filter fun x : Fin (2 * k + 1) => x.val ∈ U)) := by
  have hb : IsBallot (2 * k + 1) U := (mem_filter.1 hU).2
  obtain ⟨c, hc, p, hpc, hp⟩ := exists_matching_of_isBallot (2 * k + 1) U hb ⟨k, rfl⟩
  have hlt : ∀ x < 2 * k + 1, p x < 2 * k + 1 := fun x hx => by
    by_cases h : x = c
    · rw [h, hpc]; exact hc
    · exact (hp x hx h).2.1
  refine ⟨⟨⟨c, hc⟩, fun x => ⟨p x, hlt x x.2⟩, ?_, ?_, ?_, ?_⟩⟩
  · intro x
    apply Fin.ext
    by_cases h : x.val = c
    · simp [h, hpc]
    · exact (hp x x.2 h).2.2.1
  · exact Fin.ext hpc
  · intro x hx h
    have hx' : x.val ≠ c := fun h' => hx (Fin.ext h')
    exact (hp x x.2 hx').1 (congrArg Fin.val h)
  · intro x hx
    rw [Fin.lt_def] at hx
    have hx' : x.val ≠ c := fun h' => by
      simp only [h', hpc] at hx
      exact lt_irrefl _ hx
    simpa using (hp x x.2 hx').2.2.2 hx

/-- **Theorem** of `q3_ballot_lower_bound.md`: for every field `F` and every `k ≥ 0`, the ideal
`V ⊆ C = F[y_1, …, y_{2k+1}] / (y_1^2, …, y_{2k+1}^2)` generated by all `D_J` (`J` a perfect
matching of `{0, 1, …, 2k + 1}`) satisfies `dim_F V ≥ binomial(2k + 2, k + 1)`. -/
theorem finrank_V_ge (F : Type*) [Field F] (k : ℕ) :
    (2 * k + 2).choose (k + 1) ≤ Module.finrank F ((V F k).restrictScalars F) := by
  classical
  let ι := {U // U ∈ ballotSets (2 * k + 1)}
  let UF : ι → Finset (Fin (2 * k + 1)) := fun i => univ.filter fun x => x.val ∈ i.1
  let P : ∀ i : ι, PairData k (UF i) := fun i => (exists_pairData k i.1 i.2).some
  have hinj : Function.Injective fun i : ι => indU (UF i) := by
    intro i j hij
    have hsub : ∀ i : ι, i.1 ⊆ range (2 * k + 1) := fun i =>
      mem_powerset.1 (mem_filter.1 i.2).1
    apply Subtype.ext
    ext x
    constructor
    · intro hx
      have hxn : x < 2 * k + 1 := mem_range.1 (hsub i hx)
      have h1 := congrArg (fun m => m ⟨x, hxn⟩) hij
      simp only [indU_apply, UF, mem_filter, mem_univ, true_and, hx, if_true] at h1
      by_contra hxj
      simp [hxj] at h1
    · intro hx
      have hxn : x < 2 * k + 1 := mem_range.1 (hsub j hx)
      have h1 := congrArg (fun m => m ⟨x, hxn⟩) hij
      simp only [indU_apply, UF, mem_filter, mem_univ, true_and, hx, if_true] at h1
      by_contra hxi
      simp [hxi] at h1
  have hli := linearIndependent_of_triangular (F := F) (wt k) (fun i => (P i).g (F := F))
    (fun i => indU (UF i)) hinj
    (fun i j => by rw [indU_apply]; split_ifs <;> omega)
    (fun i => (P i).coeff_g_indU) (fun i m hm hw => (P i).coeff_g_eq_zero m hm hw)
  let b : ι → (V F k).restrictScalars F := fun i =>
    ⟨Ideal.Quotient.mk (squaresIdeal F k) ((P i).g (F := F)), (P i).mk_g_mem⟩
  have hb : LinearIndependent F b := by
    apply LinearIndependent.of_comp ((V F k).restrictScalars F).subtype
    exact hli
  haveI : Fintype ι := inferInstanceAs (Fintype {U // U ∈ ballotSets (2 * k + 1)})
  have := hb.fintype_card_le_finrank
  have hcard : Fintype.card ι = (ballotSets (2 * k + 1)).card :=
    Fintype.card_of_subtype _ (fun _ => Iff.rfl)
  rw [hcard, card_ballotSets] at this
  exact this

end BallotBound

end
