module

public import RequestProject.ColOne.Empty

/-!
# The block of colour 1 (`q_col_one.md`, Lemma 6.6)

This file formalizes **Lemma 6.6** (the block of colour 1) of `q_col_one.md`, with `p ≠ 2`.

Conventions (from `q_col_decomp.md`): `𝒞_1 = cls (cExt c) 1`, `s = |𝒞_1|`, and
`I_{c,1} = Ic1 S c ⊆ B(W_1)`.  Dimensions are `Module.finrank F`: of `I_{c,1}` regarded as an
`F`-subspace (as in `q_col_decomp.md`), and of the ideals of `C_n` restricted to `F` (as in
`q_theorem_B_lower.md` and `q_induction.md`).  The perfect matchings `J` of `{0, …, 2j+1}`, `D_J`,
the ideal `(D_J : J) = DIdeal F q j`, `Q_j(q) = Qk j q`, the point set
`T = {1, …, h} × {±1}` (`stdSetting h _`, `h = (q − 1)/2`) and closed tuples are those of
`q_theorem_B_lower.md`.
-/

@[expose] public section

open MvPolynomial

namespace ColOne

open ColSplit ColSurv ColComp ColTensor ColDecomp Peel

open scoped Classical

variable {F : Type*} [Field F] (S : ColSetting F) {k : ℕ}

/-! ### The increasing enumerations -/

/-- **Proof of Lemma 6.6** of `q_col_one.md`: the increasing map `W_1 → 𝒞_1`, `s ↦ s + 1`. -/
def succW1 (c : Fin (2 * k + 1) → S.μ) (s : W1 S c) : cls (cExt c) 1 :=
  ⟨s.1.succ, (mem_W1 S).1 s.2⟩

/-- **Proof of Lemma 6.6** of `q_col_one.md`: `s ↦ s + 1` is increasing. -/
theorem succW1_strictMono (c : Fin (2 * k + 1) → S.μ) : StrictMono (succW1 S c) := by
  intro a b h
  change a.1.succ < b.1.succ
  exact Fin.succ_lt_succ_iff.2 h

/-- **Proof of Lemma 6.6** of `q_col_one.md`: `W_1 = 𝒞_1 ∖ {0}` (shifted by one). -/
theorem map_W1 (c : Fin (2 * k + 1) → S.μ) :
    (W1 S c).map (Fin.succEmb _) = (cls (cExt c) 1).erase 0 := by
  ext x
  simp only [Finset.mem_map, Fin.coe_succEmb, Finset.mem_erase]
  constructor
  · rintro ⟨j, hj, rfl⟩
    exact ⟨Fin.succ_ne_zero j, (mem_W1 S).1 hj⟩
  · rintro ⟨hx0, hx⟩
    obtain ⟨j, rfl⟩ := Fin.exists_succ_eq.2 hx0
    exact ⟨j, (mem_W1 S).2 hx, rfl⟩

/-- **Proof of Lemma 6.6 (ii)** of `q_col_one.md`: if `0 ∈ 𝒞_1` then `|W_1| + 1 = |𝒞_1|`. -/
theorem card_W1_of_mem (c : Fin (2 * k + 1) → S.μ) (h0 : (0 : Fin (2 * k + 2)) ∈ cls (cExt c) 1) :
    (W1 S c).card + 1 = (cls (cExt c) 1).card := by
  rw [← Finset.card_map (Fin.succEmb _), map_W1, Finset.card_erase_of_mem h0]
  have := Finset.card_pos.2 ⟨_, h0⟩
  omega

/-- **Proof of Lemma 6.6 (iii)** of `q_col_one.md`: if `0 ∉ 𝒞_1` then `|W_1| = |𝒞_1|`. -/
theorem card_W1_of_notMem (c : Fin (2 * k + 1) → S.μ)
    (h0 : (0 : Fin (2 * k + 2)) ∉ cls (cExt c) 1) : (W1 S c).card = (cls (cExt c) 1).card := by
  rw [← Finset.card_map (Fin.succEmb _), map_W1, Finset.erase_eq_of_notMem h0]

/-- **Proof of Lemma 6.6 (ii)** of `q_col_one.md`: the extension `ē : {0, …, n} → 𝒞_1` of an
enumeration `e : [n] → W_1` by `ē(0) := 0`. -/
def ebar (c : Fin (2 * k + 1) → S.μ) (h0 : (0 : Fin (2 * k + 2)) ∈ cls (cExt c) 1) {n : ℕ}
    (e : Fin n → W1 S c) : Fin (n + 1) → cls (cExt c) 1 :=
  Fin.cases ⟨0, h0⟩ fun i => succW1 S c (e i)

/-- **Proof of Lemma 6.6 (ii)** of `q_col_one.md`: `ē` is increasing if `e` is. -/
theorem ebar_strictMono (c : Fin (2 * k + 1) → S.μ) (h0 : (0 : Fin (2 * k + 2)) ∈ cls (cExt c) 1)
    {n : ℕ} (e : Fin n ≃o W1 S c) : StrictMono (ebar S c h0 e) := by
  intro a b hab
  induction a using Fin.cases with
  | zero =>
    induction b using Fin.cases with
    | zero => exact absurd hab (lt_irrefl _)
    | succ j =>
      change (0 : Fin (2 * k + 2)) < (e j).1.succ
      exact Fin.succ_pos _
  | succ i =>
    induction b using Fin.cases with
    | zero => exact absurd hab (not_lt.2 (Fin.zero_le _))
    | succ j =>
      exact succW1_strictMono S c (e.strictMono (Fin.succ_lt_succ_iff.1 hab))

/-- **Proof of Lemma 6.6 (ii)** of `q_col_one.md`: `ē` is onto `𝒞_1` if `e` is onto `W_1`. -/
theorem ebar_surjective (c : Fin (2 * k + 1) → S.μ) (h0 : (0 : Fin (2 * k + 2)) ∈ cls (cExt c) 1)
    {n : ℕ} (e : Fin n ≃o W1 S c) : Function.Surjective (ebar S c h0 e) := by
  intro x
  by_cases hx : x.1 = 0
  · exact ⟨0, Subtype.ext hx.symm⟩
  · obtain ⟨j, hj⟩ := Fin.exists_succ_eq.2 hx
    have hjW : j ∈ W1 S c := (mem_W1 S).2 (hj ▸ x.2)
    refine ⟨(e.symm ⟨j, hjW⟩).succ, Subtype.ext ?_⟩
    change (e (e.symm ⟨j, hjW⟩)).1.succ = x.1
    rw [e.apply_symm_apply]
    exact hj

/-- **Proof of Lemma 6.6 (iii)** of `q_col_one.md`: if `0 ∉ 𝒞_1`, `s ↦ s + 1` is onto `𝒞_1`. -/
theorem succW1_surjective (c : Fin (2 * k + 1) → S.μ)
    (h0 : (0 : Fin (2 * k + 2)) ∉ cls (cExt c) 1) : Function.Surjective (succW1 S c) := by
  intro x
  have hx : x.1 ≠ 0 := fun h => h0 (h ▸ x.2)
  obtain ⟨j, hj⟩ := Fin.exists_succ_eq.2 hx
  exact ⟨⟨j, (mem_W1 S).2 (hj ▸ x.2)⟩, Subtype.ext hj⟩

/-! ### Lemma 6.6 -/

/-- **Lemma 6.6 (i)** of `q_col_one.md`: if `s = |𝒞_1|` is odd, then `I_{c,1} = 0` (a set of odd
size has no perfect matching, so `I_{c,1}` is generated by the empty set). -/
theorem lemma66_i (c : Fin (2 * k + 1) → S.μ) (hs : Odd (cls (cExt c) 1).card) : Ic1 S c = ⊥ := by
  have hE : IsEmpty (PerfMatch (cls (cExt c) 1)) := by
    rw [← not_nonempty_iff, PerfMatch.nonempty_perfMatch_iff, Fintype.card_coe, Nat.not_even_iff_odd]
    exact hs
  rw [Ic1, Set.range_eq_empty, Ideal.span_empty]

/-- **Lemma 6.6 (ii)** of `q_col_one.md` (with `p ≠ 2`): if `0 ∈ 𝒞_1` and `s = 2j + 2`, then
`dim_F I_{c,1} = dim_F (D_J : J a matching of {0, …, 2j+1}) ⊆ C_{2j+1}`, and hence
`dim_F I_{c,1} ≥ Q_j(q)` (by the Theorem (iv) of `q_theorem_B_lower.md`). -/
theorem lemma66_ii (hp : S.p ≠ 2) (c : Fin (2 * k + 1) → S.μ) {j : ℕ}
    (h0 : (0 : Fin (2 * k + 2)) ∈ cls (cExt c) 1) (hs : (cls (cExt c) 1).card = 2 * j + 2) :
    Module.finrank F (Ic1 S c) =
        Module.finrank F ((TheoremB.DIdeal F S.q j).restrictScalars F) ∧
      Module.finrank F (Ic1 S c) ≥ TheoremB.Qk j S.q := by
  have hW : (W1 S c).card = 2 * j + 1 := by have := card_W1_of_mem S c h0; omega
  set e := (W1 S c).orderIsoOfFin hW
  set ē : Fin (2 * j + 2) ≃o cls (cExt c) 1 :=
    StrictMono.orderIsoOfSurjective (ebar S c h0 e) (ebar_strictMono S c h0 e)
      (ebar_surjective S c h0 e)
  have hē : ∀ a, ē a = ebar S c h0 e a := fun a => rfl
  have hē0 : ∀ a, (ē a).1 ≠ 0 ↔ a ≠ 0 := by
    intro a
    rw [hē]
    induction a using Fin.cases with
    | zero => simp [ebar]
    | succ i => simp [ebar, succW1, Fin.succ_ne_zero]
  have hκ : ∀ a, (ē a).1 ≠ 0 → (e.toEquiv (TheoremB.idx a)).1.succ = (ē a).1 := by
    intro a ha
    rw [hē0] at ha
    obtain ⟨i, rfl⟩ := Fin.exists_succ_eq.2 ha
    have hi : TheoremB.idx i.succ = i := by ext; simp [TheoremB.idx]
    rw [hē, hi]
    rfl
  have key := finrank_Ic1_eq S hp c ē e.toEquiv TheoremB.idx hκ
  have hspan : Ideal.span (Set.range fun P : PerfMatch (Fin (2 * j + 2)) =>
      Ideal.Quotient.mk (powIdeal F S.q (2 * j + 1)) (fpoly S ē TheoremB.idx P)) =
        TheoremB.DIdeal F S.q j := by
    rw [TheoremB.DIdeal]
    congr 1
    ext g
    have hpt : ∀ J : BallotBound.Matching j,
        Ideal.Quotient.mk (powIdeal F S.q (2 * j + 1)) (fpoly S ē TheoremB.idx J) =
          TheoremB.DJ F S.q J := by
      intro J
      rw [fpoly, map_prod, TheoremB.DJ]
      have hfil : Finset.univ.filter (fun a => (ē a).1 ≠ 0 ∧ a < J.1 a) =
          Finset.univ.filter (fun a => a ≠ 0 ∧ J.1 a ≠ 0 ∧ a < J.1 a) := by
        ext a
        simp only [Finset.mem_filter, Finset.mem_univ, true_and, hē0]
        constructor
        · rintro ⟨h1, h2⟩
          exact ⟨h1, ne_of_gt (lt_of_le_of_lt (Fin.zero_le _) h2), h2⟩
        · rintro ⟨h1, -, h2⟩
          exact ⟨h1, h2⟩
      rw [hfil]
      refine Finset.prod_congr rfl fun a _ => ?_
      rw [map_Dab, D_eq_Dab]
      rfl
    constructor
    · rintro ⟨J, rfl⟩
      exact ⟨J, (hpt J).symm⟩
    · rintro ⟨J, rfl⟩
      exact ⟨J, hpt J⟩
  rw [hspan] at key
  exact ⟨key, key ▸ TheoremB.finrank_DIdeal_ge F (three_le_q hp) (odd_q hp) j⟩

/-- **Lemma 6.6 (iii)** of `q_col_one.md` (with `p ≠ 2`): if `0 ∉ 𝒞_1` and `s = 2j`, then
`dim_F I_{c,1}` is at least the number of closed tuples in `T^{2j}`, for the point set
`T = {1, …, h} × {±1}`, `h = (q − 1)/2`, of `q_theorem_B_lower.md` (i.e. the number of `2j`-tuples in
`T` whose multiset is closed under the involution).  The proof goes through the down-set `{∅}` of
`Par_{2j}` and the Theorem of `q_induction.md`. -/
theorem lemma66_iii (hp : S.p ≠ 2) (c : Fin (2 * k + 1) → S.μ) {j : ℕ}
    (h0 : (0 : Fin (2 * k + 2)) ∉ cls (cExt c) 1) (hs : (cls (cExt c) 1).card = 2 * j) :
    Module.finrank F (Ic1 S c) ≥
      (TheoremB.closedTuples (TheoremB.stdSetting ((S.q - 1) / 2) (one_le_h hp)) (2 * j)).card := by
  have hW : (W1 S c).card = 2 * j := by rw [card_W1_of_notMem S c h0, hs]
  set e := (W1 S c).orderIsoOfFin hW
  set ψ : W1 S c ≃o cls (cExt c) 1 :=
    StrictMono.orderIsoOfSurjective (succW1 S c) (succW1_strictMono S c)
      (succW1_surjective S c h0)
  set ē : Fin (2 * j) ≃o cls (cExt c) 1 := e.trans ψ
  have hκ : ∀ a, (ē a).1 ≠ 0 → (e.toEquiv (id a)).1.succ = (ē a).1 := fun a _ => rfl
  have key := finrank_Ic1_eq S hp c ē e.toEquiv id hκ
  have hspan : Ideal.span (Set.range fun P : PerfMatch (Fin (2 * j)) =>
      Ideal.Quotient.mk (powIdeal F S.q (2 * j)) (fpoly S ē id P)) =
        Tight.VLamAll F S.q (2 * j) {Bip.Partition'.empty} := by
    rw [VLamAll_empty_eq]
    congr 1
    ext g
    have hpt : ∀ P : PerfMatch (Fin (2 * j)),
        Ideal.Quotient.mk (powIdeal F S.q (2 * j)) (fpoly S ē id P) = DPn F S.q P := by
      intro P
      rw [fpoly, map_prod, DPn]
      have hfil : Finset.univ.filter (fun a => (ē a).1 ≠ 0 ∧ a < P.1 a) =
          Finset.univ.filter (fun a => a < P.1 a) := by
        ext a
        simp only [Finset.mem_filter, Finset.mem_univ, true_and, and_iff_right_iff_imp]
        intro _
        exact Fin.succ_ne_zero _
      rw [hfil]
      refine Finset.prod_congr rfl fun a _ => ?_
      rw [map_Dab, D_eq_Dab]
      rfl
    constructor
    · rintro ⟨P, rfl⟩
      exact ⟨P, (hpt P).symm⟩
    · rintro ⟨P, rfl⟩
      exact ⟨P, hpt P⟩
  rw [key, hspan, ← ZLam_empty_eq]
  exact Induction.finrank_VLamAll_ge_card_ZLam F (three_le_q hp) (odd_q hp) _ (2 * j) _
    (isDownSetPar_empty _ ⟨j, by ring⟩)

end ColOne

end
