module

public import RequestProject.ColOne.Coord

/-!
# The divided difference and the sum form (`q_col_one.md`, Lemma 2.4 (i) and Proposition 2.5)

This file formalizes **Lemma 2.4 (i)** and **Proposition 2.5 (local form: the sum form)** of
`q_col_one.md`.

Conventions:
* `B_m = F[y_1, …, y_m]/(y_i^q)` is `Peel.C F (q + 1) m` and `C_m = F[y_1, …, y_m]/(y_i^{q−1})` is
  `Peel.C F q m` (`q_peeling_lemma.md`); `y_i` is `Tight.y` (the class of `X i`), in either ring;
* `Y_m := y_1 ⋯ y_m ∈ B_m` is `Ym F q m` (with `Y_0 = 1`, the empty product);
* dimensions are `Module.finrank F` of ideals regarded as `F`-subspaces (`restrictScalars F`), as
  in `q_peeling_lemma.md`.
Proposition 2.5 holds for every `q` (it does not need `p ≠ 2`), and is stated in that generality.
-/

@[expose] public section

open MvPolynomial

namespace ColOne

open ColSplit Peel

variable {F : Type*} [Field F]

/-! ### Lemma 2.4 (i) -/

/-- **Lemma 2.4 (local form)** of `q_col_one.md` (and **Setting**, "Divided difference" of
`q_P3_identities.md`): for elements `a`, `b` of any commutative ring,
`D(a, b) := Σ_{u=0}^{q−2} (−1)^u a^u b^{q−2−u}` (the sum over `u ∈ range (q − 1)`). -/
def Dab {A : Type*} [CommRing A] (q : ℕ) (a b : A) : A :=
  ∑ u ∈ Finset.range (q - 1), (-1) ^ u * a ^ u * b ^ (q - 2 - u)

/-- **Lemma 2.4** of `q_col_one.md`: the divided difference `D(y_a, y_b)` of `q_P3_identities.md`
(`Tight.D`) is `Dab q y_a y_b`. -/
theorem D_eq_Dab (q : ℕ) {m : ℕ} (a b : Fin m) :
    Tight.D F q a b = Dab q (Tight.y F q a) (Tight.y F q b) := rfl

/-- **Lemma 2.4** of `q_col_one.md`: `D` commutes with ring homomorphisms. -/
theorem map_Dab {A A' H : Type*} [CommRing A] [CommRing A'] [FunLike H A A'] [RingHomClass H A A']
    (f : H) (q : ℕ) (a b : A) :
    f (Dab q a b) = Dab q (f a) (f b) := by
  simp [Dab, map_sum, map_mul, map_pow]

/-- **Proof of Lemma 2.4 (i)** of `q_col_one.md`: the polynomial identity
`(a + b)^{q−1} = Σ_{s=0}^{q−1} (−1)^s a^s b^{q−1−s}`, valid in every commutative `F`-algebra
(obtained in the domain `F[a, b]` by cancelling `a + b` from
`(a + b)·Σ (−1)^s a^s b^{q−1−s} = a^q + b^q = (a + b)^q`, `q` odd). -/
theorem add_pow_q_sub_one {S : ColSetting F} (hp : S.p ≠ 2) {A : Type*} [CommRing A]
    [Algebra F A] (a b : A) :
    (a + b) ^ (S.q - 1) = ∑ s ∈ Finset.range S.q, (-a) ^ s * b ^ (S.q - 1 - s) := by
  have hq3 := three_le_q hp
  have hodd := odd_q hp
  set P : MvPolynomial (Fin 2) F := X 0 + X 1
  set G : MvPolynomial (Fin 2) F :=
    ∑ s ∈ Finset.range S.q, (-X 0) ^ s * X 1 ^ (S.q - 1 - s)
  have hP : P ≠ 0 := by
    intro h
    have := congrArg (MvPolynomial.eval ![1, 0]) h
    simp [P] at this
  have hGP : G * P = P ^ (S.q - 1) * P := by
    have h1 := geom_sum₂_mul (-X 0 : MvPolynomial (Fin 2) F) (X 1) S.q
    rw [← pow_succ, Nat.sub_add_cancel (by omega : 1 ≤ S.q), add_pow_q S, hodd.neg_pow] at *
    have : G * P = -(G * (-X 0 - X 1)) := by simp only [P]; ring
    rw [this, h1]; ring
  have hG : G = P ^ (S.q - 1) := mul_right_cancel₀ hP hGP
  have := congrArg (MvPolynomial.aeval (R := F) ![a, b]) hG
  simp only [G, P, map_sum, map_mul, map_pow, map_neg, map_add, aeval_X] at this
  simpa using this.symm

/-- **Lemma 2.4 (i)** of `q_col_one.md`: in every commutative `F`-algebra `A` (with `p ≠ 2`), if
`b ∈ A` has `b^q = 0`, then for every `a ∈ A`, `(a + b)^{q−1}·b = −a·b·D(a, b)`, where
`D(a, b) = Σ_{u=0}^{q−2} (−1)^u a^u b^{q−2−u}`. -/
theorem lemma24_i {S : ColSetting F} (hp : S.p ≠ 2) {A : Type*} [CommRing A] [Algebra F A]
    (a b : A) (hb : b ^ S.q = 0) : (a + b) ^ (S.q - 1) * b = -a * b * Dab S.q a b := by
  rw [add_pow_q_sub_one hp]
  have hq3 := three_le_q hp
  obtain ⟨r, hr⟩ : ∃ r, S.q = r + 2 := ⟨S.q - 2, by omega⟩
  rw [hr] at hb ⊢
  rw [Dab, Finset.sum_mul, Finset.mul_sum, Finset.sum_range_succ']
  simp only [pow_zero, one_mul, show r + 2 - 1 - 0 = r + 1 by omega]
  rw [← pow_succ, hb, add_zero, show r + 2 - 1 = r + 1 by omega]
  refine Finset.sum_congr rfl fun u hu => ?_
  rw [Finset.mem_range] at hu
  rw [show r + 1 - (u + 1) = r - u by omega, show r + 2 - 2 - u = r - u by omega]
  ring

/-! ### Proposition 2.5 -/

variable (F) (q : ℕ)

/-- **Setting** of `q_col_one.md`: `Y_m := y_1 y_2 ⋯ y_m ∈ B_m = F[y_1, …, y_m]/(y_i^q)`
(`Y_0 = 1`). -/
noncomputable def Ym (m : ℕ) : C F (q + 1) m := ∏ i : Fin m, Tight.y F (q + 1) i

/-- **Proof of Proposition 2.5 (i)** of `q_col_one.md`: the monomial `y_1 ⋯ y_m` of
`F[y_1, …, y_m]`. -/
noncomputable def Ypoly (m : ℕ) : MvPolynomial (Fin m) F := ∏ i : Fin m, X i

variable {F q}

/-- **Proof of Proposition 2.5 (i)** of `q_col_one.md`: `y_1 ⋯ y_m = monomial (1, …, 1)`. -/
theorem Ypoly_eq (m : ℕ) :
    Ypoly F m = monomial (∑ i : Fin m, Finsupp.single i 1) 1 := by
  rw [monomial_sum_index, C_1, one_mul]
  rfl

/-- **Proof of Proposition 2.5 (i)** of `q_col_one.md`: the ideal `(y_i^{q'−1})` of `F[y]` is the
monomial ideal generated by the exponents `(q' − 1)·e_i`. -/
theorem powIdeal_eq_span_monomial (q' m : ℕ) :
    powIdeal F q' m = Ideal.span ((fun s => monomial s (1 : F)) ''
      Set.range fun i : Fin m => Finsupp.single i (q' - 1)) := by
  rw [powIdeal, ← Set.range_comp]
  congr 1
  ext x
  simp [X_pow_eq_monomial]

/-- **Proof of Proposition 2.5 (i)** of `q_col_one.md` (the monomial basis argument): for
`g ∈ F[y_1, …, y_m]`, `Y·g ∈ (y_i^q)` iff `g ∈ (y_i^{q−1})` (multiplication by `Y` sends the
monomial `Π y_i^{a_i}` to `Π y_i^{a_i + 1}`). -/
theorem Ypoly_mul_mem_iff (m : ℕ) (g : MvPolynomial (Fin m) F) :
    Ypoly F m * g ∈ powIdeal F (q + 1) m ↔ g ∈ powIdeal F q m := by
  rw [powIdeal_eq_span_monomial, powIdeal_eq_span_monomial, mem_ideal_span_monomial_image,
    mem_ideal_span_monomial_image, Ypoly_eq]
  set s : Fin m →₀ ℕ := ∑ i : Fin m, Finsupp.single i 1
  have hs : ∀ i, s i = 1 := by
    intro i
    simp [s, Finsupp.finset_sum_apply, Finsupp.single_apply]
  simp only [Set.mem_range, exists_exists_eq_and, Finsupp.single_le_iff, Nat.add_sub_cancel]
  constructor
  · intro h e he
    have he' : s + e ∈ (monomial s 1 * g).support := by
      rw [mem_support_iff, coeff_monomial_mul, one_mul]
      exact mem_support_iff.1 he
    obtain ⟨i, hi⟩ := h _ he'
    refine ⟨i, ?_⟩
    rw [Finsupp.add_apply, hs] at hi
    omega
  · intro h x hx
    rw [mem_support_iff, coeff_monomial_mul'] at hx
    split_ifs at hx with hsx
    · obtain ⟨i, hi⟩ := h _ (mem_support_iff.2 (by simpa using hx))
      refine ⟨i, ?_⟩
      rw [Finsupp.tsub_apply, hs] at hi
      have := Finsupp.le_def.1 hsx i
      rw [hs] at this
      omega
    · exact absurd rfl hx

/-- **Proof of Proposition 2.5 (i)** of `q_col_one.md`: `(y_i^q) ⊆ (y_i^{q−1})` in `F[y]` (so the
quotient map `B_m → C_m` exists). -/
theorem powIdeal_succ_le (m : ℕ) : powIdeal F (q + 1) m ≤ powIdeal F q m := by
  rw [powIdeal, Ideal.span_le]
  rintro _ ⟨i, rfl⟩
  rcases Nat.eq_zero_or_pos q with h | h
  · subst h; exact Ideal.subset_span ⟨i, by simp⟩
  · obtain ⟨q', rfl⟩ : ∃ q', q = q' + 1 := ⟨q - 1, by omega⟩
    simp only [Nat.add_sub_cancel]
    rw [pow_succ]
    exact Ideal.mul_mem_right _ _ (Ideal.subset_span ⟨i, by simp⟩)

/-- **Proof of Proposition 2.5** of `q_col_one.md`: `Y_m` is the class of `y_1 ⋯ y_m`. -/
theorem Ym_eq (m : ℕ) : Ym F q m = Ideal.Quotient.mk _ (Ypoly F m) := by
  simp [Ym, Ypoly, Tight.y, map_prod]

/-- **Proposition 2.5 (i)** of `q_col_one.md`, first claim: multiplication by `Y_m` on
`B_m = F[y_1, …, y_m]/(y_i^q)` has kernel exactly `(y_1^{q−1}, …, y_m^{q−1})·B_m`. -/
theorem lemma25_i_ker (m : ℕ) (f : C F (q + 1) m) :
    Ym F q m * f = 0 ↔
      f ∈ Ideal.span (Set.range fun i : Fin m => Tight.y F (q + 1) i ^ (q - 1)) := by
  obtain ⟨g, rfl⟩ := Ideal.Quotient.mk_surjective f
  have hspan : Ideal.span (Set.range fun i : Fin m => Tight.y F (q + 1) i ^ (q - 1)) =
      (powIdeal F q m).map (Ideal.Quotient.mk (powIdeal F (q + 1) m)) := by
    have e : powIdeal F q m = Ideal.span (Set.range fun i : Fin m =>
        (X i ^ (q - 1) : MvPolynomial (Fin m) F)) := rfl
    rw [e, Ideal.map_span, ← Set.range_comp]
    rfl
  rw [Ym_eq, ← map_mul, Ideal.Quotient.eq_zero_iff_mem, Ypoly_mul_mem_iff, hspan,
    Ideal.mem_quotient_iff_mem_sup, sup_eq_left.2 (powIdeal_succ_le m)]

variable (F q)

/-- **Proof of Proposition 2.5 (i)** of `q_col_one.md`: the `F`-linear map
`F[y_1, …, y_m] → B_m`, `f ↦ Y_m·f`. -/
noncomputable def mulYpoly (m : ℕ) : MvPolynomial (Fin m) F →ₗ[F] C F (q + 1) m :=
  (LinearMap.mulLeft F (Ym F q m)).comp (Ideal.Quotient.mkₐ F (powIdeal F (q + 1) m)).toLinearMap

/-- **Proposition 2.5 (i)** of `q_col_one.md`, second claim: the well-defined `F`-linear map
`μ_Y : C_m → B_m`, `f ↦ Y_m·f̃` (`f̃` any lift of `f` through `F[y_1, …, y_m]`); it is injective
(`lemma25_i_injective`). -/
noncomputable def muY (m : ℕ) : C F q m →ₗ[F] C F (q + 1) m :=
  ((powIdeal F q m).restrictScalars F).liftQ (mulYpoly F q m) (by
    intro g hg
    rw [LinearMap.mem_ker, mulYpoly, LinearMap.comp_apply, LinearMap.mulLeft_apply,
      AlgHom.toLinearMap_apply, Ideal.Quotient.mkₐ_eq_mk, Ym_eq, ← map_mul,
      Ideal.Quotient.eq_zero_iff_mem, Ypoly_mul_mem_iff]
    exact hg) ∘ₗ (Submodule.Quotient.restrictScalarsEquiv F (powIdeal F q m)).symm.toLinearMap

variable {F q}

/-- **Proposition 2.5 (i)** of `q_col_one.md`: `μ_Y(f) = Y_m·f̃` for every lift `f̃` of `f`. -/
@[simp] theorem muY_mk (m : ℕ) (g : MvPolynomial (Fin m) F) :
    muY F q m (Ideal.Quotient.mk _ g) = Ym F q m * Ideal.Quotient.mk _ g := rfl

/-- **Proposition 2.5 (i)** of `q_col_one.md`, second claim: `μ_Y : C_m → B_m` is injective. -/
theorem lemma25_i_injective (m : ℕ) : Function.Injective (muY F q m) := by
  rw [← LinearMap.ker_eq_bot, LinearMap.ker_eq_bot']
  intro x hx
  obtain ⟨g, rfl⟩ := Ideal.Quotient.mk_surjective x
  rw [muY_mk, Ym_eq, ← map_mul, Ideal.Quotient.eq_zero_iff_mem, Ypoly_mul_mem_iff] at hx
  exact Ideal.Quotient.eq_zero_iff_mem.2 hx

/-- **Proposition 2.5 (i)** of `q_col_one.md`, both claims together: multiplication by `Y_m` on
`B_m` has kernel exactly `(y_1^{q−1}, …, y_m^{q−1})·B_m`, and `μ_Y : C_m → B_m`,
`f ↦ Y_m·f̃` (`f̃` any lift of `f` through `F[y_1, …, y_m]`), is a well-defined injective `F`-linear
map. -/
theorem lemma25_i (m : ℕ) :
    (∀ f : C F (q + 1) m, Ym F q m * f = 0 ↔
      f ∈ Ideal.span (Set.range fun i : Fin m => Tight.y F (q + 1) i ^ (q - 1))) ∧
    (∀ g : MvPolynomial (Fin m) F,
      muY F q m (Ideal.Quotient.mk _ g) = Ym F q m * Ideal.Quotient.mk _ g) ∧
    Function.Injective (muY F q m) :=
  ⟨lemma25_i_ker m, muY_mk m, lemma25_i_injective m⟩

/-- **Proof of Proposition 2.5 (ii)** of `q_col_one.md`: `μ_Y(ḡ·x) = g·μ_Y(x)`. -/
theorem muY_mul (m : ℕ) (g : MvPolynomial (Fin m) F) (x : C F q m) :
    muY F q m (Ideal.Quotient.mk _ g * x) = Ideal.Quotient.mk _ g * muY F q m x := by
  obtain ⟨h, rfl⟩ := Ideal.Quotient.mk_surjective x
  rw [← map_mul, muY_mk, muY_mk, map_mul]
  ring

/-- **Proposition 2.5 (ii)** of `q_col_one.md`, first claim: for every family `(f_α)` of
polynomials in `F[y_1, …, y_m]`, the ideal `(Y_m f_α : α)·B_m` is the image under `μ_Y` of the
ideal `(f_α : α)·C_m` (as `F`-subspaces). -/
theorem lemma25_ii_map {ι : Type*} (m : ℕ) (f : ι → MvPolynomial (Fin m) F) :
    (Ideal.span (Set.range fun α => Ym F q m * Ideal.Quotient.mk _ (f α))).restrictScalars F =
      ((Ideal.span (Set.range fun α => (Ideal.Quotient.mk (powIdeal F q m) (f α)))).restrictScalars
        F).map (muY F q m) := by
  apply le_antisymm
  · intro z hz
    rw [Submodule.restrictScalars_mem] at hz
    induction hz using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨α, rfl⟩ := hx
      exact ⟨_, Ideal.subset_span ⟨α, rfl⟩, muY_mk m (f α)⟩
    | zero => exact Submodule.zero_mem _
    | add x y _ _ hx hy => exact Submodule.add_mem _ hx hy
    | smul a x _ hx =>
      obtain ⟨g, rfl⟩ := Ideal.Quotient.mk_surjective a
      obtain ⟨w, hw, rfl⟩ := hx
      refine ⟨Ideal.Quotient.mk _ g * w, Ideal.mul_mem_left _ _ hw, ?_⟩
      rw [muY_mul, smul_eq_mul]
  · rintro _ ⟨x, hx, rfl⟩
    replace hx : x ∈ Ideal.span (Set.range fun α =>
      (Ideal.Quotient.mk (powIdeal F q m) (f α))) := hx
    rw [Submodule.restrictScalars_mem]
    induction hx using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨α, rfl⟩ := hx
      exact Ideal.subset_span ⟨α, (muY_mk m (f α)).symm⟩
    | zero => rw [map_zero]; exact Submodule.zero_mem _
    | add x y _ _ hx hy => rw [map_add]; exact Submodule.add_mem _ hx hy
    | smul a x _ hx =>
      obtain ⟨g, rfl⟩ := Ideal.Quotient.mk_surjective a
      rw [smul_eq_mul, muY_mul]
      exact Ideal.mul_mem_left _ _ hx

/-- **Proposition 2.5 (ii)** of `q_col_one.md`: for every family `(f_α)` of polynomials in
`F[y_1, …, y_m]`, `dim_F (Y_m f_α : α)·B_m = dim_F (f_α : α)·C_m`. -/
theorem lemma25_ii {ι : Type*} (m : ℕ) (f : ι → MvPolynomial (Fin m) F) :
    Module.finrank F
        ((Ideal.span (Set.range fun α => Ym F q m * Ideal.Quotient.mk _ (f α))).restrictScalars F) =
      Module.finrank F ((Ideal.span (Set.range fun α =>
        (Ideal.Quotient.mk (powIdeal F q m) (f α)))).restrictScalars F) := by
  rw [lemma25_ii_map]
  exact ((Submodule.equivMapOfInjective _ (lemma25_i_injective m) _).finrank_eq).symm

end ColOne

end
