module

public import RequestProject.ColDecomp.Gens

/-!
# Proposition 6.5 of `q_col_decomp.md`: the tensor decomposition of each factor

Parts **(i)**, **(ii)** and **(iii)** of **Proposition 6.5** of `q_col_decomp.md`, following the
**Proof** given there. The Setting (the ideal `I`, the Identification `R_c = B({1, …, d})`, the
blocks `W_1`, `W_ζ`, the pair factors `f_{a,b}`, the block generators `g_P`, `g_σ` and the ideals
`I_{c,1}`, `I_{c,ζ}`) is in `RequestProject/ColDecomp/Defs.lean`.

Throughout, `π_c(I)` is `(idealI S k).map (S.piC c)`, an ideal of `R_c`; it is regarded as an
ideal of `B({1, …, d})` by mapping it along the Identification `rcEquiv (boxS S c)`.

About the hypothesis *"`r` is odd"* of the Setting: it is what makes a set `ℛ` of representatives
exist (Lemma 6.3 (i), `ColComp.lemma63_i_exists_reps`). Here `ℛ` is given together with the
hypothesis `IsReps S R`, and none of the proofs below needs `r` to be odd, so (following the
convention of `q_col_compatible.md`'s formalization) the hypothesis `Odd S.r` is not added.
-/

@[expose] public section

open MvPolynomial

namespace ColDecomp

open ColSplit ColSurv ColComp ColTensor

open scoped Classical

variable {F : Type*} [Field F] (S : ColSetting F) {k : ℕ}

/-- **Proposition 6.5 (i)** of `q_col_decomp.md`: if no matching is compatible with `c` (extended
by `c_0`), then `π_c(I) = 0`. -/
theorem prop65_i (c : Fin (2 * k + 1) → S.μ)
    (h : ¬ ∃ J : BallotBound.Matching k, Compatible (cExt c) J) :
    (idealI S k).map (S.piC c) = ⊥ := by
  rw [idealI, S.lemma61_iii c, Ideal.span_eq_bot]
  rintro _ ⟨_, ⟨J, rfl⟩, rfl⟩
  exact piC_psi_eq_zero S c J fun hJ => h ⟨J, hJ⟩

/-- **Proof** of Proposition 6.5 (ii) in `q_col_decomp.md`, without the hypothesis that a
compatible matching exists: `π_c(I)`, read in `B({1, …, d})`, is generated by the products
`ι_{W_1}(g_P)·Π_{ζ∈ℛ} ι_{W_ζ}(g_{σ_ζ})`. (If no matching is compatible there are no tuples
`(P, (σ_ζ))` by Lemma 6.3 (iii), and both sides are `0`.) -/
theorem map_idealI_eq_span (c : Fin (2 * k + 1) → S.μ) {R : Finset F} (hR : IsReps S R) :
    ((idealI S k).map (S.piC c)).map (rcEquiv (boxS S c)) =
      Ideal.span {x | ∃ (P : PerfMatch (cls (cExt c) 1))
          (σ : (ζ : R) → cls (cExt c) ζ ≃ cls (cExt c) (ζ : F)⁻¹),
        x = (boxS S c).iota (W1 S c) Finset.univ (Finset.subset_univ _) (gP S c P) *
          ∏ ζ : R, (boxS S c).iota (Wz S c ζ) Finset.univ (Finset.subset_univ _)
            (gσ S c ζ (σ ζ))} := by
  rw [idealI, S.lemma61_iii c, Ideal.map_span]
  apply le_antisymm
  · rw [Ideal.span_le]
    rintro _ ⟨_, ⟨_, ⟨J, rfl⟩, rfl⟩, rfl⟩
    by_cases hJ : Compatible (cExt c) J
    · obtain ⟨w, hw⟩ := piC_psi_eq_unit_mul S c hR ⟨J, hJ⟩
      rw [SetLike.mem_coe]
      refine (congrArg (· ∈ Ideal.span _) hw).mpr ?_
      exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨_, _, rfl⟩)
    · rw [piC_psi_eq_zero S c J hJ, map_zero]
      exact zero_mem _
  · -- each product `ι_{W_1}(g_P)·Π_ζ ι_{W_ζ}(g_{σ_ζ})` is a unit times some `π_c(ψ_J)`
    have hu : ∀ y ∈ {x | ∃ (P : PerfMatch (cls (cExt c) 1))
          (σ : (ζ : R) → cls (cExt c) ζ ≃ cls (cExt c) (ζ : F)⁻¹),
        x = (boxS S c).iota (W1 S c) Finset.univ (Finset.subset_univ _) (gP S c P) *
          ∏ ζ : R, (boxS S c).iota (Wz S c ζ) Finset.univ (Finset.subset_univ _)
            (gσ S c ζ (σ ζ))}, ∃ w : ((boxS S c).Box Finset.univ)ˣ,
        (w : (boxS S c).Box Finset.univ) * y ∈
          rcEquiv (boxS S c) '' (S.piC c '' Set.range (psi S k)) := by
      rintro _ ⟨P, σ, rfl⟩
      obtain ⟨w, hw⟩ := piC_psi_eq_unit_mul S c hR (assemble hR (cExt_mem c) (P, σ))
      rw [lemma63_iii_restrict_assemble hR (cExt_mem c) (P, σ)] at hw
      exact ⟨w, _, ⟨_, ⟨_, rfl⟩, rfl⟩, hw⟩
    -- by Lemma 6.4 (v), multiplying the generators by units does not change the ideal
    rw [← lemma64_v _ (fun y => if h : _ then Classical.choose (hu y h) else 1), Ideal.span_le]
    rintro _ ⟨y, hy, rfl⟩
    simp only [dif_pos hy]
    exact Ideal.subset_span (Classical.choose_spec (hu y hy))

/-- **Proposition 6.5 (ii)** of `q_col_decomp.md`: if some matching is compatible with `c`, then
`π_c(I)` (regarded as an ideal of `B({1, …, d})` through the Identification `R_c = B({1, …, d})`)
is the ideal generated by the products `ι_{W_1}(g_P)·Π_{ζ∈ℛ} ι_{W_ζ}(g_{σ_ζ})`, over all perfect
matchings `P` of `𝒞_1` and all families of bijections `σ_ζ : 𝒞_ζ → 𝒞_{ζ^{−1}}` (here
`ι_W := ι_{W,{1,…,d}}`). The hypothesis that a compatible matching exists is kept as in the
source, although the equality also holds without it (`map_idealI_eq_span`). -/
theorem prop65_ii (c : Fin (2 * k + 1) → S.μ) {R : Finset F} (hR : IsReps S R)
    (_ : ∃ J : BallotBound.Matching k, Compatible (cExt c) J) :
    ((idealI S k).map (S.piC c)).map (rcEquiv (boxS S c)) =
      Ideal.span {x | ∃ (P : PerfMatch (cls (cExt c) 1))
          (σ : (ζ : R) → cls (cExt c) ζ ≃ cls (cExt c) (ζ : F)⁻¹),
        x = (boxS S c).iota (W1 S c) Finset.univ (Finset.subset_univ _) (gP S c P) *
          ∏ ζ : R, (boxS S c).iota (Wz S c ζ) Finset.univ (Finset.subset_univ _)
            (gσ S c ζ (σ ζ))} :=
  map_idealI_eq_span S c hR

/-- **Proof** of Proposition 6.5 (iii) in `q_col_decomp.md`: the blocks of variables are
disjoint when the underlying subsets of `V` are. -/
theorem disjoint_varSet {T T' : Finset (Fin (2 * k + 2))} (h : Disjoint T T') :
    Disjoint (varSet T) (varSet T') := by
  rw [Finset.disjoint_left]
  intro j hj hj'
  simp only [varSet, Finset.mem_filter, Finset.mem_univ, true_and] at hj hj'
  exact Finset.disjoint_left.1 h hj hj'

/-- **Blocks of variables** (Setting of `q_col_decomp.md`), indexed by `Option ℛ`: `none` gives
`W_1` and `some ζ` gives `W_ζ` (used in the **Proof** of Proposition 6.5 (iii) to apply Lemma 6.4
(iv) to the partition `{1, …, d} = W_1 ⊔ ⊔_{ζ∈ℛ} W_ζ`). -/
noncomputable def blocks (c : Fin (2 * k + 1) → S.μ) (R : Finset F) (j : Option R) :
    Finset (Fin (2 * k + 1)) :=
  j.elim (W1 S c) fun ζ => Wz S c ζ

/-- **Blocks of variables** (Setting of `q_col_decomp.md`): by Lemma 6.3 (i), `W_1` and the `W_ζ`
(`ζ ∈ ℛ`) are pairwise disjoint. -/
theorem blocks_pairwise_disjoint (c : Fin (2 * k + 1) → S.μ) {R : Finset F} (hR : IsReps S R) :
    Pairwise fun i j => Disjoint (blocks S c R i) (blocks S c R j) := by
  have hpart := lemma63_i_partition hR (cExt_mem c)
  rintro (_ | ζ) (_ | η) hne
  · exact absurd rfl hne
  · exact disjoint_varSet (hpart.1 η η.2)
  · exact disjoint_varSet (hpart.1 ζ ζ.2).symm
  · exact disjoint_varSet (hpart.2.1 ζ ζ.2 η η.2 fun e => hne (congrArg some (Subtype.ext e)))

/-- **Blocks of variables** (Setting of `q_col_decomp.md`): by Lemma 6.3 (i), the union of `W_1`
and the `W_ζ` (`ζ ∈ ℛ`) is `{1, …, d}`. -/
theorem univ_eq_biUnion_blocks (c : Fin (2 * k + 1) → S.μ) {R : Finset F} (hR : IsReps S R) :
    (Finset.univ : Finset (Fin (2 * k + 1))) = Finset.univ.biUnion (blocks S c R) := by
  have hpart := (lemma63_i_partition hR (cExt_mem c)).2.2
  symm
  rw [Finset.eq_univ_iff_forall]
  intro j
  have hj := hpart ▸ Finset.mem_univ j.succ
  simp only [Finset.mem_union, Finset.mem_biUnion] at hj
  simp only [Finset.mem_biUnion, Finset.mem_univ, true_and]
  rcases hj with hj | ⟨ζ, hζ, hj⟩
  · exact ⟨none, by simpa [blocks, W1, varSet] using hj⟩
  · refine ⟨some ⟨ζ, hζ⟩, ?_⟩
    simp only [blocks, Option.elim_some, Wz, varSet, Finset.mem_filter, Finset.mem_univ, true_and]
    exact Finset.mem_union.2 hj

/-- **Block generators** (Setting of `q_col_decomp.md`), indexed by `Option ℛ`: the generating
sets `E_1 := {g_P}` of `I_{c,1}` and `E_ζ := {g_σ}` of `I_{c,ζ}` (used in the **Proof** of
Proposition 6.5 (iii)). -/
noncomputable def blockGenSets (c : Fin (2 * k + 1) → S.μ) (R : Finset F) :
    (j : Option R) → Set ((boxS S c).Box (blocks S c R j))
  | none => Set.range (gP S c)
  | some ζ => Set.range (gσ S c ζ)

/-- **Proposition 6.5 (iii)** of `q_col_decomp.md`: `dim_F π_c(I) = dim_F I_{c,1}·Π_{ζ∈ℛ} dim_F I_{c,ζ}`
when some matching is compatible with `c`, and `dim_F π_c(I) = 0` otherwise. -/
theorem prop65_iii (c : Fin (2 * k + 1) → S.μ) {R : Finset F} (hR : IsReps S R) :
    ((∃ J : BallotBound.Matching k, Compatible (cExt c) J) →
        Module.finrank F ((idealI S k).map (S.piC c)) =
          Module.finrank F (Ic1 S c) * ∏ ζ ∈ R, Module.finrank F (Icz S c ζ)) ∧
      ((¬ ∃ J : BallotBound.Matching k, Compatible (cExt c) J) →
        Module.finrank F ((idealI S k).map (S.piC c)) = 0) := by
  refine ⟨fun h => ?_, fun h => by
    rw [prop65_i S c h]
    exact Module.finrank_zero_of_subsingleton⟩
  refine (finrank_map_algEquiv (rcEquiv (boxS S c)) ((idealI S k).map (S.piC c))).symm.trans ?_
  rw [prop65_ii S c hR h]
  have key := (boxS S c).lemma64_iv (blocks S c R) (blockGenSets S c R)
    (blocks_pairwise_disjoint S c hR) Finset.univ (univ_eq_biUnion_blocks S c hR)
  rw [Fintype.prod_option] at key
  change _ = Module.finrank F (Ic1 S c) * ∏ ζ : R, Module.finrank F (Icz S c ζ) at key
  rw [← Finset.prod_coe_sort R, ← key]
  have hset : {x | ∃ (P : PerfMatch (cls (cExt c) 1))
          (σ : (ζ : R) → cls (cExt c) ζ ≃ cls (cExt c) (ζ : F)⁻¹),
        x = (boxS S c).iota (W1 S c) Finset.univ (Finset.subset_univ _) (gP S c P) *
          ∏ ζ : R, (boxS S c).iota (Wz S c ζ) Finset.univ (Finset.subset_univ _)
            (gσ S c ζ (σ ζ))} =
      {x | ∃ e : (j : Option R) → (boxS S c).Box (blocks S c R j),
        (∀ j, e j ∈ blockGenSets S c R j) ∧
          x = ∏ j, (boxS S c).iota (blocks S c R j) Finset.univ
            (Finset.subset_univ _) (e j)} := by
    ext x
    constructor
    · rintro ⟨P, σ, rfl⟩
      refine ⟨fun j => match j with
        | none => gP S c P
        | some ζ => gσ S c ζ (σ ζ), ?_, ?_⟩
      · rintro (_ | ζ)
        · exact ⟨P, rfl⟩
        · exact ⟨σ ζ, rfl⟩
      · rw [Fintype.prod_option]
        rfl
    · rintro ⟨e, he, rfl⟩
      obtain ⟨P, hP⟩ := he none
      choose σ hσ using fun ζ : R => he (some ζ)
      refine ⟨P, σ, ?_⟩
      rw [Fintype.prod_option]
      congr 1
      · change (boxS S c).iota (W1 S c) Finset.univ _ (e none) = _
        rw [← hP]
      · refine Finset.prod_congr rfl fun ζ _ => ?_
        change (boxS S c).iota (Wz S c ζ) Finset.univ _ (e (some ζ)) = _
        rw [← hσ ζ]
  rw [hset]

end ColDecomp

end
