# Gate C: per-colouring LOCAL computation. Over GF(p^d) ⊇ mu_r, for every c in mu_r^{n+1}:
#   R_c = GF[u]/(u_i^q), t_i = u_i + c_i ; ideal generated by the images of ALL psi_J (literal formula of [DS]).
# Uses only the Chinese remainder theorem (A1); no block structure, no change of variables, no Part B.
import sys
def matchings(s):
    if not s: yield []; return
    a=s[0]
    for i in range(1,len(s)):
        b=s[i]; rest=s[1:i]+s[i+1:]
        for M in matchings(rest): yield [(a,b)]+M
def script(m,p,k,Fq):
    q=1
    while m%(q*p)==0: q*=p
    r=m//q; n=2*k; nv=n+1
    V=[f"u{i}" for i in range(1,nv+1)]
    L=[f"ring R = ({Fq},a),({','.join(V)}),dp;" if Fq!=p else f"ring R = {p},({','.join(V)}),dp;"]
    L.append(f"ideal box = {','.join(f'u{i}^{q}' for i in range(1,nv+1))}; box=std(box);")
    if Fq!=p:
        L.append(f"number w = a^({(Fq-1)//r});")
    else:
        # find element of order r in F_p
        L.append(f"number w; int e; for(e=2;e<{p};e++){{ w=e; if((w^{r}==1) and (w!=1)) {{ break; }} }}")
    L.append(f'if(w^{r}!=1){{ ERROR("bad root"); }}')
    L.append("int s; " + f'for(s=1;s<{r};s++){{ if(w^s==1){{ ERROR("not primitive"); }} }}')
    L.append(f"proc phiL(poly U, ideal bx) {{ poly S=0; poly P=1; int i; for(i=0;i<{m};i++){{ S=S+P; P=reduce(P*U,bx); }} return(reduce(S,bx)); }}")
    Js=[sorted(J) for J in matchings(list(range(n+2)))]
    L.append("bigint total=0; int ncomp=0; int idx; int j; list c; int e0; poly t0;")
    L.append(f"for(idx=0; idx<{r**nv}; idx++) {{")
    L.append("  int rest=idx; list ex; for(j=1;j<="+str(nv)+";j++){ ex=insert(ex, rest mod "+str(r)+", size(ex)); rest = rest div "+str(r)+"; }")
    L.append("  list cc; int sum=0; for(j=1;j<="+str(nv)+";j++){ cc=insert(cc, w^(ex[j]), size(cc)); sum=sum+ex[j]; }")
    # t_i = u_i + c_i
    L.append("  ideal T; for(j=1;j<="+str(nv)+";j++){ T[j]=var(j)+cc[j]; }")
    gens=[]
    for J in Js:
        tau="*".join(f"(T[{b}]-1)" for (a,b) in J)
        ph="*".join(f"phiL(reduce(T[{a}]*T[{b}],box),box)" for (a,b) in J if a!=0)
        gens.append("reduce("+tau+("*"+ph if ph else "")+",box)")
    L.append("  ideal G = box, "+", ".join(gens)+";")
    L.append("  int v = vdim(std(G)); int d = "+str(q**nv)+" - v;")
    L.append("  if(d>0){ ncomp++; } total = total + d;")
    L.append("  kill rest, ex, cc, sum, T, G, v, d;")
    L.append("}")
    L.append(f'print("m={m} p={p} q={q} r={r} k={k} field={Fq}: colourings with nonzero image="+string(ncomp)+" sum dim="+string(total));')
    L.append("quit;")
    return "\n".join(L)
if __name__=="__main__":
    m,p,k,Fq=map(int,sys.argv[1:5]); print(script(m,p,k,Fq))
