-- Cell (3,9): is the generic row R_2 of K_3 generated by L = K'_3 + pz(M_3 : z^2) plus the guess elements y_j^(q-2) e_4(V), V of size 5, j in V ?
q = 9; S = ZZ/3[x_0..x_6]; X = gens S; e = j -> sum(subsets(X, j), s -> product s);
I7 = ideal(e 1, e 3, e 5, e 7) + ideal apply(X, u -> u^q);
Mgen = (V, j) -> ( L := {}; for A in subsets(V, j) do for B in subsets(toList(set V - set A), j) do ( C := toList(set V - set A - set B); L = append(L, product(C, i -> X#i) * product(A, i -> (X#i)^(q-1)))); L);
M3 = ideal(Mgen(toList(0..6), 1) | Mgen(toList(0..6), 2) | Mgen(toList(0..6), 3));
K3 = I7 + M3; z = x_6; KK = K3 + ideal(z^3);
S6 = ZZ/3[y_0..y_5]; pz = map(S6, S, {y_0,y_1,y_2,y_3,y_4,y_5,0});
R2 = pz(KK : z^2); << "colength row 2 = " << degree R2 << endl << flush;
Y = gens S6; e6 = j -> sum(subsets(Y, j), s -> product s);
Mgen6 = (V, j) -> ( L := {}; for A in subsets(V, j) do for B in subsets(toList(set V - set A), j) do ( C := toList(set V - set A - set B); L = append(L, product(C, i -> Y#i) * product(A, i -> (Y#i)^(q-1)))); L);
Kp3 = ideal(e6 1, e6 3, e6 5) + ideal apply(Y, u -> u^q) + ideal(e6 6) + ideal(Mgen6(toList(0..5),1) | Mgen6(toList(0..5),2));
L = Kp3 + pz(M3 : z^2);
guess = ideal flatten for V in subsets(toList(0..5), 5) list for j in V list ( (Y#j)^(q-2) * sum(subsets(V, 4), s -> product(s, i -> Y#i)) );
<< "guess elements: " << numgens guess << ", all in R2? " << toString isSubset(guess, R2) << endl << flush;
LG = L + guess; << "colength of L + guess = " << degree LG << "  (row 2 = " << degree R2 << ", |W_gen| = 3930)" << "; equal to R2? " << toString(LG == R2) << endl << flush;
-- and with j outside V? (2k-1 = 5 variables, j the 6th)
guess2 = ideal flatten for V in subsets(toList(0..5), 5) list ( j := first toList(set toList(0..5) - set V); (Y#j)^(q-2) * sum(subsets(V, 4), s -> product(s, i -> Y#i)) );
<< "j-outside elements in R2? " << toString isSubset(guess2, R2) << "; colength of L + guess + guess2 = " << degree(LG + guess2) << endl << flush;
<< "FIN-OK" << endl; exit 0
