# kc.py — Fable, Mission 15. Class K = sets P of types closed under (-2): (s,beta) in P => (s+1,beta') in P for every
# beta' obtained by deleting 2 boxes from beta (feasible ones).  Tests, for random P in K (generated by random types +
# closure), every i:  KEY  Z(m;P)_{>i} subset Z(m-1; R_i)  and  CLOSURE  R_i in K,  where R_i = Rules_i(P) (with the
# monotone union).  Usage: python3 -u kc.py Q MMAX TRIALS SEED
import sys, random
q, MMAX, TR, SEED = int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4])
sys.argv = ['x', '1', str(q)]
from peelcore import *
random.seed(SEED)
def parts(n, mx):
    if n == 0: yield (); return
    for b in range(min(n, mx), 1, -1):
        for r in parts(n-b, b): yield (b,) + r
def alltypes(m):
    return [(s_, beta) for s_ in range(m//2+1) for tot in range(0, m-2*s_+1) for beta in parts(tot, tot)]
def minus2(beta):
    out = set(); b = list(beta)
    for x in range(len(b)):
        c = list(b); c[x] -= 2; out.add(tuple(sorted([y for y in c if y >= 2], reverse=True)))
        for y in range(x+1, len(b)):
            c = list(b); c[x] -= 1; c[y] -= 1; out.add(tuple(sorted([z for z in c if z >= 2], reverse=True)))
    if not b: out.add(())
    return out
def close(m, G):
    G = set(G); ch = True
    while ch:
        ch = False
        for (s_, beta) in list(G):
            for bs in minus2(beta):
                t = (s_+1, bs)
                if 2*t[0]+sum(t[1]) <= m and t not in G: G.add(t); ch = True
    return frozenset(G)
def isclosed(m, P): return close(m, P) == frozenset(P)
kf = 0; cf = 0; tests = 0
for trial in range(TR):
    m = random.randint(2, MMAX); T = alltypes(m)
    P = close(m, random.sample(T, random.randint(1, min(3, len(T)))))
    fib = {x: fibre(x, P) for x in types(m-1)}
    Pall = {}
    for i in range(q-2, -1, -1):
        Pall[i] = canon(m-1, set(children(m, P, i)) | (set(Pall[i+1]) if i+1 in Pall else set()))
    for i in range(q-1):
        A = frozenset(x for x in fib if fib[x] > i)
        if not A: continue
        tests += 1
        if not all(inZ(x, Pall[i]) for x in A):
            kf += 1
            if kf <= 4: print('KEY FAIL m=%d P=%s i=%d' % (m, sorted(P), i))
        if not isclosed(m-1, Pall[i]):
            cf += 1
            if cf <= 4: print('CLOSURE FAIL m=%d P=%s i=%d R_i=%s' % (m, sorted(P), i, sorted(Pall[i])))
print('q=%d trials=%d tests=%d KEY failures=%d CLOSURE failures=%d' % (q, TR, tests, kf, cf))
