# b05_colour_blocks.py — pilot. Gate for B4: for an EVEN m = q*r' with q = p^v, p odd, and r' dividing p - 1 (so that mu_r' lies in F_p),
# compute, for EVERY colouring c in mu_r'^(2k+1), the dimension of the ideal generated by the images of the literal generators psi_J
# of [DS] in the local factor R_c = F_p[x_1..x_n]/(x_i^q), t_i = c_i + x_i, and compare it with the product of block counts
#     Q^[(q-1)/2](|C_1|) * N_q(|C_{-1}|) * prod_zeta N_bal(|C_zeta|, q)     (0 if c is not compatible).
# This uses only the splitting of the group algebra (Lemma 6.1 of the paper); nothing about the blocks is assumed.
# Usage: b05_colour_blocks.py k m p
import sys, itertools, numpy as np
from eng import Box, matchings, N_odd, Q_free, monomials_of_degree, rref_mod_p
from b01_theoremC_even import N_bal

def main(k, m, p):
    q = 1
    while (m // q) % p == 0: q *= p
    rp = m // q
    assert (p - 1) % rp == 0
    n = 2 * k + 1
    # a primitive r'-th root of unity in F_p
    g = next(z for z in range(2, p) if all(pow(z, (p - 1) // f, p) != 1 for f in range(2, p) if (p - 1) % f == 0)) if p > 3 else 2
    zeta = pow(g, (p - 1) // rp, p)
    box = Box([q] * n, p)
    size = q ** n
    w = np.array([q ** (n - 1 - i) for i in range(n)], dtype=np.int64)
    Js = matchings(range(n + 1))
    total = 0; bad = 0; ncomp = 0; summary = {}
    for c in itertools.product(range(rp), repeat=n):
        col = ((-sum(c)) % rp,) + c
        t = [box.poly([(pow(zeta, c[i], p), {}), (1, {i: 1})]) for i in range(n)]          # t_i = c_i + x_i
        rows = []
        for J in Js:
            f = box.one(); ks = []
            for (j, l) in J:
                ks.append(l - 1)
                f = box.mul(f, box.add(t[l - 1], box.one(), -1))
                if j != 0:
                    u = box.mul(t[j - 1], t[l - 1]); phi = box.one(); pw = box.one()
                    for _ in range(m - 1):
                        pw = box.mul(pw, u); phi = box.add(phi, pw)
                    f = box.mul(f, phi)
            if len(f[1]) == 0: continue
            for e in range((q - 1) * len(ks) + 1):
                for mrow in monomials_of_degree(tuple([q] * len(ks)), e):
                    beta = np.zeros(n, dtype=np.int64); beta[ks] = mrow
                    h = box.shift(f, beta)
                    if len(h[1]):
                        v = np.zeros(size, dtype=np.int16); v[h[0] @ w] = h[1]; rows.append(v)
        d = 0
        if rows:
            M = None
            for s in range(0, len(rows), 1500):
                chunk = np.array(rows[s:s + 1500])
                M = chunk if M is None else np.concatenate([M, chunk])
                M, piv = rref_mod_p(M, p)
            d = len(M)
        cls = [sum(1 for x in col if x == y) for y in range(rp)]
        pred = 0
        if cls[0] % 2 == 0 and (rp % 2 or cls[rp // 2] % 2 == 0) and all(cls[x] == cls[(-x) % rp] for x in range(rp)):
            pred = Q_free((q - 1) // 2, cls[0]) * (N_odd(q, cls[rp // 2]) if rp % 2 == 0 else 1)
            for x in range(1, rp):
                if x < (-x) % rp and cls[x]: pred *= N_bal(cls[x], q)
            ncomp += 1
        total += d; bad += (d != pred)
        key = (cls[0], cls[rp // 2] if rp % 2 == 0 else 0, 0 if col[0] == 0 else (1 if rp % 2 == 0 and col[0] == rp // 2 else 2))
        summary.setdefault(key, set()).add((d, pred))
    G = N_odd(m - 1, 2 * k + 2)
    print(f"BLOCKS k={k} m={m} p={p} (q={q}, r'={rp}): {rp ** n} colourings, {ncomp} compatible; sum of the dimensions={total}  |Gamma|={G}  equal={total == G}; colourings whose dimension differs from the predicted product: {bad}", flush=True)
    for key in sorted(summary):
        print(f"    |C_1|={key[0]} |C_-1|={key[1]} colour of the index 0: {['1', '-1', 'other'][key[2]]}:  (measured, predicted) = {sorted(summary[key])}", flush=True)

if __name__ == "__main__":
    main(int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3]))
