# c04_principal.py — pilot. Leg C: generators of V = gr J(Z) for the principal down-sets of the order «⊑» on marked shapes:
#   (lam, e) ⊑ (lam', e)   iff lam ≼ lam' (weak dominance);     (lam, e) ⊑ (lam', 1-e) iff lam ≼ lam' - e_j for some row j.
# For each shape s at level m:  the down-set generated by s, its number of points, the degrees of the minimal generators of gr J,
# and the generators that are NEW, i.e. not in gr J of the union of the strictly smaller principal down-sets.
# Usage: c04_principal.py r m p [maxterms]
import sys, numpy as np
from eng import Box, Graded
import shapes as sh
from grj import Grid, leq
from c01_slicetree import mingens
from c02_generators import polystr

def below(s, t):
    (a, ea), (b, eb) = s, t
    if ea == eb: return leq(a, b)
    for j in range(len(b)):
        lo = list(b); lo[j] -= 1
        if leq(a, sh.norm(lo)): return True
    return False

def main(r, m, p, maxterms=14, only=None):
    G = Grid(r, m, p)
    allshapes = sorted(sh.counts(m, r), key=lambda t: (sum(t[0]) + t[1], t[1], t[0]))
    names = [f"y{i+1}" for i in range(m)]
    print(f"PRINCIPAL r={r} m={m} p={p}", flush=True)
    for s in allshapes:
        if only and sh.show([s]).strip("{}") not in only: continue
        down = frozenset(t for t in allshapes if below(t, s))
        strict = frozenset(t for t in down if t != s)
        V = G.grJ(down); V0 = G.grJ(strict)
        mg = mingens(V)
        # new generators: degree by degree, dim V_d - dim (V0_d + y * V_{d-1})
        new = {}
        for d in sorted(V.rows):
            if V.dim(d) == 0: continue
            Wd = Graded(G.box)
            vecs = [Wd.to_vec(d, f) for f in V0.basis_polys(d)]
            if d - 1 in V.rows:
                for f in V.basis_polys(d - 1):
                    for i in range(m):
                        beta = np.zeros(m, dtype=np.int64); beta[i] = 1
                        g = G.box.shift(f, beta)
                        if len(g[1]): vecs.append(Wd.to_vec(d, g))
            if vecs: Wd.add_vecs(d, vecs)
            if V.dim(d) - Wd.dim(d): new[d] = V.dim(d) - Wd.dim(d)
        print(f"  shape {sh.show([s])}: down-set {sh.show(down)}  |Z|={sh.size(down, m, r)}  mingens={mg}  new generators (deg:number)={new}", flush=True)
        d0 = min(V.rows) if V.rows else None
        if d0 is not None and d0 in new:
            for f in V.basis_polys(d0)[:3]:
                if len(f[1]) <= maxterms: print("       ", polystr(f, names, p), flush=True)

if __name__ == "__main__":
    main(int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4]) if len(sys.argv) > 4 else 14, sys.argv[5].split("|") if len(sys.argv) > 5 else None)
