# c05_candidates.py — pilot. Leg C: test of the candidate generators of patterns.py.
# mode "grid r m p":  for EVERY down-set Lambda of the order ⊑ (interlaced pairs) at level m:
#        is the ideal generated by the patterns of the shapes of Lambda equal to gr J(Z_Lambda)?   (needs (r-1) | (p-1))
#        with the control «no absorbed pairs» (only t = 0 in the marked block) reported as well.
# mode "tree k r p":  for every node of the slice tree of the root ideal (D_{r,J}) (any characteristic, in particular 2):
#        is the node equal to the ideal generated by the patterns of its shapes?
import sys, numpy as np
from eng import Box, Graded, ideal_from_generators, slices
import shapes as sh
from grj import Grid, par, downsets, interlaced
from patterns import patterns
from a04_oddbox import gens_free

def cand(box, Lam, r, absorb=True):
    gens = []
    for s in Lam:
        gens += patterns(box, s, r, absorb)
    S = Graded(box)
    gens = [g for g in gens if len(g[1])]
    return ideal_from_generators(box, gens) if gens else S

def same(A, B):
    return A.dim() == B.dim() and A.contains_space(B)

def grid(r, m, p):
    h = (r - 1) // 2
    G = Grid(r, m, p)
    D0 = downsets(par(m, h)); D1 = downsets(par(m - 1, h))
    tot = ok = ok_noabs = inside = 0; first = None
    for L0 in D0:
        for L1 in D1:
            if not interlaced(L0, L1): continue
            Lam = frozenset([(x, 0) for x in L0] + [(x, 1) for x in L1])
            if not Lam: continue
            tot += 1
            V = G.grJ(Lam)
            C = cand(G.box, Lam, r, True)
            C0 = cand(G.box, Lam, r, False)
            good = same(V, C)
            ok += good; ok_noabs += same(V, C0); inside += V.contains_space(C)
            if not good and first is None:
                first = f"Lambda={sh.show(Lam)}: |Z|={V.dim()} dim candidate={C.dim()} candidate inside gr J: {V.contains_space(C)}"
    print(f"GRID r={r} m={m} p={p}: down-sets of ⊑: {tot};  candidate ideal = gr J(Z): {ok};  candidate inside gr J: {inside};  [control without absorbed pairs: {ok_noabs} equal]", flush=True)
    if first: print("     first failure:", first, flush=True)

def tree(k, r, p):
    n = 2 * k + 1
    box = Box([r] * n, p)
    g, f = gens_free(box, k, r, True)
    V = ideal_from_generators(box, g, free=f)
    root = frozenset({((1,), 0), ((), 1)})
    seen = set(); todo = [(n, root, V)]
    tot = ok = 0; first = None
    while todo:
        m, Lam, S = todo.pop()
        if (m, Lam) in seen: continue
        seen.add((m, Lam))
        if m >= 1:
            tot += 1
            C = cand(S.box, Lam, r, True)
            good = same(S, C); ok += good
            if not good and first is None:
                first = f"m={m} Lambda={sh.show(Lam)}: dim node={S.dim()} dim candidate={C.dim()} candidate inside node: {S.contains_space(C)}"
        if m == 0: continue
        Ls, F = sh.layers(Lam, m, r)
        box2, W = slices(S, 0)
        for i in range(r):
            if W[r - 1 - i].dim(): todo.append((m - 1, Ls[i], W[r - 1 - i]))
    print(f"TREE k={k} r={r} p={p}: nodes (m >= 1): {tot};  node = ideal of the candidate patterns: {ok}", flush=True)
    if first: print("     first failure:", first, flush=True)

if __name__ == "__main__":
    if sys.argv[1] == "grid": grid(int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4]))
    else: tree(int(sys.argv[2]), int(sys.argv[3]), int(sys.argv[4]))
