# c07_lifts.py — pilot. Gate for the lifting constructions of Leg C (the analogue of Proposition 5.8 of the paper for the odd box).
# For every ⊑-down-set Lambda at level m, every tail shape sigma = (mu, eps) at level m-1 with Phi = F_Lambda(sigma) >= 1,
# and every pattern G of sigma on the tail variables (variable 0 is the peeled one):
#   the explicit element f of the pencil construction is built, and three things are checked:
#     (1) f lies in V_Lambda (the ideal generated by the patterns of all the shapes of Lambda);
#     (2) deg_{y_0} f <= r - Phi;   (3) the coefficient of y_0^(r - Phi) in f is +G or -G.
#   Cases, by the last option of the chain  removals <= zero option <= middle <= additions  that lies in Lambda:
#     alpha  : an addition                      -> index 0 goes into the Vandermonde block of the column mu_{j0} + 1
#     beta   : middle, unmarked tail            -> index 0 goes into the first column block
#     beta'  : middle, marked tail              -> y_0 Pf_{E+}(M u 0) +- Pf with the border column D(y_0, .)
#     zeta   : zero option, unmarked tail       -> Pf_E(B_1 u 0) (or y_0^(r-1) if mu is empty)
#     zeta'  : zero option, marked tail         -> NO pencil construction: only «G lies in W_{r-Phi}(V_Lambda)» is measured
#     gamma  : a removal, ordinary column       -> sum_b eps_b Delta(S - b) D(y_0, y_b) G'
#     gamma' : removal of a row of length 1 of a marked tail -> Pf_{E'}(M u 0)
# Usage: c07_lifts.py r m p
import sys, itertools, numpy as np
from eng import Box, Graded, ideal_from_generators, slices, Dpoly, prod
import shapes as sh
from grj import par, downsets, interlaced
from patterns import patterns, Bpoly, vandermonde, pfaffian, set_splits, matchings_of
from c05_candidates import cand

def zero(box): return box.clean(np.zeros((0, box.n), dtype=np.int64), np.zeros(0, dtype=np.int64))

def pf_general(box, M, E, r, extra=None):
    """Pfaffian on M (variables) u E (border exponents) u optionally one extra border column given by a function var -> poly."""
    idx = [("v", i) for i in sorted(M)] + [("e", e) for e in E] + ([("x", 0)] if extra else [])
    def entry(a, b):
        if a[0] == "v" and b[0] == "v": return Bpoly(box, a[1], b[1], r)
        if a[0] == "v" and b[0] == "e": return box.var(a[1], b[1]) if b[1] > 0 else box.one()
        if a[0] == "v" and b[0] == "x": return extra(a[1])
        return None
    return pfaffian(box, idx, entry)

def Eset(l, r):                       # border of the marked block when the first column of mu has l rows
    return [r - 1] if l == 0 else list(range(0, l - 1))

def structures(tail, shape, r):
    """All patterns of the shape on the index list `tail`, as structures (pairs, blocks, M, t)."""
    mu, eps = shape
    cols = [sum(1 for x in mu if x >= c) for c in range(1, (mu[0] if mu else 0) + 1)]
    n = len(tail)
    if eps == 0:
        if n < sum(mu) or (n - sum(mu)) % 2: return
        for blocks, rest in set_splits(tail, cols):
            for P in matchings_of(rest): yield dict(P=P, blocks=[tuple(b) for b in blocks], M=None)
    else:
        s = (cols[0] if cols else 0) + 1
        other = cols[1:]
        free = n - sum(other) - s
        if free < 0 or free % 2: return
        for t in range(free // 2 + 1):
            for blocks, rest in set_splits(tail, other + [s + 2 * t]):
                for P in matchings_of(rest): yield dict(P=P, blocks=[tuple(b) for b in blocks[:-1]], M=tuple(blocks[-1]))

def poly_of(box, st, shape, r, drop_first=False, drop_M=False, drop_block=None):
    mu, eps = shape
    f = prod(box, [Dpoly(box, a, b, r) for (a, b) in st["P"]])
    for i, bl in enumerate(st["blocks"]):
        if (eps == 0 and drop_first and i == 0) or (drop_block is not None and i == drop_block): continue
        f = box.mul(f, vandermonde(box, bl))
    if eps == 1 and not drop_M:
        f = box.mul(f, pf_general(box, st["M"], Eset(len(mu), r), r))
    return f

def coeff(box, f, var, j):
    E, c = f
    sel = E[:, var] == j
    E2 = E[sel].copy(); E2[:, var] = 0
    return box.clean(E2, c[sel])

def eq_up_to_sign(box, f, g):
    return len(box.add(f, g, -1)[1]) == 0 or len(box.add(f, g, 1)[1]) == 0

def main(r, m, p):
    h = (r - 1) // 2
    box = Box([r] * m, p)
    tail = list(range(1, m))
    D0 = downsets(par(m, h)); D1 = downsets(par(m - 1, h))
    stats = {}
    for L0 in D0:
        for L1 in D1:
            if not interlaced(L0, L1): continue
            Lam = frozenset([(x, 0) for x in L0] + [(x, 1) for x in L1])
            if not Lam: continue
            V = cand(box, Lam, r, True)
            W = None
            for shape in sh.counts(m - 1, r):
                mu, eps = shape; l = len(mu)
                rem = [(sh.norm(mu[:j] + (mu[j] - 1,) + mu[j + 1:]), eps) for j in range(l)]
                add = [(sh.norm(mu[:j] + (mu[j] + 1,) + mu[j + 1:]), eps) for j in range(l)]
                zer = (mu, 1 - eps); mid = (sh.norm(mu + (1,)), eps) if h > l else None
                Phi = sh.fibre(Lam, shape, h)
                if Phi == 0: continue
                adds_in = [j for j in range(l) if add[j] in Lam]
                if adds_in: case = "alpha"
                elif mid is not None and mid in Lam: case = "beta" if eps == 0 else "beta'"
                elif zer in Lam: case = "zeta" if eps == 0 else "zeta'"
                else:
                    rho = sum(1 for j in range(l) if rem[j] in Lam)       # removals in Lambda are the rows 1..rho
                    case = "gamma'" if (eps == 1 and mu[rho - 1] == 1) else "gamma"
                for st in structures(tail, shape, r):
                    G = poly_of(box, st, shape, r)
                    if len(G[1]) == 0: continue
                    key = case; rec = stats.setdefault(key, [0, 0])
                    rec[0] += 1
                    target = r - Phi
                    if case == "zeta'":
                        if W is None: W = slices(V, 0)[1]
                        Gt = (np.delete(G[0], 0, axis=1), G[1])
                        ok = all(W[target].contains_vec(d, W[target].to_vec(d, part)) for d, part in W[target].box.degree_parts(Gt).items())
                        rec[1] += (not ok); continue
                    cands = []
                    if case == "alpha":
                        j0 = min(adds_in); c = mu[j0] + 1                 # column index (1-based) that receives the new box
                        st2 = dict(P=st["P"], blocks=list(st["blocks"]), M=st["M"])
                        k = (c - 1) if eps == 0 else (c - 2)              # position in the list of blocks
                        if k < len(st2["blocks"]): st2["blocks"][k] = tuple(sorted(st2["blocks"][k] + (0,)))
                        else: st2["blocks"].append((0,))
                        newshape = add[j0]
                        cands = [poly_of(box, st2, newshape, r)]
                    elif case == "beta":
                        st2 = dict(P=st["P"], blocks=list(st["blocks"]), M=None)
                        if st2["blocks"]: st2["blocks"][0] = tuple(sorted(st2["blocks"][0] + (0,)))
                        else: st2["blocks"] = [(0,)]
                        cands = [poly_of(box, st2, mid, r)]
                    elif case == "zeta":
                        rest = poly_of(box, st, shape, r, drop_first=True)
                        if l == 0: cands = [box.mul(box.var(0, r - 1), G)]
                        else: cands = [box.mul(pf_general(box, st["blocks"][0] + (0,), Eset(l, r), r), rest)]
                    elif case == "gamma":
                        c0 = mu[rho - 1]                                   # the column of height rho
                        k = (c0 - 1) if eps == 0 else (c0 - 2)
                        S = sorted(st["blocks"][k])
                        rest = poly_of(box, st, shape, r, drop_block=k)
                        f = zero(box)
                        for i, b in enumerate(S):
                            term = box.mul(box.mul(vandermonde(box, [x for x in S if x != b]), Dpoly(box, 0, b, r)), rest)
                            f = box.add(f, term, (-1) ** i)
                        cands = [f]
                    elif case == "gamma'":
                        rest = poly_of(box, st, shape, r, drop_M=True)
                        cands = [box.mul(pf_general(box, st["M"] + (0,), Eset(l - 1, r), r), rest)]
                    elif case == "beta'":
                        rest = poly_of(box, st, shape, r, drop_M=True)
                        Ep = list(range(0, l))                             # E+ = {0..l-1}
                        A = box.mul(box.var(0), pf_general(box, st["M"] + (0,), Ep, r))
                        Bx = pf_general(box, st["M"], Ep, r, extra=lambda v: Dpoly(box, 0, v, r))
                        cands = [box.mul(box.add(A, Bx, sg), rest) for sg in (1, -1)]
                    good = False
                    for f in cands:
                        degs = f[0][:, 0] if len(f[1]) else np.zeros(0, dtype=np.int64)
                        if len(degs) and degs.max() > target: continue
                        top = coeff(box, f, 0, target)
                        if eq_up_to_sign(box, top, G) and V.contains_poly(f):
                            good = True; break
                    rec[1] += (not good)
    tot = sum(v[0] for v in stats.values()); bad = sum(v[1] for v in stats.values())
    print(f"LIFTS r={r} m={m} p={p}: (generator, down-set) pairs tested: {tot}; failures: {bad};  by case (tested, failed): " +
          ", ".join(f"{k}: {tuple(v)}" for k, v in sorted(stats.items())), flush=True)

if __name__ == "__main__":
    main(int(sys.argv[1]), int(sys.argv[2]), int(sys.argv[3]))
