module

public import Mathlib

/-!
# Definitions for the ballot lower bound (`q3_ballot_lower_bound.md`)

This file formalizes the **Setting** section of `q3_ballot_lower_bound.md`.
Throughout, `k : ℕ` is fixed, `n' = 2k + 1`, and the ground set `{0, 1, …, n'}` is
`Fin (2 * k + 2)`.
-/

@[expose] public section

open MvPolynomial

namespace BallotBound

variable (F : Type*) [Field F] (k : ℕ)

/-- The ideal `(y_1^2, …, y_{n'}^2)` of `F[y_1, …, y_{n'}]` from the **Setting** of
`q3_ballot_lower_bound.md`.  The variable `y_i` (`1 ≤ i ≤ n'`) is `X (i - 1)`, i.e.
variables are indexed by `Fin (2 * k + 1)`. -/
noncomputable def squaresIdeal : Ideal (MvPolynomial (Fin (2 * k + 1)) F) :=
  Ideal.span (Set.range fun i : Fin (2 * k + 1) => (X i ^ 2 : MvPolynomial (Fin (2 * k + 1)) F))

/-- The algebra `C := F[y_1, …, y_{n'}] / (y_1^2, …, y_{n'}^2)` from the **Setting** of
`q3_ballot_lower_bound.md`, with `n' = 2k + 1`. -/
abbrev Alg : Type _ := MvPolynomial (Fin (2 * k + 1)) F ⧸ squaresIdeal F k

/-- `C` as a module over itself (a shortcut for instance search; this is the usual structure
`Semiring.toModule`, which is needed to regard ideals of `C` as `F`-subspaces). -/
noncomputable instance instModuleAlgSelf : Module (Alg F k) (Alg F k) := Semiring.toModule

/-- The generators `y_i ∈ C`, indexed by the ground set `{0, 1, …, n'} = Fin (2 * k + 2)` of
the **Setting** of `q3_ballot_lower_bound.md`: for `i = j + 1` (`1 ≤ i ≤ n'`) this is the class of
the variable `y_i = X j`.  The value at `0` is an unused dummy value `0` (the element `0` never
contributes a factor to `D_J`). -/
noncomputable def y : Fin (2 * k + 2) → Alg F k :=
  Fin.cases 0 (fun j => Ideal.Quotient.mk (squaresIdeal F k) (X j))

/-- The set `𝒥` of perfect matchings of `{0, 1, …, n'}` (a set with `2k + 2` elements) from the
**Setting** of `q3_ballot_lower_bound.md`.  A perfect matching is encoded, as usual, by the
fixed-point-free involution `J` sending each element to its partner. -/
def Matching : Type := {J : Fin (2 * k + 2) → Fin (2 * k + 2) // ∀ x, J x ≠ x ∧ J (J x) = x}

variable {F k} in
/-- The element `D_J := ∏_{ {a,b} ∈ J, a < b, 0 ∉ {a,b} } (y_b − y_a) ∈ C` of the **Setting** of
`q3_ballot_lower_bound.md`.  A pair `{a, b}` of `J` with `a < b` not containing `0` is recorded
by its smaller element `a` (so `b = J a`); the empty product (case `k = 0`) is `1`. -/
noncomputable def D (J : Matching k) : Alg F k :=
  ∏ a ∈ Finset.univ.filter (fun a => a ≠ 0 ∧ J.1 a ≠ 0 ∧ a < J.1 a), (y F k (J.1 a) - y F k a)

/-- The ideal `V ⊆ C` generated by all `D_J`, `J ∈ 𝒥`, from the **Setting** of
`q3_ballot_lower_bound.md`. -/
noncomputable def V : Ideal (Alg F k) := Ideal.span (Set.range (D (F := F) (k := k)))

end BallotBound

end
