# auditoria_T3.py — auditor's own gate of Theorem T3 of the pilot (Grepy Chats, 2 Oct 2026). Own code; nothing imported from the pilot.
# Box ring F_p[y_1..y_m]/(y_i^3).  D(a,b) = a^2 - ab + b^2.  Ideals I(m,J) as defined in PROOF_ODD_BOX.md section 8.
# Checks: dim I(m,J) against |Z_J^(m)| = #{M in {-1,0,1}^m : |sum M| <= J}; and the three slice containments of the proof, as memberships.
import sys, itertools
import numpy as np

def matchings(S, k):                       # all sets of k disjoint pairs inside the sorted list S
    S = list(S)
    if k == 0: yield (); return
    if len(S) < 2 * k: return
    a = S[0]; rest = S[1:]
    for i, b in enumerate(rest):
        for M in matchings(rest[:i] + rest[i+1:], k - 1): yield ((a, b),) + M
    yield from matchings(rest, k)

class Box:
    def __init__(s, m, p): s.m, s.p, s.N = m, p, 3 ** m
    def mono(s, exps):
        A = np.zeros((3,) * s.m, dtype=np.int64); A[tuple(exps)] = 1; return A
    def var(s, i, e=1):
        x = [0] * s.m; x[i] = e; return s.mono(x)
    def mul(s, A, B):
        C = np.zeros_like(A)
        for idx in zip(*np.nonzero(B)):
            c = B[idx]; sl_src = tuple(slice(0, 3 - d) for d in idx); sl_dst = tuple(slice(d, 3) for d in idx)
            C[sl_dst] += c * A[sl_src]
        return C % s.p
    def D(s, a, b): return (s.var(a, 2) - s.mul(s.var(a), s.var(b)) + s.var(b, 2)) % s.p
    def DP(s, P):
        A = s.mono([0] * s.m)
        for a, b in P: A = s.mul(A, s.D(a, b))
        return A
    def span(s, gens):                     # echelon basis (list of rows) of the ideal generated by gens
        rows = []
        for g in gens:
            for idx in itertools.product(range(3), repeat=s.m):
                sl_src = tuple(slice(0, 3 - d) for d in idx); sl_dst = tuple(slice(d, 3) for d in idx)
                C = np.zeros_like(g); C[sl_dst] = g[sl_src]
                if C.any(): rows.append(C.reshape(-1))
        if not rows: return np.zeros((0, s.N), dtype=np.int64), []
        M = np.array(rows, dtype=np.int64) % s.p
        return s.echelon(M)
    def echelon(s, M):
        p = s.p; r = 0; piv = []
        for c in range(M.shape[1]):
            nz = np.flatnonzero(M[r:, c])
            if len(nz) == 0: continue
            i = nz[0] + r
            if i != r: M[[r, i]] = M[[i, r]]
            M[r] = (M[r] * pow(int(M[r, c]), -1, p)) % p
            o = np.flatnonzero(M[:, c]); o = o[o != r]
            if len(o): M[o] = (M[o] - M[o, c][:, None] * M[r][None, :]) % p
            piv.append(c); r += 1
            if r == M.shape[0]: break
        return M[:r], piv
    def member(s, E, piv, v):
        v = v.reshape(-1) % s.p
        if len(piv): v = (v - v[piv] @ E) % s.p
        return not v.any()

def gens(R, m, J, idx=None):               # generators of I(m,J) on the variables idx (default all)
    idx = list(range(m)) if idx is None else idx
    out = []
    if J >= m: return [R.mono([0] * R.m)]
    if (m - J) % 2 == 0:
        for P in matchings(idx, (m - J) // 2): out.append(R.DP(P))
    elif J >= 1:
        p = (m - 1 - J) // 2
        for P in matchings(idx, p):
            used = {x for pr in P for x in pr}; free = [x for x in idx if x not in used]
            for a, b in itertools.combinations(free, 2): out.append(R.mul((R.var(b) - R.var(a)) % R.p, R.DP(P)))
        for P in matchings(idx, p + 1): out.append(R.DP(P))
    else:                                   # J = 0, m odd
        for c in idx:
            rest = [x for x in idx if x != c]
            for P in matchings(rest, len(rest) // 2): out.append(R.mul(R.var(c, 2), R.DP(P)))
        for a, b, c in itertools.combinations(idx, 3):
            rest = [x for x in idx if x not in (a, b, c)]
            V = R.mul(R.mul((R.var(b) - R.var(a)) % R.p, (R.var(c) - R.var(a)) % R.p), (R.var(c) - R.var(b)) % R.p)
            for P in matchings(rest, len(rest) // 2): out.append(R.mul(V, R.DP(P)))
    return out

def Zcount(m, J):
    return sum(1 for M in itertools.product((-1, 0, 1), repeat=m) if abs(sum(M)) <= J)

def slices(R, E):                           # W_0, W_1, W_2 of the ideal with echelon basis E, peeling variable 0: as echelon bases in the box of the other variables
    m = R.m; out = []
    T = E.reshape((-1,) + (3,) * m)
    R2 = Box(m - 1, R.p)
    for j in range(3):
        # elements with y_0-degree <= j: solve by elimination ordering: put coefficients of y_0^2, y_0^1, y_0^0 in that order
        order = [2, 1, 0]
        M = np.concatenate([T[:, d].reshape(len(T), -1) for d in order], axis=1) % R.p
        Ech, piv = R2.echelon(M.copy()) if len(M) else (M, [])
        n1 = 3 ** (m - 1)
        lead_block = order.index(j)
        rows = [row[lead_block * n1:(lead_block + 1) * n1] for row, pc in zip(Ech, piv) if pc // n1 == lead_block]
        W = np.array(rows, dtype=np.int64).reshape(-1, n1) if rows else np.zeros((0, n1), dtype=np.int64)
        out.append(R2.echelon(W.copy()) if len(W) else (W, []))
    return out

mmax = int(sys.argv[1]); ok = bad = 0
for p in (2, 3):
    for m in range(1, mmax + 1):
        R = Box(m, p)
        for J in range(0, m + 1):
            E, piv = R.span(gens(R, m, J)); dim = len(piv); z = Zcount(m, J)
            line = f"p={p} m={m} J={J}: dim I = {dim}, |Z| = {z}, dim>=|Z| {dim >= z}, equal {dim == z}"
            good = dim >= z
            if m >= 2 and J < m:
                W = slices(R, E)
                R2 = Box(m - 1, p)
                want = [J - 1, J, J + 1] if J >= 1 else [None, None, 1]
                for j, Jt in zip(range(3), want):
                    if Jt is None or Jt < 0: continue
                    sub = gens(R2, m - 1, Jt)
                    inside = all(R2.member(W[j][0], W[j][1], g) for g in sub)
                    line += f" | W_{j} contains I({m-1},{Jt}): {inside}"
                    good = good and inside
            print(line, flush=True); ok += good; bad += (not good)
print(f"T3 gate: {ok} ideals pass, {bad} fail")
print("FIN-OK")
