# fria_gate5.py — cold audit, gate G5: Lemma 5.1 of PROOF_ODD_BOX.md as stated: Pf_{E_l}(M) lies in the ideal (Delta(S) D_Q : |S| = l+1, Q a perfect matching of M minus S). Own code.
# Control that can fail: the ideal generated by the products with ONE fixed S only (the first l+1 indices). (A first control, |S| = l+3, was invalid: an alternating polynomial is always a multiple of the Vandermonde determinant, so it could not fail; see the audit file, errors.)
import sys, itertools
from fria_engine import *
ok = bad = ctrl_out = ctrl_n = 0
for a in sys.argv[1:]:
    r, l, t, p = (int(x) for x in a.split(','))
    n = l + 1 + 2 * t; R = Box(n, r, p); M = list(range(n))
    PF = R.pfE(M, E_of(l, r))
    def gens(sz):
        out = []
        for S in itertools.combinations(M, sz):
            rest = [x for x in M if x not in S]
            for Q in kpairs(rest, len(rest) // 2):
                if 2 * len(Q) != len(rest): continue
                out.append(R.prod([R.vdm(S)] + [R.D(x, y) for x, y in Q]))
        return out
    U = R.ideal(gens(l + 1)); inside = R.member(U, PF)
    line = f"r={r} l={l} t={t} p={p}: n={n}, Pf nonzero {bool(PF.any())}, in the ideal {inside}"
    ok += inside; bad += (not inside)
    if t >= 1 and PF.any():
        S0 = tuple(M[:l + 1]); rest0 = M[l + 1:]
        g0 = [R.prod([R.vdm(S0)] + [R.D(x, y) for x, y in Q]) for Q in kpairs(rest0, len(rest0) // 2)]
        U2 = R.ideal(g0); c = R.member(U2, PF); ctrl_n += 1; ctrl_out += (not c)
        line += f"; control (one fixed S only): in the smaller ideal {c}"
    print(line, flush=True)
print(f"Lemma 5.1: {ok} hold, {bad} fail; control fired in {ctrl_out} of {ctrl_n}"); print("FIN-OK")
