# fria_gate3.py — cold audit, gate G3: Theorem 7.6 of the paper (bipartite down-set theorem) at an EVEN box q in characteristic 2,
# at EVERY down-set of BPar_q(alpha, beta), not only the roots. Own code (Grepy Chats, 2 Oct 2026).
# Ring F_p[x_1..x_alpha, z_1..z_beta]/(x^q, z^q). Tight patterns as in section 7.2 of the paper. Z_Lambda in Omega^alpha x Omega^beta, |Omega| = q.
# Control that can fail: the ideal generated by the patterns of the maximal elements of Lambda only.
import sys, itertools, random
from fria_engine import Box, partitions, wdom, columns, blocks
import numpy as np

def bpar(al, be, q):
    out = []
    for sp in range(0, al + 1):
        sm = sp - (al - be)
        if sm < 0 or sm > be: continue
        for lp in partitions(sp, q):
            for lm in partitions(sm, q):
                if len(lp) + len(lm) <= q: out.append((lp, lm))
    return out
def leq(a, b): return wdom(a[0], b[0]) and wdom(a[1], b[1])
def shape(xi, eta, q):
    lp = []; lm = []
    for u in range(q):
        d = xi.count(u) - eta.count(u)
        if d > 0: lp.append(d)
        elif d < 0: lm.append(-d)
    return (tuple(sorted(lp, reverse=True)), tuple(sorted(lm, reverse=True)))
def products(R, lam, al, be, q):
    lp, lm = lam; npairs = al - sum(lp); out = []
    A = list(range(al)); B = list(range(al, al + be))
    xz = {}
    def pw(i, l):
        if (i, l) not in xz:
            base = (R.var(i) - R.var(l)) % R.p; P = R.one()
            for _ in range(q - 1): P = R.mul(P, base)
            xz[(i, l)] = P
        return xz[(i, l)]
    for As in itertools.combinations(A, npairs):
        for Bs in itertools.permutations(B, npairs):
            if npairs and False: pass
            DP = R.prod([pw(i, l) for i, l in zip(As, Bs)])
            restA = [x for x in A if x not in As]; restB = [x for x in B if x not in Bs]
            for BA in blocks(restA, columns(lp)):
                for BB in blocks(restB, columns(lm)):
                    out.append(R.prod([DP] + [R.vdm(b) for b in BA] + [R.vdm(b) for b in BB]))
    return out
def downsets(P, cap=4000, seed=1):
    n = len(P); below = [[j for j in range(n) if leq(P[j], P[i])] for i in range(n)]
    if n <= 14:
        res = []
        for bits in range(1, 1 << n):
            if all((bits >> j) & 1 for i in range(n) if (bits >> i) & 1 for j in below[i]): res.append(bits)
        return res, True
    rng = random.Random(seed); res = set()
    for i in range(n): res.add(sum(1 << j for j in below[i]))
    for _ in range(cap):
        k = rng.randint(2, 4); b = 0
        for i in rng.sample(range(n), k):
            for j in below[i]: b |= 1 << j
        res.add(b)
    return sorted(res), False

tot = dict(ds=0, ge=0, eq=0, ctrl=0)
for a in sys.argv[1:]:
    q, al, be, p = (int(x) for x in a.split(','))
    R = Box(al + be, q, p); P = bpar(al, be, q); n = len(P)
    Vs = [R.ideal(products(R, lam, al, be, q)) for lam in P]
    cnt = {}
    for xi in itertools.product(range(q), repeat=al):
        for eta in itertools.product(range(q), repeat=be):
            s = shape(xi, eta, q); cnt[s] = cnt.get(s, 0) + 1
    assert set(cnt) <= set(P)
    DS, exhaustive = downsets(P)
    c = dict(ds=0, ge=0, eq=0, ctrl=0)
    for bits in DS:
        idx = [i for i in range(n) if (bits >> i) & 1]
        V = R.add([Vs[i] for i in idx]); dim = R.dim(V); z = sum(cnt.get(P[i], 0) for i in idx)
        mx = [i for i in idx if not any(j != i and leq(P[i], P[j]) for j in idx)]
        dc = R.dim(R.add([Vs[i] for i in mx]))
        c['ds'] += 1; c['ge'] += dim >= z; c['eq'] += dim == z; c['ctrl'] += dc < z
        if dim < z: print(f"  !!! q={q} ({al},{be}) p={p} Lambda={[P[i] for i in idx]}: dim {dim} < |Z| {z}", flush=True)
    print(f"q={q} (alpha,beta)=({al},{be}) char {p}: |BPar|={n}, down-sets {c['ds']} ({'all' if exhaustive else 'sample'}); dim>=|Z| {c['ge']}; equal {c['eq']}; control (maximal shapes only) below |Z| in {c['ctrl']}", flush=True)
    for k in tot: tot[k] += c[k]
print("TOTAL", tot); print("FIN-OK")
