# G6 — L1 (Lemma 9.10, case 0 not in C_1, the map theta) and N1 (Proposition 9.2: in(I) contains Y*(D_J), §9 intro),
# over F_2, in the group algebra F_2[(Z/q)^n], vectors as Python int bitsets.
import sys, itertools
sys.path.insert(0, 'checks')
from pflib import matchings
import math

def N_r(N, r):
    h = (r-1)//2; tot = 0
    for a in itertools.product(range(N//2+1), repeat=h):
        zc = N - 2*sum(a)
        if zc < 0: continue
        tot += math.factorial(N) // (math.factorial(zc) * math.prod(math.factorial(x)**2 for x in a))
    return tot

# --- group algebra elements as dicts {exponent tuple mod q: 1} over F_2 ---
def gmul(f, g, q):
    out = {}
    for a in f:
        for b in g:
            k = tuple((x+y) % q for x, y in zip(a, b))
            if k in out: del out[k]
            else: out[k] = 1
    return out
def gadd(f, g):
    out = dict(f)
    for k in g:
        if k in out: del out[k]
        else: out[k] = 1
    return out
def mono(n, idx_exp, q):
    e = [0]*n
    for i, x in idx_exp: e[i] = x % q
    return {tuple(e): 1}
def one(n): return {tuple([0]*n): 1}
def t_minus_1(i, n, q): return gadd(mono(n, [(i, 1)], q), one(n))
def phi(i, l, n, q):     # 1 + u + ... + u^{q-1}, u = t_i t_l
    out = {}
    for j in range(q): out = gadd(out, mono(n, [(i, j), (l, j)], q))
    return out

def enc(e, q):
    v = 0
    for x in e: v = v*q + x
    return v
def to_int(f, q):
    v = 0
    for e in f: v ^= (1 << enc(e, q))
    return v

class Span:
    def __init__(self): self.piv = {}
    def reduce(self, v):
        while v:
            hb = v.bit_length() - 1
            if hb in self.piv: v ^= self.piv[hb]
            else: return v
        return 0
    def add(self, v):
        v = self.reduce(v)
        if v: self.piv[v.bit_length()-1] = v; return True
        return False
    def dim(self): return len(self.piv)
    def contains(self, v): return self.reduce(v) == 0

def ideal_span(gens, n, q):
    S = Span()
    for g in gens:
        for nu in itertools.product(range(q), repeat=n):
            S.add(to_int(gmul(g, {nu: 1}, q), q))
    return S

def gen_g_P(P, n, q, zero_partner=None):
    """g_P = prod over pairs {i<l} of P of (t_l - 1) phi(t_i t_l); if zero_partner given, times (t_{k0} - 1)"""
    g = one(n)
    for (i, l) in P:
        g = gmul(g, gmul(t_minus_1(l, n, q), phi(i, l, n, q), q), q)
    if zero_partner is not None:
        g = gmul(g, t_minus_1(zero_partner, n, q), q)
    return g

print('L1: Lemma 9.10, 0 not in C_1, |C_1| = 2k\'')
for (q, n) in [(2, 2), (2, 4), (2, 6), (4, 2), (4, 4), (4, 6), (8, 2), (8, 4)]:
    gens = [gen_g_P(P, n, q) for P in matchings(list(range(n)))]
    M = ideal_span(gens, n, q)
    # theta: coefficient of t_{i1}^0, i1 = index 0; image in F_2[H'] (n-1 variables)
    Th = Span()
    for g in gens:
        for nu in itertools.product(range(q), repeat=n):
            f = gmul(g, {nu: 1}, q)
            f0 = {e[1:]: 1 for e in f if e[0] == 0}
            Th.add(to_int(f0, q))
    # previous case in n-1 variables: generators (t_{k0}-1) * prod over a perfect matching of the other n-2 indices
    m1 = n - 1; prev_gens = []
    for k0 in range(m1):
        rest = [i for i in range(m1) if i != k0]
        for Q in matchings(rest):
            prev_gens.append(gen_g_P(Q, m1, q, zero_partner=k0))
    Prev = ideal_span(prev_gens, m1, q)
    contained = all(Th.contains(v) for v in Prev.piv.values())
    # control: the ideal generated by (t_{k0} - 1) alone (no phi factors) must NOT be contained (when n >= 4)
    ctrl = None
    if n >= 4:
        C = ideal_span([t_minus_1(0, m1, q)], m1, q)
        ctrl = all(Th.contains(v) for v in C.piv.values())
    # control 2: one matching removed -> dim M drops?
    M2 = ideal_span(gens[1:], n, q) if len(gens) > 1 else None
    target = N_r(n, q-1) if q > 2 else 1
    print(f'  q={q} 2k\'={n}: dim M={M.dim()}  dim theta(M)={Th.dim()}  dim prev={Prev.dim()}  N_(q-1)(2k\')={target}  '
          f'theta(M) contains prev: {contained}  theta injective: {M.dim()==Th.dim()}  '
          f'control[(t-1) alone contained]: {ctrl}  dim M with one P removed: {M2.dim() if M2 else None}', flush=True)

print('\nN1: Proposition 9.2, in(I) contains Y*(D_J) = (L_J)B, in B = F_2[s]/(s^q)')
def s_basis_vec(f, n, q):
    """convert group-algebra element (t-monomials) to s-monomial coordinates, s = t+1 = t-1 over F_2:
    t^a = (1+s)^a = sum_b C(a,b) s^b mod 2"""
    out = {}
    for e in f:
        choices = [[b for b in range(a+1) if (math.comb(a, b) % 2)] for a in e]
        for bs in itertools.product(*choices):
            if bs in out: del out[bs]
            else: out[bs] = 1
    return out
def deg_order_index(n, q):
    mons = sorted(itertools.product(range(q), repeat=n), key=lambda e: (-sum(e), e))
    # bit position: higher bit = LOWER degree (so that pivot = highest bit = lowest-degree monomial)
    return {m: i for i, m in enumerate(mons)}, mons
for (k, q) in [(0, 2), (1, 2), (2, 2), (1, 4), (2, 4), (1, 8)]:
    n = 2*k + 1
    idx, mons = deg_order_index(n, q)
    def vec(sdict):
        v = 0
        for e in sdict: v ^= (1 << idx[e])
        return v
    # psi_J: J matching of {0..2k+1} with j_0 = 0; indices 1..2k+1 -> 0..2k here; factor (t_{k0}-1) and pairs avoiding 0
    psis = []
    for k0 in range(n):
        rest = [i for i in range(n) if i != k0]
        for Q in matchings(rest):
            psis.append(gen_g_P(Q, n, q, zero_partner=k0))
    def ideal_in_s(gs):
        # B = F_2[s]/(s^q) is spanned by the s-monomials, so (g)B = span{ g * s^m }
        S = Span()
        for g in gs:
            gsd = s_basis_vec(g, n, q)
            for m in itertools.product(range(q), repeat=n):
                prod = {}
                for e1 in gsd:
                    e3 = tuple(x+y for x, y in zip(e1, m))
                    if max(e3) < q:
                        if e3 in prod: del prod[e3]
                        else: prod[e3] = 1
                S.add(vec(prod))
        return S
    I = ideal_in_s(psis)
    # in(I): for each basis vector (pivot = lowest-degree monomial), its lowest-degree component
    def lowest_component(v):
        hb = v.bit_length() - 1; d = sum(mons[hb]); w = 0
        x = v
        while x:
            b = x.bit_length() - 1
            if sum(mons[b]) != d: break
            w |= (1 << b); x ^= (1 << b)
        return w
    # need reduced form so that pivots are distinct lowest monomials: Span pivots are distinct highest bits -> OK
    INI = Span()
    for v in I.piv.values(): INI.add(lowest_component(v))
    # (L_J)B: L_J = Y * D_J, D(a,b) = sum_{w=0}^{q-2} a^w b^{q-2-w} in s-variables
    Ls = []
    for k0 in range(n):
        rest = [i for i in range(n) if i != k0]
        for Q in matchings(rest):
            L = {tuple([1]*n): 1}
            for (a, b) in Q:
                Dd = {}
                for w in range(q-1):
                    e = [0]*n; e[a] = w; e[b] = q-2-w; Dd[tuple(e)] = 1
                newL = {}
                for e1 in L:
                    for e2 in Dd:
                        e3 = tuple(x+y for x, y in zip(e1, e2))
                        if max(e3) < q:
                            if e3 in newL: del newL[e3]
                            else: newL[e3] = 1
                L = newL
            Ls.append(L)
    LB = Span()
    for L in Ls:
        for m in itertools.product(range(q), repeat=n):
            prod = {}
            for e1 in L:
                e3 = tuple(x+y for x, y in zip(e1, m))
                if max(e3) < q: prod[e3] = 1
            LB.add(vec(prod))
    cont = all(INI.contains(v) for v in LB.piv.values())
    # control: in(I') for I' = I without one generator must NOT contain (L_J)B (when its dimension is smaller)
    Ip = ideal_in_s(psis[1:]) if len(psis) > 1 else None
    ctrl = None
    if Ip is not None:
        INIp = Span()
        for v in Ip.piv.values(): INIp.add(lowest_component(v))
        ctrl = all(INIp.contains(v) for v in LB.piv.values())
    r = q - 1
    target = N_r(2*k+2, r) if r >= 3 else 1
    print(f'  (k,q)=({k},{q}): dim I={I.dim()} dim in(I)={INI.dim()} dim (L_J)B={LB.dim()} N_r(2k+2)={target}  in(I) contains (L_J)B: {cont}  in(I)=(L_J)B: {cont and INI.dim()==LB.dim()}  control[in(I minus one psi) contains (L_J)B]: {ctrl}', flush=True)
