# k03b_control.py -- Grepy Skies 2. A control that CAN fail for the test "dim >= count" of k03:
# the balanced bipartite ideal generated by a SUB-family of the bijections (one bijection; all but one),
# box q over F_p. If the test is not blind, these dimensions fall below N_bal(a,q).
import sys, itertools
sys.path.insert(0, __file__.rsplit('/', 1)[0])
from eng2 import *
from math import comb

def Nbal(a, q):
    c = 0
    for xi in itertools.product(range(q), repeat=a):
        for eta in itertools.product(range(q), repeat=a):
            if sorted(xi) == sorted(eta): c += 1
    return c

for (q, a, p) in [(2, 2, 2), (2, 3, 2), (2, 4, 2), (4, 2, 2), (4, 3, 2), (8, 2, 2), (3, 2, 3)]:
    n = 2 * a
    def xz(i, l):
        c = {}
        for u in range(q):
            k = [0] * n; k[i] = u; k[a + l] = q - 1 - u
            c[tuple(k)] = comb(q - 1, u) * (-1) ** (q - 1 - u)
        return c
    gens = []
    for s in itertools.permutations(range(a)):
        f = one(n)
        for i in range(a): f = pmul(f, xz(i, s[i]), q)
        gens.append(f)
    full = idim(ideal(gens, n, q, p))
    one_bij = idim(ideal(gens[:1], n, q, p))
    all_but_one = idim(ideal(gens[1:], n, q, p))
    N = Nbal(a, q)
    print("q=%d a=%d p=%d: N_bal=%d | all %d bijections: %d | one bijection: %d (<N: %s) | all but one: %d (<N: %s)"
          % (q, a, p, N, len(gens), full, one_bij, one_bij < N, all_but_one, all_but_one < N))
