# k06_colours.py -- Grepy Skies 2. The colour reduction for an ODD prime p of an EVEN degree m (item B4,
# Lemma B.0), from the LITERAL generators psi_J of [DS], one colouring at a time.
# m = q r', q = p^v, r' even, and r' | p-1 so that mu_{r'} lies in F_p (no field extension needed).
# For every colouring c in mu_{r'}^{2k+1}:  R_c = F_p[s_i]/(s_i^q), t_i = c_i + s_i;
#   dim of the ideal generated by the images of ALL the psi_J in R_c      (my linear algebra, non-graded)
# against
#   |Gamma_c| = #{g in Gamma : mu_{r'}-part of g = c}                    (brute force on the definition of [DS])
# and against the product of block counts N_1 * N_{-1} * prod N_zeta      (the formulas of B4 / Lemma 6.8).
# usage: python3 k06_colours.py k m p [only_all_minus_one]
import sys, itertools, time
sys.path.insert(0, __file__.rsplit('/', 1)[0])
from eng2 import matchings, Nr
from flint import nmod_mat
from fractions import Fraction
from math import factorial, comb

k = int(sys.argv[1]); m = int(sys.argv[2]); p = int(sys.argv[3])
only = len(sys.argv) > 4
n1 = 2 * k + 1
q = 1
while m % (q * p) == 0: q *= p
rp = m // q
assert q > 1 and rp % 2 == 0 and (p - 1) % rp == 0, "need p odd, r' even, r' | p-1"
# primitive r'-th root of unity in F_p
omega = next(w for w in range(2, p) if pow(w, rp, p) == 1 and all(pow(w, d, p) != 1 for d in range(1, rp)))
t0 = time.time()

# ---- Gamma by brute force (additive notation: g_i = zeta_m^{a_i}), tallied by a mod r'
Js = [[pr for pr in J if 0 not in pr] for J in matchings(list(range(2 * k + 2)))]
gam = {}
for a in itertools.product(range(1, m), repeat=n1):
    for J in Js:
        if all((a[x - 1] + a[y - 1]) % m == 0 for (x, y) in J):
            e = tuple(v % rp for v in a)
            gam[e] = gam.get(e, 0) + 1
            break
total = sum(gam.values())

# ---- block counts by formula
def Qcount(q, N):            # N-tuples in mu_q \ 1 closed under inversion (q odd): N! [x^N] I_0(2x)^{(q-1)/2}
    h = (q - 1) // 2
    I0 = [Fraction(1, factorial(i // 2) ** 2) if i % 2 == 0 else Fraction(0) for i in range(N + 1)]
    f = [Fraction(1)] + [Fraction(0)] * N
    for _ in range(h):
        g = [Fraction(0)] * (N + 1)
        for i, x in enumerate(f):
            if x:
                for j, y in enumerate(I0):
                    if i + j <= N and y: g[i + j] += x * y
        f = g
    return int(f[N] * factorial(N))
def Nbal(a, q):              # sum over compositions (a!/prod c_i!)^2 = (a!)^2 [x^a] (sum_j x^j/(j!)^2)^q
    s = [Fraction(1, factorial(j) ** 2) for j in range(a + 1)]
    f = [Fraction(1)] + [Fraction(0)] * a
    for _ in range(q):
        g = [Fraction(0)] * (a + 1)
        for i, x in enumerate(f):
            if x:
                for j, y in enumerate(s):
                    if i + j <= a: g[i + j] += x * y
        f = g
    return int(f[a] * factorial(a) ** 2)
def predicted(e):
    e0 = (-sum(e)) % rp
    col = [e0] + list(e)
    cls = {}
    for i, c in enumerate(col): cls.setdefault(c, []).append(i)
    prod = 1
    c1 = cls.get(0, []); cm = cls.get(rp // 2, [])
    if len(c1) % 2 or len(cm) % 2: return 0
    prod *= Qcount(q, len(c1)) * Nr(q, len(cm))
    for z in range(1, rp // 2):
        A = cls.get(z, []); B = cls.get(rp - z, [])
        if len(A) != len(B): return 0
        has0 = (0 in A) or (0 in B)
        a = len(A)
        prod *= Nbal(a, q) if not has0 else Nbal(a, q)   # phantom: N_ph(a-1,q) = N_bal(a,q), a = size with 0 included
    return prod

# ---- the ideal in R_c
allmon = list(itertools.product(range(q), repeat=n1))
midx = {e: i for i, e in enumerate(allmon)}
def rref(rows):
    rows = [r_ for r_ in rows if r_]
    if not rows: return []
    nc = len(allmon)
    ent = [0] * (len(rows) * nc)
    for a_, row in enumerate(rows):
        b = a_ * nc
        for kk, v in row.items(): ent[b + midx[kk]] = v % p
    Rm, rk = nmod_mat(len(rows), nc, ent, p).rref()
    out = []
    for a_ in range(rk):
        row = {}
        for c in range(nc):
            v = int(Rm[a_, c])
            if v: row[allmon[c]] = v
        out.append(row)
    return out
def close(gens):
    basis = rref(gens)
    while True:
        rows = list(basis)
        for b in basis:
            for i in range(n1):
                nb = {}
                for kk, v in b.items():
                    if kk[i] + 1 < q:
                        k2 = list(kk); k2[i] += 1; nb[tuple(k2)] = v
                if nb: rows.append(nb)
        nb_ = rref(rows)
        if len(nb_) == len(basis): return len(basis)
        basis = nb_

def tpow(c, e):               # (c + s)^e mod s^q, coefficients list
    return [comb(e, j) * pow(c, e - j, p) % p if j <= e else 0 for j in range(q)]
def mul1(a, b):
    c = [0] * q
    for i, x in enumerate(a):
        if x:
            for j, y in enumerate(b):
                if i + j < q and y: c[i + j] = (c[i + j] + x * y) % p
    return c
def generator(J, cvals):
    """image of psi_J = prod (t_k - 1) prod_{pairs without 0} phi(t_j t_k) in R_c, as dict on exponent tuples."""
    poly = {tuple([0] * n1): 1}
    for (j, kk) in J:
        ck = cvals[kk - 1]
        tk1 = tpow(ck, 1); tk1[0] = (tk1[0] - 1) % p          # t_k - 1
        if j == 0:
            fac = {}                                           # one variable
            for b, v in enumerate(tk1):
                if v: fac[(None, b)] = v
        else:
            cj = cvals[j - 1]
            fac = {}
            for e in range(m):
                pj = tpow(cj, e); pk = mul1(tpow(ck, e), tk1)
                for a_, x in enumerate(pj):
                    if x:
                        for b, y in enumerate(pk):
                            if y: fac[(a_, b)] = (fac.get((a_, b), 0) + x * y) % p
        new = {}
        for ex, c0 in poly.items():
            for (a_, b), v in fac.items():
                if not v: continue
                e2 = list(ex)
                if a_ is not None: e2[j - 1] += a_
                e2[kk - 1] += b
                key = tuple(e2)
                new[key] = (new.get(key, 0) + c0 * v) % p
        poly = {kk_: v for kk_, v in new.items() if v}
        if not poly: break
    return poly

Jall = list(matchings(list(range(2 * k + 2))))
print("(k,m,p)=(%d,%d,%d): q=%d r'=%d omega=%d, %d colourings, |Gamma| = %d (brute force), N_{m-1}(2k+2) = %d"
      % (k, m, p, q, rp, omega, rp ** n1, total, Nr(m - 1, 2 * k + 2)))
cols = list(itertools.product(range(rp), repeat=n1))
if only: cols = [tuple([rp // 2] * n1)]
bad = badf = 0; sdim = 0; ncompat = 0; nonzero = 0
for e in cols:
    cvals = [pow(omega, x, p) for x in e]
    gens = [generator(J, cvals) for J in Jall]
    d = close(gens)
    g = gam.get(e, 0); pr = predicted(e)
    sdim += d
    if d: nonzero += 1
    if g: ncompat += 1
    if d != g: bad += 1; print("   MISMATCH colouring", e, "dim", d, "|Gamma_c|", g)
    if pr != g: badf += 1; print("   FORMULA MISMATCH colouring", e, "product of block counts", pr, "|Gamma_c|", g)
em = tuple([rp // 2] * n1)
if em in cols:
    cvals = [pow(omega, x, p) for x in em]
    dm = close([generator(J, cvals) for J in Jall])
    print("   colouring 'all -1' (0 in C_{-1}, |C_{-1}| = %d): dim = %d ; N_q(2k+2) = (O) at (k,q) = %d" % (2 * k + 2, dm, Nr(q, 2 * k + 2)))
    dc = close([generator(J, cvals) for J in Jall[1:]])
    print("   control (can fail): the same colouring with one matching removed: dim = %d (< %d: %s)" % (dc, dm, dc < dm))
print("   colourings tested %d: dim != |Gamma_c| in %d ; product formula != |Gamma_c| in %d ; colourings with Gamma_c non-empty %d, with non-zero ideal %d ; sum of dims = %d  [%.1fs]"
      % (len(cols), bad, badf, ncompat, nonzero, sdim, time.time() - t0), flush=True)
