# k06b_colours_p2.py -- Grepy Skies 2. The colour reduction for the prime 2 of m = 2^v * 3 (item B3),
# from the LITERAL generators psi_J of [DS], one colouring at a time, over F_4 (which contains mu_3).
# F_4 = F_2[w]/(w^2+w+1); an F_4-space of dimension d is an F_2-space of dimension 2d, and the F_4-span of S
# is the F_2-span of S and w*S: so the linear algebra is done over F_2 with two columns per monomial.
# For every colouring c in mu_3^{2k+1}:  R_c = F_4[s_i]/(s_i^q), t_i = c_i + s_i;
#   dim_{F_4} of the ideal generated by the images of ALL psi_J
# against |Gamma_c| (brute force on the definition of [DS]) and against N_{q-1}(|C_1|) * N_bal(|C_zeta|, q).
# usage: python3 k06b_colours_p2.py k m
import sys, itertools, time
sys.path.insert(0, __file__.rsplit('/', 1)[0])
from eng2 import matchings, Nr
from flint import nmod_mat
from fractions import Fraction
from math import factorial, comb

k = int(sys.argv[1]); m = int(sys.argv[2])
n1 = 2 * k + 1
q = 1
while m % (2 * q) == 0: q *= 2
assert m == 3 * q and q >= 2
t0 = time.time()

# F_4: elements 0,1,2(=w),3(=w+1); addition = xor
MUL = [[0, 0, 0, 0], [0, 1, 2, 3], [0, 2, 3, 1], [0, 3, 1, 2]]
def fpow(c, e):
    x = 1
    for _ in range(e % 3 if c else e): x = MUL[x][c]
    return x if (c or e == 0) else 0
W = [1, 2, 3]            # w^0, w^1, w^2
assert MUL[2][2] == 3 and MUL[2][3] == 1

Js = [[pr for pr in J if 0 not in pr] for J in matchings(list(range(2 * k + 2)))]
gam = {}
for a in itertools.product(range(1, m), repeat=n1):
    for J in Js:
        if all((a[x - 1] + a[y - 1]) % m == 0 for (x, y) in J):
            e = tuple(v % 3 for v in a); gam[e] = gam.get(e, 0) + 1; break
total = sum(gam.values())

def Nbal(a, qq):
    s = [Fraction(1, factorial(j) ** 2) for j in range(a + 1)]
    f = [Fraction(1)] + [Fraction(0)] * a
    for _ in range(qq):
        g = [Fraction(0)] * (a + 1)
        for i, x in enumerate(f):
            if x:
                for j, y in enumerate(s):
                    if i + j <= a: g[i + j] += x * y
        f = g
    return int(f[a] * factorial(a) ** 2)
def predicted(e):
    col = [(-sum(e)) % 3] + list(e)
    c1 = col.count(0); A = col.count(1); B = col.count(2)
    if c1 % 2 or A != B: return 0
    return Nr(q - 1, c1) * Nbal(A, q)

allmon = list(itertools.product(range(q), repeat=n1))
midx = {e: i for i, e in enumerate(allmon)}
NC = 2 * len(allmon)
def rref(rows):
    rows = [r_ for r_ in rows if r_]
    if not rows: return []
    ent = [0] * (len(rows) * NC)
    for a_, row in enumerate(rows):
        b = a_ * NC
        for kk, v in row.items():
            if v & 1: ent[b + 2 * midx[kk]] = 1
            if v & 2: ent[b + 2 * midx[kk] + 1] = 1
    Rm, rk = nmod_mat(len(rows), NC, ent, 2).rref()
    out = []
    for a_ in range(rk):
        row = {}
        for c in range(len(allmon)):
            v = int(Rm[a_, 2 * c]) + 2 * int(Rm[a_, 2 * c + 1])
            if v: row[allmon[c]] = v
        out.append(row)
    return out
def close(gens):
    gens = [g for g in gens if g]
    basis = rref(gens + [{kk: MUL[2][v] for kk, v in g.items()} for g in gens])
    while True:
        rows = list(basis)
        for b in basis:
            for i in range(n1):
                nb = {}
                for kk, v in b.items():
                    if kk[i] + 1 < q:
                        k2 = list(kk); k2[i] += 1; nb[tuple(k2)] = v
                if nb: rows.append(nb)
        nb_ = rref(rows)
        if len(nb_) == len(basis):
            assert len(basis) % 2 == 0
            return len(basis) // 2
        basis = nb_

def tpow(c, e):               # (c + s)^e mod s^q over F_4
    return [fpow(c, e - j) if (j <= e and comb(e, j) % 2) else 0 for j in range(q)]
def mul1(a, b):
    c = [0] * q
    for i, x in enumerate(a):
        if x:
            for j, y in enumerate(b):
                if i + j < q and y: c[i + j] ^= MUL[x][y]
    return c
def generator(J, cvals):
    poly = {tuple([0] * n1): 1}
    for (j, kk) in J:
        ck = cvals[kk - 1]
        tk1 = tpow(ck, 1); tk1[0] ^= 1                         # t_k - 1 = t_k + 1
        if j == 0:
            fac = {(None, b): v for b, v in enumerate(tk1) if v}
        else:
            cj = cvals[j - 1]; fac = {}
            for e in range(m):
                pj = tpow(cj, e); pk = mul1(tpow(ck, e), tk1)
                for a_, x in enumerate(pj):
                    if x:
                        for b, y in enumerate(pk):
                            if y: fac[(a_, b)] = fac.get((a_, b), 0) ^ MUL[x][y]
        new = {}
        for ex, c0 in poly.items():
            for (a_, b), v in fac.items():
                if not v: continue
                e2 = list(ex)
                if a_ is not None: e2[j - 1] += a_
                e2[kk - 1] += b
                key = tuple(e2)
                new[key] = new.get(key, 0) ^ MUL[c0][v]
        poly = {kk_: v for kk_, v in new.items() if v}
        if not poly: break
    return poly

Jall = list(matchings(list(range(2 * k + 2))))
print("(k,m,p)=(%d,%d,2): q=%d r'=3 over F_4, %d colourings, |Gamma| = %d (brute force), N_{m-1}(2k+2) = %d"
      % (k, m, q, 3 ** n1, total, Nr(m - 1, 2 * k + 2)))
bad = badf = 0; sdim = 0; ncompat = 0; nonzero = 0
c1sizes = {}
only_sorted = len(sys.argv) > 3      # test one colouring per orbit of the permutations of the indices 1..2k+1
ntested = 0
for e in itertools.product(range(3), repeat=n1):
    if only_sorted and list(e) != sorted(e): continue
    ntested += 1
    cvals = [W[x] for x in e]
    d = close([generator(J, cvals) for J in Jall])
    g = gam.get(e, 0); pr = predicted(e)
    sdim += d
    if d: nonzero += 1
    if g: ncompat += 1
    if d != g: bad += 1; print("   MISMATCH colouring", e, "dim", d, "|Gamma_c|", g)
    if pr != g: badf += 1; print("   FORMULA MISMATCH colouring", e, "product", pr, "|Gamma_c|", g)
    col = [(-sum(e)) % 3] + list(e)
    if g:
        key = (col.count(0), col[0] == 0)
        c1sizes[key] = c1sizes.get(key, 0) + 1
e1 = tuple([0] * n1)
d1 = close([generator(J, [1] * n1) for J in Jall])
print("   colouring 'all 1' (the block is the conjecture at (k, 2^v) = (%d, %d) itself): dim = %d ; N_{q-1}(2k+2) = %d"
      % (k, q, d1, Nr(q - 1, 2 * k + 2)))
dc = close([generator(J, [1] * n1) for J in Jall[1:]])
print("   control (can fail): the same colouring with one matching removed: dim = %d (< %d: %s)" % (dc, d1, dc < d1))
print("   compatible colourings by (|C_1|, 0 in C_1):", sorted(c1sizes.items()))
print("   colourings tested %d: dim != |Gamma_c| in %d ; product formula != |Gamma_c| in %d ; colourings with Gamma_c non-empty %d, with non-zero ideal %d ; sum of dims = %d  [%.1fs]"
      % (ntested, bad, badf, ncompat, nonzero, sdim, time.time() - t0), flush=True)
if only_sorted: print("   (only the colourings with non-decreasing exponents were tested: one per orbit of S_{2k+1}; the sum of dims is over these only)")
