# k07_constructions.py -- Grepy Skies 2. Proposition 6.1 of PROOF_ODD_BOX.md, case by case, AS WRITTEN:
# for every interlaced pair Lambda, every tail shape sigma with Phi = F_Lambda(sigma) >= 1 and every pattern of sigma
# on the indices 2..m, build the element f of the proof and check
#   (i)   every pattern the proof uses is a pattern of a shape IN Lambda (sizes checked) and f is in V_Lambda
#         (ideal membership over F_p);
#   (ii)  deg_{y_1} f <= r - Phi                                     (over Z, exact);
#   (iii) [y_1^{r-Phi}] f = +G or -G                                 (over Z, exact);
#   for the case (Z, eps=1): the same for every f_{S,Q}, with top coefficient +-Delta(S) D_Q D_P R, and then
#         G in the ideal generated by these top coefficients          (this is where Lemma 5.1 is used).
# The sign theta of case (M, eps=1) is computed from (F4): it is the sign for which
#   Pf_{E+}(M u 1) - theta * Pf(M; y^{E+}, B(y_1,.)) has y_1-degree <= max(E+).
# usage: python3 k07_constructions.py r m p
import sys, itertools, time
sys.path.insert(0, __file__.rsplit('/', 1)[0])
from eng2 import *

r = int(sys.argv[1]); m = int(sys.argv[2]); p = int(sys.argv[3])
CONTROL = len(sys.argv) > 4 and sys.argv[4] == 'control'   # deliberately wrong border sets in two cases
if CONTROL: print("CONTROL RUN: wrong border sets (E_l instead of E_{l+1} in (M,eps=1); E_l instead of E_{l-1} in (R,eps=1,mu_rho=1))")
h = (r - 1) // 2; n = m
t0 = time.time()

def patterns_struct(shape, I):
    """all patterns of `shape` on the index list I, as dicts (P, blocks (by column, 0-based), M or None)."""
    lam, eps = shape
    mm = len(I); l = len(lam); cols = conj(lam)
    if eps == 0:
        pnum = (mm - sum(lam)) // 2
        for P, rest in pair_sets(I, pnum):
            for blocks in all_block_splits(rest, cols):
                yield dict(P=P, blocks=list(blocks), M=None)
    else:
        tot = (mm - 1 - sum(lam)) // 2
        for t in range(0, tot + 1):
            for Mb in itertools.combinations(I, l + 1 + 2 * t):
                rest0 = [x for x in I if x not in Mb]
                for P, rest in pair_sets(rest0, tot - t):
                    for blocks in all_block_splits(rest, cols[1:]):
                        yield dict(P=P, blocks=list(blocks), M=tuple(Mb))

def all_block_splits(items, sizes):
    items = list(items)
    if not sizes:
        if not items: yield ()
        return
    for blk in itertools.combinations(items, sizes[0]):
        rest = [x for x in items if x not in blk]
        for more in all_block_splits(rest, sizes[1:]):
            yield (blk,) + more

def DPof(P):
    f = one(n)
    for (a, b) in P: f = pmul(f, Dpoly(n, a, b, r), r)
    return f
def Rof(blocks):
    f = one(n)
    for blk in blocks:
        f = pmul(f, vdm(n, blk, r), r)
        if not f: break
    return f
def product(pat, lam, eps):
    f = pmul(DPof(pat['P']), Rof(pat['blocks']), r)
    if eps == 1 and f:
        f = pmul(f, bordered_pf(n, pat['M'], E_l(len(lam), r), r), r)
    return f
def valid(pat, shape, level):
    """is pat a pattern of `shape` on `level` indices (sizes only)?"""
    lam, eps = shape
    cols = conj(lam); l = len(lam)
    used = [x for pr in pat['P'] for x in pr] + [x for b in pat['blocks'] for x in b] + (list(pat['M']) if pat['M'] else [])
    if sorted(used) != list(range(level)): return False
    if eps == 0:
        return pat['M'] is None and [len(b) for b in pat['blocks']] == cols and 2 * len(pat['P']) == level - sum(lam)
    if pat['M'] is None: return False
    t2 = len(pat['M']) - l - 1
    return t2 >= 0 and t2 % 2 == 0 and [len(b) for b in pat['blocks']] == cols[1:] and len(pat['P']) + t2 // 2 == (level - 1 - sum(lam)) // 2

def y1deg(f): return max((k[0] for k in f), default=-1)
def y1coef(f, j): return {(0,) + k[1:]: v for k, v in f.items() if k[0] == j}
def pm_equal(a, b): return a == b or a == pscal(b, -1)

tailI = list(range(1, n))
stats = {}
def rec(case, ok_valid, ok_deg, ok_top, f_for_membership):
    s = stats.setdefault(case, dict(n=0, bad_valid=0, bad_deg=0, bad_top=0, bad_mem=0, zeroG=0))
    s['n'] += 1
    if not ok_valid: s['bad_valid'] += 1
    if not ok_deg: s['bad_deg'] += 1
    if not ok_top: s['bad_top'] += 1
    return s

pairs = [L for L in interlaced_pairs(m, h) if L]
theta_seen = set()
for L in pairs:
    IL = ideal(V_gens(L, list(range(n)), n, r), n, r, p)
    tomember = []      # (case, f)
    for sigma in Sh(m - 1, h):
        mu, eps = sigma; l = len(mu)
        opts = options(mu, eps, h)
        flags = [o in L for o in opts]
        Phi = sum(flags)
        if Phi == 0: continue
        last = Phi - 1
        assert flags == [True] * Phi + [False] * (r - Phi)
        if last < l: kind = 'R'
        elif last == l: kind = 'Z'
        elif last <= l + 2 * (h - l): kind = 'M'
        else: kind = 'A'
        for pat in patterns_struct(sigma, tailI):
            G = product(pat, mu, eps)
            if not G:
                stats.setdefault('zero G (skipped)', dict(n=0, bad_valid=0, bad_deg=0, bad_top=0, bad_mem=0))['n'] += 1
                continue
            P = pat['P']; blocks = pat['blocks']; M = pat['M']
            DPR = pmul(DPof(P), Rof(blocks), r)
            if kind == 'A':
                j0 = (r - 1) - last + 1                       # additions are listed for rows l, l-1, ..., 1
                j0 = l - (last - (l + 1 + 2 * (h - l)))      # row (1-based) of the last option in Lambda
                cstar = mu[j0 - 1] + 1                         # column (1-based), >= 2
                bi = cstar - 1 if eps == 0 else cstar - 2      # index in blocks
                nb = [tuple(b) for b in blocks]
                if bi < len(nb): nb[bi] = tuple(sorted(nb[bi] + (0,)))
                else: nb.append((0,))
                newpat = dict(P=P, blocks=nb, M=M)
                newshape = (plus(mu, j0 - 1), eps)
                okv = newshape in L and valid(newpat, newshape, m) and (bi == len(blocks) or len(blocks[bi]) == j0 - 1)
                f = product(newpat, newshape[0], eps)
                case = 'A eps=%d' % eps
            elif kind == 'M' and eps == 0:
                nb = [tuple(b) for b in blocks]
                if nb: nb[0] = tuple(sorted(nb[0] + (0,)))
                else: nb = [(0,)]
                newpat = dict(P=P, blocks=nb, M=None); newshape = (join1(mu), 0)
                okv = newshape in L and valid(newpat, newshape, m)
                f = product(newpat, newshape[0], 0)
                case = 'M eps=0'
            elif kind == 'M' and eps == 1:
                Eplus = E_l(l + 1, r) if not CONTROL else E_l(l, r)
                M1 = (0,) + tuple(M)
                A = bordered_pf(n, M1, Eplus, r)
                Bt = bordered_pf(n, M, Eplus, r, extra_cols=[lambda i: Bpoly(n, 0, i, r)])
                Dt = bordered_pf(n, M, Eplus, r, extra_cols=[lambda i: Dpoly(n, 0, i, r)])
                cand = [th for th in (1, -1) if y1deg(padd(A, Bt, -th)) <= (max(Eplus) if Eplus else -1) or not Bt]
                if len(cand) == 2 and Bt: theta_seen.add('ambiguous')
                th = cand[0] if cand else None
                okv = ((join1(mu), 1) in L) and ((mu, 0) in L) and th is not None
                if th is None: th = 1; theta_seen.add('NO THETA SATISFIES (F4)')
                # the pattern with marked block M u {1}
                okv = okv and valid(dict(P=P, blocks=blocks, M=M1), (join1(mu), 1), m)
                f = pmul(padd(pmul(mono(n, 0, 1, r), A, r), Dt, th), DPR, r)
                case = 'M eps=1 (t=%s)' % ('0' if len(M) == l + 1 else '>=1')
            elif kind == 'Z' and eps == 0:
                if l == 0:
                    newpat = dict(P=P, blocks=[], M=(0,)); newshape = ((), 1)
                    okv = newshape in L and valid(newpat, newshape, m)
                    f = pmul(mono(n, 0, r - 1, r), G, r)
                else:
                    M1 = (0,) + tuple(blocks[0])
                    newpat = dict(P=P, blocks=blocks[1:], M=M1); newshape = (mu, 1)
                    okv = newshape in L and valid(newpat, newshape, m)
                    f = pmul(bordered_pf(n, M1, E_l(l, r), r), pmul(DPof(P), Rof(blocks[1:]), r), r)
                case = 'Z eps=0'
            elif kind == 'Z' and eps == 1:
                case = 'Z eps=1 (t=%s)' % ('0' if len(M) == l + 1 else '>=1')
                okv = (mu, 0) in L
                okd = okt = True
                tops = []
                for Sset in itertools.combinations(M, l + 1):
                    restM = [x for x in M if x not in Sset]
                    for Q in matchings(restM):
                        DQ = DPof(Q)
                        base = pmul(DQ, DPR, r)
                        fSQ = {}
                        for c, b in enumerate(Sset, start=1):
                            sgn = (-1) ** (l + 1 + c)
                            Sb = tuple(x for x in Sset if x != b)
                            term = pmul(pmul(vdm(n, Sb, r), Dpoly(n, 0, b, r), r), base, r)
                            fSQ = padd(fSQ, term, sgn)
                            okv = okv and valid(dict(P=tuple(P) + tuple(Q) + ((0, b),), blocks=[x for x in ([Sb] + [tuple(x) for x in blocks]) if x], M=None), (mu, 0), m)
                        top = pmul(vdm(n, Sset, r), base, r)
                        if y1deg(fSQ) > r - 1 - l: okd = False
                        if not pm_equal(y1coef(fSQ, r - 1 - l), top): okt = False
                        tomember.append((case, fSQ))
                        tops.append(top)
                # Lemma 5.1 as used: G in the ideal generated by the tops (computed in the ring, over F_p)
                It = ideal(tops, n, r, p, maxdeg=deg(G))
                if not member(G, It, n, r, p): okt = False
                s = rec(case, okv, okd, okt, None)
                continue
            elif kind == 'R':
                rho = last + 1
                if eps == 0 or mu[rho - 1] >= 2:
                    c0 = mu[rho - 1]
                    bi = c0 - 1 if eps == 0 else c0 - 2
                    Sset = tuple(sorted(blocks[bi]))
                    others = [b for i, b in enumerate(blocks) if i != bi]
                    Gp = pmul(DPof(P), Rof(others), r)
                    if eps == 1: Gp = pmul(Gp, bordered_pf(n, M, E_l(l, r), r), r)
                    okv = len(Sset) == rho and (minus(mu, rho - 1), eps) in L
                    f = {}
                    for c, b in enumerate(Sset, start=1):
                        sgn = (-1) ** (rho + c)
                        Sb = tuple(x for x in Sset if x != b)
                        f = padd(f, pmul(pmul(vdm(n, Sb, r), Dpoly(n, 0, b, r), r), Gp, r), sgn)
                        nb = [tuple(x) for x in blocks]; nb[bi] = Sb
                        nb = [x for x in nb if x]
                        okv = okv and valid(dict(P=tuple(P) + ((0, b),), blocks=nb, M=M), (minus(mu, rho - 1), eps), m)
                    case = 'R ordinary eps=%d' % eps
                else:
                    M1 = (0,) + tuple(M)
                    newshape = (minus(mu, l - 1), 1)
                    okv = rho == l and newshape in L and valid(dict(P=P, blocks=blocks, M=M1), newshape, m)
                    f = pmul(bordered_pf(n, M1, E_l(l - 1, r) if not CONTROL else E_l(l, r), r), DPR, r)
                    case = 'R eps=1 mu_rho=1 (l=%s)' % ('1' if l == 1 else '>=2')
            okd = y1deg(f) <= r - Phi
            okt = pm_equal(y1coef(f, r - Phi), G)
            rec(case, okv, okd, okt, f)
            tomember.append((case, f))
    # membership in V_Lambda, in batch per degree, then individually if a batch fails
    bydeg = {}
    for case, f in tomember:
        f2 = {k: v % p for k, v in f.items() if v % p}
        if f2: bydeg.setdefault(deg(f2), []).append((case, f2))
    for d, lst in bydeg.items():
        basis = IL[d][0]
        b2, _ = rref_rows(list(basis) + [f for _, f in lst], n, r, d, p)
        if len(b2) != len(basis):
            for case, f in lst:
                if not member(f, IL, n, r, p): stats[case]['bad_mem'] += 1

print("CELL r=%d m=%d p=%d: %d non-empty interlaced pairs  [%.1fs]" % (r, m, p, len(pairs), time.time() - t0))
tot = 0
for case in sorted(stats):
    s = stats[case]; tot += s['n']
    if case.startswith('zero'):
        print("   %-28s %6d" % (case, s['n'])); continue
    print("   %-28s cases %6d | pattern not valid / shape not in Lambda: %d | deg_{y1} f > r-Phi: %d | top coeff != +-G: %d | f not in V_Lambda: %d"
          % (case, s['n'], s['bad_valid'], s['bad_deg'], s['bad_top'], s['bad_mem']))
print("   theta of (M,eps=1):", sorted(theta_seen) or "determined uniquely by (F4) whenever the B-term is non-zero")
