module

public import RequestProject.EvenBlocks.Setting
public import RequestProject.EvenBlocks.Blocks

/-!
# Part B of `q_even_blocks.md`: Lemma 9.5, the tensor decomposition, (B2)–(B4)

* (B2) `EvenBlocks.map_idealI_eq_span2` (the generators of `π_c(I)`, read in `B({1, …, d})`) and
  `EvenBlocks.map_idealI_eq_bot` (the case with no compatible matching, `ColDecomp.prop65_i`);
* (B3) `EvenBlocks.lemma95`: Lemma 9.5, with the blocks indexed by `SInv S ⊕ R`;
* (B4) `EvenBlocks.prod_finrank_IcS_of_SInv_eq`, `EvenBlocks.prop65_iii_of_SInv_eq`: consistency
  with `ColDecomp.prop65_iii` when `SInv S = {1}`.

No hypothesis on the parity of `p`, `q` or `r` is made.
-/

@[expose] public section

open MvPolynomial

namespace EvenBlocks

open ColSplit ColSurv ColComp ColTensor ColDecomp

open scoped Classical

variable {F : Type*} [Field F] (S : ColSetting F) {k : ℕ}

/-- **Part B, (B2)** of `q_even_blocks.md` (model `ColDecomp.map_idealI_eq_span`): for
`IsReps2 S R`, `π_c(I)`, read in `B({1, …, d})` through `rcEquiv`, is the ideal generated by the
products `Π_{ζ∈SInv S} ι(g_{P_ζ}) · Π_{ζ∈R} ι(g_{σ_ζ})` over all `((P_ζ), (σ_ζ))`. This holds
whether or not a compatible matching exists (more general than the hypothesis of (B2); if none
exists both sides are `0`). -/
theorem map_idealI_eq_span2 (c : Fin (2 * k + 1) → S.μ) {R : Finset F} (hR : IsReps2 S R) :
    ((idealI S k).map (S.piC c)).map (rcEquiv (boxS S c)) =
      Ideal.span {x | ∃ (P : (ζ : SInv S) → PerfMatch (cls (cExt c) (ζ : F)))
          (σ : (ζ : R) → cls (cExt c) ζ ≃ cls (cExt c) (ζ : F)⁻¹),
        x = (∏ ζ : SInv S, (boxS S c).iota (WS S c ζ) Finset.univ (Finset.subset_univ _)
            (gPS S c ζ (P ζ))) *
          ∏ ζ : R, (boxS S c).iota (Wz S c ζ) Finset.univ (Finset.subset_univ _)
            (gσ S c ζ (σ ζ))} := by
  rw [idealI, S.lemma61_iii c, Ideal.map_span]
  apply le_antisymm
  · rw [Ideal.span_le]
    rintro _ ⟨_, ⟨_, ⟨J, rfl⟩, rfl⟩, rfl⟩
    by_cases hJ : Compatible (cExt c) J
    · obtain ⟨w, hw⟩ := piC_psi_eq_unit_mul2 S c hR ⟨J, hJ⟩
      rw [SetLike.mem_coe]
      refine (congrArg (· ∈ Ideal.span _) hw).mpr ?_
      exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨_, _, rfl⟩)
    · rw [piC_psi_eq_zero S c J hJ, map_zero]
      exact zero_mem _
  · have hu : ∀ y ∈ {x | ∃ (P : (ζ : SInv S) → PerfMatch (cls (cExt c) (ζ : F)))
          (σ : (ζ : R) → cls (cExt c) ζ ≃ cls (cExt c) (ζ : F)⁻¹),
        x = (∏ ζ : SInv S, (boxS S c).iota (WS S c ζ) Finset.univ (Finset.subset_univ _)
            (gPS S c ζ (P ζ))) *
          ∏ ζ : R, (boxS S c).iota (Wz S c ζ) Finset.univ (Finset.subset_univ _)
            (gσ S c ζ (σ ζ))}, ∃ w : ((boxS S c).Box Finset.univ)ˣ,
        (w : (boxS S c).Box Finset.univ) * y ∈
          rcEquiv (boxS S c) '' (S.piC c '' Set.range (psi S k)) := by
      rintro _ ⟨P, σ, rfl⟩
      obtain ⟨w, hw⟩ := piC_psi_eq_unit_mul2 S c hR (assemble2 hR (cExt_mem c) (P, σ))
      rw [restrict2_assemble2 hR (cExt_mem c) (P, σ)] at hw
      exact ⟨w, _, ⟨_, ⟨_, rfl⟩, rfl⟩, hw⟩
    rw [← lemma64_v _ (fun y => if h : _ then Classical.choose (hu y h) else 1), Ideal.span_le]
    rintro _ ⟨y, hy, rfl⟩
    simp only [dif_pos hy]
    exact Ideal.subset_span (Classical.choose_spec (hu y hy))

/-- **Part B, (B2)** of `q_even_blocks.md`, second claim: if no matching is compatible with
`cExt c`, the image `((idealI S k).map (S.piC c)).map (rcEquiv (boxS S c))` is `⊥`
(from `ColDecomp.prop65_i`, which needs no representatives). -/
theorem map_idealI_eq_bot (c : Fin (2 * k + 1) → S.μ)
    (h : ¬ ∃ J : BallotBound.Matching k, Compatible (cExt c) J) :
    ((idealI S k).map (S.piC c)).map (rcEquiv (boxS S c)) = ⊥ := by
  rw [prop65_i S c h, Ideal.map_bot]

/-- **Part B, (B3)** of `q_even_blocks.md` (proof): the blocks of variables indexed by
`SInv S ⊕ R`: `inl ζ ↦ W_ζ^S = WS S c ζ` and `inr ζ ↦ W_ζ = Wz S c ζ` (in place of the
`Option R` of `ColDecomp.blocks`). -/
noncomputable def blocks2 (c : Fin (2 * k + 1) → S.μ) (R : Finset F) :
    SInv S ⊕ R → Finset (Fin (2 * k + 1))
  | Sum.inl ζ => WS S c ζ
  | Sum.inr ζ => Wz S c ζ

/-- **Part B, (B3)** of `q_even_blocks.md` (proof): by (A5) the blocks are pairwise disjoint. -/
theorem blocks2_pairwise_disjoint (c : Fin (2 * k + 1) → S.μ) {R : Finset F}
    (hR : IsReps2 S R) :
    Pairwise fun i j => Disjoint (blocks2 S c R i) (blocks2 S c R j) := by
  obtain ⟨hA, hB, -, hD, -⟩ := partitionA5 hR (cExt_mem c)
  rintro (ζ | ζ) (η | η) hne
  · exact disjoint_varSet (hA ζ ζ.2 η η.2 fun e => hne (congrArg Sum.inl (Subtype.ext e)))
  · exact disjoint_varSet (hB ζ ζ.2 η η.2)
  · exact disjoint_varSet (hB η η.2 ζ ζ.2).symm
  · exact disjoint_varSet (hD ζ ζ.2 η η.2 fun e => hne (congrArg Sum.inr (Subtype.ext e)))

/-- **Part B, (B3)** of `q_even_blocks.md` (proof): by (A5) the union of the blocks is
`{1, …, d}`. -/
theorem univ_eq_biUnion_blocks2 (c : Fin (2 * k + 1) → S.μ) {R : Finset F} (hR : IsReps2 S R) :
    (Finset.univ : Finset (Fin (2 * k + 1))) = Finset.univ.biUnion (blocks2 S c R) := by
  have hpart := (partitionA5 hR (cExt_mem c)).2.2.2.2
  symm
  rw [Finset.eq_univ_iff_forall]
  intro j
  have hj := hpart ▸ Finset.mem_univ j.succ
  simp only [Finset.mem_union, Finset.mem_biUnion] at hj
  simp only [Finset.mem_biUnion, Finset.mem_univ, true_and]
  rcases hj with ⟨ζ, hζ, hj⟩ | ⟨ζ, hζ, hj⟩
  · exact ⟨Sum.inl ⟨ζ, hζ⟩, by simpa [blocks2, WS, varSet] using hj⟩
  · refine ⟨Sum.inr ⟨ζ, hζ⟩, ?_⟩
    simp only [blocks2, Wz, varSet, Finset.mem_filter, Finset.mem_univ, true_and]
    exact Finset.mem_union.2 hj

/-- **Part B, (B3)** of `q_even_blocks.md` (proof): the generating sets of the block ideals,
indexed by `SInv S ⊕ R`: `{g_P}` for `inl ζ` and `{g_σ}` for `inr ζ`. -/
noncomputable def blockGenSets2 (c : Fin (2 * k + 1) → S.μ) (R : Finset F) :
    (j : SInv S ⊕ R) → Set ((boxS S c).Box (blocks2 S c R j))
  | Sum.inl ζ => Set.range (gPS S c ζ)
  | Sum.inr ζ => Set.range (gσ S c ζ)

/-- **Part B, (B3) Lemma 9.5** of `q_even_blocks.md`: for `IsReps2 S R` (no parity hypothesis),
`dim_F π_c(I) = Π_{ζ∈SInv S} dim_F I_{c,ζ}^S · Π_{ζ∈R} dim_F I_{c,ζ}` when some matching is
compatible with `cExt c`, and `dim_F π_c(I) = 0` otherwise (model `ColDecomp.prop65_iii`, with
the blocks indexed by `SInv S ⊕ R`, and `ColTensor.BoxSetting.lemma64_iv`). -/
theorem lemma95 (c : Fin (2 * k + 1) → S.μ) {R : Finset F} (hR : IsReps2 S R) :
    ((∃ J : BallotBound.Matching k, Compatible (cExt c) J) →
        Module.finrank F ((idealI S k).map (S.piC c)) =
          (∏ ζ ∈ SInv S, Module.finrank F (IcS S c ζ)) *
            ∏ ζ ∈ R, Module.finrank F (Icz S c ζ)) ∧
      ((¬ ∃ J : BallotBound.Matching k, Compatible (cExt c) J) →
        Module.finrank F ((idealI S k).map (S.piC c)) = 0) := by
  refine ⟨fun _ => ?_, fun h => by
    rw [prop65_i S c h]
    exact Module.finrank_zero_of_subsingleton⟩
  refine (finrank_map_algEquiv (rcEquiv (boxS S c)) ((idealI S k).map (S.piC c))).symm.trans ?_
  rw [map_idealI_eq_span2 S c hR]
  have key := (boxS S c).lemma64_iv (blocks2 S c R) (blockGenSets2 S c R)
    (blocks2_pairwise_disjoint S c hR) Finset.univ (univ_eq_biUnion_blocks2 S c hR)
  rw [Fintype.prod_sum_type] at key
  change _ = (∏ ζ : SInv S, Module.finrank F (IcS S c ζ)) *
    ∏ ζ : R, Module.finrank F (Icz S c ζ) at key
  rw [← Finset.prod_coe_sort R, ← Finset.prod_coe_sort (SInv S), ← key]
  have hset : {x | ∃ (P : (ζ : SInv S) → PerfMatch (cls (cExt c) (ζ : F)))
          (σ : (ζ : R) → cls (cExt c) ζ ≃ cls (cExt c) (ζ : F)⁻¹),
        x = (∏ ζ : SInv S, (boxS S c).iota (WS S c ζ) Finset.univ (Finset.subset_univ _)
            (gPS S c ζ (P ζ))) *
          ∏ ζ : R, (boxS S c).iota (Wz S c ζ) Finset.univ (Finset.subset_univ _)
            (gσ S c ζ (σ ζ))} =
      {x | ∃ e : (j : SInv S ⊕ R) → (boxS S c).Box (blocks2 S c R j),
        (∀ j, e j ∈ blockGenSets2 S c R j) ∧
          x = ∏ j, (boxS S c).iota (blocks2 S c R j) Finset.univ
            (Finset.subset_univ _) (e j)} := by
    ext x
    constructor
    · rintro ⟨P, σ, rfl⟩
      refine ⟨fun j => match j with
        | Sum.inl ζ => gPS S c ζ (P ζ)
        | Sum.inr ζ => gσ S c ζ (σ ζ), ?_, ?_⟩
      · rintro (ζ | ζ)
        · exact ⟨P ζ, rfl⟩
        · exact ⟨σ ζ, rfl⟩
      · rw [Fintype.prod_sum_type]
        rfl
    · rintro ⟨e, he, rfl⟩
      choose P hP using fun ζ : SInv S => he (Sum.inl ζ)
      choose σ hσ using fun ζ : R => he (Sum.inr ζ)
      refine ⟨P, σ, ?_⟩
      rw [Fintype.prod_sum_type]
      congr 1
      · refine Finset.prod_congr rfl fun ζ _ => ?_
        change (boxS S c).iota (WS S c ζ) Finset.univ _ (e (Sum.inl ζ)) = _
        rw [← hP ζ]
      · refine Finset.prod_congr rfl fun ζ _ => ?_
        change (boxS S c).iota (Wz S c ζ) Finset.univ _ (e (Sum.inr ζ)) = _
        rw [← hσ ζ]
  rw [hset]

/-- **Part B, (B4)** of `q_even_blocks.md`: if `SInv S = {1}`, the product over `SInv S` in (B3)
is `dim_F I_{c,1}` (as `Ic1 S c = IcS S c 1`). -/
theorem prod_finrank_IcS_of_SInv_eq (h : SInv S = {1}) (c : Fin (2 * k + 1) → S.μ) :
    ∏ ζ ∈ SInv S, Module.finrank F (IcS S c ζ) = Module.finrank F (Ic1 S c) := by
  rw [h, Finset.prod_singleton]
  rfl

/-- **Part B, (B4)** of `q_even_blocks.md`: consistency — if `SInv S = {1}` (e.g. `r` odd or
`p = 2`, (A2)) and `IsReps S R`, then (B3) is exactly `ColDecomp.prop65_iii`; here this statement
is derived from `lemma95`, (A4) and the first part of (B4), without using `prop65_iii`. -/
theorem prop65_iii_of_SInv_eq (h : SInv S = {1}) (c : Fin (2 * k + 1) → S.μ) {R : Finset F}
    (hR : IsReps S R) :
    ((∃ J : BallotBound.Matching k, Compatible (cExt c) J) →
        Module.finrank F ((idealI S k).map (S.piC c)) =
          Module.finrank F (Ic1 S c) * ∏ ζ ∈ R, Module.finrank F (Icz S c ζ)) ∧
      ((¬ ∃ J : BallotBound.Matching k, Compatible (cExt c) J) →
        Module.finrank F ((idealI S k).map (S.piC c)) = 0) := by
  have h95 := lemma95 S c ((isReps2_iff_isReps h R).2 hR)
  rw [prod_finrank_IcS_of_SInv_eq S h c] at h95
  exact h95

end EvenBlocks

end
