module

public import RequestProject.FreeZ.Main
public import RequestProject.ColOne.Empty

/-!
# Integral generators for (D2) of `q_oddbox_equality.md`

(D2) of `q_oddbox_equality.md` speaks of the subgroup generated by the `D_J·y^α` (resp. the
`D_P·y^α`) in `ℤ[y]/(y_i^r)`. This file shows that the ideals `FreeZ.VZ … {(1)}` and
`FreeZ.VZ … {∅}` of `q_free_Z.md` are exactly the ideals of `C_{m,ℤ}` generated by the integer
polynomials `D_J` and `D_P`, so that (D2) holds in the literal form of the file.
-/

@[expose] public section

open MvPolynomial

namespace OddEquality

open EveryField FreeZ

set_option synthInstance.maxHeartbeats 200000

variable {q : ℕ}

/-- **(D2)** of `q_oddbox_equality.md`: the integer polynomial
`D_J = Π_{{a<b} ∈ J, a ≠ 0} D(y_a, y_b) ∈ ℤ[y_1, …, y_{2k+1}]` (as `TheoremB.DJ`, over `ℤ`). -/
noncomputable def DJZ (q : ℕ) {k : ℕ} (J : BallotBound.Matching k) :
    MvPolynomial (Fin (2 * k + 1)) ℤ :=
  ∏ a ∈ Finset.univ.filter (fun a => a ≠ 0 ∧ J.1 a ≠ 0 ∧ a < J.1 a),
    DPR ℤ q (TheoremB.idx a) (TheoremB.idx (J.1 a))

/-- **(D2)** of `q_oddbox_equality.md`: the ideal of `C_{2k+1,ℤ}` generated by the integer `D_J`. -/
noncomputable def DIdealZ (q k : ℕ) : Ideal (CZ q (2 * k + 1)) :=
  Ideal.span (Set.range fun J : BallotBound.Matching k => Ideal.Quotient.mk _ (DJZ q J))

/-- **(D2)** of `q_oddbox_equality.md`: the integer polynomial `D_P = Π_{{a<b} ∈ P} D(y_a, y_b)`
(as `ColOne.DPn`, over `ℤ`). -/
noncomputable def DPnZ (q : ℕ) {n : ℕ} (P : ColComp.PerfMatch (Fin n)) : MvPolynomial (Fin n) ℤ :=
  ∏ a ∈ Finset.univ.filter (fun a => a < P.1 a), DPR ℤ q a (P.1 a)

/-- **(D2)** of `q_oddbox_equality.md`: the ideal `ℳ_ℤ` of `C_{n,ℤ}` generated by the integer
`D_P`. -/
noncomputable def MidealZ (q n : ℕ) : Ideal (CZ q n) :=
  Ideal.span (Set.range fun P : ColComp.PerfMatch (Fin n) => Ideal.Quotient.mk _ (DPnZ q P))

/-- **(D2)** of `q_oddbox_equality.md` (proof): the ring map `C_{m,ℤ} → C_m(ℚ)`. -/
noncomputable def toRat (q m : ℕ) : CZ q m →+* Peel.C ℚ q m :=
  Ideal.Quotient.lift (powIdealZ q m)
    ((Ideal.Quotient.mk (Peel.powIdeal ℚ q m)).comp (MvPolynomial.map (Int.castRingHom ℚ)))
    (fun _ hp => Ideal.Quotient.eq_zero_iff_mem.2 (map_mem_powIdeal ℚ hp))

/-- **(D2)** of `q_oddbox_equality.md` (proof): `C_{m,ℤ} → C_m(ℚ)` is injective (both have the box
monomials as a basis). -/
theorem toRat_injective (hq : 2 ≤ q) (m : ℕ) : Function.Injective (toRat q m) := by
  rw [injective_iff_map_eq_zero]
  intro x hx
  obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
  change Ideal.Quotient.mk _ (MvPolynomial.map (Int.castRingHom ℚ) p) = 0 at hx
  rw [mk_eq_boxToC] at hx
  have h0 := (boxToC_bijective (F := ℚ) hq m).1 (hx.trans (map_zero _).symm)
  rw [mk_eq_boxToCZ]
  have : (fun b : Box q m => p.coeff (boxExp b)) = 0 := by
    funext b
    have := congrFun h0 b
    simpa [coeff_map] using this
  rw [this, map_zero]

/-- **(D2)** of `q_oddbox_equality.md` (proof): `D(y_a, y_b)` over `ℤ` reads over `ℚ` as
`Tight.D`. -/
theorem toRat_DPR {m : ℕ} (a b : Fin m) :
    toRat q m (Ideal.Quotient.mk _ (DPR ℤ q a b)) = Tight.D ℚ q a b := by
  change Ideal.Quotient.mk _ (MvPolynomial.map (Int.castRingHom ℚ) (DPR ℤ q a b)) = _
  simp [DPR, Tight.D, Tight.y, map_sum, map_mul, map_pow]

/-- **(D2)** of `q_oddbox_equality.md` (proof): the image of the integer `D_J` is `D_J`. -/
theorem toRat_DJZ {k : ℕ} (J : BallotBound.Matching k) :
    toRat q (2 * k + 1) (Ideal.Quotient.mk _ (DJZ q J)) = TheoremB.DJ ℚ q J := by
  rw [DJZ, map_prod, map_prod, TheoremB.DJ]
  exact Finset.prod_congr rfl fun a _ => toRat_DPR _ _

/-- **(D2)** of `q_oddbox_equality.md` (proof): the image of the integer `D_P` is `D_P`. -/
theorem toRat_DPnZ {n : ℕ} (P : ColComp.PerfMatch (Fin n)) :
    toRat q n (Ideal.Quotient.mk _ (DPnZ q P)) = ColOne.DPn ℚ q P := by
  rw [DPnZ, map_prod, map_prod, ColOne.DPn]
  exact Finset.prod_congr rfl fun a _ => toRat_DPR _ _

/-- **(D2)** of `q_oddbox_equality.md` (proof): the image of a tight-pattern product. -/
theorem toRat_prodPR {m : ℕ} {lam : ChainLemma.Partition} (Tp : Tight.TightPattern lam
    (Finset.univ : Finset (Fin m))) :
    toRat q m (Ideal.Quotient.mk _ (prodPR ℤ q Tp)) = Tp.prod ℚ q :=
  mk_map_prodPR_int ℚ q Tp

/-- **(D2)** of `q_oddbox_equality.md`: `V_{(1),ℤ}` is the ideal of `C_{2k+1,ℤ}` generated by the
integer `D_J` (for `q ≥ 2`). -/
theorem VZ_one_eq_DIdealZ (hq : 2 ≤ q) (k : ℕ) :
    VZ q (2 * k + 1) {TheoremB.one} = DIdealZ q k := by
  apply le_antisymm
  · refine Ideal.span_le.2 ?_
    rintro _ ⟨lam, hlam, Tp, rfl⟩
    rw [Set.mem_singleton_iff] at hlam
    subst hlam
    obtain ⟨c, hc⟩ := TheoremB.exists_block Tp
    refine Ideal.subset_span ⟨TheoremB.matchingOf Tp hc, toRat_injective hq _ ?_⟩
    rw [toRat_DJZ, toRat_prodPR, TheoremB.DJ_matchingOf]
  · refine Ideal.span_le.2 ?_
    rintro _ ⟨J, rfl⟩
    refine Ideal.subset_span ⟨TheoremB.one, rfl, TheoremB.patternOf J, toRat_injective hq _ ?_⟩
    rw [toRat_DJZ, toRat_prodPR, TheoremB.prod_patternOf]

/-- **(D2)** of `q_oddbox_equality.md`: `V_{{∅},ℤ}` is the ideal `ℳ_ℤ` of `C_{n,ℤ}` generated by the
integer `D_P` (for `q ≥ 2`). -/
theorem VZ_empty_eq_MidealZ (hq : 2 ≤ q) (n : ℕ) :
    VZ q n {Bip.Partition'.empty} = MidealZ q n := by
  apply le_antisymm
  · refine Ideal.span_le.2 ?_
    rintro _ ⟨lam, hlam, Tp, rfl⟩
    rw [Set.mem_singleton_iff] at hlam
    subst hlam
    refine Ideal.subset_span ⟨ColOne.pmOfPattern Tp, toRat_injective hq _ ?_⟩
    rw [toRat_DPnZ, toRat_prodPR, ColOne.DPn_pmOfPattern]
  · refine Ideal.span_le.2 ?_
    rintro _ ⟨P, rfl⟩
    refine Ideal.subset_span ⟨Bip.Partition'.empty, rfl, ColOne.patternOfPM P,
      toRat_injective hq _ ?_⟩
    rw [toRat_DPnZ, toRat_prodPR, ColOne.prod_patternOfPM]

end OddEquality

end
