module

public import RequestProject.OddEquality.PartA
public import RequestProject.OddEquality.IntegralGen

/-!
# Part D of `q_oddbox_equality.md`: the theorem

This file formalizes **Part D** of `q_oddbox_equality.md`: the equality at the odd box for every
field (D1, Corollary 8.13), and the freeness over `ℤ` (D2, Theorem O, second sentence). (D3) is not
formalized (see the docstring of `D2_M`). The literal integral ideals generated by the `D_J` and
the `D_P` are identified with those of `q_free_Z.md` in `RequestProject/OddEquality/IntegralGen.lean`.
-/

@[expose] public section

namespace OddEquality

open EveryField FreeZ

set_option synthInstance.maxHeartbeats 200000

/-! ### (D1) -/

/-- **(D1)** of `q_oddbox_equality.md`, over `ℚ`: for `h ≥ 1` and every `k`,
`dim_ℚ (D_J) = Q^e_k(2h+2)` and `dim_ℚ ℳ = Q^e_k(2h+2)`. (`≤`: (A5), (B3), Part C; `≥`:
`OddTheorem.theoremO` and (A2).) -/
theorem D1_rat {h : ℕ} (hh : 1 ≤ h) (k : ℕ) :
    Module.finrank ℚ ((TheoremB.DIdeal ℚ (2 * h + 2) k).restrictScalars ℚ) =
        EvenCount.QkEven k (2 * h + 2) ∧
      Module.finrank ℚ ((Mideal ℚ (2 * h + 2) (2 * k + 2)).restrictScalars ℚ) =
        EvenCount.QkEven k (2 * h + 2) := by
  have hM : Module.finrank ℚ ((Mideal ℚ (2 * h + 2) (2 * k + 2)).restrictScalars ℚ) ≤
      EvenCount.QkEven k (2 * h + 2) := (B3 h).trans (partC h k)
  have hD := (A5 (F := ℚ) h k).trans hM
  have hO := OddTheorem.theoremO ℚ hh k
  have hA := A2 (F := ℚ) hh k
  omega

/-- **(D1)** of `q_oddbox_equality.md` (proof): `ℳ = V_{{∅}}` (`ColOne.VLamAll_empty_eq`), an ideal
of the form treated in `q_every_field.md`. -/
theorem Mideal_eq_VLamAll (F : Type*) [Field F] (q n : ℕ) :
    Mideal F q n = Tight.VLamAll F q n {Bip.Partition'.empty} :=
  (ColOne.VLamAll_empty_eq n).symm

/-- **(D1)** of `q_oddbox_equality.md` (proof, "rank over `F` ≤ rank over `ℚ` of the integer
matrix"): for every field `F`, `q ≥ 2`, `m` and `Λ`, `dim_F V_Λ(F) ≤ dim_ℚ V_Λ(ℚ)`
(`EveryField.finrank_VLamAll_eq_rankOver`, `EveryField.rankOver_le_rankOver_rat`). -/
theorem finrank_VLamAll_le_rat (F : Type*) [Field F] {q : ℕ} (hq : 2 ≤ q) (m : ℕ)
    (Λ : Set ChainLemma.Partition) :
    Module.finrank F ((Tight.VLamAll F q m Λ).restrictScalars F) ≤
      Module.finrank ℚ ((Tight.VLamAll ℚ q m Λ).restrictScalars ℚ) := by
  rw [finrank_VLamAll_eq_rankOver hq, finrank_VLamAll_eq_rankOver hq]
  exact rankOver_le_rankOver_rat F _

/-- **(D1) Equality over every field (Corollary 8.13)** of `q_oddbox_equality.md`: for every field
`F`, every `h ≥ 1` and every `k`,
`dim_F (D_J : J) = Q^e_k(2h + 2)` (`TheoremB.DIdeal F (2h+2) k`) and `dim_F ℳ = Q^e_k(2h + 2)`.
No hypothesis on the characteristic of `F`; `k = 0` is included. -/
theorem D1 (F : Type*) [Field F] {h : ℕ} (hh : 1 ≤ h) (k : ℕ) :
    Module.finrank F ((TheoremB.DIdeal F (2 * h + 2) k).restrictScalars F) =
        EvenCount.QkEven k (2 * h + 2) ∧
      Module.finrank F ((Mideal F (2 * h + 2) (2 * k + 2)).restrictScalars F) =
        EvenCount.QkEven k (2 * h + 2) := by
  obtain ⟨hDQ, hMQ⟩ := D1_rat hh k
  have hD : Module.finrank F ((TheoremB.DIdeal F (2 * h + 2) k).restrictScalars F) ≤
      EvenCount.QkEven k (2 * h + 2) := by
    rw [← TheoremB.VLamAll_one_eq, ← hDQ, ← TheoremB.VLamAll_one_eq]
    exact finrank_VLamAll_le_rat F (by omega) _ _
  have hM : Module.finrank F ((Mideal F (2 * h + 2) (2 * k + 2)).restrictScalars F) ≤
      EvenCount.QkEven k (2 * h + 2) := by
    rw [Mideal_eq_VLamAll, ← hMQ, Mideal_eq_VLamAll]
    exact finrank_VLamAll_le_rat F (by omega) _ _
  have hO := OddTheorem.theoremO F hh k
  have hA := A2 (F := F) hh k
  omega

/-- **Checks** at the end of `q_oddbox_equality.md` («the bound of Part B is attained»), in general
over `ℚ`: for `h ≥ 1` and every `k`, `dim_ℚ C_ℚ/⋂_P I_P·C_ℚ = Q^e_k(2h + 2) = dim_ℚ ℳ`
(from (B3), Part C and (D1)). -/
theorem partB_attained {h : ℕ} (hh : 1 ≤ h) (k : ℕ) :
    Module.finrank ℚ (Peel.C ℚ (2 * h + 2) (2 * k + 2) ⧸ Kint ℚ (2 * h + 2) (2 * k + 2)) =
      EvenCount.QkEven k (2 * h + 2) := by
  have h1 := B3 (F := ℚ) (n := 2 * k + 2) h
  have h2 := partC h k
  have h3 := (D1_rat hh k).2
  omega

/-! ### (D2) -/

/-- **(D2)** of `q_oddbox_equality.md` (proof): for `Λ` such that `dim_F V_Λ(F) = Q` for every field
`F` (here only fields in `Type` are needed), `C_{m,ℤ}/V_{Λ,ℤ}` is free of rank `(q − 1)^m − Q`
(`FreeZ.quotient_free_of_finrank_image`, as in `FreeZ.free_quotient_VZ`). -/
theorem free_of_finrank_const {q : ℕ} (hq : 2 ≤ q) (m : ℕ) (Λ : Set ChainLemma.Partition) (Q : ℕ)
    (hQ : ∀ (F : Type) [Field F], Module.finrank F ((Tight.VLamAll F q m Λ).restrictScalars F) = Q) :
    Module.Free ℤ (CZ q m ⧸ VZ q m Λ) ∧
      Module.finrank ℤ (CZ q m ⧸ VZ q m Λ) = (q - 1) ^ m - Q := by
  have hZ : ∀ (F : Type) [Field F], Module.finrank F (Submodule.span F
      (((rowLattice (intMat q m Λ)).map (castLin F (Box q m)) : Submodule ℤ (Box q m → F)) :
        Set (Box q m → F))) = Q := fun F _ => by
    rw [finrank_span_map_rowLattice F hq, hQ F]
  obtain ⟨hfree, hrank⟩ := quotient_free_of_finrank_image (rowLattice (intMat q m Λ))
    (fun p _ => by rw [hZ, hZ])
  rw [hZ, Fintype.card_fun, Fintype.card_fin, Fintype.card_fin] at hrank
  let e : ((Box q m → ℤ) ⧸ rowLattice (intMat q m Λ)) ≃ₗ[ℤ] (CZ q m ⧸ VZ q m Λ) :=
    (Submodule.Quotient.equiv _ _ (boxEquivZ hq m) (map_rowLattice_eq_VZ _ m Λ)).trans
      (Submodule.Quotient.restrictScalarsEquiv ℤ (VZ q m Λ))
  exact ⟨Module.Free.of_equiv e, e.finrank_eq.symm.trans hrank⟩

/-- **(D2)** of `q_oddbox_equality.md` (form of `q_free_Z.md`), for the ideal `(D_J)`: for `h ≥ 1`
and every `k`, `C_{2k+1,ℤ}/V_{(1),ℤ}` (`FreeZ.CZ`, `FreeZ.VZ … {TheoremB.one}`) is a free `ℤ`-module
of rank `r^{2k+1} − Q^e_k(2h + 2)`, `r = 2h + 1`. (`V_{(1),ℤ}` is the ideal generated by the integer
`D_J`, `VZ_one_eq_DIdealZ`; see `D2_DJ`.) -/
theorem D2_DJ_VZ {h : ℕ} (hh : 1 ≤ h) (k : ℕ) :
    Module.Free ℤ (CZ (2 * h + 2) (2 * k + 1) ⧸ VZ (2 * h + 2) (2 * k + 1) {TheoremB.one}) ∧
      Module.finrank ℤ (CZ (2 * h + 2) (2 * k + 1) ⧸ VZ (2 * h + 2) (2 * k + 1) {TheoremB.one}) =
        (2 * h + 1) ^ (2 * k + 1) - EvenCount.QkEven k (2 * h + 2) := by
  have := free_of_finrank_const (q := 2 * h + 2) (by omega) (2 * k + 1) {TheoremB.one}
    (EvenCount.QkEven k (2 * h + 2)) (fun F _ => by rw [TheoremB.VLamAll_one_eq]; exact (D1 F hh k).1)
  simpa using this

/-- **(D2)** of `q_oddbox_equality.md` (form of `q_free_Z.md`), for `ℳ`: for `h ≥ 1` and every `k`,
`C_{N,ℤ}/V_{{∅},ℤ}` (`N = 2k + 2`) is a free `ℤ`-module of rank `r^N − Q^e_k(2h + 2)`.
(`V_{{∅},ℤ}` is the ideal generated by the integer `D_P`, `VZ_empty_eq_MidealZ`; see `D2_M`.) -/
theorem D2_M_VZ {h : ℕ} (hh : 1 ≤ h) (k : ℕ) :
    Module.Free ℤ (CZ (2 * h + 2) (2 * k + 2) ⧸ VZ (2 * h + 2) (2 * k + 2) {Bip.Partition'.empty}) ∧
      Module.finrank ℤ
          (CZ (2 * h + 2) (2 * k + 2) ⧸ VZ (2 * h + 2) (2 * k + 2) {Bip.Partition'.empty}) =
        (2 * h + 1) ^ (2 * k + 2) - EvenCount.QkEven k (2 * h + 2) := by
  have := free_of_finrank_const (q := 2 * h + 2) (by omega) (2 * k + 2) {Bip.Partition'.empty}
    (EvenCount.QkEven k (2 * h + 2)) (fun F _ => by rw [← Mideal_eq_VLamAll]; exact (D1 F hh k).2)
  simpa using this

/-- **(D2) Freeness over `ℤ` (Theorem O, second sentence)** of `q_oddbox_equality.md`, for the
ideal `(D_J)`: for `h ≥ 1` and every `k`, the quotient of
`C_{2k+1,ℤ} = ℤ[y_1, …, y_{2k+1}]/(y_i^r)` (`FreeZ.CZ (2h+2) (2k+1)`, `r = 2h + 1`) by the ideal
generated by the integer polynomials `D_J` (`DIdealZ`; as a subgroup it is generated by the
`D_J·y^α`) is a free `ℤ`-module of rank `r^{2k+1} − Q^e_k(2h + 2)`. -/
theorem D2_DJ {h : ℕ} (hh : 1 ≤ h) (k : ℕ) :
    Module.Free ℤ (CZ (2 * h + 2) (2 * k + 1) ⧸ DIdealZ (2 * h + 2) k) ∧
      Module.finrank ℤ (CZ (2 * h + 2) (2 * k + 1) ⧸ DIdealZ (2 * h + 2) k) =
        (2 * h + 1) ^ (2 * k + 1) - EvenCount.QkEven k (2 * h + 2) := by
  rw [← VZ_one_eq_DIdealZ (by omega)]
  exact D2_DJ_VZ hh k

/-- **(D2) Freeness over `ℤ`** of `q_oddbox_equality.md`, for `ℳ`: for `h ≥ 1` and every `k`, the
quotient of `C_{N,ℤ} = ℤ[y_1, …, y_N]/(y_i^r)` (`N = 2k + 2`, `r = 2h + 1`) by the ideal `ℳ_ℤ`
generated by the integer polynomials `D_P` over the perfect matchings `P` of `Fin N` (`MidealZ`) is a
free `ℤ`-module of rank `r^N − Q^e_k(2h + 2)`.

(D3), the independence of `F` of the dimension of each graded piece of `(D_J)`, is optional in the
file and is not formalized here.) -/
theorem D2_M {h : ℕ} (hh : 1 ≤ h) (k : ℕ) :
    Module.Free ℤ (CZ (2 * h + 2) (2 * k + 2) ⧸ MidealZ (2 * h + 2) (2 * k + 2)) ∧
      Module.finrank ℤ (CZ (2 * h + 2) (2 * k + 2) ⧸ MidealZ (2 * h + 2) (2 * k + 2)) =
        (2 * h + 1) ^ (2 * k + 2) - EvenCount.QkEven k (2 * h + 2) := by
  rw [← VZ_empty_eq_MidealZ (by omega)]
  exact D2_M_VZ hh k

end OddEquality

end
