# Direct test of Proposition 5.8: V_{Lambda_i} ⊆ W_{q-2-i}(V_Lambda) for every down-set Lambda and every i,
# with Lambda_i := {mu in Par_{m-1} : F_Lambda(mu) > i}, F_Lambda from §5.4 (counted directly from the options, NOT from (5.1)).
# Also checks formula (5.1) against the direct count, and the 'no slack' control (q-3-i instead of q-2-i).
import sys, itertools
import numpy as np
from ideal import *
from p2test import partitions_upto, leq, options, sort_desc
from downset import Par, downsets, tight_pattern_products, conj

def all_monos(m,e):
    return list(itertools.product(range(e),repeat=m))

def full_basis(m,e,p,gens):
    """echelon basis of the ideal generated by gens in F_p[y]/(y_i^e) as rows over all monomials"""
    monos=all_monos(m,e); idx={mo:i for i,mo in enumerate(monos)}
    # closure: multiply by variables until stable (graded by degree)
    maxdeg=m*(e-1)
    rows=[]
    bydeg={}
    for g in gens:
        d=sum(next(iter(g)))
        bydeg.setdefault(d,[]).append(g)
    prev=[]  # list of dict polys basis at previous degree
    allrows=[]
    for d in range(maxdeg+1):
        cand=[]
        for f in prev:
            for v in range(m):
                nf={}
                for k,c in f.items():
                    kk=list(k); kk[v]+=1
                    if kk[v]<e: nf[tuple(kk)]=c
                if nf: cand.append(nf)
        cand+=bydeg.get(d,[])
        if not cand: prev=[]; continue
        dm=[mo for mo in monos if sum(mo)==d]; di={mo:i for i,mo in enumerate(dm)}
        M=np.zeros((len(cand),len(dm)),dtype=np.int64)
        for r,f in enumerate(cand):
            for k,c in f.items(): M[r,di[k]]=c
        Bm=rowspace_basis_mod_p(M,p)
        prev=[]
        for row in Bm:
            f={dm[j]:int(row[j]) for j in np.nonzero(row)[0]}
            prev.append(f); allrows.append(f)
    return allrows

def slice_W(basis_polys,m,e,p,j):
    """W_j(V): {[y_1^j] f : f in V, deg_{y1} f <= j}, as list of polys in variables 2..m (index tuples of length m-1)"""
    if not basis_polys: return []
    monos=all_monos(m,e)
    hi=[mo for mo in monos if mo[0]>j]; lo=[mo for mo in monos if mo[0]<=j]
    order=hi+lo; idx={mo:i for i,mo in enumerate(order)}
    M=np.zeros((len(basis_polys),len(order)),dtype=np.int64)
    for r,f in enumerate(basis_polys):
        for k,c in f.items(): M[r,idx[k]]=c
    Bm=rowspace_basis_mod_p(M,p)
    nh=len(hi)
    res=[]
    for row in Bm:
        if np.any(row[:nh]): continue
        f={}
        for jj in np.nonzero(row)[0]:
            mo=order[jj]
            if mo[0]==j: f[mo[1:]]=int(row[jj])
        if f: res.append(f)
    return res

def in_span(polys, target, m1, e, p):
    if not target: return True
    monos=all_monos(m1,e); idx={mo:i for i,mo in enumerate(monos)}
    M=np.zeros((len(polys)+1,len(monos)),dtype=np.int64)
    for r,f in enumerate(polys):
        for k,c in f.items(): M[r,idx[k]]=c
    for k,c in target.items(): M[-1,idx[k]]=c
    return rank_mod_p(M[:-1],p)==rank_mod_p(M,p)

def F_direct(mu,Lam,q):
    return sum(1 for o in options(mu,q) if o in Lam)

def F_51(mu,Lam,q):
    h=(q-1)//2; l=len(mu)
    rem=[sort_desc(list(mu[:i])+[mu[i]-1]+list(mu[i+1:])) for i in range(l)]
    r=sum(1 for x in rem if x in Lam)
    N=1 if (l<h and sort_desc(list(mu)+[1]) in Lam) else 0
    adds=[sort_desc(list(mu[:i])+[mu[i]+1]+list(mu[i+1:])) for i in range(l)]
    j0=None
    for i in range(l):
        if adds[i] in Lam: j0=i+1; break
    return r+(q-1-2*l)*N+((l-j0+1) if j0 else 0)

if __name__=="__main__":
    q=int(sys.argv[1]); m=int(sys.argv[2]); h=(q-1)//2; e=q-1; p=3
    P=Par(m,h); Pm1=Par(m-1,h)
    DS=downsets(P)
    gens={lam:tight_pattern_products(lam,m,q) for lam in P}
    gens1={mu:tight_pattern_products(mu,m-1,q) for mu in Pm1}
    print(f"q={q} m={m}: {len(DS)} down-sets; Par_(m-1)={Pm1}")
    total_fail=0; slack_hits=0; slack_tests=0
    for Lam in DS:
        G=[g for lam in Lam for g in gens[lam]]
        V=full_basis(m,e,p,G)
        # F values and (5.1)
        for mu in Pm1:
            assert F_direct(mu,Lam,q)==F_51(mu,Lam,q), ("(5.1) mismatch",Lam,mu)
        Ws={j:slice_W(V,m,e,p,j) for j in range(e)}
        for i in range(e):
            Li=[mu for mu in Pm1 if F_direct(mu,Lam,q)>i]
            # down-set check
            for mu in Li:
                for nu in Pm1:
                    if leq(nu,mu): assert nu in Li, ("Lambda_i not down-set",Lam,i,mu,nu)
            for mu in Li:
                for g in gens1[mu]:
                    ok=in_span(Ws[e-1-i],g,m-1,e,p)
                    if not ok:
                        total_fail+=1; print("  FAIL: Lambda",sorted(Lam),"i",i,"mu",mu)
                    if e-2-i>=0:
                        slack_tests+=1
                        if not in_span(Ws[e-2-i],g,m-1,e,p): slack_hits+=1
    print(f"P3 failures: {total_fail}; no-slack control: {slack_hits} of {slack_tests} generator tests fail one slice tighter")
