# Proposition 2.6 (both forms) and Proposition 7.1 (sandwich), numerically at small cells.
import itertools, numpy as np
from ideal import *
from sform import matchings
from fact72 import Q

def subspace_of_ideal(nvars,e,p,gens):
    """row-echelon basis (over all monomials with exps<e) of the ideal generated by gens in F_p[x]/(x_i^e)"""
    monos=list(itertools.product(range(e),repeat=nvars)); idx={mo:i for i,mo in enumerate(monos)}
    rows=[]
    for g in gens:
        for mo in monos:
            new={}
            for kk,c in g.items():
                s=tuple(x+y for x,y in zip(kk,mo))
                if max(s)<e: new[s]=(new.get(s,0)+c)%p
            new={k:v for k,v in new.items() if v}
            if new:
                v=np.zeros(len(monos),dtype=np.int64)
                for kk,c in new.items(): v[idx[kk]]=c
                rows.append(v)
    if not rows: return np.zeros((0,len(monos)),dtype=np.int64)
    return rowspace_basis_mod_p(np.array(rows),p)

def intersect(B1,B2,p):
    # intersection of row spaces: solve; use kernel approach via stacking
    if B1.shape[0]==0 or B2.shape[0]==0: return np.zeros((0,B1.shape[1]),dtype=np.int64)
    M=np.vstack([B1,B2])
    # find left kernel of M restricted... simpler: intersection dim = r1+r2-rank(stack); get basis via nullspace of [B1; -B2]^T
    A=np.vstack([B1,(-B2)%p]).T % p   # columns = generators
    # nullspace of A over F_p
    A=A.copy(); rows,cols=A.shape; piv=[]; r=0
    for c in range(cols):
        if r>=rows: break
        nz=np.nonzero(A[r:,c])[0]
        if len(nz)==0: continue
        i=r+nz[0]
        if i!=r: A[[r,i]]=A[[i,r]]
        A[r]=(A[r]*pow(int(A[r,c]),p-2,p))%p
        for i2 in np.nonzero(A[:,c])[0]:
            if i2!=r: A[i2]=(A[i2]-A[i2,c]*A[r])%p
        piv.append(c); r+=1
    free=[c for c in range(cols) if c not in piv]
    res=[]
    for f in free:
        v=np.zeros(cols,dtype=np.int64); v[f]=1
        for i,c in enumerate(piv): v[c]=(-A[i,f])%p
        w=(v[:B1.shape[0]]@B1)%p
        res.append(w)
    if not res: return np.zeros((0,B1.shape[1]),dtype=np.int64)
    return rowspace_basis_mod_p(np.array(res),p)

def lin(i,n,c=1): 
    k=[0]*n; k[i]=1; return {tuple(k):c}

for (k,q) in [(1,3),(2,3),(1,9)]:
    p=3; e=q-1; N=2*k+2; n=2*k+1
    # y-form: F_3[y_1..y_n]/ ∩_J (I'_J + (y^{q-1}))
    inter=None
    for J in matchings(list(range(N))):
        gens=[padd(lin(a-1,n),lin(b-1,n),p) for (a,b) in J if a!=0]
        B=subspace_of_ideal(n,e,p,gens)
        inter=B if inter is None else intersect(inter,B,p)
    by=e**n-inter.shape[0]
    # x-form: F_3[x_0..x_{2k+1}]/ ∩_J (I_J + (x^{q-1}))
    inter=None
    for J in matchings(list(range(N))):
        gens=[padd(lin(a,N),lin(b,N),p) for (a,b) in J]
        B=subspace_of_ideal(N,e,p,gens)
        inter=B if inter is None else intersect(inter,B,p)
    bx=e**N-inter.shape[0]
    # right side of sandwich: dim S/(E + (x^{q-1}))
    def e_j(j):
        r={}
        for S in itertools.combinations(range(N),j):
            kk=[0]*N
            for i in S: kk[i]=1
            r[tuple(kk)]=1
        return r
    B=subspace_of_ideal(N,e,p,[e_j(j) for j in range(1,N+1,2)])
    right=e**N-B.shape[0]
    print(f"(k,q)=({k},{q}): y-form b_k(q-1)={by}, x-form={bx}, Q_k(q)={Q(k,q)}, dim S/(E+(x^(q-1)))={right}")
