# Section 6, composite-m blocks. PREDICTIONS stated before computing.
# Block (c) "Y-free symmetric": ideal generated by prod_{(j,k) in P} (y_j+y_k)^{q-1} over perfect matchings P of [2r], in F_p[y]/(y_i^q).
#   Predicted dimension = N_q(2r) = (2r)! [x^{2r}] e^x I_0(2x)^{(q-1)/2}   (local Gamma-count at a component zeta = -1).
# Block (a) "Y-free bipartite": generators prod_j (y_j + y'_{sigma(j)})^{q-1} over bijections sigma of [r], in F_p[y,y']/(y^q).
#   Predicted dimension = (r!)^2 [x^{2r}] I_0(2x)^q.
import itertools, time
from fractions import Fraction
from math import factorial
from ideal import *
from sform import matchings
from thmA import N_q
def I0pow_coeff(N,e):
    I0=[Fraction(0)]*(N+1)
    for b in range(N//2+1): I0[2*b]=Fraction(1,factorial(b)**2)
    r=[Fraction(1)]+[Fraction(0)]*N
    for _ in range(e):
        c=[Fraction(0)]*(N+1)
        for i in range(N+1):
            if r[i]:
                for j in range(N+1-i): c[i+j]+=r[i]*I0[j]
        r=c
    return r[N]
def powsum(f,n,p,e):
    r=const(1,len(next(iter(f))))
    for _ in range(n): r=pmul(r,f,p,e)
    return r
for (r,q,p) in [(1,3,3),(2,3,3),(1,5,5),(2,5,5),(3,3,3),(2,3,5),(2,9,3)]:
    m=2*r; pred=N_q(m,q)
    print(f"PREDICTION block (c): r={r}, q={q}, F_{p}: dim = N_q(2r) = {pred}",flush=True)
    gens=[]
    for P in matchings(list(range(m))):
        g=const(1,m)
        for (a,b) in P: g=pmul(g,powsum(padd(var(a,m),var(b,m),p),q-1,p,q),p,q)
        gens.append(g)
    t=time.time(); d=ideal_dim(m,q,p,gens)[0]
    print(f"RESULT: {d} ({'match' if d==pred else 'MISMATCH'}, {time.time()-t:.1f}s)",flush=True)
for (r,q,p) in [(1,3,3),(2,3,3),(1,5,5),(2,5,5),(3,3,3)]:
    m=2*r; pred=factorial(r)**2*I0pow_coeff(2*r,q)
    print(f"PREDICTION block (a): r={r}, q={q}, F_{p}: dim = (r!)^2 [x^2r] I_0(2x)^q = {pred}",flush=True)
    gens=[]
    for sigma in itertools.permutations(range(r)):
        g=const(1,m)
        for j in range(r): g=pmul(g,powsum(padd(var(j,m),var(r+sigma[j],m),p),q-1,p,q),p,q)
        gens.append(g)
    t=time.time(); d=ideal_dim(m,q,p,gens)[0]
    print(f"RESULT: {d} ({'match' if d==pred else 'MISMATCH'}, {time.time()-t:.1f}s)",flush=True)
