module

public import RequestProject.OddPatterns.MarkedPf
public import RequestProject.Tight.Main
public import RequestProject.OddShapes.Main
public import RequestProject.Membership.Main

/-!
# Part B of `q_oddbox_patterns.md`: definitions

This file formalizes **Definitions (B0), (B1), (B2)** of `q_oddbox_patterns.md`: the marked
block `Pf_{E_ℓ}(B)`, the marked patterns and their products, and the ideals `V_Λ(I)`.

Throughout, `F` is a field, `h` a natural number, `r = 2h + 1`, `q = 2h + 2`, and the ring is
`C_m = Peel.C F (2*h+2) m` with `y_i = Tight.y F (2*h+2) i`.
-/

@[expose] public section

namespace OddPatterns

open ChainLemma OddShapes

set_option synthInstance.maxHeartbeats 200000

variable (F : Type*) [Field F] (h : ℕ)

/-- **Definition (B0)** of `q_oddbox_patterns.md` (the marked block): for `B ⊆ Fin m` with
increasing enumeration `ι_B = B.orderEmbOfFin rfl` and `ℓ ≥ 0`,
`Pf_{E_ℓ}(B) := mPf_ℓ(y ∘ ι_B) ∈ C_m`. -/
noncomputable def markedPf (l : ℕ) {m : ℕ} (B : Finset (Fin m)) : Peel.C F (2 * h + 2) m :=
  mPf h l (fun i : Fin B.card => Tight.y F (2 * h + 2) (B.orderEmbOfFin rfl i))

/-- **Definition (B1)** of `q_oddbox_patterns.md` (marked pattern; Definition 8.6 of the paper
with `δ = 1`): a marked pattern of the partition `λ` (with `ℓ = ℓ(λ)`) on `I ⊆ Fin m` consists of
a set `P` (`pairs`) of pairwise disjoint 2-element sets, pairwise disjoint blocks
`B_2, …, B_{λ_1}` (`blocks c` for `c ∈ [2, λ_1]`) with `|B_c| = λ'_c`, and a marked block `B_0`
(`marked`) with `|B_0| = ℓ + 1 + 2t` for some `t`, such that the pairs, the blocks and the marked
block are pairwise disjoint and their union is `I`. -/
structure MarkedPattern {m : ℕ} (lam : Partition) (I : Finset (Fin m)) where
  /-- The set `P` of pairs. -/
  pairs : Finset (Finset (Fin m))
  /-- The blocks `B_c` (`c = 2, …, λ_1`). -/
  blocks : ℕ → Finset (Fin m)
  /-- The marked block `B_0`. -/
  marked : Finset (Fin m)
  /-- Each pair is a 2-element set. -/
  card_pair : ∀ e ∈ pairs, e.card = 2
  /-- The pairs are pairwise disjoint. -/
  pairs_disjoint : (pairs : Set (Finset (Fin m))).PairwiseDisjoint id
  /-- `|B_c| = λ'_c` for `c = 2, …, λ_1`. -/
  card_block : ∀ c ∈ Finset.Icc 2 (lam.row 1), (blocks c).card = Tight.colLen lam c
  /-- The blocks are pairwise disjoint. -/
  blocks_disjoint : (↑(Finset.Icc 2 (lam.row 1)) : Set ℕ).PairwiseDisjoint blocks
  /-- Pairs and blocks are disjoint. -/
  pairs_blocks_disjoint : ∀ e ∈ pairs, ∀ c ∈ Finset.Icc 2 (lam.row 1), Disjoint e (blocks c)
  /-- Pairs and the marked block are disjoint. -/
  pairs_marked_disjoint : ∀ e ∈ pairs, Disjoint e marked
  /-- Blocks and the marked block are disjoint. -/
  blocks_marked_disjoint : ∀ c ∈ Finset.Icc 2 (lam.row 1), Disjoint (blocks c) marked
  /-- `|B_0| = ℓ + 1 + 2t` for some `t ≥ 0`. -/
  marked_card : ∃ t, marked.card = lam.len + 1 + 2 * t
  /-- The pairs, the blocks and the marked block cover `I` (and are contained in `I`). -/
  cover : pairs.sup id ∪ (Finset.Icc 2 (lam.row 1)).sup blocks ∪ marked = I

/-- **Definition (B1)** of `q_oddbox_patterns.md`: the **product** of a marked pattern,
`G := Π_{{a<b} ∈ P} D(y_a, y_b) · Pf_{E_ℓ}(B_0) · Π_{c=2}^{λ_1} Δ(B_c) ∈ C_m`. -/
noncomputable def MarkedPattern.prod {m : ℕ} {lam : Partition} {I : Finset (Fin m)}
    (T : MarkedPattern lam I) : Peel.C F (2 * h + 2) m :=
  (∏ e ∈ T.pairs, Tight.pairD F (2 * h + 2) e) * markedPf F h lam.len T.marked *
    ∏ c ∈ Finset.Icc 2 (lam.row 1), Tight.Delta F (2 * h + 2) (T.blocks c)

/-- **Definition (B2)** of `q_oddbox_patterns.md` (the ideals `V_Λ(I)`): for a set `Λ` of shapes
and `I ⊆ Fin m`, the ideal of `C_m` generated by the products of all tight patterns on `I` of all
`λ` with `(λ, 0) ∈ Λ` and the products of all marked patterns on `I` of all `λ` with
`(λ, 1) ∈ Λ`. -/
noncomputable def VS {m : ℕ} (Lam : Set Shape) (I : Finset (Fin m)) :
    Ideal (Peel.C F (2 * h + 2) m) :=
  Tight.VLam F (2 * h + 2) (comp Lam false) I ⊔
    Ideal.span {g | ∃ lam ∈ comp Lam true, ∃ T : MarkedPattern lam I, T.prod F h = g}

/-- **Definition (B2)** of `q_oddbox_patterns.md`: `V_Λ := V_Λ(Fin m)`. -/
noncomputable def VSAll (m : ℕ) (Lam : Set Shape) : Ideal (Peel.C F (2 * h + 2) m) :=
  VS F h Lam (Finset.univ : Finset (Fin m))

end OddPatterns
