module

public import RequestProject.Odd3.Defs
public import RequestProject.Membership.Vand
public import RequestProject.Pfaffian.Main

/-!
# Part M of `q_membership.md`: definitions

The **Definitions** of Part M of `q_membership.md` in the suggested form: `pairDy` (`D_e(y)`),
`DPy` (`D_P(y)`), the ideals `UB` (`𝔘_p(y; B)`) and `U` (`𝔘_p(y)`). Then two auxiliary facts
used in Theorem M: the set of pairs of a perfect matching transported along an order
embedding, and the transport of the generators along the increasing enumeration of `B`.
-/

@[expose] public section

namespace Membership

open Finset Pfaffian

variable {A : Type*} [CommRing A]

/-- **Part M, Definitions** of `q_membership.md`: for a 2-element set `e = {a < b}` of indices,
`D_e(y) := D(y_a, y_b) = ColOne.Dab (r+1) y_a y_b` (`a` the smaller element, `b` the larger one);
`1` for the empty set. -/
noncomputable def pairDy (r : ℕ) {n : ℕ} (y : Fin n → A) (e : Finset (Fin n)) : A :=
  if h : e.Nonempty then ColOne.Dab (r + 1) (y (e.min' h)) (y (e.max' h)) else 1

/-- **Part M, Definitions** of `q_membership.md`: for a set `P` of pairs,
`D_P(y) := Π_{e ∈ P} D_e(y)` (so `D_∅(y) = 1`). -/
noncomputable def DPy (r : ℕ) {n : ℕ} (y : Fin n → A) (P : Finset (Finset (Fin n))) : A :=
  ∏ e ∈ P, pairDy r y e

/-- **Part M, Definitions** of `q_membership.md`: the ideal `𝔘_p(y; B)` of `A` generated by the
elements `Tight.vand y S · D_P(y)`, where `S ⊆ B` has `p` elements and `P` is a perfect matching
of `B ∖ S` (`Odd3.IsPairs P` and `Odd3.supp P = B ∖ S`). -/
def UB (r p : ℕ) {n : ℕ} (y : Fin n → A) (B : Finset (Fin n)) : Ideal A :=
  Ideal.span {g | ∃ (S : Finset (Fin n)) (P : Finset (Finset (Fin n))), S ⊆ B ∧ S.card = p ∧
    Odd3.IsPairs P ∧ Odd3.supp P = B \ S ∧ g = Tight.vand y S * DPy r y P}

/-- **Part M, Definitions** of `q_membership.md`: `𝔘_p(y) := 𝔘_p(y; all the indices)`. -/
def U (r p : ℕ) {n : ℕ} (y : Fin n → A) : Ideal A := UB r p y Finset.univ

/-- Auxiliary for Part M of `q_membership.md`: `D_{{a, b}}(y) = D(y_a, y_b)` for `a < b`. -/
theorem pairDy_pair (r : ℕ) {n : ℕ} (y : Fin n → A) {a b : Fin n} (hab : a < b) :
    pairDy r y {a, b} = ColOne.Dab (r + 1) (y a) (y b) := by
  have hne : ({a, b} : Finset (Fin n)).Nonempty := insert_nonempty _ _
  have h1 : ({a, b} : Finset (Fin n)).min' hne = a := by
    apply le_antisymm (min'_le _ _ (by simp))
    exact (le_min'_iff _ _).2 fun c hc => by
      simp only [mem_insert, mem_singleton] at hc; rcases hc with rfl | rfl <;> [rfl; exact hab.le]
  have h2 : ({a, b} : Finset (Fin n)).max' hne = b := by
    apply le_antisymm _ (le_max' _ _ (by simp))
    exact (max'_le_iff _ _).2 fun c hc => by
      simp only [mem_insert, mem_singleton] at hc; rcases hc with rfl | rfl <;> [exact hab.le; rfl]
  unfold pairDy; rw [dif_pos hne, h1, h2]

/-- Auxiliary for (M1) of `q_membership.md`: the set of pairs `P_π` of a perfect matching `π` of
`Fin k`, transported along an order embedding `ι : Fin k ↪o Fin n`:
`P_π = { {ι(x), ι(π(x))} : x < π(x) }`. -/
def pairsOf {k n : ℕ} (ι : Fin k ↪o Fin n) (π : Fin k → Fin k) : Finset (Finset (Fin n)) :=
  (univ.filter (fun x => x < π x)).image (fun x => ({ι x, ι (π x)} : Finset (Fin n)))

/-- Auxiliary for (M1) of `q_membership.md`: `P_π` is a set of pairwise disjoint pairs. -/
theorem isPairs_pairsOf {k n : ℕ} (ι : Fin k ↪o Fin n) {π : Fin k → Fin k}
    (hπ : IsMatching π) : Odd3.IsPairs (pairsOf ι π) := by
  refine ⟨fun e he => ?_, ?_⟩
  · obtain ⟨x, -, rfl⟩ := mem_image.1 he
    exact card_pair fun h => hπ.2 x (ι.injective h).symm
  · rintro e he e' he' hne
    have he : e ∈ pairsOf ι π := he
    have he' : e' ∈ pairsOf ι π := he'
    unfold pairsOf at he he'
    obtain ⟨x, hx, rfl⟩ := mem_image.1 he
    obtain ⟨x', hx', rfl⟩ := mem_image.1 he'
    simp only [mem_filter, mem_univ, true_and] at hx hx'
    simp only [Function.onFun, id]
    rw [disjoint_left]
    intro c hc hc'
    apply hne
    simp only [mem_insert, mem_singleton] at hc hc'
    have key : x = x' := by
      rcases hc with rfl | rfl <;> rcases hc' with h | h
      · exact ι.injective h
      · have h' := ι.injective h
        have := hπ.1 x'; rw [← h'] at this
        exact absurd (this ▸ hx) (by rw [h']; exact lt_asymm hx')
      · have h' := ι.injective h
        have := hπ.1 x; rw [h'] at this
        exact absurd (this ▸ hx') (by rw [← h']; exact lt_asymm hx)
      · have h' := ι.injective h
        rw [← hπ.1 x, ← hπ.1 x', h']
    rw [key]

/-- Auxiliary for (M1) of `q_membership.md`: `P_π` covers exactly the image of `ι`. -/
theorem supp_pairsOf {k n : ℕ} (ι : Fin k ↪o Fin n) {π : Fin k → Fin k}
    (hπ : IsMatching π) : Odd3.supp (pairsOf ι π) = univ.map ι.toEmbedding := by
  ext c
  simp only [Odd3.supp, mem_sup, pairsOf, mem_image, mem_filter, mem_univ, true_and, id,
    mem_map, RelEmbedding.coe_toEmbedding]
  constructor
  · rintro ⟨e, ⟨x, -, rfl⟩, hc⟩
    simp only [mem_insert, mem_singleton] at hc
    rcases hc with rfl | rfl
    · exact ⟨x, rfl⟩
    · exact ⟨π x, rfl⟩
  · rintro ⟨z, rfl⟩
    rcases lt_or_gt_of_ne (hπ.2 z).symm with h | h
    · exact ⟨_, ⟨z, h, rfl⟩, by simp⟩
    · refine ⟨_, ⟨π z, by rw [hπ.1]; exact h, rfl⟩, by simp [hπ.1]⟩

/-- Auxiliary for (M1) of `q_membership.md`: `D_{P_π}(y) = Π_{x < π(x)} D(y_{ι(x)}, y_{ι(π(x))})`
(since `ι` is increasing, the smaller element of the pair of `x` is `ι(x)`). -/
theorem DPy_pairsOf (r : ℕ) {k n : ℕ} (y : Fin n → A) (ι : Fin k ↪o Fin n)
    (π : Fin k → Fin k) :
    DPy r y (pairsOf ι π) =
      ∏ x ∈ univ.filter (fun x => x < π x), ColOne.Dab (r + 1) (y (ι x)) (y (ι (π x))) := by
  unfold DPy pairsOf
  rw [prod_image]
  · refine prod_congr rfl fun x hx => ?_
    simp only [mem_filter, mem_univ, true_and] at hx
    exact pairDy_pair r y (ι.lt_iff_lt.2 hx)
  · intro x hx x' hx' he
    simp only [coe_filter, Set.mem_setOf_eq, mem_univ, true_and] at hx hx'
    have hm : ∀ z (hz : z < π z), ({ι z, ι (π z)} : Finset (Fin n)).min' (insert_nonempty _ _)
        = ι z := fun z hz => by
      apply le_antisymm (min'_le _ _ (by simp))
      exact (le_min'_iff _ _).2 fun c hc => by
        simp only [mem_insert, mem_singleton] at hc
        rcases hc with rfl | rfl
        · rfl
        · exact (ι.lt_iff_lt.2 hz).le
    have := hm x hx
    simp only [he, hm x' hx'] at this
    exact ι.injective this.symm

/-- Auxiliary for (M4) of `q_membership.md`: `D_e` is transported along an order embedding:
`D_{ι(e)}(y) = D_e(y ∘ ι)`. -/
theorem pairDy_map (r : ℕ) {n m : ℕ} (y : Fin m → A) (ι : Fin n ↪o Fin m)
    (e : Finset (Fin n)) : pairDy r y (e.map ι.toEmbedding) = pairDy r (y ∘ ι) e := by
  unfold pairDy
  by_cases he : e.Nonempty
  · have he' : (e.map ι.toEmbedding).Nonempty := he.map
    rw [dif_pos he, dif_pos he']
    have h1 : (e.map ι.toEmbedding).min' he' = ι (e.min' he) := by
      apply le_antisymm (min'_le _ _ (mem_map_of_mem _ (min'_mem _ _)))
      exact (le_min'_iff _ _).2 fun c hc => by
        obtain ⟨a, ha, rfl⟩ := mem_map.1 hc
        exact ι.le_iff_le.2 (min'_le _ _ ha)
    have h2 : (e.map ι.toEmbedding).max' he' = ι (e.max' he) := by
      apply le_antisymm _ (le_max' _ _ (mem_map_of_mem _ (max'_mem _ _)))
      exact (max'_le_iff _ _).2 fun c hc => by
        obtain ⟨a, ha, rfl⟩ := mem_map.1 hc
        exact ι.le_iff_le.2 (le_max' _ _ ha)
    rw [h1, h2]; rfl
  · rw [dif_neg he, dif_neg (by simpa using he)]

/-- Auxiliary for (M4) of `q_membership.md`: transport of the generators along an order
embedding `ι : Fin n ↪o Fin m`: `𝔘_p(y ∘ ι) ≤ 𝔘_p(y; ι(Fin n))`. -/
theorem U_le_UB (r p : ℕ) {n m : ℕ} (y : Fin m → A) (ι : Fin n ↪o Fin m) :
    U r p (y ∘ ι) ≤ UB r p y (univ.map ι.toEmbedding) := by
  unfold U UB
  rw [Ideal.span_le]
  rintro g ⟨S, P, -, hS, hP, hsupp, rfl⟩
  apply Ideal.subset_span
  refine ⟨S.map ι.toEmbedding, P.image (fun e => e.map ι.toEmbedding), map_subset_map.2
    (subset_univ _), by rw [card_map, hS], ⟨fun e he => ?_, ?_⟩, ?_, ?_⟩
  · obtain ⟨e', he', rfl⟩ := mem_image.1 he
    rw [card_map, hP.1 e' he']
  · rintro a ha b hb hab
    have ha : a ∈ P.image (fun e => e.map ι.toEmbedding) := ha
    have hb : b ∈ P.image (fun e => e.map ι.toEmbedding) := hb
    obtain ⟨a', ha', rfl⟩ := mem_image.1 ha
    obtain ⟨b', hb', rfl⟩ := mem_image.1 hb
    have hab' : a' ≠ b' := fun h => hab (by rw [h])
    simp only [Function.onFun, id]
    rw [disjoint_map]
    exact hP.2 ha' hb' hab'
  · rw [← Finset.map_sdiff, ← hsupp]
    unfold Odd3.supp
    ext c
    simp [mem_sup]
    exact ⟨fun ⟨i, hi, a, ha, h⟩ => ⟨a, ⟨i, hi, ha⟩, h⟩, fun ⟨a, ⟨i, hi, ha⟩, h⟩ => ⟨i, hi, a, ha, h⟩⟩
  · rw [vand_map]
    unfold DPy
    rw [prod_image (fun a _ b _ h => map_injective _ h)]
    simp_rw [pairDy_map]

end Membership
