module

public import RequestProject.Peel.Defs

/-!
# Definitions for the degeneration proposition (`q_degeneration.md`)

This file formalizes the **Setting** section of `q_degeneration.md`: the top-degree form
`f^{top}` of a polynomial, the ideal `gr(I)` of top-degree forms of an ideal `I`, the set
`Σ ⊆ T^m` (union of the supports of the `g_i`) and the ideal `V ⊆ C_m` generated by the images of
the `g_i`.

Encoding conventions:
* `S = F[y_1, …, y_m]` is `MvPolynomial (Fin m) F` (the variable `y_i` is `X (i - 1)`), and the ring
  `C_m` is `Peel.C F q m` of `q_peeling_lemma.md`;
* the finitely many polynomials `g_1, …, g_s` are a family `g : Fin s → MvPolynomial (Fin m) F`;
* `T ⊆ F` is a `Finset F`, and `T^m` is the type of functions `Fin m → T`.
-/

@[expose] public section

open MvPolynomial

namespace Degeneration

variable {F : Type*} [Field F] {m : ℕ}

/-- **Setting** of `q_degeneration.md`, *top-degree forms*: for `f ∈ S` of total degree `d`,
`f^{top}` is its homogeneous component of degree `d`.  (For `f = 0` this is `0`; the source only
uses `f^{top}` for `f ≠ 0`.) -/
noncomputable def top (f : MvPolynomial (Fin m) F) : MvPolynomial (Fin m) F :=
  homogeneousComponent f.totalDegree f

/-- **Setting** of `q_degeneration.md`: the set `{f^{top} : f ∈ I ∖ {0}}` of top-degree forms of
the nonzero elements of an ideal `I ⊆ S`. -/
def topForms (I : Ideal (MvPolynomial (Fin m) F)) : Set (MvPolynomial (Fin m) F) :=
  {p | ∃ f ∈ I, f ≠ 0 ∧ top f = p}

/-- **Setting** of `q_degeneration.md`: the ideal `gr(I)` of top-degree forms of an ideal
`I ⊆ S`, generated by the `f^{top}`, `f ∈ I ∖ {0}`.  The source describes `gr(I)` as the set of `0`
and the `f^{top}` together with their sums; that this set is exactly this ideal is
`Degeneration.gr_restrictScalars_eq_span`, and its description degree by degree is
`Degeneration.mem_gr_iff_of_isHomogeneous` (both in `RequestProject/Degeneration/Lemma.lean`). -/
noncomputable def gr (I : Ideal (MvPolynomial (Fin m) F)) : Ideal (MvPolynomial (Fin m) F) :=
  Ideal.span (topForms I)

/-- **Proposition (degeneration)** of `q_degeneration.md`: the set
`Σ := {M ∈ T^m : g_i(M) ≠ 0 for some i}`, the union of the supports of the `g_i` on `T^m`. -/
noncomputable def supportSet (T : Finset F) {s : ℕ} (g : Fin s → MvPolynomial (Fin m) F) :
    Finset (Fin m → T) :=
  open Classical in
  Finset.univ.filter fun M => ∃ i, eval (fun j => (M j : F)) (g i) ≠ 0

/-- **Proposition (degeneration)** of `q_degeneration.md`: the ideal `V ⊆ C_m` generated by the
images of `g_1, …, g_s`. -/
noncomputable def genIdeal (q : ℕ) {s : ℕ} (g : Fin s → MvPolynomial (Fin m) F) :
    Ideal (Peel.C F q m) :=
  Ideal.span (Set.range fun i => Ideal.Quotient.mk (Peel.powIdeal F q m) (g i))

end Degeneration

end
