module

public import RequestProject.Degeneration.Lemma
public import RequestProject.Peel.Main

/-!
# The degeneration proposition (`q_degeneration.md`)

This file proves the **Proposition (degeneration)** of `q_degeneration.md`: for homogeneous
`g_1, …, g_s ∈ S`, the ideal `V ⊆ C_m` generated by their images satisfies `dim_F V ≤ |Σ|`, where
`Σ ⊆ T^m` is the union of the supports of the `g_i` on `T^m`.

The proof follows the **Proof** of the source, with `I := (g_1, …, g_s) + (y_j^{q−1} − 1)`:
* (steps 1–2) evaluation on the points of `T^m ∖ Σ` maps `S/I` onto `F^{T^m ∖ Σ}` (Lagrange
  interpolation), so `dim_F S/I ≥ (q − 1)^m − |Σ|`; and `S/I` is finite-dimensional since it is
  spanned by the monomials with exponents `< q − 1`;
* (step 3) by part (i) of the Lemma, `I' := (g_1, …, g_s) + (y_j^{q−1}) ⊆ gr(I)`;
* (step 4) by part (ii) of the Lemma, `dim S/gr(I) = dim S/I`, and `C_m ↠ S/I' ↠ S/gr(I)` kills
  `V`, so `dim V ≤ dim C_m − dim S/gr(I) ≤ (q − 1)^m − ((q − 1)^m − |Σ|) = |Σ|`.
Only the inequality `dim_F S/I ≥ (q−1)^m − |Σ|` (not the full isomorphism `S/I ≅ F^{T^m ∖ Σ}` of
step 2) is needed for the conclusion, and this is what is formalized.
-/

@[expose] public section

open MvPolynomial

namespace Degeneration

set_option synthInstance.maxHeartbeats 200000

variable {F : Type*} [Field F]

/-- **Proof** of the Proposition of `q_degeneration.md`, last step: `C_m` is a nonzero ring for
`q ≥ 2` (evaluation at `0` is a ring map `C_m → F`). -/
theorem nontrivial_C {q : ℕ} (hq : 2 ≤ q) (m : ℕ) : Nontrivial (Peel.C F q m) := by
  let φ : Peel.C F q m →+* F := Ideal.Quotient.lift (Peel.powIdeal F q m) (eval 0) (by
    intro a ha
    refine (Ideal.span_le.2 ?_ : Peel.powIdeal F q m ≤ RingHom.ker (eval 0)) ha
    rintro _ ⟨i, rfl⟩
    simp only [SetLike.mem_coe, RingHom.mem_ker, map_pow, eval_X, Pi.zero_apply]
    exact zero_pow (by omega))
  exact φ.domain_nontrivial

/-- **Proof** of the Proposition of `q_degeneration.md`, last step: `dim_F C_m = (q − 1)^m`. -/
theorem finrank_C {q : ℕ} (hq : 2 ≤ q) : ∀ m : ℕ, Module.finrank F (Peel.C F q m) = (q - 1) ^ m
  | 0 => by
    have h0 : Peel.powIdeal F q 0 = ⊥ := by
      rw [Peel.powIdeal, Set.range_eq_empty, Ideal.span_empty]
    have e : Peel.C F q 0 ≃ₐ[F] F :=
      (Ideal.quotientEquivAlgOfEq F h0).trans
        ((AlgEquiv.quotientBot F _).trans (MvPolynomial.isEmptyAlgEquiv F (Fin 0)))
    rw [e.toLinearEquiv.finrank_eq, Module.finrank_self, pow_zero]
  | n + 1 => by
    haveI := nontrivial_C (F := F) hq n
    rw [(Peel.peelEquiv' F q n).toLinearEquiv.finrank_eq]
    let pb := AdjoinRoot.powerBasis' (Peel.monic_X_pow_q q (Peel.C F q n))
    let e : Peel.Peeled q (Peel.C F q n) ≃ₗ[F] (Fin pb.dim → Peel.C F q n) :=
      pb.basis.equivFun.restrictScalars F
    rw [e.finrank_eq, Module.finrank_pi_fintype, Finset.sum_const, Finset.card_univ,
      Fintype.card_fin, smul_eq_mul, finrank_C hq n, AdjoinRoot.powerBasis'_dim,
      Polynomial.natDegree_X_pow, pow_succ, mul_comm]

/-- **Proof** of the Proposition of `q_degeneration.md`: the ideal
`(y_1^{q−1} − 1, …, y_m^{q−1} − 1) ⊆ S`. -/
noncomputable def rootIdeal (q m : ℕ) : Ideal (MvPolynomial (Fin m) F) :=
  Ideal.span (Set.range fun j : Fin m => (X j ^ (q - 1) - 1 : MvPolynomial (Fin m) F))

/-- **Proof** of the Proposition of `q_degeneration.md`: the ideal
`I := (g_1, …, g_s) + (y_1^{q−1} − 1, …, y_m^{q−1} − 1) ⊆ S`. -/
noncomputable def idealI (q : ℕ) {m s : ℕ} (g : Fin s → MvPolynomial (Fin m) F) :
    Ideal (MvPolynomial (Fin m) F) :=
  Ideal.span (Set.range g) ⊔ rootIdeal q m

/-- **Proof** of the Proposition of `q_degeneration.md`, step 1: every `u ∈ T` satisfies
`u^{q−1} = 1`, since `Π_{u∈T} (y − u) = y^{q−1} − 1`. -/
theorem pow_eq_one_of_mem {q : ℕ} {T : Finset F}
    (hprod : ∏ u ∈ T, (Polynomial.X - Polynomial.C u) = Polynomial.X ^ (q - 1) - 1)
    {u : F} (hu : u ∈ T) : u ^ (q - 1) = 1 := by
  have h := congrArg (Polynomial.eval u) hprod
  rw [Polynomial.eval_prod, Finset.prod_eq_zero hu (by simp)] at h
  simp only [Polynomial.eval_sub, Polynomial.eval_pow, Polynomial.eval_X, Polynomial.eval_one]
    at h
  exact (sub_eq_zero.1 h.symm)

/-- **Proof** of the Proposition of `q_degeneration.md`, step 2: `S/I` is finite-dimensional
(it is spanned by the images of the monomials with all exponents `< q − 1`). -/
theorem finite_quotient_idealI {q : ℕ} (hq : 2 ≤ q) {m s : ℕ}
    (g : Fin s → MvPolynomial (Fin m) F) :
    FiniteDimensional F (MvPolynomial (Fin m) F ⧸ idealI q g) := by
  have hpos : 0 < q - 1 := by omega
  have hX : ∀ j, (Ideal.Quotient.mk (idealI q g) (X j)) ^ (q - 1) = 1 := by
    intro j
    rw [← map_pow, ← map_one (Ideal.Quotient.mk (idealI q g)), Ideal.Quotient.eq]
    exact Ideal.mem_sup_right (Ideal.subset_span ⟨j, rfl⟩)
  have hXn : ∀ j n, (Ideal.Quotient.mk (idealI q g) (X j)) ^ n =
      (Ideal.Quotient.mk (idealI q g) (X j)) ^ (n % (q - 1)) := by
    intro j n
    conv_lhs => rw [← Nat.div_add_mod n (q - 1), pow_add, pow_mul, hX, one_pow, one_mul]
  let v : (Fin m → Fin (q - 1)) → MvPolynomial (Fin m) F ⧸ idealI q g :=
    fun b => ∏ j, (Ideal.Quotient.mk (idealI q g) (X j)) ^ (b j : ℕ)
  have hspan : Submodule.span F (Set.range v) = ⊤ := by
    rw [eq_top_iff]
    rintro x -
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
    induction p using MvPolynomial.induction_on' with
    | monomial u a =>
      have h : Ideal.Quotient.mk (idealI q g) (monomial u a) =
          a • v (fun j => ⟨u j % (q - 1), Nat.mod_lt _ hpos⟩) := by
        rw [monomial_eq, map_mul, Finsupp.prod_fintype _ _ (fun _ => pow_zero _), map_prod,
          Algebra.smul_def, ← Ideal.Quotient.mk_algebraMap, MvPolynomial.algebraMap_eq]
        congr 1
        exact Finset.prod_congr rfl fun j _ => by rw [map_pow, hXn]
      rw [h]
      exact Submodule.smul_mem _ _ (Submodule.subset_span ⟨_, rfl⟩)
    | add p₁ p₂ h₁ h₂ =>
      rw [map_add]
      exact add_mem h₁ h₂
  exact ⟨Submodule.fg_def.2 ⟨_, Set.finite_range v, hspan⟩⟩

open Classical in
/-- **Proof** of the Proposition of `q_degeneration.md`, step 2 (the idempotents `e_M`): the
Lagrange polynomial `δ_M := Π_j Π_{u ∈ T, u ≠ M_j} (y_j − u)/(M_j − u)` of a point `M ∈ T^m`. -/
noncomputable def lagrangePoly {m : ℕ} (T : Finset F) (M : Fin m → T) : MvPolynomial (Fin m) F :=
  ∏ j, ∏ u ∈ T.erase (M j), C (((M j : F) - u)⁻¹) * (X j - C u)

open Classical in
/-- **Proof** of the Proposition of `q_degeneration.md`, step 2: `δ_M(N) = 1` if `N = M` and `0`
otherwise, for points `M, N ∈ T^m`. -/
theorem eval_lagrangePoly {m : ℕ} (T : Finset F) (M N : Fin m → T) :
    eval (fun j => (N j : F)) (lagrangePoly T M) = if N = M then 1 else 0 := by
  simp only [lagrangePoly, eval_prod, eval_mul, eval_C, eval_sub, eval_X]
  split_ifs with h
  · subst h
    exact Finset.prod_eq_one fun j _ => Finset.prod_eq_one fun u hu =>
      inv_mul_cancel₀ (sub_ne_zero.2 (Finset.ne_of_mem_erase hu).symm)
  · obtain ⟨j, hj⟩ := Function.ne_iff.1 h
    refine Finset.prod_eq_zero (Finset.mem_univ j) (Finset.prod_eq_zero (i := (N j : F))
      (Finset.mem_erase.2 ⟨fun e => hj (Subtype.ext e), (N j).2⟩) ?_)
    rw [sub_self, mul_zero]

/-- **Proof** of the Proposition of `q_degeneration.md`, steps 1–2 (Chinese remainder and ideals
of a product of fields, in the form needed): `dim_F S/I ≥ |T^m ∖ Σ| = (q − 1)^m − |Σ|`. -/
theorem card_compl_le_finrank_quotient_idealI {q : ℕ} {m s : ℕ} (T : Finset F)
    (hT : T.card = q - 1) (hprod : ∏ u ∈ T, (Polynomial.X - Polynomial.C u) = Polynomial.X ^ (q - 1) - 1)
    (g : Fin s → MvPolynomial (Fin m) F)
    (hfin : FiniteDimensional F (MvPolynomial (Fin m) F ⧸ idealI q g)) :
    (q - 1) ^ m - (supportSet T g).card ≤ Module.finrank F (MvPolynomial (Fin m) F ⧸ idealI q g) := by
  classical
  let U := {M : Fin m → T // M ∉ supportSet T g}
  let ev : MvPolynomial (Fin m) F →ₐ[F] (U → F) :=
    Pi.algHom F _ fun M => aeval fun j => ((M.1 j : T) : F)
  have hev : ∀ p M, ev p M = eval (fun j => ((M.1 j : T) : F)) p := fun p M => by
    simp [ev]
  have hker : ∀ a ∈ idealI q g, ev a = 0 := by
    intro a ha
    refine (sup_le (Ideal.span_le.2 ?_) (Ideal.span_le.2 ?_) :
      idealI q g ≤ RingHom.ker ev.toRingHom) ha
    · rintro _ ⟨i, rfl⟩
      rw [SetLike.mem_coe, RingHom.mem_ker]
      funext M
      have hM := M.2
      simp only [supportSet, Finset.mem_filter, Finset.mem_univ, true_and, not_exists,
        not_not] at hM
      rw [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, hev, hM i, Pi.zero_apply]
    · rintro _ ⟨j, rfl⟩
      rw [SetLike.mem_coe, RingHom.mem_ker]
      funext M
      rw [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, hev]
      simp [pow_eq_one_of_mem hprod (M.1 j).2]
  let ψ : (MvPolynomial (Fin m) F ⧸ idealI q g) →ₐ[F] (U → F) :=
    Ideal.Quotient.liftₐ (idealI q g) ev hker
  have hsurj : Function.Surjective ψ := by
    intro h
    refine ⟨Ideal.Quotient.mk _ (∑ M : U, C (h M) * lagrangePoly T M.1), ?_⟩
    funext N
    change ev (∑ M : U, C (h M) * lagrangePoly T M.1) N = h N
    rw [hev, eval_sum]
    simp only [eval_mul, eval_C, eval_lagrangePoly]
    rw [Finset.sum_eq_single N (fun b _ hb => by rw [if_neg (fun e => hb (Subtype.ext e).symm),
      mul_zero]) (fun h' => absurd (Finset.mem_univ N) h'), if_pos rfl, mul_one]
  have hle := LinearMap.finrank_range_le ψ.toLinearMap
  rw [LinearMap.range_eq_top.2 hsurj, finrank_top, Module.finrank_fintype_fun_eq_card] at hle
  have hU : Fintype.card U = (q - 1) ^ m - (supportSet T g).card := by
    rw [Fintype.card_subtype_compl, Fintype.card_fun, Fintype.card_coe, hT, Fintype.card_fin,
      Fintype.card_coe]
  omega

/-- **Proof** of the Proposition of `q_degeneration.md`, step 3: the top-degree form of
`y_j^{q−1} − 1` is `y_j^{q−1}` (for `q ≥ 2`). -/
theorem top_X_pow_sub_one {q m : ℕ} (hq : 2 ≤ q) (j : Fin m) :
    top (X j ^ (q - 1) - 1 : MvPolynomial (Fin m) F) = X j ^ (q - 1) := by
  have hc : homogeneousComponent (q - 1) (X j ^ (q - 1) - 1 : MvPolynomial (Fin m) F) =
      X j ^ (q - 1) := by
    rw [map_sub, homogeneousComponent_of_mem
      ((mem_homogeneousSubmodule _ _).2 (isHomogeneous_X_pow j (q - 1))), if_pos rfl,
      homogeneousComponent_eq_zero _ _ (by rw [totalDegree_one]; omega), sub_zero]
  have hdeg : (X j ^ (q - 1) - 1 : MvPolynomial (Fin m) F).totalDegree = q - 1 := by
    refine le_antisymm ((totalDegree_sub _ _).trans ?_) ?_
    · rw [totalDegree_X_pow, totalDegree_one]; omega
    · by_contra h
      have h0 := homogeneousComponent_eq_zero _ _ (not_le.1 h)
      rw [hc] at h0
      exact pow_ne_zero _ (X_ne_zero j) h0
  rw [top, hdeg, hc]

/-- **Proof** of the Proposition of `q_degeneration.md`, step 3: by part (i) of the Lemma,
`I' := (g_1, …, g_s) + (y_1^{q−1}, …, y_m^{q−1}) ⊆ gr(I)`. -/
theorem sup_powIdeal_le_gr {q : ℕ} (hq : 2 ≤ q) {m s : ℕ} (g : Fin s → MvPolynomial (Fin m) F)
    (hg : ∀ i, ∃ n, (g i).IsHomogeneous n) :
    Ideal.span (Set.range g) ⊔ Peel.powIdeal F q m ≤ gr (idealI q g) := by
  refine sup_le (Ideal.span_le.2 ?_) (Ideal.span_le.2 ?_)
  · rintro _ ⟨i, rfl⟩
    by_cases h0 : g i = 0
    · rw [h0]; exact zero_mem _
    obtain ⟨n, hn⟩ := hg i
    have htop : top (g i) = g i := by
      rw [top, hn.totalDegree h0, homogeneousComponent_of_mem
        ((mem_homogeneousSubmodule _ _).2 hn), if_pos rfl]
    have h := span_top_le_gr (idealI q g) (fun _ : Fin 1 => g i)
      (fun _ => Ideal.mem_sup_left (Ideal.subset_span ⟨i, rfl⟩)) (fun _ => h0)
      (Ideal.subset_span ⟨0, rfl⟩)
    simp only [htop] at h
    exact h
  · rintro _ ⟨j, rfl⟩
    have hne : (X j ^ (q - 1) - 1 : MvPolynomial (Fin m) F) ≠ 0 := by
      intro h
      have h' := top_X_pow_sub_one (F := F) hq j
      rw [h, top, map_zero] at h'
      exact pow_ne_zero _ (X_ne_zero j) h'.symm
    have h := span_top_le_gr (idealI q g) (fun _ : Fin 1 => (X j ^ (q - 1) - 1 : MvPolynomial _ F))
      (fun _ => Ideal.mem_sup_right (Ideal.subset_span ⟨j, rfl⟩)) (fun _ => hne)
      (Ideal.subset_span ⟨0, rfl⟩)
    simp only [top_X_pow_sub_one hq] at h
    exact h

/-- **Proposition (degeneration)** of `q_degeneration.md`: let `F` be a field, `q ≥ 3`, `T ⊆ F` a
set of `q − 1` elements with `Π_{u∈T} (y − u) = y^{q−1} − 1`, and `g_1, …, g_s ∈ S` homogeneous.
With `Σ := {M ∈ T^m : g_i(M) ≠ 0 for some i}` (`supportSet T g`) and `V ⊆ C_m` the ideal
generated by the images of the `g_i` (`genIdeal q g`), `dim_F V ≤ |Σ|`.

Encoding: `dim_F V` is the `F`-dimension of `V` regarded as an `F`-subspace of `C_m`; homogeneity
of `g_i` is `∃ n, (g i).IsHomogeneous n` (in particular `g_i = 0` is allowed).  The hypotheses
are those of the source; the proof only uses `q ≥ 2` from `q ≥ 3`. -/
theorem finrank_genIdeal_le_card_supportSet {q : ℕ} (hq : 3 ≤ q) (m : ℕ) (T : Finset F)
    (hT : T.card = q - 1)
    (hprod : ∏ u ∈ T, (Polynomial.X - Polynomial.C u) = Polynomial.X ^ (q - 1) - 1)
    {s : ℕ} (g : Fin s → MvPolynomial (Fin m) F) (hg : ∀ i, ∃ n, (g i).IsHomogeneous n) :
    Module.finrank F ((genIdeal q g).restrictScalars F) ≤ (supportSet T g).card := by
  have hq2 : 2 ≤ q := by omega
  have hfin := finite_quotient_idealI (F := F) hq2 g
  have hgr := (finrank_quotient_gr (idealI q g) hfin).2
  have hcard := card_compl_le_finrank_quotient_idealI T hT hprod g hfin
  have hle := sup_powIdeal_le_gr hq2 g hg
  let φ : Peel.C F q m →ₐ[F] (MvPolynomial (Fin m) F ⧸ gr (idealI q g)) :=
    Ideal.Quotient.liftₐ (Peel.powIdeal F q m) (Ideal.Quotient.mkₐ F (gr (idealI q g)))
      (fun a ha => by
        rw [Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.eq_zero_iff_mem]
        exact hle (Ideal.mem_sup_right ha))
  have hφ : Function.Surjective φ := by
    intro y
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective y
    exact ⟨Ideal.Quotient.mk _ p, rfl⟩
  have hV : (genIdeal q g).restrictScalars F ≤ LinearMap.ker φ.toLinearMap := by
    intro x hx
    have h : genIdeal q g ≤ RingHom.ker φ.toRingHom := by
      rw [genIdeal, Ideal.span_le]
      rintro _ ⟨i, rfl⟩
      rw [SetLike.mem_coe, RingHom.mem_ker]
      change Ideal.Quotient.mk _ (g i) = 0
      rw [Ideal.Quotient.eq_zero_iff_mem]
      exact hle (Ideal.mem_sup_left (Ideal.subset_span ⟨i, rfl⟩))
    exact h hx
  have hrank := LinearMap.finrank_range_add_finrank_ker φ.toLinearMap
  rw [LinearMap.range_eq_top.2 hφ, finrank_top, finrank_C hq2] at hrank
  have hmono := Submodule.finrank_mono hV
  omega

end Degeneration

end
