module

public import RequestProject.EveryField.Integral

/-!
# The Setting and part (i) of the Theorem of `q_free_Z.md`

Formalization of the **Setting** of `q_free_Z.md` and of **part (i)** of its Theorem.

* `C_{m,ℤ} = ℤ[y_1, …, y_m]/(y_1^{q−1}, …, y_m^{q−1})` is `CZ q m`, the quotient of
  `MvPolynomial (Fin m) ℤ` by the ideal `powIdealZ q m` (the same formula as `Peel.powIdeal` of
  `q_peeling_lemma.md`, which is stated over a field).
* `V_{Λ,ℤ} ⊆ C_{m,ℤ}` is `VZ q m Λ`, the ideal generated by the classes of the integer
  tight-pattern products `G_ℤ = EveryField.prodPR ℤ q Tp` (the same integer formulas as over a
  field) of the tight patterns on `{1, …, m}` of the elements of `Λ`.
* The box `B_m` is `EveryField.Box q m`, the box monomials of `C_{m,ℤ}` are `boxMonoZ`, and
  `boxToCZ : ℤ^{B_m} → C_{m,ℤ}` is `w ↦ Σ_a w_a y^a`; it is a `ℤ`-linear bijection
  (`boxToCZ_bijective`): `C_{m,ℤ}` is free abelian with basis the box monomials.
* The integer vectors `v_{a,G}` are `EveryField.intVec q a G_ℤ` of `q_every_field.md`.
-/

@[expose] public section

open MvPolynomial

namespace FreeZ

open ChainLemma Tight EveryField

set_option synthInstance.maxHeartbeats 200000

variable (q : ℕ)

/-- **Setting** of `q_free_Z.md`: the ideal `(y_1^{q−1}, …, y_m^{q−1})` of `ℤ[y_1, …, y_m]`
(variables `y_i = X (i - 1)`, indexed by `Fin m`). -/
noncomputable def powIdealZ (m : ℕ) : Ideal (MvPolynomial (Fin m) ℤ) :=
  Ideal.span (Set.range fun i : Fin m => (X i ^ (q - 1) : MvPolynomial (Fin m) ℤ))

/-- **Setting** of `q_free_Z.md`: the ring `C_{m,ℤ} := ℤ[y_1, …, y_m]/(y_1^{q−1}, …, y_m^{q−1})`. -/
abbrev CZ (m : ℕ) : Type := MvPolynomial (Fin m) ℤ ⧸ powIdealZ q m

/-- **Setting** of `q_free_Z.md`: `V_{Λ,ℤ} ⊆ C_{m,ℤ}`, the ideal generated by the tight-pattern
products (over `ℤ`, `G_ℤ = prodPR ℤ q Tp`) of the tight patterns on `{1, …, m}` of the elements
of `Λ`. -/
noncomputable def VZ (m : ℕ) (Λ : Set Partition) : Ideal (CZ q m) :=
  Ideal.span {g | ∃ lam ∈ Λ, ∃ Tp : TightPattern lam (Finset.univ : Finset (Fin m)),
    Ideal.Quotient.mk (powIdealZ q m) (prodPR ℤ q Tp) = g}

/-- **Setting** of `q_free_Z.md`: the box monomial `y^a ∈ C_{m,ℤ}`, `a ∈ B_m`. -/
noncomputable def boxMonoZ {m : ℕ} (a : Box q m) : CZ q m :=
  Ideal.Quotient.mk _ (monomial (boxExp a) 1)

/-- **Setting** of `q_free_Z.md`: the `ℤ`-linear map `ℤ^{B_m} → C_{m,ℤ}`,
`w ↦ Σ_{a ∈ B_m} w_a y^a` (coordinates in the box-monomial basis). -/
noncomputable def boxToCZ (m : ℕ) : (Box q m → ℤ) →ₗ[ℤ] CZ q m :=
  Fintype.linearCombination ℤ (boxMonoZ q)

variable {q}

/-- **Setting** of `q_free_Z.md` (auxiliary): the class of an integer polynomial `p` in `C_{m,ℤ}` is
`Σ_{b ∈ B_m} [y^b] p · y^b` (reduction modulo `(y_i^{q−1})` kills the monomials outside the box). -/
theorem mk_eq_boxToCZ {m : ℕ} (p : MvPolynomial (Fin m) ℤ) :
    Ideal.Quotient.mk (powIdealZ q m) p = boxToCZ q m (fun b => p.coeff (boxExp b)) := by
  classical
  induction p using MvPolynomial.induction_on' with
  | monomial d c =>
    by_cases hd : ∀ i, d i < q - 1
    · let b0 : Box q m := fun i => ⟨d i, hd i⟩
      have hb0 : boxExp b0 = d := by ext i; rfl
      rw [boxToCZ, Fintype.linearCombination_apply, Finset.sum_eq_single b0]
      · rw [hb0, coeff_monomial, if_pos rfl, boxMonoZ, hb0, ← map_zsmul, smul_monomial,
          smul_eq_mul, mul_one]
      · intro b _ hb
        rw [coeff_monomial, if_neg, zero_smul]
        intro h
        exact hb (boxExp_injective (h.symm ▸ hb0.symm) |>.symm ▸ rfl)
      · simp
    · push_neg at hd
      obtain ⟨i, hi⟩ := hd
      have hle : Finsupp.single i (q - 1) ≤ d := by
        rw [Finsupp.single_le_iff]; exact hi
      have hrhs : (fun b : Box q m => (monomial d c).coeff (boxExp b)) = 0 := by
        funext b
        rw [coeff_monomial, if_neg, Pi.zero_apply]
        intro h
        have := congrArg (· i) h
        simp only [boxExp_apply] at this
        have := (b i).2
        omega
      rw [hrhs, map_zero, Ideal.Quotient.eq_zero_iff_mem]
      have : monomial d c = monomial (d - Finsupp.single i (q - 1)) c * X i ^ (q - 1) := by
        rw [X_pow_eq_monomial, monomial_mul, mul_one, tsub_add_cancel_of_le hle]
      rw [this]
      exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨i, rfl⟩)
  | add p p' hp hp' =>
    rw [map_add, hp, hp', ← map_add]
    rfl

/-- **Setting** of `q_free_Z.md` (auxiliary): the ideal `(y_i^{q−1})` of `ℤ[y]` is sent into the
ideal `(y_i^{q−1})` of `F[y]` by the ring map `ℤ → F`. -/
theorem map_mem_powIdeal (F : Type*) [Field F] {m : ℕ} {p : MvPolynomial (Fin m) ℤ}
    (hp : p ∈ powIdealZ q m) :
    MvPolynomial.map (Int.castRingHom F) p ∈ Peel.powIdeal F q m := by
  have : (powIdealZ q m).map (MvPolynomial.map (Int.castRingHom F)) = Peel.powIdeal F q m := by
    rw [powIdealZ, Ideal.map_span, ← Set.range_comp]
    congr 1
    ext
    simp [Function.comp_apply]
  exact this ▸ Ideal.mem_map_of_mem _ hp

/-- **Setting** of `q_free_Z.md`: `C_{m,ℤ}` is a free abelian group with basis the box monomials
`y^a`, `a ∈ B_m`, i.e. `w ↦ Σ_a w_a y^a` is a bijection `ℤ^{B_m} → C_{m,ℤ}` (for `q ≥ 2`).
Injectivity is read over `ℚ`, where the box monomials form a basis (`q_every_field.md`). -/
theorem boxToCZ_bijective (hq : 2 ≤ q) (m : ℕ) : Function.Bijective (boxToCZ q m) := by
  classical
  refine ⟨?_, ?_⟩
  · rw [← LinearMap.ker_eq_bot, LinearMap.ker_eq_bot']
    intro w hw
    set p : MvPolynomial (Fin m) ℤ := ∑ a, monomial (boxExp a) (w a) with hpdef
    have hcoeff : ∀ b, p.coeff (boxExp b) = w b := by
      intro b
      rw [hpdef, coeff_sum, Finset.sum_eq_single b]
      · rw [coeff_monomial, if_pos rfl]
      · intro a _ hab
        rw [coeff_monomial, if_neg]
        exact fun h => hab (boxExp_injective h)
      · simp
    have hmk : Ideal.Quotient.mk (powIdealZ q m) p = 0 := by
      rw [mk_eq_boxToCZ]
      simpa only [hcoeff] using hw
    have hQ := map_mem_powIdeal ℚ (Ideal.Quotient.eq_zero_iff_mem.1 hmk)
    rw [← Ideal.Quotient.eq_zero_iff_mem, mk_eq_boxToC] at hQ
    have h0 := (boxToC_bijective (F := ℚ) hq m).1 (hQ.trans (map_zero _).symm)
    funext b
    have := congrFun h0 b
    simp only [coeff_map, hcoeff, eq_intCast, Pi.zero_apply, Int.cast_eq_zero] at this
    exact this
  · intro x
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
    exact ⟨_, (mk_eq_boxToCZ p).symm⟩

/-- **Proof of part (i)** of the Theorem of `q_free_Z.md` (auxiliary): the element of `C_{m,ℤ}`
with coordinates `v_{a,G}` is the class of `y^a · G`. -/
theorem boxToCZ_intVec {m : ℕ} (a : Box q m) (G : MvPolynomial (Fin m) ℤ) :
    boxToCZ q m (intVec q a G) = boxMonoZ q a * Ideal.Quotient.mk _ G := by
  rw [boxMonoZ, ← map_mul, mk_eq_boxToCZ]
  rfl

/-- **Part (i)** of the Theorem of `q_free_Z.md`: as a subgroup of `C_{m,ℤ}`, `V_{Λ,ℤ}` is the
subgroup generated by the vectors `v_{a,G}`, i.e. by the classes of `y^a · G`, `a ∈ B_m`, `G` a
tight-pattern product of an element of `Λ` (read in the box-monomial coordinates). -/
theorem VZ_eq_span_intVec (m : ℕ) (Λ : Set Partition) :
    (VZ q m Λ).restrictScalars ℤ =
      Submodule.span ℤ (Set.range fun x : Box q m × GZ q m Λ =>
        boxToCZ q m (intVec q x.1 x.2)) := by
  have htop : Submodule.span ℤ (Set.range (boxMonoZ q (m := m))) = ⊤ := by
    rw [← Fintype.range_linearCombination, LinearMap.range_eq_top]
    intro x
    obtain ⟨p, rfl⟩ := Ideal.Quotient.mk_surjective x
    exact ⟨_, (mk_eq_boxToCZ p).symm⟩
  have hV : VZ q m Λ = Submodule.span (CZ q m) {g | ∃ lam ∈ Λ,
      ∃ Tp : TightPattern lam (Finset.univ : Finset (Fin m)),
        Ideal.Quotient.mk (powIdealZ q m) (prodPR ℤ q Tp) = g} := rfl
  rw [hV, ← Submodule.span_smul_of_span_eq_top htop]
  congr 1
  ext x
  simp only [Set.mem_smul, Set.mem_range, smul_eq_mul]
  constructor
  · rintro ⟨_, ⟨a, rfl⟩, _, ⟨lam, hlam, Tp, rfl⟩, rfl⟩
    exact ⟨(a, ⟨prodPR ℤ q Tp, lam, hlam, Tp, rfl⟩), boxToCZ_intVec _ _⟩
  · rintro ⟨⟨a, G, lam, hlam, Tp, hG⟩, rfl⟩
    exact ⟨_, ⟨a, rfl⟩, _, ⟨lam, hlam, Tp, rfl⟩, by rw [boxToCZ_intVec, hG]⟩

end FreeZ

end
