module

public import RequestProject.EveryField.Rank

/-!
# The Lemma (integer matrices) of `q_free_Z.md`

Formalization of the **Lemma (integer matrices)** of `q_free_Z.md`: if `L ⊆ ℤ^n` is a subgroup
whose image in `F_p^n` has, for every prime `p`, the same dimension `r` as the `ℚ`-span of `L` in
`ℚ^n`, then `ℤ^n / L` is a free abelian group of rank `n − r`.

Conventions:
* `ℤ^n` is `ι → ℤ` for a finite type `ι` with `n = |ι|` (the case `ι = Fin n` is
  `quotient_free_of_finrank_image_fin`); subgroups of `ℤ^n` are `ℤ`-submodules.
* The map `ℤ^n → F^n` (for a field `F`) is `EveryField.castLin F ι` of `q_every_field.md`; the
  image of `L` is `L.map (castLin F ι)` and its `F`-dimension is the `F`-dimension of its `F`-span
  (for `F = F_p = ZMod p` the image is already an `F_p`-subspace).
* As in the file, the proof uses the Smith normal form (`Submodule.smithNormalForm`).
-/

@[expose] public section

namespace FreeZ

open EveryField

variable {ι : Type*} [Fintype ι]

omit [Fintype ι] in
/-- **Proof of the Lemma (integer matrices)** of `q_free_Z.md` (auxiliary): the `F`-span of the
image in `F^n` of the subgroup generated by a set `s ⊆ ℤ^n` is the `F`-span of the image of `s`. -/
theorem span_map_castLin_span (F : Type*) [Field F] (s : Set (ι → ℤ)) :
    Submodule.span F (((Submodule.span ℤ s).map (castLin F ι) : Submodule ℤ (ι → F)) :
      Set (ι → F)) = Submodule.span F (castLin F ι '' s) := by
  rw [Submodule.map_span, Submodule.span_span_of_tower]

/-- **Proof of the Lemma (integer matrices)** of `q_free_Z.md` (auxiliary): an integer `d` whose
image in `F_p` is non-zero for every prime `p` is `±1`. -/
theorem isUnit_of_intCast_ne_zero {d : ℤ} (h : ∀ (p : ℕ) [Fact p.Prime], (d : ZMod p) ≠ 0) :
    IsUnit d := by
  rw [Int.isUnit_iff_natAbs_eq]
  by_contra hne
  obtain ⟨p, hp, hdvd⟩ := Nat.exists_prime_and_dvd hne
  haveI := Fact.mk hp
  exact h p ((ZMod.intCast_zmod_eq_zero_iff_dvd d p).2 (Int.natCast_dvd.2 hdvd))

/-- **Lemma (integer matrices)** of `q_free_Z.md`: let `L ⊆ ℤ^n` be a subgroup (here
`ℤ^n = ι → ℤ`, `n = |ι|`) and `r := dim_ℚ (ℚ ⊗ L)`, the `ℚ`-dimension of the `ℚ`-span of `L` in
`ℚ^n`.  Suppose that for every prime `p` the image of `L` in `F_p^n` has `F_p`-dimension `r`.
Then `ℤ^n / L` is a free abelian group of rank `n − r`.

Proof as in the file: take a Smith normal form `d_1 e_1, …, d_s e_s` of `L` (a basis
`e_1, …, e_n` of `ℤ^n`); then `s = r`, the image of `L` in `F_p^n` is spanned by the images of
the `d_i e_i`, so the hypothesis forces `p ∤ d_i` for every prime `p`, i.e. every `d_i = ±1`, and
then `ℤ^n / L` is torsion free (hence free) of rank `n − s`. -/
theorem quotient_free_of_finrank_image (L : Submodule ℤ (ι → ℤ))
    (h : ∀ (p : ℕ) [Fact p.Prime],
      Module.finrank (ZMod p)
          (Submodule.span (ZMod p) ((L.map (castLin (ZMod p) ι) : Submodule ℤ (ι → ZMod p)) :
            Set (ι → ZMod p))) =
        Module.finrank ℚ
          (Submodule.span ℚ ((L.map (castLin ℚ ι) : Submodule ℤ (ι → ℚ)) : Set (ι → ℚ)))) :
    Module.Free ℤ ((ι → ℤ) ⧸ L) ∧
      Module.finrank ℤ ((ι → ℤ) ⧸ L) = Fintype.card ι -
        Module.finrank ℚ
          (Submodule.span ℚ ((L.map (castLin ℚ ι) : Submodule ℤ (ι → ℚ)) : Set (ι → ℚ))) := by
  classical
  obtain ⟨n, snf⟩ := L.smithNormalForm (Pi.basisFun ℤ ι)
  set W : Fin n → ι → ℤ := fun i => (snf.bN i : ι → ℤ) with hW
  have hWL : Submodule.span ℤ (Set.range W) = L := by
    rw [show W = L.subtype ∘ snf.bN from rfl, Set.range_comp, Submodule.span_image,
      snf.bN.span_eq, Submodule.map_subtype_top]
  have hWind : LinearIndependent ℤ W :=
    snf.bN.linearIndependent.map' L.subtype (Submodule.ker_subtype _)
  have hspan : ∀ (F : Type) [Field F], Submodule.span F
      ((L.map (castLin F ι) : Submodule ℤ (ι → F)) : Set (ι → F)) =
        Submodule.span F (Set.range (castLin F ι ∘ W)) := by
    intro F _
    rw [← hWL, span_map_castLin_span, Set.range_comp]
  -- `r = s`
  have hr : Module.finrank ℚ
      (Submodule.span ℚ ((L.map (castLin ℚ ι) : Submodule ℤ (ι → ℚ)) : Set (ι → ℚ))) = n := by
    rw [hspan, finrank_span_eq_card (linearIndependent_castLin hWind), Fintype.card_fin]
  rw [hr]
  -- every `d_i` is a unit
  have hunit : ∀ i, IsUnit (snf.a i) := by
    intro i
    refine isUnit_of_intCast_ne_zero fun p _ => ?_
    have hind : LinearIndependent (ZMod p) (castLin (ZMod p) ι ∘ W) := by
      rw [linearIndependent_iff_card_eq_finrank_span, Set.finrank, ← hspan, h, hr, Fintype.card_fin]
    intro hp0
    apply hind.ne_zero i
    simp only [Function.comp_apply, W, snf.snf, map_zsmul, ← Int.cast_smul_eq_zsmul (ZMod p),
      hp0, zero_smul]
  -- membership in `L` via the coordinates in `e_1, …, e_n`
  have hmem : ∀ x : ι → ℤ, (∀ j, j ∉ Set.range snf.f → snf.bM.repr x j = 0) → x ∈ L := by
    intro x hx
    rw [← snf.bM.sum_repr x]
    refine Submodule.sum_mem _ fun j _ => ?_
    by_cases hj : j ∈ Set.range snf.f
    · obtain ⟨i, rfl⟩ := hj
      refine Submodule.smul_mem _ _ ?_
      obtain ⟨u, hu⟩ := hunit i
      have : snf.bM (snf.f i) = (↑u⁻¹ : ℤ) • (snf.bN i : ι → ℤ) := by
        rw [snf.snf, ← hu, smul_smul, Units.inv_mul, one_smul]
      rw [this]
      exact Submodule.smul_mem _ _ (snf.bN i).2
    · rw [hx j hj, zero_smul]
      exact Submodule.zero_mem _
  have htf : Module.IsTorsionFree ℤ ((ι → ℤ) ⧸ L) := by
    refine Module.IsTorsionFree.of_smul_eq_zero fun k y hky => ?_
    obtain ⟨x, rfl⟩ := Submodule.Quotient.mk_surjective L y
    rw [← Submodule.Quotient.mk_smul, Submodule.Quotient.mk_eq_zero] at hky
    by_cases hk : k = 0
    · exact Or.inl hk
    refine Or.inr ((Submodule.Quotient.mk_eq_zero L).2 (hmem x fun j hj => ?_))
    have h0 := snf.repr_eq_zero_of_notMem_range ⟨k • x, hky⟩ hj
    simp only [map_zsmul, Finsupp.smul_apply, smul_eq_mul] at h0
    exact (mul_eq_zero.1 h0).resolve_left hk
  refine ⟨inferInstance, ?_⟩
  have hadd := Submodule.finrank_quotient_add_finrank L
  rw [Module.finrank_eq_card_basis snf.bN, Fintype.card_fin,
    Module.finrank_fintype_fun_eq_card] at hadd
  omega

/-- **Lemma (integer matrices)** of `q_free_Z.md`, literally for `ℤ^n = Fin n → ℤ`: if the image
of a subgroup `L ⊆ ℤ^n` in `F_p^n` has dimension `r := dim_ℚ (ℚ ⊗ L)` for every prime `p`, then
`ℤ^n / L` is a free abelian group of rank `n − r`. -/
theorem quotient_free_of_finrank_image_fin {n : ℕ} (L : Submodule ℤ (Fin n → ℤ))
    (h : ∀ (p : ℕ) [Fact p.Prime],
      Module.finrank (ZMod p)
          (Submodule.span (ZMod p) ((L.map (castLin (ZMod p) (Fin n)) :
            Submodule ℤ (Fin n → ZMod p)) : Set (Fin n → ZMod p))) =
        Module.finrank ℚ
          (Submodule.span ℚ ((L.map (castLin ℚ (Fin n)) : Submodule ℤ (Fin n → ℚ)) :
            Set (Fin n → ℚ)))) :
    Module.Free ℤ ((Fin n → ℤ) ⧸ L) ∧
      Module.finrank ℤ ((Fin n → ℤ) ⧸ L) = n -
        Module.finrank ℚ
          (Submodule.span ℚ ((L.map (castLin ℚ (Fin n)) : Submodule ℤ (Fin n → ℚ)) :
            Set (Fin n → ℚ))) := by
  simpa using quotient_free_of_finrank_image L h

end FreeZ

end
