module

public import RequestProject.FreeZ.Lemma
public import RequestProject.FreeZ.Defs
public import RequestProject.EveryField.Main

/-!
# Part (ii) of the Theorem of `q_free_Z.md`: freeness over `ℤ`

Formalization of **part (ii)** of the Theorem of `q_free_Z.md`: for odd `q ≥ 3`, every `m` and
every down-set `Λ` of `Par_m`, `C_{m,ℤ} / V_{Λ,ℤ}` is a free abelian group of rank
`(q − 1)^m − |Z_Λ|`.

As in `q_every_field.md`, `Z_Λ` is `S.ZLam m Λ` for a point set
`S : Fibres.FibreSetting T ((q - 1) / 2)` (any finite set `T` with a fixed-point-free involution
and `|T| = 2h`), and "down-set of `Par_m`" is `Lifts.IsDownSetPar ((q - 1) / 2) m Λ`.  "Free
abelian group of rank `k`" is `Module.Free ℤ` together with `Module.finrank ℤ = k`.
-/

@[expose] public section

namespace FreeZ

open ChainLemma Fibres Tight Lifts EveryField

set_option synthInstance.maxHeartbeats 200000

variable {q : ℕ}

/-- **Proof of part (ii)** of the Theorem of `q_free_Z.md` (auxiliary): the identification
`ℤ^n ≅ C_{m,ℤ}`, `n = |B_m|`, by the monomial basis (`q ≥ 2`). -/
noncomputable def boxEquivZ (hq : 2 ≤ q) (m : ℕ) : (Box q m → ℤ) ≃ₗ[ℤ] CZ q m :=
  LinearEquiv.ofBijective (boxToCZ q m) (boxToCZ_bijective hq m)

/-- **Proof of part (ii)** of the Theorem of `q_free_Z.md` (auxiliary): under the identification
`ℤ^n ≅ C_{m,ℤ}`, the subgroup `L ⊆ ℤ^n` generated by the rows `v_{a,G}` of the matrix `A` is
sent onto `V_{Λ,ℤ}` (part (i)). -/
theorem map_rowLattice_eq_VZ (hq : 2 ≤ q) (m : ℕ) (Λ : Set Partition) :
    (rowLattice (intMat q m Λ)).map (boxEquivZ hq m : (Box q m → ℤ) →ₗ[ℤ] CZ q m) =
      (VZ q m Λ).restrictScalars ℤ := by
  rw [VZ_eq_span_intVec, rowLattice, Submodule.map_span, ← Set.range_comp]
  rfl

/-- **Proof of part (ii)** of the Theorem of `q_free_Z.md` (auxiliary): for every field `F`, the
`F`-span of the image of `L` in `F^n` has dimension `rank_F(A) = dim_F V_Λ(F)`
(part (i) of `q_every_field.md`). -/
theorem finrank_span_map_rowLattice (F : Type*) [Field F] (hq : 2 ≤ q) (m : ℕ)
    (Λ : Set Partition) :
    Module.finrank F (Submodule.span F (((rowLattice (intMat q m Λ)).map
      (castLin F (Box q m)) : Submodule ℤ (Box q m → F)) : Set (Box q m → F))) =
        Module.finrank F ((VLamAll F q m Λ).restrictScalars F) := by
  rw [finrank_VLamAll_eq_rankOver hq, rankOver, Matrix.rank_eq_finrank_span_row, rowLattice,
    span_map_castLin_span, ← Set.range_comp]
  rfl

variable {T : Type*} [Fintype T] [DecidableEq T]

/-- **Part (ii)** of the Theorem of `q_free_Z.md`: for odd `q ≥ 3`, every `m ≥ 0` and every
down-set `Λ` of `Par_m`, `C_{m,ℤ} / V_{Λ,ℤ}` is a free abelian group of rank
`(q − 1)^m − |Z_Λ|` (with `Z_Λ` computed with any point set `S` on a finite set `T`).

Proof as in the file: identify `C_{m,ℤ}` with `ℤ^n`, `n = (q − 1)^m`, by the monomial basis, and
let `L := V_{Λ,ℤ}`, the subgroup generated by the `v_{a,G}` (part (i)).  For every field `F` the
image of `L` spans `V_Λ(F)`, of dimension `|Z_Λ|` (parts (i) and (iv) of `q_every_field.md`);
with `F = ℚ` and `F = F_p` the Lemma (integer matrices) applies. -/
theorem free_quotient_VZ (hq : 3 ≤ q) (hodd : Odd q) (S : FibreSetting T ((q - 1) / 2)) (m : ℕ)
    (Λ : Set Partition) (hΛ : IsDownSetPar ((q - 1) / 2) m Λ) :
    Module.Free ℤ (CZ q m ⧸ VZ q m Λ) ∧
      Module.finrank ℤ (CZ q m ⧸ VZ q m Λ) = (q - 1) ^ m - (S.ZLam m Λ).card := by
  have hZ : ∀ (F : Type) [Field F], Module.finrank F (Submodule.span F
      (((rowLattice (intMat q m Λ)).map (castLin F (Box q m)) : Submodule ℤ (Box q m → F)) :
        Set (Box q m → F))) = (S.ZLam m Λ).card := fun F _ => by
    rw [finrank_span_map_rowLattice F (by omega), finrank_VLamAll_eq_card_ZLam F hq hodd S m Λ hΛ]
  obtain ⟨hfree, hrank⟩ := quotient_free_of_finrank_image (rowLattice (intMat q m Λ))
    (fun p _ => by rw [hZ, hZ])
  rw [hZ, Fintype.card_fun, Fintype.card_fin, Fintype.card_fin] at hrank
  let e : ((Box q m → ℤ) ⧸ rowLattice (intMat q m Λ)) ≃ₗ[ℤ] (CZ q m ⧸ VZ q m Λ) :=
    (Submodule.Quotient.equiv _ _ (boxEquivZ (by omega) m) (map_rowLattice_eq_VZ _ m Λ)).trans
      (Submodule.Quotient.restrictScalarsEquiv ℤ (VZ q m Λ))
  exact ⟨Module.Free.of_equiv e, e.finrank_eq.symm.trans hrank⟩

end FreeZ

end
