"""Shared tools for the cold audit of 'The Chaise Longue Theorem'.
Everything is over F_3 unless stated. Written from the paper's definitions only.
"""
import itertools, sys, time
from collections import defaultdict
import numpy as np
import flint

P = 3

def matchings(n):
    """All perfect matchings of {0..n-1} as sorted tuples of pairs (a<b), pairs sorted by a."""
    idx = list(range(n))
    def rec(rest):
        if not rest:
            yield ()
            return
        a = rest[0]
        for i in range(1, len(rest)):
            b = rest[i]
            for m in rec(rest[1:i] + rest[i+1:]):
                yield ((a, b),) + m
    return list(rec(idx))

def poly_mul(f, g, e):
    """multiply dicts exponent-tuple->coeff mod 3, truncating exponents >= e (box (y_i^e))."""
    h = defaultdict(int)
    for ea, ca in f.items():
        for eb, cb in g.items():
            ex = tuple(x + y for x, y in zip(ea, eb))
            if max(ex) >= e:
                continue
            h[ex] = (h[ex] + ca * cb) % P
    return {k: v for k, v in h.items() if v}

def D_poly(a, b, q, nvars, e):
    """D(y_a, y_b) = sum_{u=0}^{q-2} (-1)^u y_a^u y_b^{q-2-u}, truncated in box y_i^e."""
    f = {}
    for u in range(q - 1):
        ex = [0] * nvars
        ex[a] = u
        ex[b] = q - 2 - u
        if max(ex) >= e:
            continue
        f[tuple(ex)] = (-1) ** u % P
    return f

def D_J(J, q, nvars, e):
    """product over the pairs of J avoiding index 0 of D(y_{a-1}, y_{b-1}); variables are y_1..y_{2k+1} -> 0..2k."""
    f = {tuple([0] * nvars): 1}
    for (a, b) in J:
        if a == 0:
            continue
        f = poly_mul(f, D_poly(a - 1, b - 1, q, nvars, e), e)
    return f

def monomials_of_degree(nvars, e, d):
    """all exponent tuples in [0,e-1]^nvars of total degree d"""
    out = []
    def rec(i, rem, cur):
        if i == nvars - 1:
            if rem < e:
                out.append(tuple(cur + [rem]))
            return
        for x in range(min(e - 1, rem) + 1):
            rec(i + 1, rem - x, cur + [x])
    rec(0, d, [])
    return out

def rank_mod3(rows, ncols):
    """rows: list of dict col->coeff. returns rank over F_3 via flint nmod_mat"""
    if not rows or ncols == 0:
        return 0
    M = flint.nmod_mat(len(rows), ncols, P)
    for i, r in enumerate(rows):
        for c, v in r.items():
            M[i, c] = v % P
    return M.rank()

def graded_ideal_dims(gens, nvars, e, verbose=False, maxdeg=None):
    """dims of the graded pieces of the ideal generated by homogeneous gens (dicts) in the box ring.
    returns dict degree -> dim."""
    degs = {}
    for g in gens:
        dg = {sum(k) for k in g}
        assert len(dg) == 1, "generators must be homogeneous"
        degs.setdefault(dg.pop(), []).append(g)
    top = nvars * (e - 1)
    res = {}
    for d in range(min(degs), top + 1):
        if maxdeg is not None and d > maxdeg:
            break
        cols = monomials_of_degree(nvars, e, d)
        colidx = {m: i for i, m in enumerate(cols)}
        rows = []
        for dg, gl in degs.items():
            if dg > d:
                continue
            for beta in monomials_of_degree(nvars, e, d - dg):
                for g in gl:
                    r = {}
                    for ex, c in g.items():
                        ex2 = tuple(x + y for x, y in zip(ex, beta))
                        if max(ex2) >= e:
                            continue
                        r[colidx[ex2]] = c
                    if r:
                        rows.append(r)
        t = time.time()
        rk = rank_mod3(rows, len(cols))
        res[d] = rk
        if verbose:
            print(f"  deg {d}: rows {len(rows)} cols {len(cols)} rank {rk}  ({time.time()-t:.1f}s)", flush=True)
    return res

def Q(k, q):
    """Q_k(q) = N! [x^N] I_0(2x)^h, N=2k+2, h=(q-1)/2, exact integer arithmetic"""
    from fractions import Fraction
    from math import factorial
    N = 2 * k + 2
    h = (q - 1) // 2
    # I_0(2x) = sum x^{2b}/(b!)^2 ; only even powers; compute power h up to x^N
    ser = [Fraction(0)] * (N + 1)
    ser[0] = Fraction(1)
    base = [Fraction(0)] * (N + 1)
    for b in range(N // 2 + 1):
        base[2 * b] = Fraction(1, factorial(b) ** 2)
    for _ in range(h):
        new = [Fraction(0)] * (N + 1)
        for i in range(N + 1):
            if ser[i] == 0:
                continue
            for j in range(N + 1 - i):
                new[i + j] += ser[i] * base[j]
        ser = new
    val = ser[N] * factorial(N)
    assert val.denominator == 1
    return int(val)

def gamma_count(k, q, K):
    """|Gamma_K| computed on T=F_q^x with negation: y in T^{2k+1} such that for some J in K,
    y_{k_i} = -y_{j_i} for the pairs avoiding 0. T is modelled as {+-1..+-h} (only the involution matters)."""
    h = (q - 1) // 2
    T = [i for i in range(1, h + 1)] + [-i for i in range(1, h + 1)]
    n = 2 * k + 1
    cnt = 0
    pairsets = [[(a - 1, b - 1) for (a, b) in J if a != 0] for J in K]
    for y in itertools.product(T, repeat=n):
        for ps in pairsets:
            if all(y[a] + y[b] == 0 for a, b in ps):
                cnt += 1
                break
    return cnt
