# cold_T3: the dictionary of Remark 8.4(1) / Proposition 1.2 of the note.
#  (a) the t-coefficients of E(t)/E(-t) - 1 generate the ideal (e_j : j odd) modulo the box (char != 2);
#  (b) prod_x f(x) - 1 lies in (e_odd) for random f in Z;
#  (c) finite-field caveat: over F_3 the F_3-points of Z do NOT generate (e_odd)  (q=3, n=3,4; q=5, n=3);
#  (d) even q, odd n: dimension against walks 0 -> eps_1 (Remark 8.4(6), problem 6).
import itertools, random, numpy as np
from cold_lib import *

def red(f, p):
    return {k: v % p for k, v in f.items() if v % p}

def coeffs_cayley(N, r, p):
    """homogeneous components c_i (i>=1) of E(t)/E(-t) - 1 in the box ring over F_p."""
    top = N * (r - 1)
    e = [red(elem_sym(N, j, r), p) if j <= N else {} for j in range(0, top + 1)]
    e[0] = one(N)
    a = [one(N)]                       # 1/E(-t) = sum a_i t^i
    for i in range(1, top + 1):
        acc = {}
        for j in range(1, min(i, N) + 1):
            acc = padd(acc, pmul(e[j], a[i - j], r), -((-1) ** j))
        a.append(red(acc, p))
    c = []
    for i in range(1, top + 1):
        acc = {}
        for j in range(0, min(i, N) + 1):
            acc = padd(acc, pmul(e[j], a[i - j], r), 1)
        c.append(red(acc, p))
    return c

def graded_compare(box, gensA, gensB, p):
    """returns (dimA, dimB, dimA+B) of the two homogeneous ideals"""
    tA = tB = tU = 0
    for d in range(box.top + 1):
        RA = ideal_rows(box, gensA, d, p); RB = ideal_rows(box, gensB, d, p)
        tA += rank_mod(RA, p) if len(RA) else 0
        tB += rank_mod(RB, p) if len(RB) else 0
        U = np.vstack([RA, RB])
        tU += rank_mod(U, p) if len(U) else 0
    return tA, tB, tU

def power_series_inverse(a, r, p):
    # a: list of coefficients mod p of length r with a[0] invertible
    inv0 = pow(a[0], -1, p)
    b = [inv0] + [0] * (r - 1)
    for i in range(1, r):
        s = sum(a[j] * b[i - j] for j in range(1, i + 1)) % p
        b[i] = (-s * inv0) % p
    return b

def Z_element(r, p, alphas):
    """f = (1+a)/(1-a) mod x^r, a = sum alphas[j] x^(2j+1)"""
    a = [0] * r
    for j, al in enumerate(alphas):
        if 2 * j + 1 < r: a[2 * j + 1] = al % p
    num = a[:]; num[0] = (num[0] + 1) % p
    den = [(-x) % p for x in a]; den[0] = (den[0] + 1) % p
    dinv = power_series_inverse(den, r, p)
    f = [sum(num[j] * dinv[i - j] for j in range(i + 1)) % p for i in range(r)]
    # sanity: f(x) f(-x) = 1
    g = [(f[i] * ((-1) ** i)) % p for i in range(r)]
    prod = [sum(f[j] * g[i - j] for j in range(i + 1)) % p for i in range(r)]
    assert prod[0] == 1 and all(v == 0 for v in prod[1:]), "not an isometry"
    return f

def action_minus_one(N, r, p, f):
    u = one(N)
    for i in range(N):
        fi = {}
        for a, c in enumerate(f):
            if c:
                e = [0] * N; e[i] = a; fi[tuple(e)] = c
        u = red(pmul(u, fi, r), p)
    return red(padd(u, one(N), -1), p)

print("== (a) coefficients of E(t)/E(-t)-1 versus (e_odd), modulo the box")
for (r, N) in [(3, 3), (3, 4), (3, 5), (5, 3), (5, 4), (7, 3), (4, 3), (4, 4), (2, 5), (6, 3)]:
    box = Box(N, r)
    for p in [3, 5, 7, 1000003, 2]:
        c = [g for g in coeffs_cayley(N, r, p) if g]
        eodd = [red(elem_sym(N, j, r), p) for j in range(1, N + 1, 2)]
        tA, tB, tU = graded_compare(box, c, eodd, p)
        print(f"  r={r} n={N} p={p}: dim ideal(coeffs)={tA}  dim (e_odd)={tB}  dim sum={tU}  equal: {tA==tB==tU}", flush=True)

print("== (b) random elements of Z: prod f(x) - 1 in (e_odd)?")
random.seed(20261001)
for (r, N) in [(3, 4), (5, 3), (5, 4), (7, 3), (4, 4), (6, 3)]:
    box = Box(N, r)
    for p in [3, 5, 1000003]:
        eodd = [red(elem_sym(N, j, r), p) for j in range(1, N + 1, 2)]
        ok = True
        for trial in range(6):
            al = [random.randrange(p) for _ in range(r)]
            f = Z_element(r, p, al)
            u = action_minus_one(N, r, p, f)
            parts = homog_parts(u)
            for d, comp in parts.items():
                R = ideal_rows(box, eodd, d, p)
                rk = rank_mod(R, p) if len(R) else 0
                rk2 = rank_mod(np.vstack([R, vec(box, d, comp, p)[None, :]]), p)
                if rk2 != rk: ok = False
        print(f"  r={r} n={N} p={p}: 6 random f in Z, all in (e_odd): {ok}", flush=True)

print("== (c) finite field F_3: ideal generated by {prod f(x) - 1 : f in Z(F_3)} against (e_odd)")
for (r, N) in [(3, 3), (3, 4), (5, 3)]:
    p = 3
    allm = list(itertools.product(range(r), repeat=N)); gi = {m: i for i, m in enumerate(allm)}
    nodd = len(range(1, r, 2))
    gens = []
    for al in itertools.product(range(p), repeat=nodd):
        f = Z_element(r, p, list(al))
        u = action_minus_one(N, r, p, f)
        if u: gens.append(u)
    rows = []
    for g in gens:
        for m in allm:
            h = red(pmul(g, {m: 1}, r), p)
            if h:
                v = np.zeros(len(allm), dtype=np.int64)
                for e, cc in h.items(): v[gi[e]] = cc
                rows.append(v)
    dimZ = rank_mod(np.array(rows), p)
    box = Box(N, r)
    eodd = [red(elem_sym(N, j, r), p) for j in range(1, N + 1, 2)]
    dimE = sum(span_rank_ideal(box, eodd, p).values())
    print(f"  r=q={r} n={N}: |Z(F_3)|={p**nodd}; dim of the ideal of Z(F_3)-coinvariants relations = {dimZ}; dim (e_odd) = {dimE}; "
          f"coinvariants of Z(F_3): {r**N-dimZ}; ring of Theorem A: {r**N-dimE}; equal: {dimZ==dimE}", flush=True)

print("== (d) even q: dim F[x]/((e_odd)+(x^q)) against walks (closed for even n; 0 -> eps_1 for odd n)")
for (r, N) in [(2, 3), (2, 4), (2, 5), (4, 3), (4, 4), (4, 5), (6, 3)]:
    box = Box(N, r); h = r // 2
    w = closed_walks(N, h, False) if N % 2 == 0 else walks_to(N, h, False, [1] + [0] * (h - 1))
    for p in [3, 5, 7, 1000003, 2]:
        eodd = [red(elem_sym(N, j, r), p) for j in range(1, N + 1, 2)]
        dimE = sum(span_rank_ideal(box, eodd, p).values())
        print(f"  q={r} n={N} p={p}: dim ring = {r**N-dimE}  walks = {w}  equal: {r**N-dimE==w}", flush=True)
print("FIN-OK")
