# cold_lib.py -- independent engine of the cold reader (not derived from generacion*.py)
# Graded linear algebra in the box ring C_r = F_p[x_0..x_{N-1}]/(x_i^r).
import itertools, sys
import numpy as np
from fractions import Fraction
from math import factorial

def monos_by_deg(N, r):
    out = {}
    for e in itertools.product(range(r), repeat=N):
        out.setdefault(sum(e), []).append(e)
    return out

class Box:
    def __init__(self, N, r):
        self.N, self.r = N, r
        self.mons = monos_by_deg(N, r)
        self.idx = {d: {m: i for i, m in enumerate(L)} for d, L in self.mons.items()}
        self.top = N * (r - 1)
    def dim(self, d):
        return len(self.mons.get(d, []))
    def total(self):
        return self.r ** self.N

def pmul(f, g, r):
    """product of two polynomials (dict exps->int) in the box ring (exponent >= r kills)."""
    out = {}
    for a, ca in f.items():
        for b, cb in g.items():
            e = tuple(x + y for x, y in zip(a, b))
            if max(e) >= r:
                continue
            out[e] = out.get(e, 0) + ca * cb
    return {k: v for k, v in out.items() if v != 0}

def padd(f, g, c=1):
    out = dict(f)
    for k, v in g.items():
        out[k] = out.get(k, 0) + c * v
    return {k: v for k, v in out.items() if v != 0}

def var(N, i):
    e = [0] * N; e[i] = 1
    return {tuple(e): 1}

def mono(e):
    return {tuple(e): 1}

def one(N):
    return {tuple([0] * N): 1}

def D_r(N, r, a, b):
    """sum_{u=0}^{r-1} (-1)^u x_a^u x_b^{r-1-u}"""
    out = {}
    for u in range(r):
        e = [0] * N; e[a] = u; e[b] = r - 1 - u
        out[tuple(e)] = (-1) ** u
    return out

def matchings(pts):
    pts = list(pts)
    if not pts:
        yield []
        return
    a = pts[0]
    for i in range(1, len(pts)):
        b = pts[i]
        rest = pts[1:i] + pts[i + 1:]
        for m in matchings(rest):
            yield [(a, b)] + m

def D_J(N, r, J):
    f = one(N)
    for (a, b) in J:
        f = pmul(f, D_r(N, r, a, b), r)
    return f

def elem_sym(N, j, r):
    out = {}
    for S in itertools.combinations(range(N), j):
        e = [0] * N
        for i in S: e[i] = 1
        if r > 1:
            out[tuple(e)] = 1
    return out

def rank_mod(M, p):
    M = np.array(M, dtype=np.int64) % p
    if M.size == 0:
        return 0
    rows, cols = M.shape
    rk = 0
    for c in range(cols):
        if rk == rows:
            break
        nz = np.nonzero(M[rk:, c])[0]
        if len(nz) == 0:
            continue
        piv = rk + nz[0]
        if piv != rk:
            M[[rk, piv]] = M[[piv, rk]]
        inv = pow(int(M[rk, c]), -1, p)
        M[rk] = (M[rk] * inv) % p
        below = rk + 1 + np.nonzero(M[rk + 1:, c])[0]
        if len(below):
            M[below] = (M[below] - np.outer(M[below, c], M[rk])) % p
        rk += 1
    return rk

def rref_mod(M, p):
    """full reduced row echelon form; returns (R, pivots)."""
    M = np.array(M, dtype=np.int64) % p
    rows, cols = M.shape
    rk = 0; piv = []
    for c in range(cols):
        if rk == rows:
            break
        nz = np.nonzero(M[rk:, c])[0]
        if len(nz) == 0:
            continue
        pv = rk + nz[0]
        if pv != rk:
            M[[rk, pv]] = M[[pv, rk]]
        inv = pow(int(M[rk, c]), -1, p)
        M[rk] = (M[rk] * inv) % p
        oth = np.nonzero(M[:, c])[0]
        oth = oth[oth != rk]
        if len(oth):
            M[oth] = (M[oth] - np.outer(M[oth, c], M[rk])) % p
        piv.append(c); rk += 1
    return M[:rk], piv

def nullspace_mod(M, p):
    """basis (rows) of {v : M v = 0} mod p."""
    M = np.array(M, dtype=np.int64) % p
    rows, cols = M.shape
    R, piv = rref_mod(M, p)
    free = [c for c in range(cols) if c not in set(piv)]
    out = np.zeros((len(free), cols), dtype=np.int64)
    for k, f in enumerate(free):
        out[k, f] = 1
        for i, pc in enumerate(piv):
            out[k, pc] = (-R[i, f]) % p
    return out

def vec(box, d, f, p):
    v = np.zeros(box.dim(d), dtype=np.int64)
    ix = box.idx.get(d, {})
    for e, c in f.items():
        v[ix[e]] = c % p
    return v

def homog_parts(f):
    out = {}
    for e, c in f.items():
        out.setdefault(sum(e), {})[e] = c
    return out

def span_rank_ideal(box, gens, p, mons_filter=None):
    """graded ranks of the ideal generated by homogeneous gens (list of dict polys) in the box ring.
    returns dict d -> rank.  mons_filter(e) restricts the multipliers (used only when justified)."""
    N, r = box.N, box.r
    res = {}
    for d in range(box.top + 1):
        rows = []
        for g in gens:
            if not g:
                continue
            dg = sum(next(iter(g)))
            if d - dg < 0:
                continue
            for m in box.mons.get(d - dg, []):
                if mons_filter is not None and not mons_filter(m):
                    continue
                h = pmul(g, {m: 1}, r)
                if h:
                    rows.append(vec(box, d, h, p))
        res[d] = rank_mod(np.array(rows), p) if rows else 0
    return res

def ideal_rows(box, gens, d, p):
    N, r = box.N, box.r
    rows = []
    for g in gens:
        if not g:
            continue
        dg = sum(next(iter(g)))
        if d - dg < 0:
            continue
        for m in box.mons.get(d - dg, []):
            h = pmul(g, {m: 1}, r)
            if h:
                rows.append(vec(box, d, h, p))
    if not rows:
        return np.zeros((0, box.dim(d)), dtype=np.int64)
    return np.array(rows)

# ---- counts ---------------------------------------------------------------
def series_I0(n):
    # I_0(2y) = sum y^{2b}/(b!)^2 up to degree n
    return [Fraction(1, factorial(i // 2) ** 2) if i % 2 == 0 else Fraction(0) for i in range(n + 1)]

def series_exp(n):
    return [Fraction(1, factorial(i)) for i in range(n + 1)]

def smul(a, b, n):
    c = [Fraction(0)] * (n + 1)
    for i, x in enumerate(a):
        if x == 0: continue
        for j, y in enumerate(b):
            if i + j > n: break
            c[i + j] += x * y
    return c

def closed_walks(n, h, loop):
    """n! [y^n] (e^y if loop) * I_0(2y)^h"""
    s = [Fraction(1)] + [Fraction(0)] * n
    if loop:
        s = smul(s, series_exp(n), n)
    for _ in range(h):
        s = smul(s, series_I0(n), n)
    v = s[n] * factorial(n)
    assert v.denominator == 1
    return int(v)

def walks_to(n, h, loop, target):
    """number of walks of length n on Z^h from 0 to target with steps +-e_i (and 0 if loop)."""
    from collections import Counter
    cur = Counter({tuple([0] * h): 1})
    steps = []
    for i in range(h):
        for s in (1, -1):
            e = [0] * h; e[i] = s; steps.append(tuple(e))
    if loop:
        steps.append(tuple([0] * h))
    for _ in range(n):
        nxt = Counter()
        for pnt, c in cur.items():
            for s in steps:
                nxt[tuple(a + b for a, b in zip(pnt, s))] += c
        cur = nxt
    return cur.get(tuple(target), 0)
