#!/usr/bin/env python3
"""
downset_bip_peel.py -- control for Proposition 7.5 (and the surrounding definitions of section
7.1-7.4) at one small cell, from the definitions only.

For every down-set Lambda of BPar_q(alpha,beta), peel w = x_1 and compute
  * V_Lambda (full ring, all degrees), its slices W_j(V) = {[w^j] f : f in V, deg_w f <= j}
  * the layers Lambda_i = {mu in BPar_q(alpha-1,beta) : F_Lambda(mu) > i}, with F_Lambda counted
    from the q options of section 7.3 (lines 579-582)
  * V_{Lambda_i} in R_{[alpha-1],[beta]} (the x-variables x_2..x_alpha relabelled x_1..x_{alpha-1})
and check
  (P3)   V_{Lambda_i} subset of W_{q-1-i}(V_Lambda)                 [Proposition 7.5]
  (low)  whether V_{Lambda_i} subset of W_{q-2-i}(V_Lambda)        [should FAIL for some (Lambda,i)]
plus cheap checks of the claims used around it:
  (P1)   |F(M')| = F_Lambda(shape(M')) for every tail M'          [section 7.3]
  (P2)   every Lambda_i is a down-set                              [Proposition 7.4]
  (7.1iii) dim V = sum_j dim W_j(V), (7.1iv) |Z_Lambda| = sum_i |Z_{Lambda_i}|.

usage: downset_bip_peel.py --cell ALPHA BETA Q
"""
import argparse
import itertools
import sys
import time

import numpy as np

sys.path.insert(0, __file__.rsplit("/", 1)[0])
from downset_bip_engine import *  # noqa


def full_basis(ring, gens, p):
    """RREF basis (int) of the ideal generated by gens in the whole ring (columns = all monomials)"""
    E = Echelon(p, ring.N)
    for g in gens:
        for idx in range(ring.N):
            mono = np.zeros(ring.N, dtype=np.int64)
            mono[idx] = 1
            E.add(ring.mul_poly(g, mono) % p)
    return E.basis_int(), E.piv


def slice_W(ring, Vbasis, p, j, w=0):
    """W_j(V) as a matrix over the monomials of R' = ring without variable w (index idx' with
    idx = e_w + q*idx' for w = 0).  V_{<=j}: reorder columns so that monomials with w-exponent > j
    come first; the RREF rows whose pivot lies outside that block form a basis of V_{<=j}."""
    q = ring.q
    assert w == 0
    wdeg = ring.w_degree(w)
    high = np.flatnonzero(wdeg > j)
    low = np.flatnonzero(wdeg <= j)
    order = np.concatenate([high, low])
    if Vbasis.shape[0] == 0:
        return np.zeros((0, ring.N // q), dtype=np.int64)
    # ONE batch, ordered pivoting: every basis row's pivot is then its leading entry in the
    # permuted column order, so rows with pivot in the low block vanish on the high block and
    # span exactly V_{<= j}
    E = Echelon(p, ring.N, batch=max(1, Vbasis.shape[0]), ordered=True)
    E.add(Vbasis[:, order])
    Bchk = E.basis_int()
    for r_, c_ in zip(Bchk, E.piv):
        assert np.flatnonzero(r_)[0] == c_, "pivot is not the leading entry"
    Bm = E.basis_int()
    rows_le = Bm[E.piv >= len(high)]              # basis of V_{<= j} (in permuted columns)
    # back to natural column order
    nat = np.zeros_like(rows_le)
    nat[:, order] = rows_le
    cols = np.flatnonzero(wdeg == j)               # monomials w^j * m',  idx = j + q*idx'
    W = nat[:, cols]                               # coefficient of w^j m', ordered by idx' = (idx - j)//q
    assert np.all((cols - j) % q == 0) and np.all(np.diff((cols - j) // q) == 1)
    return W


def contained(p, W, U):
    """is row-space(U) contained in row-space(W)?"""
    if U.shape[0] == 0:
        return True
    E = Echelon(p, W.shape[1])
    E.add(W)
    r = E.rank
    E.add(U)
    return E.rank == r


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cell", nargs=3, type=int, required=True)
    args = ap.parse_args()
    alpha, beta, q = args.cell
    p = min(f for f in range(2, q + 1) if q % f == 0)
    assert alpha >= 1
    T0 = time.time()
    print("peeling control at (alpha,beta,q) = (%d,%d,%d), p = %d, w = x_1, date %s" % (alpha, beta, q, p, now()))
    ring = BoxRing(alpha, beta, q)
    ringp = BoxRing(alpha - 1, beta, q)
    elems = bpar(alpha, beta, q)
    sub = bpar(alpha - 1, beta, q)
    dsets = all_downsets(elems)
    hist = shape_histogram(alpha, beta, q)
    histp = shape_histogram(alpha - 1, beta, q)
    print("BPar(alpha,beta): %s" % " ".join(fmt_pp(e) for e in elems))
    print("BPar(alpha-1,beta): %s" % " ".join(fmt_pp(e) for e in sub))
    print("%d down-sets" % len(dsets))

    # (P1) direct: for every tail M' (coordinates 2..alpha of xi, and eta), the fibre
    # F(M') = {u : (u, M') in Z_Lambda} depends only on shape(M') and equals F_Lambda(shape(M'))
    tails = list(itertools.product(range(q), repeat=alpha - 1 + beta))
    tail_shape = {M: shape(M[:alpha - 1], M[alpha - 1:]) for M in tails}
    n_bad_P1 = 0
    n_bad_P2 = 0
    n_bad_P3 = 0
    n_low_fail = 0
    n_low_hold = 0
    n_bad_71 = 0
    cache_sub = {}
    for k, mask in enumerate(dsets):
        L = mask_to_set(mask, elems)
        Lset = frozenset(L)
        lay, F = layers(Lset, alpha, beta, q)
        # (P1)
        for M in tails:
            fib = sum(1 for u in range(q) if shape((u,) + M[:alpha - 1], M[alpha - 1:]) in Lset)
            if fib != F[tail_shape[M]]:
                n_bad_P1 += 1
        # (P2)
        for i in range(q):
            Li = lay[i]
            for mu in Li:
                for nu in sub:
                    if bpar_le(nu, mu) and nu not in Li:
                        n_bad_P2 += 1
        # (7.1 iv)
        Z = size_Z(mask, elems, hist)
        Zlay = [sum(histp.get(mu, 0) for mu in lay[i]) for i in range(q)]
        if sum(Zlay) != Z:
            n_bad_71 += 1
        # V_Lambda and its slices
        gens = generators_of_downset(ring, L) if L else []
        Vb, _ = full_basis(ring, gens, p)
        dimV = Vb.shape[0]
        Ws = [slice_W(ring, Vb, p, j) for j in range(q)]
        dimW = [W.shape[0] for W in Ws]
        # W_j is a row space possibly with dependent rows: take ranks
        rW = []
        for W in Ws:
            E = Echelon(p, W.shape[1])
            E.add(W)
            rW.append(E.rank)
        if sum(rW) != dimV:
            n_bad_71 += 1
        # V_{Lambda_i}
        res = []
        for i in range(q):
            Li = tuple(sorted(lay[i]))
            if Li not in cache_sub:
                gsub = generators_of_downset(ringp, list(Li)) if Li else []
                cache_sub[Li] = full_basis(ringp, gsub, p)[0]
            U = cache_sub[Li]
            j = q - 1 - i
            ok = contained(p, Ws[j], U)
            if not ok:
                n_bad_P3 += 1
            if j - 1 >= 0:
                low = contained(p, Ws[j - 1], U)
            else:
                low = (U.shape[0] == 0)      # W_{-1} := 0
            if low:
                n_low_hold += 1
            else:
                n_low_fail += 1
            res.append("i=%d: |L_i|=%d dimV_{L_i}=%d W_%d rank=%d P3:%s lower(W_%d):%s" % (
                i, len(Li), U.shape[0], j, rW[j], "OK" if ok else "FAIL", j - 1,
                "contained" if low else "not-contained"))
        print("  #%2d Lambda={%s} |Z|=%d dimV=%d slices rank(W_j)=%s sum=%d | layers |Z_{L_i}|=%s sum=%d" % (
            k, " ".join(fmt_pp(l) for l in L), Z, dimV, rW, sum(rW), Zlay, sum(Zlay)))
        for r in res:
            print("       " + r)
    print()
    print("SUMMARY cell=(%d,%d,%d): P1 violations=%d, P2 violations=%d, P3 (V_{L_i} in W_{q-1-i}) violations=%d, "
          "lowered slice W_{q-2-i}: contained in %d cases, NOT contained in %d cases, Lemma7.1(iii/iv) violations=%d, %.1fs" % (
              alpha, beta, q, n_bad_P1, n_bad_P2, n_bad_P3, n_low_hold, n_low_fail, n_bad_71, time.time() - T0))


if __name__ == "__main__":
    main()
