#!/usr/bin/env python3
"""
fable7_hyp_test.py -- two extra probes of Prop. 7.5 (§7.5) that the cells (2,1,3),(2,2,3),(2,1,5) cannot reach.
Reuses the definitions of fable7_prop75_test.py (same directory) with a numpy RREF mod p.

(A) case (alpha) with j0 = 2, i.e. S = B^+_{c*} non-empty: cell (4,1,3) over F_3, all down-sets of BPar_3(4,1)
    (the down-set generated by ((2,2),(1)) contains ((2,2),(1)) but not ((3,1),(1)); the tail ((2,1),(1)) then has
    j0 = 2, c* = 2, |S| = 1, slice 1).  Prediction: every construction succeeds, every layer containment holds,
    dim V = |Z| for every down-set over F_3 (as in the smaller cells), lowered slice fails at every i where the
    layer size strictly drops.
(B) the binomial hypothesis: cell (1,3,5), Lambda = {(∅,(1,1))}, tail mu = (∅,(1,1,1)) has Phi = r = 3, and the
    construction (gamma) has top coefficient C(4,2)·G = 6·G.  Over F_5: 6 ≠ 0, everything must hold (theorem).
    Over F_3: 6 = 0, the construction gives top coefficient 0 -> reported as a construction failure; we then test
    whether the containment V_{Lambda_2} ⊆ W_2(V_Lambda) holds anyway.  Prediction over F_3: unknown (this is
    outside the hypotheses of §7); recorded as data.
Predicted cost: < 40 s, < 100 MB.
"""
import sys, os, time
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fable7_prop75_test as T

t0 = time.time()

def rref_np(rows, ncols, K, col_order=None):
    p = K.p
    assert p is not None, "numpy RREF only for prime fields"
    if col_order is None: col_order = list(range(ncols))
    if not rows: return [], []
    order = np.array(col_order, dtype=np.int64)
    inv_order = np.empty(ncols, dtype=np.int64); inv_order[order] = np.arange(ncols)
    M = np.zeros((len(rows), ncols), dtype=np.int64)
    for i, r in enumerate(rows):
        for c, v in r.items(): M[i, inv_order[c]] = v % p
    nr = M.shape[0]; piv = []; row = 0
    for c in range(ncols):
        if row >= nr: break
        nz = np.nonzero(M[row:, c])[0]
        if len(nz) == 0: continue
        i = row + nz[0]
        if i != row: M[[row, i]] = M[[i, row]]
        inv = pow(int(M[row, c]), -1, p)
        M[row] = (M[row] * inv) % p
        others = np.nonzero(M[:, c])[0]
        others = others[others != row]
        if len(others):
            M[others] = (M[others] - np.outer(M[others, c], M[row])) % p
        piv.append(c); row += 1
    out = []
    for i in range(len(piv)):
        nzc = np.nonzero(M[i])[0]
        out.append({int(order[cc]): int(M[i, cc]) for cc in nzc})
    pivots = [int(order[c]) for c in piv]
    return out, pivots

# sanity: compare numpy RREF with the pure-python one on a small case
K3 = T.Field(3)
R = T.Ring([1, 2], [1], 3)
rows = R.ideal_rows(R.V_Lambda(frozenset([((1,), ())])))
b1, p1 = T.rref(rows, len(R.monos), K3)
b2, p2 = rref_np(rows, len(R.monos), K3)
assert len(b1) == len(b2) == 15 and sorted(p1) == sorted(p2), (len(b1), len(b2))
print("numpy RREF agrees with the pure-python RREF on (2,1,3) root: rank 15")
T.rref = rref_np  # monkeypatch: span_basis / rank_of / slices look up rref in module globals

print("\n##### (A) cell (4,1,3) over F_3, all down-sets (case (alpha) with j0 = 2 occurs) #####")
elems = T.bpar(4, 1, 3)
gen = ((2, 2), (1,))
principal = frozenset(e for e in elems if T.bdom(e, gen))
print("down-set generated by ((2,2),(1)) =", sorted(principal))
summA = T.run_cell(4, 1, 3, T.Field(3), 1)

print("\n##### (B) cell (1,3,5), Lambda = {(∅,(1,1))}: case (gamma) with r = 3, coefficient C(4,2) = 6 #####")
Lam = frozenset([((), (1, 1))])
for p in (5, 3):
    print(f"\n--- over F_{p} ---")
    T.run_cell(1, 3, 5, T.Field(p), 1, only_downsets=[Lam])

print(f"\nwall time inside script: {time.time()-t0:.2f} s")
