#!/usr/bin/env python3
"""
fable7_prop75_test.py  --  cold-referee test of §7.2-§7.5 (Prop. 7.5, Thm 7.6, Remarks 7.9)
of PAPER_OFICIAL_v6.md, written from the definitions only (no code of the author used).

Cells (alpha, beta, q) = (2,1,3), (2,2,3), (2,1,5); fields F_p (p = prime of q) and Q.
For every down-set Lambda of BPar_q(alpha,beta):
  * |Z_Lambda| by brute force over Omega^alpha x Omega^beta;
  * V_Lambda = ideal generated by all tight-pattern products (enumerated from the definition);
  * slices W_j(V_Lambda) w.r.t. w = x_{i1} (Lemma 7.1), and sum_j dim W_j = dim V_Lambda;
  * layers Lambda_i via F_Lambda(mu) (§7.3), cross-checked against brute-force fibre counts,
    and the formula (7.1) (r, iota, j0), and the chain (Lemma 7.3), and Prop 7.4 on all pairs;
  * containment V_{Lambda_i} <= W_{q-1-i}(V_Lambda)  [Prop 7.5]  and the lowered slice W_{q-2-i};
  * for EVERY generator G of every layer: the explicit construction f of Prop 7.5 (alpha/beta/gamma),
    f in V_Lambda, deg_w f <= q-Phi, [w^{q-Phi}] f = kappa*G with kappa != 0, and G in/not in W_{q-Phi-1};
  * dim V_Lambda vs |Z_Lambda| (>= is the theorem; = is only claimed at the roots, Cor. 7.8).
Also Remark 7.9(2) (dims over Q) and Remark 7.9(3) (top z-slice of I^bal_{a+1} contains I^ph_a).
Predicted cost: < 30 s, < 100 MB.
"""
import itertools, sys, time
from fractions import Fraction
from collections import Counter
from math import comb

t_start = time.time()

# ---------------- partitions, dominance, BPar ----------------
def partitions_of(n, maxpart=None):
    if maxpart is None: maxpart = n
    if n == 0:
        yield (); return
    for k in range(min(n, maxpart), 0, -1):
        for rest in partitions_of(n - k, k):
            yield (k,) + rest

def S(lam, t): return sum(lam[:t])
def dom(lam, mu):  # lam ≼ mu (weak dominance, partitions of any sizes)
    T = max(len(lam), len(mu), 1)
    return all(S(lam, t) <= S(mu, t) for t in range(1, T + 1))
def conj(lam):
    if not lam: return ()
    return tuple(sum(1 for r in lam if r >= c) for c in range(1, lam[0] + 1))
def sortp(l): return tuple(sorted([x for x in l if x > 0], reverse=True))

def bpar(alpha, beta, q):
    out = []
    for sp in range(0, alpha + beta + 1):
        sm = sp - (alpha - beta)
        if sm < 0 or sp + sm > alpha + beta: continue
        for lp in partitions_of(sp):
            for lm in partitions_of(sm):
                if len(lp) + len(lm) <= q: out.append((lp, lm))
    return out
def bdom(a, b): return dom(a[0], b[0]) and dom(a[1], b[1])

def downsets(elems):
    n = len(elems); res = []
    for mask in range(1 << n):
        Sset = frozenset(elems[i] for i in range(n) if mask >> i & 1)
        if all(all((not bdom(e, s)) or (e in Sset) for e in elems) for s in Sset):
            res.append(Sset)
    return res

def shape(xi, eta):
    X = Counter(xi); Y = Counter(eta)
    plus = sortp([X[u] - Y[u] for u in set(X) | set(Y) if X[u] > Y[u]])
    minus = sortp([Y[u] - X[u] for u in set(X) | set(Y) if Y[u] > X[u]])
    return (plus, minus)

# options of a tail shape mu (§7.3), positions 1..q
def options(mu, q):
    mp, mm = mu; lp, lm = len(mp), len(mm)
    opts = []
    for p in range(1, lm + 1):  # removals from mu_-
        new = list(mm); new[p - 1] -= 1
        opts.append((mp, sortp(new)))
    for p in range(lm + 1, q - lp + 1):  # middle
        opts.append((sortp(list(mp) + [1]), mm))
    for p in range(q - lp + 1, q + 1):  # additions, j = q+1-p
        j = q + 1 - p; new = list(mp); new[j - 1] += 1
        opts.append((sortp(new), mm))
    assert len(opts) == q
    return opts

def F_Lambda(mu, Lam, q):
    return sum(1 for o in options(mu, q) if o in Lam)

def case_data(mu, Lam, q):
    """(r, iota, j0) of (7.1) read off from the options in Lambda; returns also Phi."""
    mp, mm = mu; lp, lm = len(mp), len(mm)
    opts = options(mu, q)
    inL = [o in Lam for o in opts]
    r = 0
    for p in range(1, lm + 1):
        if inL[p - 1]: r = p
    iota = 1 if (lm < q - lp and inL[lm]) else 0
    j0 = None
    for p in range(q - lp + 1, q + 1):
        if inL[p - 1]:
            j = q + 1 - p; j0 = j if j0 is None else min(j0, j)
    Phi = sum(inL)
    return r, iota, j0, Phi

# ---------------- ring arithmetic: dict {exponent tuple: coeff}, truncated at q ----------------
class Field:
    def __init__(self, p=None):
        self.p = p
    def norm(self, c):
        if self.p: return c % self.p
        return Fraction(c)
    def is0(self, c):
        return (c % self.p == 0) if self.p else (c == 0)
    def inv(self, c):
        return pow(c, -1, self.p) if self.p else 1 / c
    def name(self): return f"F_{self.p}" if self.p else "Q"

def padd(a, b):
    r = dict(a)
    for k, v in b.items(): r[k] = r.get(k, 0) + v
    return {k: v for k, v in r.items() if v != 0}
def pscale(a, c): return {k: v * c for k, v in a.items()} if c != 0 else {}
def pmul(a, b, q):
    r = {}
    for ka, va in a.items():
        for kb, vb in b.items():
            k = tuple(x + y for x, y in zip(ka, kb))
            if max(k) >= q: continue
            r[k] = r.get(k, 0) + va * vb
    return {k: v for k, v in r.items() if v != 0}
def pvar(idx, n):
    e = [0] * n; e[idx] = 1; return {tuple(e): 1}
def pconst(c, n): return {tuple([0] * n): c} if c != 0 else {}
def ppow(a, e, q, n):
    r = pconst(1, n)
    for _ in range(e): r = pmul(r, a, q)
    return r
def vandermonde(varidx_sorted, q, n):
    r = pconst(1, n)
    for c in range(len(varidx_sorted)):
        for c2 in range(c + 1, len(varidx_sorted)):
            r = pmul(r, padd(pvar(varidx_sorted[c2], n), pscale(pvar(varidx_sorted[c], n), -1)), q)
    return r

def ordered_block_partitions(items, sizes):
    if not sizes:
        if not items: yield ()
        return
    s = sizes[0]
    for blk in itertools.combinations(items, s):
        rest = [x for x in items if x not in blk]
        for tail in ordered_block_partitions(rest, sizes[1:]):
            yield (tuple(sorted(blk)),) + tail

def tight_patterns(lam, A, B):
    """A, B: lists of variable indices (positions in the ring) for x- and z-variables."""
    lp, lm = lam
    np_ = len(A) - sum(lp)
    if np_ < 0 or np_ != len(B) - sum(lm): return
    colsP, colsM = conj(lp), conj(lm)
    for Asub in itertools.combinations(A, np_):
        for Bsub in itertools.permutations(B, np_):
            P = list(zip(Asub, Bsub))
            restA = [a for a in A if a not in Asub]
            restB = [b for b in B if b not in Bsub]
            for blocksA in ordered_block_partitions(restA, list(colsP)):
                for blocksB in ordered_block_partitions(restB, list(colsM)):
                    yield P, blocksA, blocksB

def pattern_product(P, blocksA, blocksB, q, n):
    r = pconst(1, n)
    for (i, l) in P:
        r = pmul(r, ppow(padd(pvar(i, n), pscale(pvar(l, n), -1)), q - 1, q, n), q)
    for blk in blocksA: r = pmul(r, vandermonde(list(blk), q, n), q)
    for blk in blocksB: r = pmul(r, vandermonde(list(blk), q, n), q)
    return r

# ---------------- linear algebra ----------------
def rref(rows, ncols, K, col_order=None):
    """rows: list of dict{col: coeff}. Returns (list of reduced rows as dicts, pivot cols) in the
    order given by col_order (a list of columns, default range(ncols))."""
    if col_order is None: col_order = list(range(ncols))
    M = [{c: K.norm(v) for c, v in r.items() if not K.is0(K.norm(v))} for r in rows]
    M = [r for r in M if r]
    piv_rows = []; pivots = []
    for c in col_order:
        # find a row (not yet pivot) with nonzero entry in c
        idx = None
        for i, r in enumerate(M):
            if c in r: idx = i; break
        if idx is None: continue
        r = M.pop(idx)
        inv = K.inv(r[c]); r = {k: K.norm(v * inv) for k, v in r.items()}
        r = {k: v for k, v in r.items() if not K.is0(v)}
        # eliminate from all other rows (remaining and previous pivot rows)
        newM = []
        for r2 in M:
            if c in r2:
                f = r2[c]
                r3 = {k: K.norm(v - f * r.get(k, 0)) for k, v in r2.items()}
                for k, v in r.items():
                    if k not in r2: r3[k] = K.norm(-f * v)
                r3 = {k: v for k, v in r3.items() if not K.is0(v)}
                if r3: newM.append(r3)
            else: newM.append(r2)
        M = newM
        for j, pr in enumerate(piv_rows):
            if c in pr:
                f = pr[c]
                r3 = {k: K.norm(v - f * r.get(k, 0)) for k, v in pr.items()}
                for k, v in r.items():
                    if k not in pr: r3[k] = K.norm(-f * v)
                piv_rows[j] = {k: v for k, v in r3.items() if not K.is0(v)}
        piv_rows.append(r); pivots.append(c)
        if not M: break
    return piv_rows, pivots

class Ring:
    def __init__(self, xs, zs, q):
        """xs, zs: labels of the x- and z-variables. Positions: xs then zs."""
        self.xs, self.zs, self.q = list(xs), list(zs), q
        self.n = len(xs) + len(zs)
        self.labels = [('x', a) for a in xs] + [('z', b) for b in zs]
        self.pos = {lab: i for i, lab in enumerate(self.labels)}
        self.monos = list(itertools.product(range(q), repeat=self.n))
        self.mindex = {m: i for i, m in enumerate(self.monos)}
        self.A = [self.pos[('x', a)] for a in xs]
        self.B = [self.pos[('z', b)] for b in zs]
    def vec(self, poly):
        return {self.mindex[k]: v for k, v in poly.items()}
    def ideal_rows(self, gens):
        rows = []
        for g in gens:
            for m in self.monos:
                prod = pmul({m: 1}, g, self.q)
                if prod: rows.append(self.vec(prod))
        return rows
    def V_Lambda(self, Lam):
        gens = []
        for lam in Lam:
            for P, bA, bB in tight_patterns(lam, self.A, self.B):
                g = pattern_product(P, bA, bB, self.q, self.n)
                if g: gens.append(g)
        return gens

def span_basis(rows, ncols, K):
    b, piv = rref(rows, ncols, K)
    return b
def rank_of(rows, ncols, K): return len(rref(rows, ncols, K)[0])
def contained(rows_sub, basis_big, ncols, K):
    return rank_of(list(basis_big) + list(rows_sub), ncols, K) == len(basis_big)
def in_span(vec, basis_big, ncols, K):
    return contained([vec], basis_big, ncols, K)

def slices(R, basis_rows, wpos, K):
    """W_j(V) for j = 0..q-1 w.r.t. the variable at position wpos; V given by basis rows (dict col->coef).
    Returns list of (basis of W_j as rows over the small ring Rs, Rs)."""
    q = R.q
    Rs_labels = [lab for i, lab in enumerate(R.labels) if i != wpos]
    Rs = Ring([a for (t, a) in Rs_labels if t == 'x'], [b for (t, b) in Rs_labels if t == 'z'], q)
    out = []
    for j in range(q):
        high = [R.mindex[m] for m in R.monos if m[wpos] > j]
        low = [R.mindex[m] for m in R.monos if m[wpos] <= j]
        b, piv = rref(basis_rows, len(R.monos), K, col_order=high + low)
        highset = set(high)
        Vle = [r for r, pc in zip(b, piv) if pc not in highset]
        # sanity: no high entries
        for r in Vle: assert not any(c in highset for c in r)
        Wrows = []
        for r in Vle:
            wr = {}
            for c, v in r.items():
                m = R.monos[c]
                if m[wpos] == j:
                    ms = tuple(e for i, e in enumerate(m) if i != wpos)
                    wr[Rs.mindex[ms]] = v
            if wr: Wrows.append(wr)
        Wb = span_basis(Wrows, len(Rs.monos), K)
        out.append(Wb)
    return out, Rs

def deg_w(poly, wpos):
    return max((k[wpos] for k in poly), default=-1)
def coeff_w(poly, wpos, j):
    """[w^j] poly as a poly in the small ring (drop coordinate wpos)."""
    return {tuple(e for i, e in enumerate(k) if i != wpos): v for k, v in poly.items() if k[wpos] == j}
def lift(poly_small, wpos, n):
    return {tuple(list(k[:wpos]) + [0] + list(k[wpos:])): v for k, v in poly_small.items()}

def scalar_multiple(u, v, K):
    """return kappa with u = kappa*v (as dicts), or None."""
    u = {k: K.norm(c) for k, c in u.items() if not K.is0(K.norm(c))}
    v = {k: K.norm(c) for k, c in v.items() if not K.is0(K.norm(c))}
    if not v: return None if u else 'both zero'
    if set(u) != set(v): return None
    k0 = next(iter(v)); kappa = K.norm(u[k0] * K.inv(v[k0]))
    for k in v:
        if not K.is0(K.norm(u[k] - kappa * v[k])): return None
    return kappa

# ---------------- main test per cell ----------------
def N_bal(a, q):
    return sum((fact(a) // prod_fact(cs)) ** 2 for cs in compositions(a, q))
def fact(n):
    r = 1
    for i in range(2, n + 1): r *= i
    return r
def prod_fact(cs):
    r = 1
    for c in cs: r *= fact(c)
    return r
def compositions(a, q):
    if q == 1:
        yield (a,); return
    for c in range(a + 1):
        for rest in compositions(a - c, q - 1): yield (c,) + rest

def brute_count(alpha, beta, q, Lam):
    Om = range(q); cnt = 0
    for xi in itertools.product(Om, repeat=alpha):
        for eta in itertools.product(Om, repeat=beta):
            if shape(xi, eta) in Lam: cnt += 1
    return cnt

def run_cell(alpha, beta, q, K, peel_label, only_downsets=None):
    print(f"\n=== cell (alpha,beta,q)=({alpha},{beta},{q}) over {K.name()}, peel w = x_{peel_label} ===")
    elems = bpar(alpha, beta, q)
    print("BPar_q(alpha,beta) =", elems)
    tails = bpar(alpha - 1, beta, q)
    print("tail shapes BPar_q(alpha-1,beta) =", tails)
    # chain (Lemma 7.3) and P2 (Prop 7.4) on all tails / comparable pairs
    chain_fail = 0; p2_fail = 0; mem_fail = 0
    for mu in tails:
        op = options(mu, q)
        for o in op:
            if o not in elems: mem_fail += 1
        for a in range(q - 1):
            if not bdom(op[a], op[a + 1]): chain_fail += 1
    for mu in tails:
        for mut in tails:
            if bdom(mu, mut):
                om, omt = options(mu, q), options(mut, q)
                for a in range(q):
                    if not bdom(om[a], omt[a]): p2_fail += 1
    print(f"membership of options in BPar: failures={mem_fail}; chain failures={chain_fail}; Prop7.4 failures={p2_fail}")
    # P1 brute force: fibre size == F_Lambda(shape of tail) for every tail and every down-set
    ds = downsets(elems)
    print(f"number of down-sets: {len(ds)}")
    if only_downsets is not None:
        ds = [d for d in ds if d in only_downsets]
        print(f"restricted to {len(ds)} down-set(s)")
    R = Ring(range(1, alpha + 1), range(1, beta + 1), q)
    wpos = R.pos[('x', peel_label)]
    Om = range(q)
    summary = []
    for Lam in ds:
        LamS = sorted(Lam)
        # P1 brute force
        p1_fail = 0
        for xi in itertools.product(Om, repeat=alpha - 1):
            for eta in itertools.product(Om, repeat=beta):
                fib = sum(1 for u in Om if shape(tuple(list(xi[:wpos]) + [u] + list(xi[wpos:])), eta) in Lam)
                if fib != F_Lambda(shape(xi, eta), Lam, q): p1_fail += 1
        Z = brute_count(alpha, beta, q, Lam)
        gens = R.V_Lambda(Lam)
        rows = R.ideal_rows(gens)
        Vb = span_basis(rows, len(R.monos), K)
        dimV = len(Vb)
        Wb, Rs = slices(R, Vb, wpos, K)
        dimsW = [len(w) for w in Wb]
        # layers
        layers = []
        for i in range(q):
            Li = frozenset(mu for mu in tails if F_Lambda(mu, Lam, q) > i)
            layers.append(Li)
        layer_ok = []; lower_ok = []; dimsL = []; Zl = []
        for i in range(q):
            gi = Rs.V_Lambda(layers[i])
            rows_i = Rs.ideal_rows(gi)
            Lb = span_basis(rows_i, len(Rs.monos), K)
            dimsL.append(len(Lb))
            Zl.append(brute_count(alpha - 1, beta, q, layers[i]))
            ok = contained(Lb, Wb[q - 1 - i], len(Rs.monos), K)
            layer_ok.append(ok)
            if q - 2 - i >= 0:
                lower_ok.append(contained(Lb, Wb[q - 2 - i], len(Rs.monos), K))
            else:
                lower_ok.append(len(Lb) == 0)
        # explicit constructions of Prop 7.5, generator by generator
        n_gen = 0; c_fail = 0; lowfail = 0; lowhold = 0; cases = Counter()
        for mu in tails:
            Phi = F_Lambda(mu, Lam, q)
            if Phi == 0: continue
            r, iota, j0, Phi2 = case_data(mu, Lam, q)
            assert Phi == Phi2
            mp, mm = mu; lp, lm = len(mp), len(mm)
            if j0 is not None:
                case = 'alpha'; assert Phi == q - j0 + 1
            elif iota == 1:
                case = 'beta'; assert Phi == q - lp
            else:
                case = 'gamma'; assert Phi == r and r >= 1
            for P, bA, bB in tight_patterns(mu, Rs.A, Rs.B):
                G = pattern_product(P, bA, bB, q, Rs.n)
                n_gen += 1; cases[case] += 1
                # build f in the big ring R. Map small-ring positions to big-ring positions:
                def big(pos_small):
                    return pos_small if pos_small < wpos else pos_small + 1
                Pb = [(big(i), big(l)) for (i, l) in P]
                bAb = [tuple(sorted(big(x) for x in blk)) for blk in bA]
                bBb = [tuple(sorted(big(x) for x in blk)) for blk in bB]
                if case == 'alpha':
                    cstar = mp[j0 - 1] + 1  # column index (1-based)
                    blocks = list(bAb)
                    if cstar <= len(bAb):
                        assert len(bAb[cstar - 1]) == j0 - 1
                        blocks[cstar - 1] = tuple(sorted(list(bAb[cstar - 1]) + [wpos]))
                    else:
                        assert j0 == 1 and cstar == len(bAb) + 1
                        blocks.append((wpos,))
                    lam_new = (sortp(list(mp[:j0 - 1]) + [mp[j0 - 1] + 1] + list(mp[j0:])), mm)
                    assert lam_new in Lam
                    assert [len(b) for b in blocks] == list(conj(lam_new[0]))
                    f = pattern_product(Pb, blocks, bBb, q, R.n)
                    kappa_expected = 'pm1'
                elif case == 'beta':
                    blocks = list(bAb)
                    if blocks:
                        assert len(blocks[0]) == lp
                        blocks[0] = tuple(sorted(list(blocks[0]) + [wpos]))
                    else:
                        blocks = [(wpos,)]
                    lam_new = (sortp(list(mp) + [1]), mm)
                    assert lam_new in Lam
                    assert [len(b) for b in blocks] == list(conj(lam_new[0]))
                    f = pattern_product(Pb, blocks, bBb, q, R.n)
                    kappa_expected = 'pm1'
                else:
                    c0 = mm[r - 1]
                    Sblk = bBb[c0 - 1]; assert len(Sblk) == r
                    lam_new = (mp, sortp(list(mm[:r - 1]) + [mm[r - 1] - 1] + list(mm[r:])))
                    assert lam_new in Lam
                    f = {}
                    Ssorted = list(Sblk)
                    for cidx, b in enumerate(Ssorted, start=1):
                        eps = (-1) ** (r + cidx)
                        otherB = [blk for k, blk in enumerate(bBb) if k != c0 - 1]
                        newB = otherB + ([tuple(x for x in Ssorted if x != b)] if r - 1 > 0 else [])
                        # the tight pattern of lam_new: pairs Pb + (w,b), x-blocks bAb, z-blocks newB
                        assert sorted(len(x) for x in newB) == sorted(conj(lam_new[1]))
                        term = pattern_product(Pb + [(wpos, b)], bAb, newB, q, R.n)
                        f = padd(f, pscale(term, eps))
                    kappa_expected = comb(q - 1, r - 1)
                # checks
                fv = R.vec(f)
                ok_mem = in_span(fv, Vb, len(R.monos), K)
                d = deg_w(f, wpos)
                ok_deg = (d <= q - Phi)
                top = coeff_w(f, wpos, q - Phi)
                kappa = scalar_multiple(top, G, K)
                ok_top = kappa is not None and kappa != 'both zero' and not K.is0(kappa)
                if kappa == 'both zero': ok_top = True  # G = 0 in the ring: trivial
                # compare the scalar with the paper's claim: +-1 in (alpha),(beta); +-C(q-1,r-1) in (gamma)
                if ok_top and kappa != 'both zero':
                    exp = 1 if kappa_expected == 'pm1' else kappa_expected
                    if kappa not in (K.norm(exp), K.norm(-exp)):
                        ok_top = False
                        print(f"   KAPPA MISMATCH: mu={mu} case={case} kappa={kappa} expected +-{exp}")
                if not (ok_mem and ok_deg and ok_top):
                    c_fail += 1
                    print(f"   CONSTRUCTION FAILURE: Lam={LamS} mu={mu} case={case} Phi={Phi} P={P} bA={bA} bB={bB} "
                          f"mem={ok_mem} deg={d} (<= {q-Phi}?) kappa={kappa} expected={kappa_expected}")
                # lowered slice per generator
                Gv = Rs.vec(G)
                if q - Phi - 1 >= 0:
                    low = in_span(Gv, Wb[q - Phi - 1], len(Rs.monos), K)
                else:
                    low = (len(Gv) == 0)
                if low: lowhold += 1
                else: lowfail += 1
        rel = '=' if dimV == Z else ('>' if dimV > Z else '<!!')
        print(f"Lambda={LamS}")
        print(f"   |Z|={Z} dim V={dimV} [{rel}]  sum_j dim W_j={sum(dimsW)}  dims W_0..W_{q-1}={dimsW}  P1 brute-force failures={p1_fail}")
        print(f"   layers: {[sorted(l) for l in layers]}")
        print(f"   dim V_(Lambda_i) i=0..q-1 = {dimsL}; |Z_(Lambda_i)| = {Zl}; sum |Z_(Lambda_i)| = {sum(Zl)}")
        print(f"   Prop 7.5  V_(Lambda_i) <= W_(q-1-i): {layer_ok}")
        print(f"   lowered   V_(Lambda_i) <= W_(q-2-i): {lower_ok}")
        print(f"   generators of layers: {n_gen} (cases {dict(cases)}), construction failures: {c_fail}; "
              f"per-generator lowered slice: holds {lowhold}, fails {lowfail}")
        summary.append((LamS, Z, dimV, all(layer_ok), lower_ok, c_fail))
    return summary

def remark_79(K, cells=((1, 3), (2, 3), (1, 5))):
    print(f"\n=== Remarks 7.9(2),(3) over {K.name()} ===")
    for (a, q) in cells:
        # I^bal_{a+1} in R_{[a+1],[a+1]}, peel z_{a+1}; compare with I^ph_a in R_{[a+1],[a]}
        R = Ring(range(1, a + 2), range(1, a + 2), q)
        gens = R.V_Lambda(frozenset([((), ())]))
        Vb = span_basis(R.ideal_rows(gens), len(R.monos), K)
        zpos = R.pos[('z', a + 1)]
        Wb, Rs = slices(R, Vb, zpos, K)
        gph = Rs.V_Lambda(frozenset([((1,), ())]))
        Pb = span_basis(Rs.ideal_rows(gph), len(Rs.monos), K)
        # top coefficient of each generator of I^bal_{a+1} in z_{a+1}
        topok = True
        for g in gens:
            d = deg_w(g, zpos)
            top = coeff_w(g, zpos, q - 1)
            # is top exactly one of the phantom generators (coefficient +1)?
            found = any(scalar_multiple(top, h, K) == K.norm(1) for h in gph)
            if d != q - 1 or not found: topok = False
        cont = contained(Pb, Wb[q - 1], len(Rs.monos), K)
        print(f"(a,q)=({a},{q}): dim I^bal_{a+1}={len(Vb)}, N_bal={N_bal(a+1,q)}; dim I^ph_{a}={len(Pb)}, N_ph=N_bal(a+1)={N_bal(a+1,q)}; "
              f"dims W_j(I^bal, peel z_{a+1})={[len(w) for w in Wb]}; every generator has z-degree q-1 with top coeff = a phantom generator (coeff +1): {topok}; "
              f"I^ph_a <= W_(q-1): {cont}; W_j=0 for j<q-1: {all(len(w)==0 for w in Wb[:q-1])}")
    # Remark 7.9(2): dim_Q((x-z)^2) in Q[x,z]/(x^3,z^3)
    R = Ring([1], [1], 3)
    Vb = span_basis(R.ideal_rows(R.V_Lambda(frozenset([((), ())]))), len(R.monos), K)
    print(f"dim ((x-z)^2) in {K.name()}[x,z]/(x^3,z^3) = {len(Vb)}  (Remark 7.9(2): 4 over Q, 3 over F_3)")

if __name__ == '__main__':
    print("N_bal(a,3) for a=1..5:", [N_bal(a, 3) for a in range(1, 6)], " N_bal(2,q) q=3,5,7,9,11:", [N_bal(2, q) for q in (3, 5, 7, 9, 11)])
    allsum = {}
    for (alpha, beta, q) in [(2, 1, 3), (2, 2, 3), (2, 1, 5)]:
        p = 3 if q == 3 else 5
        for K in (Field(p), Field(None)):
            peel_labels = [1, 2] if (alpha, beta, q) == (2, 1, 3) else [1]
            for pl in peel_labels:
                allsum[(alpha, beta, q, K.name(), pl)] = run_cell(alpha, beta, q, K, pl)
    remark_79(Field(3), cells=((1, 3), (2, 3)))
    remark_79(Field(5), cells=((1, 5),))
    remark_79(Field(None))
    # extra: (1,5) root over F_5 for Remark 7.9(3) at q=5 handled above via (a,q)=(1,5)
    print("\n=== SUMMARY ===")
    for key, summ in allsum.items():
        alpha, beta, q, Kn, pl = key
        eq = sum(1 for s in summ if s[2] == s[1]); gt = sum(1 for s in summ if s[2] > s[1]); lt = sum(1 for s in summ if s[2] < s[1])
        p75 = all(s[3] for s in summ); cf = sum(s[5] for s in summ)
        lowered_all = sum(1 for s in summ if all(s[4]))
        print(f"cell {key}: down-sets={len(summ)}; dimV vs |Z|: eq={eq} gt={gt} LT={lt}; Prop7.5 all layers OK={p75}; "
              f"construction failures={cf}; down-sets where the lowered slice holds for ALL i: {lowered_all}")
    print(f"\nwall time inside script: {time.time()-t_start:.2f} s")
