#!/usr/bin/env python3
"""
ref6a: independent numerical test of PAPER_OFICIAL_v6 §6.1-§6.3 (and, as a by-product, §6.4-§6.8)
at the smallest cell where mu_r is contained in F_p:  m = 21, p = q = 7, r = 3, k = 1 (n = 2, N = 4).

All arithmetic is over F_7 (mu_3 = {1,2,4} in F_7), so no field extension is needed and the
dimensions over F_7 equal the dimensions over Fbar_7.

Checks:
 (A) Lemma 6.2 / (6.2): for every colouring c and every J, the image pi_c(psi_J) in R_c is 0 iff
     J is not compatible, and otherwise it generates the same principal ideal as the literal
     product  (t_{k0}-1) * prod_{i>=1} (t_{ki}-1)(t_{ji}t_{ki}-1)^{q-1}   (equality up to a unit).
 (B) Lemma 6.3: compatible matchings = product set (P, sigma), for k = 1,2,3 and r = 3,5.
 (C) Proposition 6.5: dim pi_c(I) computed DIRECTLY from the images of the three psi_J in R_c
     (dim R_c = 343) equals the product of the block-ideal dimensions computed separately in
     the block rings.
 (D) Lemma 6.8 / global: sum_c dim pi_c(I) versus |Gamma_J| = Q_1(21) = 3*20*19 = 1140, with the
     per-colouring counts |Gamma_c| obtained by brute force over mu_21^3 (9261 tuples).
 (E) extra block checks: I^{bal}_2 at q = 7 (expected N_bal(2,7) = 91) and the even colour-1 block
     with 4 variables and 0 outside the block (expected 90).
"""
import itertools, sys, time
import numpy as np

p = 7; q = 7; r = 3; m = q * r
mu3 = [1, 2, 4]                       # cube roots of unity in F_7
inv3 = {1: 1, 2: 4, 4: 2}
assert all(pow(z, 3, p) == 1 for z in mu3)

# ---------- truncated polynomial arithmetic in F_p[x_S]/(x_i^q) ----------
def zero(nv):
    return np.zeros((q,) * nv, dtype=np.int64)

def const(nv, a):
    f = zero(nv); f[(0,) * nv] = a % p; return f

def var(nv, pos):
    f = zero(nv); idx = [0] * nv; idx[pos] = 1; f[tuple(idx)] = 1; return f

def mul(f, g):
    """product in F_p[x]/(x_i^q); iterate over the nonzero terms of f (keep f sparse)."""
    h = np.zeros_like(g)
    for idx in np.argwhere(f):
        coef = int(f[tuple(idx)])
        src = tuple(slice(0, q - i) for i in idx)
        dst = tuple(slice(i, q) for i in idx)
        h[dst] += coef * g[src]
    return h % p

def power(f, e):
    acc = const(f.ndim, 1)
    for _ in range(e):
        acc = mul(f, acc)
    return acc

def phi(u):
    """phi(u) = 1 + u + ... + u^{m-1}"""
    acc = const(u.ndim, 0); pw = const(u.ndim, 1)
    for _ in range(m):
        acc = (acc + pw) % p
        pw = mul(u, pw)
    return acc

# ---------- rank over F_p ----------
def rank_mod_p(M):
    """Gaussian elimination mod p, in place on an int8 matrix with entries in 0..p-1;
    temporaries are int16 chunks of at most 512 rows (memory ~ size of M)."""
    M = np.ascontiguousarray(M, dtype=np.int8)
    rows, cols = M.shape
    piv = 0
    for c in range(cols):
        if piv == rows:
            break
        nz = np.nonzero(M[piv:, c])[0]
        if len(nz) == 0:
            continue
        i = piv + int(nz[0])
        if i != piv:
            tmp = M[piv].copy(); M[piv] = M[i]; M[i] = tmp
        inv = pow(int(M[piv, c]), p - 2, p)
        M[piv] = ((M[piv].astype(np.int16) * inv) % p).astype(np.int8)
        prow = M[piv].astype(np.int16)
        below = np.nonzero(M[piv + 1:, c])[0] + piv + 1
        for s in range(0, len(below), 512):
            blk = below[s:s + 512]
            t = (M[blk].astype(np.int16) - M[blk, c].astype(np.int16)[:, None] * prow[None, :]) % p
            M[blk] = t.astype(np.int8)
        piv += 1
    return piv

def ideal_rows(gens, nv):
    """rows spanning the ideal generated by gens: all monomial multiples x^e * g."""
    D = q ** nv
    rows = np.zeros((len(gens) * D, D), dtype=np.int8)     # int8 from the start: values 0..p-1
    rr = 0
    for g in gens:
        g8 = (g % p).astype(np.int8)
        for e in itertools.product(range(q), repeat=nv):
            src = tuple(slice(0, q - i) for i in e)
            dst = tuple(slice(i, q) for i in e)
            h = np.zeros_like(g8); h[dst] = g8[src]
            rows[rr] = h.reshape(-1); rr += 1
    return rows

def ideal_dim(gens, nv):
    gens = [g for g in gens if np.any(g)]
    if not gens:
        return 0
    return rank_mod_p(ideal_rows(gens, nv))

# ---------- matchings ----------
def matchings(indices):
    indices = sorted(indices)
    if not indices:
        yield []
        return
    a = indices[0]
    for b in indices[1:]:
        rest = [i for i in indices if i not in (a, b)]
        for M in matchings(rest):
            yield [(a, b)] + M

# ---------- (B) Lemma 6.3 : compatible matchings form the product set ----------
def check_lemma_6_3(k, rr):
    n = 2 * k; N = n + 2
    roots = list(range(rr))          # exponents mod rr; inverse = -e mod rr
    J_all = list(matchings(range(N)))
    bad = 0; ncomp = 0
    for c in itertools.product(roots, repeat=n + 1):
        c0 = (-sum(c)) % rr
        col = [c0] + list(c)
        comp = [J for J in J_all if all((col[a] + col[b]) % rr == 0 for a, b in J)]
        C = {z: [i for i in range(N) if col[i] == z] for z in roots}
        ok = (len(C[0]) % 2 == 0) and all(len(C[z]) == len(C[(-z) % rr]) for z in roots)
        if ok:
            reps = [z for z in roots if 0 < z < rr - z]
            npred = 1
            s = len(C[0])
            for t in range(s - 1, 0, -2):
                npred *= t
            for z in reps:
                a = len(C[z]); f = 1
                for t in range(2, a + 1):
                    f *= t
                npred *= f
        else:
            npred = 0
        ncomp += (len(comp) > 0)
        if len(comp) != npred:
            bad += 1
    return bad, ncomp

print("== (B) Lemma 6.3: #compatible J == (|C_1|-1)!! * prod |C_zeta|!  (product set) ==")
for k in (1, 2, 3):
    for rr in (3, 5):
        if k == 3 and rr == 5:
            continue
        bad, ncomp = check_lemma_6_3(k, rr)
        print(f"  k={k} r={rr}: mismatches={bad}, compatible colourings={ncomp}")
sys.stdout.flush()

# ---------- k = 1, m = 21 set-up ----------
k = 1; n = 2; N = 4; nv = n + 1
J_all = [[(0, 1), (2, 3)], [(0, 2), (1, 3)], [(0, 3), (1, 2)]]     # j_0 = 0 always

def t_elem(S, i, c):
    """t_i = c_i + x_i as an element of the ring on variable set S (sorted list of indices >= 1)."""
    pos = S.index(i)
    return (const(len(S), c[i]) + var(len(S), pos)) % p

def psi_image(J, c, S):
    """literal image of psi_J = prod_{i=0}^{k}(t_{ki}-1) * prod_{i>=1} phi(t_{ji} t_{ki}) in R_c, ring on S."""
    nvS = len(S)
    f = const(nvS, 1)
    for idx, (a, b) in enumerate(J):
        tb = t_elem(S, b, c)
        f = mul((tb - const(nvS, 1)) % p, f)
        if idx >= 1:
            ta = t_elem(S, a, c)
            f = mul(phi(mul(ta, tb)), f)
    return f

def g_literal(J, c, S):
    """RHS of (6.2) without the unit: (t_{k0}-1) * prod_{i>=1}(t_{ki}-1)(t_{ji}t_{ki}-1)^{q-1}."""
    nvS = len(S)
    f = const(nvS, 1)
    for idx, (a, b) in enumerate(J):
        tb = t_elem(S, b, c)
        f = mul((tb - const(nvS, 1)) % p, f)
        if idx >= 1:
            ta = t_elem(S, a, c)
            f = mul(power((mul(ta, tb) - const(nvS, 1)) % p, q - 1), f)
    return f

def block_factor(pair, c, S):
    """the factor of (6.2) belonging to one pair {a<b}: (t_b-1) if a == 0, else (t_b-1)(t_a t_b-1)^{q-1}."""
    a, b = pair
    nvS = len(S)
    tb = t_elem(S, b, c)
    f = (tb - const(nvS, 1)) % p
    if a != 0:
        ta = t_elem(S, a, c)
        f = mul(power((mul(ta, tb) - const(nvS, 1)) % p, q - 1), f)
    return f

# brute-force Gamma_J at m = 21, classified by colouring (exponents mod 3 -> mu_3(F_7) via 0->1, 1->2, 2->4)
expo_to_mu3 = {0: 1, 1: 2, 2: 4}
gamma_by_c = {}
total_gamma = 0
for a in itertools.product(range(m), repeat=nv):
    a0 = (-sum(a)) % m
    full = [a0] + list(a)
    if any(x == 0 for x in full):
        continue
    ok = False
    for J in J_all:
        if all((full[x] + full[y]) % m == 0 for x, y in J):
            ok = True; break
    if ok:
        total_gamma += 1
        cc = tuple(expo_to_mu3[x % 3] for x in a)
        gamma_by_c[cc] = gamma_by_c.get(cc, 0) + 1
print(f"\n== (D) brute force |Gamma_J| at m=21, k=1: {total_gamma}  (Q_1(21) = {3*20*19}) ==")
sys.stdout.flush()

print("\n== (A),(C): per colouring c=(c_1,c_2,c_3): direct dim pi_c(I) vs block product vs |Gamma_c| ==")
S_full = [1, 2, 3]
sum_direct = 0; sum_block = 0
fail_A = 0; fail_C = 0; fail_D = 0
t0 = time.time()
for c123 in itertools.product(mu3, repeat=nv):
    c = {i + 1: c123[i] for i in range(nv)}
    c[0] = inv3[(c[1] * c[2] * c[3]) % p]
    assert (c[0] * c[1] * c[2] * c[3]) % p == 1
    comp = [J for J in J_all if all((c[a] * c[b]) % p == 1 for a, b in J)]
    # (A) images of the three psi_J
    imgs = []
    for J in J_all:
        f = psi_image(J, c, S_full)
        is_comp = J in comp
        if not is_comp:
            if np.any(f):
                fail_A += 1; print("  (A) FAIL: non-compatible J has nonzero image", c123, J)
        else:
            if not np.any(f):
                fail_A += 1; print("  (A) FAIL: compatible J has zero image", c123, J)
            g = g_literal(J, c, S_full)
            df = ideal_dim([f], nv); dg = ideal_dim([g], nv); dfg = ideal_dim([f, g], nv)
            if not (df == dg == dfg):
                fail_A += 1; print("  (A) FAIL: (6.2) not a unit multiple", c123, J, df, dg, dfg)
        imgs.append(f)
    direct = ideal_dim(imgs, nv)
    # (C) block decomposition
    Cz = {z: [i for i in range(N) if c[i] == z] for z in mu3}
    blocks = [Cz[1], Cz[2] + Cz[4]]          # colour 1, and the pair {zeta, zeta^-1} = {2, 4}
    if comp:
        prod = 1; block_info = []
        for blk in blocks:
            S = sorted(i for i in blk if i != 0)
            if len(blk) == 0:
                block_info.append((blk, 1)); continue
            # generators: for colour-1 block all perfect matchings of blk; for pair block the bijections
            if blk is blocks[0]:
                Ms = list(matchings(blk))
            else:
                A = Cz[2]; B = Cz[4]
                Ms = [list(zip(A, perm)) for perm in itertools.permutations(B)] if len(A) == len(B) else []
                Ms = [[tuple(sorted(pr)) for pr in Mt] for Mt in Ms]
            gens = []
            for Mt in Ms:
                gg = const(len(S), 1)
                for pr in Mt:
                    gg = mul(block_factor(pr, c, S), gg)
                gens.append(gg)
            d = ideal_dim(gens, len(S)) if S else (1 if gens else 0)
            block_info.append((blk, d)); prod *= d
    else:
        prod = 0; block_info = []
    gam = gamma_by_c.get(c123, 0)
    flag = ""
    if direct != prod:
        fail_C += 1; flag += " <-- (C) FAIL"
    if direct != gam:
        fail_D += 1; flag += " <-- (D) per-colouring mismatch"
    sum_direct += direct; sum_block += prod
    print(f"  c={c123} c0={c[0]} |C_1|={len(Cz[1])} |C_2|={len(Cz[2])} |C_4|={len(Cz[4])} "
          f"#compJ={len(comp)} direct={direct} blocks={[(b, d) for b, d in block_info]} prod={prod} |Gamma_c|={gam}{flag}")
    sys.stdout.flush()
print(f"  sum_c direct dim pi_c(I) = {sum_direct}; sum_c block products = {sum_block}; |Gamma_J| = {total_gamma}")
print(f"  failures: (A)={fail_A} (C)={fail_C} (D)={fail_D}   [{time.time()-t0:.1f}s]")
sys.stdout.flush()

# ---------- (E) extra block checks ----------
print("\n== (E) extra block checks at q=7 ==")
# I^{bal}_2 in F_7[x1,x2,z1,z2]/(x^7,z^7): gens (x1-z1)^6 (x2-z2)^6 and (x1-z2)^6 (x2-z1)^6
nv4 = 4
x1, x2, z1, z2 = (var(nv4, i) for i in range(4))
gb1 = mul(power((x1 - z1) % p, q - 1), power((x2 - z2) % p, q - 1))
gb2 = mul(power((x1 - z2) % p, q - 1), power((x2 - z1) % p, q - 1))
dbal = ideal_dim([gb1, gb2], nv4)
# N_bal(2,7) = sum over compositions of 2 into 7 parts of (2!/prod c!)^2 = 7*1 + C(7,2)*4 = 91
print(f"  dim I^bal_2 (q=7) = {dbal}  (N_bal(2,7) = {7 + 21*4})")
# even colour-1 block, 4 variables (indices 1..4 all colour 1, 0 outside the block):
c_even = {0: 2, 1: 1, 2: 1, 3: 1, 4: 1}
S4 = [1, 2, 3, 4]
gens = []
for Mt in matchings([1, 2, 3, 4]):
    gg = const(4, 1)
    for pr in Mt:
        gg = mul(block_factor(pr, c_even, S4), gg)
    gens.append(gg)
deven = ideal_dim(gens, 4)
# expected: # of 4-tuples in T (6 elements, 3 involution pairs) closed under involution = 3*6 + 3*24 = 90
print(f"  dim (g_P : P) for |C_1|=4, 0 not in C_1, q=7 = {deven}  (expected 90)")
print("\nDONE")
