#!/usr/bin/env python3
"""
Referee check for PAPER_OFICIAL_v6.md §6.4-§6.5 (Lemmas 6.6 and 6.7) by direct
modular linear algebra (numpy, exact arithmetic mod p).

(A) Colour-1 block, 0 NOT in C_1, |C_1| = n even, computed DIRECTLY in the
    t-variables: R = F_p[t_1..t_n]/((t_i-1)^q), generators
    g_P = prod_{(i<l) in P} (t_l - 1)(t_i t_l - 1)^{q-1} over perfect matchings P.
    Claim (Lemma 6.6, second bullet): dim (g_P) >= N_1(c) = Q_{n/2-1}(q); by
    Theorem 5.9' the y-form has dim exactly |Z_{emptyset}| = Q_{n/2-1}(q).
(B) Colour-1 block, 0 IN C_1, C_1 = {0,1,..,n}, n odd, in the t-variables:
    the pair {0,k_0} contributes (t_{k_0}-1). Expect Q_{(n-1)/2}(q).
(C) y-form: dim (D_P : P) C_m for even m (V_{emptyset}) and (D_J : J) C_m for odd m
    (V_{(1)}), graded computation. Expect Q_{m/2-1}(q), resp. Q_{(m-1)/2}(q).
(D) Pair blocks (Lemma 6.7(iii)) in F_p with mu_r inside F_p: (p,r,zeta) =
    (7,3,2), (11,5,3), (13,3,3). Balanced alpha=beta=1 and phantom (alpha,beta)
    = (2,1) with 0 in B, and (1,2) with 0 in A, computed directly in the
    t-variables with the generators of (6.2), versus the ideals I^bal_1, I^ph_1
    in the x,z-variables, versus N_bal(1,q) = q and N_ph(1,q) = N_bal(2,q).
"""
import itertools, math, sys, time
from fractions import Fraction
import numpy as np

t_start = time.time()
ok_all = True
def report(name, ok, extra=""):
    global ok_all
    ok_all &= bool(ok)
    print(f"[{'OK' if ok else 'FAIL'}] {name} {extra}", flush=True)

MEM_LIMIT = 60_000_000  # bytes for the main matrix

# ---------------- exact arithmetic mod p on dense arrays ----------------
def pmul(a, b, p):
    """product in F_p[s_1..s_n]/(s_i^box), arrays of shape (box,)*n."""
    res = np.zeros_like(a)
    box = a.shape[0]
    for idx in zip(*np.nonzero(a)):
        coef = int(a[idx])
        src = tuple(slice(0, box - e) for e in idx)
        dst = tuple(slice(e, box) for e in idx)
        res[dst] = (res[dst] + coef * b[src]) % p
    return res

def ppow(a, k, p):
    res = np.zeros_like(a); res[(0,)*a.ndim] = 1
    for _ in range(k):
        res = pmul(res, a, p)
    return res

def var(i, n, box):
    a = np.zeros((box,)*n, dtype=np.int64)
    idx = [0]*n; idx[i] = 1
    a[tuple(idx)] = 1
    return a

def const(c, n, box, p):
    a = np.zeros((box,)*n, dtype=np.int64)
    a[(0,)*n] = c % p
    return a

def shift(g, e):
    """monomial s^e times g, truncated."""
    box = g.shape[0]
    res = np.zeros_like(g)
    src = tuple(slice(0, box - ei) for ei in e)
    dst = tuple(slice(ei, box) for ei in e)
    res[dst] = g[src]
    return res

def rank_mod_p(M, p):
    if M.dtype != np.int32:
        M = (M % p).astype(np.int32)
    rows, cols = M.shape
    r = 0
    for c in range(cols):
        if r == rows:
            break
        col = M[r:, c]
        nzr = np.flatnonzero(col)
        if nzr.size == 0:
            continue
        i = r + int(nzr[0])
        if i != r:
            M[[r, i]] = M[[i, r]]
        inv = pow(int(M[r, c]), p - 2, p)
        M[r] = (M[r] * inv) % p
        nz = np.flatnonzero(M[:, c])
        nz = nz[nz != r]
        if nz.size:
            M[nz] = (M[nz] - np.outer(M[nz, c], M[r])) % p
        r += 1
    return r

def ideal_dim_full(gens, p):
    """dim of the ideal generated by gens in F_p[s]/(s_i^box), all monomial shifts."""
    box = gens[0].shape[0]; n = gens[0].ndim
    monos = list(itertools.product(range(box), repeat=n))
    nrows = len(gens) * len(monos); ncols = box**n
    assert nrows * ncols * 4 < MEM_LIMIT, f"matrix too big: {nrows}x{ncols}"
    M = np.zeros((nrows, ncols), dtype=np.int32)
    k = 0
    for g in gens:
        for e in monos:
            M[k] = shift(g, e).reshape(-1); k += 1
    return rank_mod_p(M, p)

def ideal_dim_graded(gens, p):
    """dim of a homogeneous ideal generated by homogeneous gens (same degree d0),
    computed degree by degree."""
    box = gens[0].shape[0]; n = gens[0].ndim
    monos = np.array(list(itertools.product(range(box), repeat=n)))
    degs = monos.sum(axis=1)
    d0 = None
    for g in gens:
        nzd = set(int(degs[i]) for i in np.flatnonzero(g.reshape(-1)))
        if nzd:
            assert len(nzd) == 1, "generator not homogeneous"
            dd = nzd.pop()
            assert d0 is None or d0 == dd
            d0 = dd
    total = 0
    maxdeg = n * (box - 1)
    for d in range(d0, maxdeg + 1):
        cols = np.flatnonzero(degs == d)
        shifts = monos[degs == d - d0]
        nrows = len(gens) * len(shifts)
        if nrows == 0 or len(cols) == 0:
            continue
        assert nrows * len(cols) * 4 < MEM_LIMIT, f"matrix too big at degree {d}: {nrows}x{len(cols)}"
        M = np.zeros((nrows, len(cols)), dtype=np.int32)
        k = 0
        for g in gens:
            for e in shifts:
                M[k] = shift(g, tuple(int(x) for x in e)).reshape(-1)[cols]; k += 1
        total += rank_mod_p(M, p)
    return total

# ---------------- combinatorics ----------------
def Q(k, q):
    N = 2*k + 2; h = (q - 1)//2; nn = N//2
    if h == 0:
        return 1 if N == 0 else 0
    def rec(i, rem):
        if i == h - 1:
            return Fraction(1, math.factorial(rem)**2)
        return sum(Fraction(1, math.factorial(bb)**2) * rec(i + 1, rem - bb) for bb in range(rem + 1))
    val = rec(0, nn) * math.factorial(N)
    assert val.denominator == 1
    return int(val)

def perfect_matchings(S):
    S = list(S)
    if not S:
        yield []
        return
    a = S[0]
    for j in range(1, len(S)):
        b = S[j]
        rest = S[1:j] + S[j+1:]
        for m in perfect_matchings(rest):
            yield [(a, b)] + m

def prime_of(q):
    for p in range(2, q + 1):
        if q % p == 0:
            return p

def N_bal(a, q):
    # sum over compositions of a into q parts of (a!/prod c_i!)^2
    tot = 0
    for comp in itertools.product(range(a + 1), repeat=q):
        if sum(comp) == a:
            m = math.factorial(a)
            for c in comp: m //= math.factorial(c)
            tot += m * m
    return tot

# ---------------- (A) colour-1 block, 0 not in C_1, t-variables ----------------
def gens_colour1_t(q, p, n, zero_in):
    """C_1 = {1..n} (zero_in False) or {0,1..n} (zero_in True). t_i = 1 + s_i."""
    box = q
    one = const(1, n, box, p)
    t = [None] + [const(1, n, box, p) + var(i - 1, n, box) for i in range(1, n + 1)]
    gens = []
    idxset = ([0] if zero_in else []) + list(range(1, n + 1))
    for P in perfect_matchings(idxset):
        g = one.copy()
        for (i, l) in P:
            if i == 0:
                g = pmul(g, (t[l] - one) % p, p)
            else:
                u = (pmul(t[i], t[l], p) - one) % p
                g = pmul(g, pmul((t[l] - one) % p, ppow(u, q - 1, p), p), p)
        gens.append(g)
    return gens

print("=== (A) colour-1 block, 0 not in C_1, direct in t-variables (Lemma 6.6, second bullet) ===")
for (q, n) in [(3, 2), (3, 4), (3, 6), (5, 2), (5, 4), (7, 2), (9, 2), (7, 4)]:
    p = prime_of(q)
    if len(list(perfect_matchings(range(1, n + 1)))) * q**n * q**n * 4 >= MEM_LIMIT:
        print(f"   skip (q,n)=({q},{n}): too big"); continue
    t0 = time.time()
    gens = gens_colour1_t(q, p, n, zero_in=False)
    d = ideal_dim_full(gens, p)
    exp = Q(n//2 - 1, q)
    report(f"(A) q={q} |C_1|={n}, 0 not in C_1: dim I_c1 = {d}, expected N_1 = Q_{n//2-1}({q}) = {exp}", d == exp, f"[{time.time()-t0:.1f}s]")

print("=== (B) colour-1 block, 0 in C_1 = {0,1..n}, n odd, direct in t-variables (Lemma 6.6, first bullet) ===")
for (q, n) in [(3, 1), (3, 3), (3, 5), (5, 1), (5, 3), (7, 1), (7, 3), (9, 1), (9, 3)]:
    p = prime_of(q)
    if len(list(perfect_matchings(range(0, n + 1)))) * q**n * q**n * 4 >= MEM_LIMIT:
        print(f"   skip (q,n)=({q},{n}): too big"); continue
    t0 = time.time()
    gens = gens_colour1_t(q, p, n, zero_in=True)
    d = ideal_dim_full(gens, p)
    exp = Q((n - 1)//2, q)
    report(f"(B) q={q} C_1={{0..{n}}} (|C_1|={n+1}): dim I_c1 = {d}, expected N_1 = Q_{(n-1)//2}({q}) = {exp}", d == exp, f"[{time.time()-t0:.1f}s]")

# ---------------- (C) y-form, graded ----------------
def Dpoly(a_idx, b_idx, n, box, p, q):
    ya = var(a_idx, n, box); yb = var(b_idx, n, box)
    res = np.zeros((box,)*n, dtype=np.int64)
    for u in range(q - 1):
        term = pmul(ppow(ya, u, p), ppow(yb, q - 2 - u, p), p)
        res = (res + ((-1)**u) * term) % p
    return res

def gens_y(q, p, m):
    """m even: D_P over perfect matchings of [m]; m odd: D_J over matchings of {0..m}, pairs avoiding 0."""
    box = q - 1
    one = const(1, m, box, p)
    idxset = list(range(1, m + 1)) if m % 2 == 0 else [0] + list(range(1, m + 1))
    gens = []
    for P in perfect_matchings(idxset):
        g = one.copy()
        for (a, b) in P:
            if a == 0:
                continue
            g = pmul(g, Dpoly(a - 1, b - 1, m, box, p, q), p)
        gens.append(g)
    return gens

print("=== (C) y-form: dim V_{emptyset} (m even) / dim V_{(1)} (m odd), graded, box q-1 ===")
for (q, m) in [(3, 2), (3, 3), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (5, 2), (5, 3), (5, 4), (5, 5), (7, 2), (7, 3), (7, 4), (9, 2), (9, 3), (9, 4), (5, 6)]:
    p = prime_of(q)
    t0 = time.time()
    try:
        gens = gens_y(q, p, m)
        d = ideal_dim_graded(gens, p)
    except AssertionError as ex:
        print(f"   skip (q,m)=({q},{m}): {ex}"); continue
    exp = Q(m//2 - 1, q) if m % 2 == 0 else Q((m - 1)//2, q)
    lab = "V_{emptyset} = (D_P)" if m % 2 == 0 else "V_{(1)} = (D_J)"
    report(f"(C) q={q} m={m} {lab}: dim = {d}, expected |Z| = {exp}", d == exp, f"[{time.time()-t0:.1f}s]")

# ---------------- (D) pair blocks ----------------
def pair_block_t(q, p, colours, matchings):
    """colours: dict index->colour in F_p (index 0 has no variable). Variables t_i = c_i + s_i.
    matchings: list of lists of pairs (i<l). Generator per (6.2)."""
    idx = sorted(i for i in colours if i != 0)
    pos = {i: k for k, i in enumerate(idx)}
    n = len(idx); box = q
    one = const(1, n, box, p)
    t = {i: const(colours[i], n, box, p) + var(pos[i], n, box) for i in idx}
    gens = []
    for J in matchings:
        g = one.copy()
        for (i, l) in J:
            if i == 0:
                g = pmul(g, (t[l] - one) % p, p)
            else:
                u = (pmul(t[i], t[l], p) - one) % p
                g = pmul(g, pmul((t[l] - one) % p, ppow(u, q - 1, p), p), p)
        gens.append(g)
    return ideal_dim_full(gens, p)

def xz_ideal_dim(q, p, alpha, beta, pairs_list):
    """I generated by prod_{(i,l) in pairs}(x_i - z_l)^{q-1} in F_p[x_1..x_alpha, z_1..z_beta]/(x^q,z^q)."""
    n = alpha + beta; box = q
    one = const(1, n, box, p)
    gens = []
    for pairs in pairs_list:
        g = one.copy()
        for (i, l) in pairs:
            u = (var(i - 1, n, box) - var(alpha + l - 1, n, box)) % p
            g = pmul(g, ppow(u, q - 1, p), p)
        gens.append(g)
    return ideal_dim_full(gens, p)

print("=== (D) pair blocks, Lemma 6.7(iii), direct in t-variables over F_p containing mu_r ===")
for (p, r, zeta) in [(7, 3, 2), (11, 5, 3), (13, 3, 3)]:
    q = p
    zinv = pow(zeta, p - 2, p)
    assert pow(zeta, r, p) == 1 and zeta != 1 and (zeta * zinv) % p == 1
    # balanced alpha=beta=1: index 1 colour zeta, index 2 colour zeta^{-1}; 0 has colour (zeta*zinv)^{-1} = 1, not in A u B.
    t0 = time.time()
    d_t = pair_block_t(q, p, {1: zeta, 2: zinv}, [[(1, 2)]])
    d_xz = xz_ideal_dim(q, p, 1, 1, [[(1, 1)]])
    report(f"(D) p={p} r={r} zeta={zeta}: balanced a=1: dim I_c,zeta (t-form) = {d_t}, dim I^bal_1 (x,z-form) = {d_xz}, N_bal(1,{q}) = {q}",
           d_t == d_xz == q, f"[{time.time()-t0:.1f}s]")
    if p**3 * 2 * p**3 * 4 >= MEM_LIMIT:
        print(f"   skip phantom at p={p}: too big"); continue
    # phantom, 0 in B: A = {1,2} colour zeta, B = {0,3}, c_3 = zeta^{-1}; then c_0 = (zeta*zeta*zinv)^{-1} = zinv (in B). alpha=2, beta=1.
    c0 = pow((zeta * zeta * zinv) % p, p - 2, p)
    assert c0 == zinv
    t0 = time.time()
    d_t = pair_block_t(q, p, {1: zeta, 2: zeta, 3: zinv}, [[(0, 1), (2, 3)], [(0, 2), (1, 3)]])
    d_xz = xz_ideal_dim(q, p, 2, 1, [[(2, 1)], [(1, 1)]])
    exp = N_bal(2, q)
    report(f"(D) p={p}: phantom 0 in B (alpha,beta)=(2,1): dim I_c,zeta (t-form) = {d_t}, dim I^ph_1 (x,z-form) = {d_xz}, N_ph(1,{q}) = N_bal(2,{q}) = {exp}",
           d_t == d_xz == exp, f"[{time.time()-t0:.1f}s]")
    # phantom, 0 in A: A = {0,1} colour zeta (c_1 = zeta), B = {2,3} colour zinv; c_0 = (zeta*zinv*zinv)^{-1} = zeta. alpha=1, beta=2.
    c0 = pow((zeta * zinv * zinv) % p, p - 2, p)
    assert c0 == zeta
    t0 = time.time()
    d_t = pair_block_t(q, p, {1: zeta, 2: zinv, 3: zinv}, [[(0, 2), (1, 3)], [(0, 3), (1, 2)]])
    # after exchanging names x<->z this is I^ph_1 again; compute also the un-exchanged ideal directly:
    d_xz_direct = xz_ideal_dim(q, p, 1, 2, [[(1, 2)], [(1, 1)]])
    report(f"(D) p={p}: phantom 0 in A (alpha,beta)=(1,2): dim I_c,zeta (t-form) = {d_t}, dim ((x_1-z_2)^(q-1),(x_1-z_1)^(q-1)) = {d_xz_direct}, N_ph(1,{q}) = {exp}",
           d_t == d_xz_direct == exp, f"[{time.time()-t0:.1f}s]")

print(f"\nALL OK: {ok_all}   elapsed {time.time()-t_start:.1f}s")
sys.exit(0 if ok_all else 1)
