# Lemma 6.1 check: F=F_p, m=q r, roots mu_r in F_p (r | p-1). F[G] -> prod R_c iso; dim I' = sum dim pi_c(I').
import itertools, random
def polmul(f,g,p):
    h={}
    for a,x in f.items():
        for b,y in g.items():
            e=tuple(i+j for i,j in zip(a,b)); h[e]=(h.get(e,0)+x*y)%p
    return {e:c for e,c in h.items() if c}
def rank(rows,p):
    rows=[r[:] for r in rows]; rk=0; ncol=len(rows[0]) if rows else 0
    for c in range(ncol):
        piv=next((i for i in range(rk,len(rows)) if rows[i][c]),None)
        if piv is None: continue
        rows[rk],rows[piv]=rows[piv],rows[rk]; inv=pow(rows[rk][c],p-2,p)
        rows[rk]=[x*inv%p for x in rows[rk]]
        for i in range(len(rows)):
            if i!=rk and rows[i][c]:
                f=rows[i][c]; rows[i]=[(x-f*y)%p for x,y in zip(rows[i],rows[rk])]
        rk+=1
    return rk
def binom(n,k):
    from math import comb; return comb(n,k)
def image_vec(mono,c,q,p,d):
    # express t^a in R_c basis (t_i-c_i)^b, b_i<q : t = c + s
    vec={}
    parts=[]
    for i in range(d):
        a=mono[i]; ci=c[i]
        # (c+s)^a = sum_b C(a,b) c^{a-b} s^b, truncated b<q
        parts.append({b:(binom(a,b)*pow(ci,a-b,p))%p for b in range(min(a,q-1)+1) if binom(a,b)*pow(ci,a-b,p)%p})
    for combo in itertools.product(*[list(x.items()) for x in parts]):
        e=tuple(b for b,_ in combo); v=1
        for _,x in combo: v=v*x%p
        vec[e]=(vec.get(e,0)+v)%p
    return vec
res=[]
for p,q,r in [(3,3,2),(5,5,2),(7,7,3),(7,7,2),(3,9,2),(5,5,4)]:
    m=q*r; mu=[x for x in range(1,p) if pow(x,r,p)==1]; assert len(mu)==r
    for d in (1,2):
        if m**d>500: continue
        monsG=list(itertools.product(range(m),repeat=d)); cs=list(itertools.product(mu,repeat=d))
        monsR=list(itertools.product(range(q),repeat=d))
        # big matrix: rows = monomials of F[G], columns = (c, basis)
        colidx={(c,b):k for k,(c,b) in enumerate(itertools.product(cs,monsR))}
        M=[]
        for a in monsG:
            row=[0]*len(colidx)
            for c in cs:
                for b,v in image_vec(a,c,q,p,d).items(): row[colidx[(c,b)]]=v
            M.append(row)
        rk=rank(M,p); iso=(rk==len(monsG)==len(colidx))
        # (ii) random ideals: I' generated by 2 random elements times all monomials (in F[G], reduce exponents mod m)
        ok=True
        for trial in range(3):
            gens=[{tuple(random.randrange(m) for _ in range(d)):random.randrange(1,p) for _ in range(3)} for _ in range(2)]
            elems=[]
            for g in gens:
                for a in monsG:
                    h={}
                    for e,x in g.items():
                        e2=tuple((ei+ai)%m for ei,ai in zip(e,a)); h[e2]=(h.get(e2,0)+x)%p
                    elems.append(h)
            dimI=rank([[h.get(a,0) for a in monsG] for h in elems],p)
            tot=0
            for c in cs:
                rowsc=[]
                for h in elems:
                    v=[0]*len(monsR); 
                    for a,x in h.items():
                        for b,y in image_vec(a,c,q,p,d).items(): v[monsR.index(b)]=(v[monsR.index(b)]+x*y)%p
                    rowsc.append(v)
                tot+=rank(rowsc,p)
            ok=ok and dimI==tot
        res.append((p,q,r,d,iso,ok)); print(p,q,r,d,'iso',iso,'dim additive',ok)
print('cells',len(res),'failures',sum(1 for x in res if not(x[4] and x[5])))
